-- GrowthZone Connector — connector metadata seed (generated by `mj sync push`)
-- Seeds the core __mj integration catalog (Integration / IntegrationObject / IntegrationObjectField + Actions).
-- Do not hand-edit; regenerate from ../metadata via `mj sync push` + `scripts/wrap-migration.mjs`.

-- SQL Logging Session
-- Session ID: 3d4233ae-94aa-4025-8750-53882dd90386
-- Started: 2026-07-04T02:06:03.917Z
-- Description: MetadataSync push operation
-- Generated by MemberJunction

-- Save MJ: Integration Objects (core SP call only)
DECLARE @IntegrationID_981ebb34 UNIQUEIDENTIFIER,
@Name_981ebb34 NVARCHAR(255),
@DisplayName_981ebb34 NVARCHAR(255),
@Description_981ebb34 NVARCHAR(MAX),
@Category_981ebb34 NVARCHAR(100),
@APIPath_981ebb34 NVARCHAR(500),
@ResponseDataKey_981ebb34 NVARCHAR(255),
@DefaultPageSize_981ebb34 INT,
@SupportsPagination_981ebb34 BIT,
@PaginationType_981ebb34 NVARCHAR(20),
@SupportsIncrementalSync_981ebb34 BIT,
@SupportsWrite_981ebb34 BIT,
@DefaultQueryParams_981ebb34 NVARCHAR(MAX),
@Configuration_981ebb34 NVARCHAR(MAX),
@Sequence_981ebb34 INT,
@Status_981ebb34 NVARCHAR(25),
@WriteAPIPath_981ebb34 NVARCHAR(500),
@WriteMethod_981ebb34 NVARCHAR(10),
@DeleteMethod_981ebb34 NVARCHAR(10),
@IsCustom_981ebb34 BIT,
@CreateAPIPath_981ebb34 NVARCHAR(MAX),
@CreateMethod_981ebb34 NVARCHAR(20),
@CreateBodyShape_981ebb34 NVARCHAR(50),
@CreateBodyKey_981ebb34 NVARCHAR(100),
@CreateIDLocation_981ebb34 NVARCHAR(20),
@UpdateAPIPath_981ebb34 NVARCHAR(MAX),
@UpdateMethod_981ebb34 NVARCHAR(20),
@UpdateBodyShape_981ebb34 NVARCHAR(50),
@UpdateBodyKey_981ebb34 NVARCHAR(100),
@UpdateIDLocation_981ebb34 NVARCHAR(20),
@DeleteAPIPath_981ebb34 NVARCHAR(MAX),
@DeleteIDLocation_981ebb34 NVARCHAR(20),
@IncrementalWatermarkField_981ebb34 NVARCHAR(255),
@MetadataSource_981ebb34 NVARCHAR(20),
@SupportsCreate_981ebb34 BIT,
@SupportsUpdate_981ebb34 BIT,
@SupportsDelete_981ebb34 BIT,
@SyncStrategy_981ebb34 NVARCHAR(50),
@ContentHashApplicable_981ebb34 BIT,
@StableOrderingKey_981ebb34 NVARCHAR(255),
@ID_981ebb34 UNIQUEIDENTIFIER
SET
  @IntegrationID_981ebb34 = '248E9418-6E27-469B-B7B5-2C4A863A4051'
SET
  @Name_981ebb34 = N'MembershipChange'
SET
  @DisplayName_981ebb34 = N'MembershipChange'
SET
  @Description_981ebb34 = N'GrowthZone Membership object ''MembershipChange''. APIPath /api/memberships/change/{membershipId}/{changeType} (documented endpoint catalog). Fields from curated OpenAPI components.schemas.Models.BackOffice.UpgradeDowngradeMembershipViewModel.'
SET
  @Category_981ebb34 = N'Membership'
SET
  @APIPath_981ebb34 = N'/api/memberships/change/{membershipId}/{changeType}'
SET
  @DefaultPageSize_981ebb34 = 100
SET
  @SupportsPagination_981ebb34 = 0
SET
  @PaginationType_981ebb34 = N'None'
SET
  @SupportsIncrementalSync_981ebb34 = 0
SET
  @SupportsWrite_981ebb34 = 0
SET
  @Configuration_981ebb34 = N'{"apiPath":"/api/memberships/change/{membershipId}/{changeType}","pathParams":["membershipId","changeType"],"pagination":{"style":"odata","skipParam":"$skip","topParam":"$top","orderByParam":"$orderby","topMax":100},"syncStrategy":"FullPullHashDiff","contentHashApplicable":true,"listSupported":false,"supportsCreate":false,"supportsUpdate":false,"supportsDelete":false,"parentObjectName":"Membership","parentObjectIDFieldName":"membershipId","gap":"Path needs {membershipId}+{changeType}; {changeType} is an enum with no parent object — two vars with a single parentObjectName trip the engine PARENT_CYCLE guard (0 rows). Detail-only until an enum-iteration mechanism exists."}'
SET
  @Sequence_981ebb34 = 0
SET
  @Status_981ebb34 = N'Active'
SET
  @WriteMethod_981ebb34 = N'POST'
SET
  @DeleteMethod_981ebb34 = N'DELETE'
SET
  @IsCustom_981ebb34 = 0
SET
  @MetadataSource_981ebb34 = N'Declared'
SET
  @SupportsCreate_981ebb34 = 0
SET
  @SupportsUpdate_981ebb34 = 0
SET
  @SupportsDelete_981ebb34 = 0
SET
  @ContentHashApplicable_981ebb34 = 1
SET
  @ID_981ebb34 = '3E5B6F3B-D107-455E-9EC5-92C4A99A5D28' EXEC [__mj].spUpdateIntegrationObject @IntegrationID = @IntegrationID_981ebb34,
  @Name = @Name_981ebb34,
  @DisplayName = @DisplayName_981ebb34,
  @Description = @Description_981ebb34,
  @Category = @Category_981ebb34,
  @APIPath = @APIPath_981ebb34,
  @ResponseDataKey = @ResponseDataKey_981ebb34,
  @ResponseDataKey_Clear = 1,
  @DefaultPageSize = @DefaultPageSize_981ebb34,
  @SupportsPagination = @SupportsPagination_981ebb34,
  @PaginationType = @PaginationType_981ebb34,
  @SupportsIncrementalSync = @SupportsIncrementalSync_981ebb34,
  @SupportsWrite = @SupportsWrite_981ebb34,
  @DefaultQueryParams = @DefaultQueryParams_981ebb34,
  @DefaultQueryParams_Clear = 1,
  @Configuration = @Configuration_981ebb34,
  @Sequence = @Sequence_981ebb34,
  @Status = @Status_981ebb34,
  @WriteAPIPath = @WriteAPIPath_981ebb34,
  @WriteAPIPath_Clear = 1,
  @WriteMethod = @WriteMethod_981ebb34,
  @DeleteMethod = @DeleteMethod_981ebb34,
  @IsCustom = @IsCustom_981ebb34,
  @CreateAPIPath = @CreateAPIPath_981ebb34,
  @CreateAPIPath_Clear = 1,
  @CreateMethod = @CreateMethod_981ebb34,
  @CreateMethod_Clear = 1,
  @CreateBodyShape = @CreateBodyShape_981ebb34,
  @CreateBodyShape_Clear = 1,
  @CreateBodyKey = @CreateBodyKey_981ebb34,
  @CreateBodyKey_Clear = 1,
  @CreateIDLocation = @CreateIDLocation_981ebb34,
  @CreateIDLocation_Clear = 1,
  @UpdateAPIPath = @UpdateAPIPath_981ebb34,
  @UpdateAPIPath_Clear = 1,
  @UpdateMethod = @UpdateMethod_981ebb34,
  @UpdateMethod_Clear = 1,
  @UpdateBodyShape = @UpdateBodyShape_981ebb34,
  @UpdateBodyShape_Clear = 1,
  @UpdateBodyKey = @UpdateBodyKey_981ebb34,
  @UpdateBodyKey_Clear = 1,
  @UpdateIDLocation = @UpdateIDLocation_981ebb34,
  @UpdateIDLocation_Clear = 1,
  @DeleteAPIPath = @DeleteAPIPath_981ebb34,
  @DeleteAPIPath_Clear = 1,
  @DeleteIDLocation = @DeleteIDLocation_981ebb34,
  @DeleteIDLocation_Clear = 1,
  @IncrementalWatermarkField = @IncrementalWatermarkField_981ebb34,
  @IncrementalWatermarkField_Clear = 1,
  @MetadataSource = @MetadataSource_981ebb34,
  @SupportsCreate = @SupportsCreate_981ebb34,
  @SupportsUpdate = @SupportsUpdate_981ebb34,
  @SupportsDelete = @SupportsDelete_981ebb34,
  @SyncStrategy = @SyncStrategy_981ebb34,
  @SyncStrategy_Clear = 1,
  @ContentHashApplicable = @ContentHashApplicable_981ebb34,
  @StableOrderingKey = @StableOrderingKey_981ebb34,
  @StableOrderingKey_Clear = 1,
  @ID = @ID_981ebb34;

GO

-- Save MJ: Integration Objects (core SP call only)
DECLARE @IntegrationID_e2620e97 UNIQUEIDENTIFIER,
@Name_e2620e97 NVARCHAR(255),
@DisplayName_e2620e97 NVARCHAR(255),
@Description_e2620e97 NVARCHAR(MAX),
@Category_e2620e97 NVARCHAR(100),
@APIPath_e2620e97 NVARCHAR(500),
@ResponseDataKey_e2620e97 NVARCHAR(255),
@DefaultPageSize_e2620e97 INT,
@SupportsPagination_e2620e97 BIT,
@PaginationType_e2620e97 NVARCHAR(20),
@SupportsIncrementalSync_e2620e97 BIT,
@SupportsWrite_e2620e97 BIT,
@DefaultQueryParams_e2620e97 NVARCHAR(MAX),
@Configuration_e2620e97 NVARCHAR(MAX),
@Sequence_e2620e97 INT,
@Status_e2620e97 NVARCHAR(25),
@WriteAPIPath_e2620e97 NVARCHAR(500),
@WriteMethod_e2620e97 NVARCHAR(10),
@DeleteMethod_e2620e97 NVARCHAR(10),
@IsCustom_e2620e97 BIT,
@CreateAPIPath_e2620e97 NVARCHAR(MAX),
@CreateMethod_e2620e97 NVARCHAR(20),
@CreateBodyShape_e2620e97 NVARCHAR(50),
@CreateBodyKey_e2620e97 NVARCHAR(100),
@CreateIDLocation_e2620e97 NVARCHAR(20),
@UpdateAPIPath_e2620e97 NVARCHAR(MAX),
@UpdateMethod_e2620e97 NVARCHAR(20),
@UpdateBodyShape_e2620e97 NVARCHAR(50),
@UpdateBodyKey_e2620e97 NVARCHAR(100),
@UpdateIDLocation_e2620e97 NVARCHAR(20),
@DeleteAPIPath_e2620e97 NVARCHAR(MAX),
@DeleteIDLocation_e2620e97 NVARCHAR(20),
@IncrementalWatermarkField_e2620e97 NVARCHAR(255),
@MetadataSource_e2620e97 NVARCHAR(20),
@SupportsCreate_e2620e97 BIT,
@SupportsUpdate_e2620e97 BIT,
@SupportsDelete_e2620e97 BIT,
@SyncStrategy_e2620e97 NVARCHAR(50),
@ContentHashApplicable_e2620e97 BIT,
@StableOrderingKey_e2620e97 NVARCHAR(255),
@ID_e2620e97 UNIQUEIDENTIFIER
SET
  @IntegrationID_e2620e97 = '248E9418-6E27-469B-B7B5-2C4A863A4051'
SET
  @Name_e2620e97 = N'MembershipStatusLookup'
SET
  @DisplayName_e2620e97 = N'MembershipStatusLookup'
SET
  @Description_e2620e97 = N'GrowthZone Membership object ''MembershipStatusLookup''. APIPath /api/memberships/lookup/status/{defaultMembershipStatus} (documented endpoint catalog). Fields from curated OpenAPI components.schemas.Models.BackOffice.ItemChoiceModel.'
SET
  @Category_e2620e97 = N'Membership'
SET
  @APIPath_e2620e97 = N'/api/memberships/lookup/status/{defaultMembershipStatus}'
SET
  @DefaultPageSize_e2620e97 = 100
SET
  @SupportsPagination_e2620e97 = 0
SET
  @PaginationType_e2620e97 = N'None'
SET
  @SupportsIncrementalSync_e2620e97 = 0
SET
  @SupportsWrite_e2620e97 = 0
SET
  @Configuration_e2620e97 = N'{"apiPath":"/api/memberships/lookup/status/{defaultMembershipStatus}","pathParams":["defaultMembershipStatus"],"pagination":{"style":"odata","skipParam":"$skip","topParam":"$top","orderByParam":"$orderby","topMax":100},"syncStrategy":"FullPullHashDiff","contentHashApplicable":true,"listSupported":false,"supportsCreate":false,"supportsUpdate":false,"supportsDelete":false,"gap":"{defaultMembershipStatus} is a configured value, not a parent object — list iteration is structurally impossible; detail-only."}'
SET
  @Sequence_e2620e97 = 0
SET
  @Status_e2620e97 = N'Active'
SET
  @WriteMethod_e2620e97 = N'POST'
SET
  @DeleteMethod_e2620e97 = N'DELETE'
SET
  @IsCustom_e2620e97 = 0
SET
  @MetadataSource_e2620e97 = N'Declared'
SET
  @SupportsCreate_e2620e97 = 0
SET
  @SupportsUpdate_e2620e97 = 0
SET
  @SupportsDelete_e2620e97 = 0
SET
  @ContentHashApplicable_e2620e97 = 1
SET
  @ID_e2620e97 = '246947F1-D497-4ECB-ABB4-80AF5E5BC070' EXEC [__mj].spUpdateIntegrationObject @IntegrationID = @IntegrationID_e2620e97,
  @Name = @Name_e2620e97,
  @DisplayName = @DisplayName_e2620e97,
  @Description = @Description_e2620e97,
  @Category = @Category_e2620e97,
  @APIPath = @APIPath_e2620e97,
  @ResponseDataKey = @ResponseDataKey_e2620e97,
  @ResponseDataKey_Clear = 1,
  @DefaultPageSize = @DefaultPageSize_e2620e97,
  @SupportsPagination = @SupportsPagination_e2620e97,
  @PaginationType = @PaginationType_e2620e97,
  @SupportsIncrementalSync = @SupportsIncrementalSync_e2620e97,
  @SupportsWrite = @SupportsWrite_e2620e97,
  @DefaultQueryParams = @DefaultQueryParams_e2620e97,
  @DefaultQueryParams_Clear = 1,
  @Configuration = @Configuration_e2620e97,
  @Sequence = @Sequence_e2620e97,
  @Status = @Status_e2620e97,
  @WriteAPIPath = @WriteAPIPath_e2620e97,
  @WriteAPIPath_Clear = 1,
  @WriteMethod = @WriteMethod_e2620e97,
  @DeleteMethod = @DeleteMethod_e2620e97,
  @IsCustom = @IsCustom_e2620e97,
  @CreateAPIPath = @CreateAPIPath_e2620e97,
  @CreateAPIPath_Clear = 1,
  @CreateMethod = @CreateMethod_e2620e97,
  @CreateMethod_Clear = 1,
  @CreateBodyShape = @CreateBodyShape_e2620e97,
  @CreateBodyShape_Clear = 1,
  @CreateBodyKey = @CreateBodyKey_e2620e97,
  @CreateBodyKey_Clear = 1,
  @CreateIDLocation = @CreateIDLocation_e2620e97,
  @CreateIDLocation_Clear = 1,
  @UpdateAPIPath = @UpdateAPIPath_e2620e97,
  @UpdateAPIPath_Clear = 1,
  @UpdateMethod = @UpdateMethod_e2620e97,
  @UpdateMethod_Clear = 1,
  @UpdateBodyShape = @UpdateBodyShape_e2620e97,
  @UpdateBodyShape_Clear = 1,
  @UpdateBodyKey = @UpdateBodyKey_e2620e97,
  @UpdateBodyKey_Clear = 1,
  @UpdateIDLocation = @UpdateIDLocation_e2620e97,
  @UpdateIDLocation_Clear = 1,
  @DeleteAPIPath = @DeleteAPIPath_e2620e97,
  @DeleteAPIPath_Clear = 1,
  @DeleteIDLocation = @DeleteIDLocation_e2620e97,
  @DeleteIDLocation_Clear = 1,
  @IncrementalWatermarkField = @IncrementalWatermarkField_e2620e97,
  @IncrementalWatermarkField_Clear = 1,
  @MetadataSource = @MetadataSource_e2620e97,
  @SupportsCreate = @SupportsCreate_e2620e97,
  @SupportsUpdate = @SupportsUpdate_e2620e97,
  @SupportsDelete = @SupportsDelete_e2620e97,
  @SyncStrategy = @SyncStrategy_e2620e97,
  @SyncStrategy_Clear = 1,
  @ContentHashApplicable = @ContentHashApplicable_e2620e97,
  @StableOrderingKey = @StableOrderingKey_e2620e97,
  @StableOrderingKey_Clear = 1,
  @ID = @ID_e2620e97;

GO

-- Save MJ: Integration Object Fields (core SP call only)
DECLARE @IntegrationObjectID_d36e9550 UNIQUEIDENTIFIER,
@Name_d36e9550 NVARCHAR(255),
@DisplayName_d36e9550 NVARCHAR(255),
@Description_d36e9550 NVARCHAR(MAX),
@Category_d36e9550 NVARCHAR(100),
@Type_d36e9550 NVARCHAR(100),
@Length_d36e9550 INT,
@Precision_d36e9550 INT,
@Scale_d36e9550 INT,
@AllowsNull_d36e9550 BIT,
@DefaultValue_d36e9550 NVARCHAR(255),
@IsPrimaryKey_d36e9550 BIT,
@IsUniqueKey_d36e9550 BIT,
@IsReadOnly_d36e9550 BIT,
@IsRequired_d36e9550 BIT,
@RelatedIntegrationObjectID_d36e9550 UNIQUEIDENTIFIER,
@RelatedIntegrationObjectFieldName_d36e9550 NVARCHAR(255),
@Sequence_d36e9550 INT,
@Configuration_d36e9550 NVARCHAR(MAX),
@Status_d36e9550 NVARCHAR(25),
@IsCustom_d36e9550 BIT,
@MetadataSource_d36e9550 NVARCHAR(20),
@ID_d36e9550 UNIQUEIDENTIFIER
SET
  @IntegrationObjectID_d36e9550 = 'A6CC2D80-7FB1-4F06-81FA-C9382ECCA0D1'
SET
  @Name_d36e9550 = N'Note'
SET
  @DisplayName_d36e9550 = N'Note'
SET
  @Type_d36e9550 = N'String'
SET
  @Length_d36e9550 = 4000
SET
  @AllowsNull_d36e9550 = 1
SET
  @IsPrimaryKey_d36e9550 = 0
SET
  @IsUniqueKey_d36e9550 = 0
SET
  @IsReadOnly_d36e9550 = 0
SET
  @IsRequired_d36e9550 = 0
SET
  @Sequence_d36e9550 = 0
SET
  @Status_d36e9550 = N'Active'
SET
  @IsCustom_d36e9550 = 0
SET
  @MetadataSource_d36e9550 = N'Declared'
SET
  @ID_d36e9550 = 'F7FA47E9-508F-4878-B395-F24155F9C613' EXEC [__mj].spUpdateIntegrationObjectField @IntegrationObjectID = @IntegrationObjectID_d36e9550,
  @Name = @Name_d36e9550,
  @DisplayName = @DisplayName_d36e9550,
  @Description = @Description_d36e9550,
  @Description_Clear = 1,
  @Category = @Category_d36e9550,
  @Category_Clear = 1,
  @Type = @Type_d36e9550,
  @Length = @Length_d36e9550,
  @Precision = @Precision_d36e9550,
  @Precision_Clear = 1,
  @Scale = @Scale_d36e9550,
  @Scale_Clear = 1,
  @AllowsNull = @AllowsNull_d36e9550,
  @DefaultValue = @DefaultValue_d36e9550,
  @DefaultValue_Clear = 1,
  @IsPrimaryKey = @IsPrimaryKey_d36e9550,
  @IsUniqueKey = @IsUniqueKey_d36e9550,
  @IsReadOnly = @IsReadOnly_d36e9550,
  @IsRequired = @IsRequired_d36e9550,
  @RelatedIntegrationObjectID = @RelatedIntegrationObjectID_d36e9550,
  @RelatedIntegrationObjectID_Clear = 1,
  @RelatedIntegrationObjectFieldName = @RelatedIntegrationObjectFieldName_d36e9550,
  @RelatedIntegrationObjectFieldName_Clear = 1,
  @Sequence = @Sequence_d36e9550,
  @Configuration = @Configuration_d36e9550,
  @Configuration_Clear = 1,
  @Status = @Status_d36e9550,
  @IsCustom = @IsCustom_d36e9550,
  @MetadataSource = @MetadataSource_d36e9550,
  @ID = @ID_d36e9550;

GO

-- Save MJ: Integration Object Fields (core SP call only)
DECLARE @IntegrationObjectID_1ed89574 UNIQUEIDENTIFIER,
@Name_1ed89574 NVARCHAR(255),
@DisplayName_1ed89574 NVARCHAR(255),
@Description_1ed89574 NVARCHAR(MAX),
@Category_1ed89574 NVARCHAR(100),
@Type_1ed89574 NVARCHAR(100),
@Length_1ed89574 INT,
@Precision_1ed89574 INT,
@Scale_1ed89574 INT,
@AllowsNull_1ed89574 BIT,
@DefaultValue_1ed89574 NVARCHAR(255),
@IsPrimaryKey_1ed89574 BIT,
@IsUniqueKey_1ed89574 BIT,
@IsReadOnly_1ed89574 BIT,
@IsRequired_1ed89574 BIT,
@RelatedIntegrationObjectID_1ed89574 UNIQUEIDENTIFIER,
@RelatedIntegrationObjectFieldName_1ed89574 NVARCHAR(255),
@Sequence_1ed89574 INT,
@Configuration_1ed89574 NVARCHAR(MAX),
@Status_1ed89574 NVARCHAR(25),
@IsCustom_1ed89574 BIT,
@MetadataSource_1ed89574 NVARCHAR(20),
@ID_1ed89574 UNIQUEIDENTIFIER
SET
  @IntegrationObjectID_1ed89574 = '488CD41E-C418-42B0-A207-AD95EFF449BF'
SET
  @Name_1ed89574 = N'Description'
SET
  @DisplayName_1ed89574 = N'Description'
SET
  @Type_1ed89574 = N'String'
SET
  @Length_1ed89574 = 4000
SET
  @AllowsNull_1ed89574 = 1
SET
  @IsPrimaryKey_1ed89574 = 0
SET
  @IsUniqueKey_1ed89574 = 0
SET
  @IsReadOnly_1ed89574 = 0
SET
  @IsRequired_1ed89574 = 0
SET
  @Sequence_1ed89574 = 0
SET
  @Status_1ed89574 = N'Active'
SET
  @IsCustom_1ed89574 = 0
SET
  @MetadataSource_1ed89574 = N'Declared'
SET
  @ID_1ed89574 = '8AED1AD2-53B9-4F2F-A18F-574633F59AE5' EXEC [__mj].spUpdateIntegrationObjectField @IntegrationObjectID = @IntegrationObjectID_1ed89574,
  @Name = @Name_1ed89574,
  @DisplayName = @DisplayName_1ed89574,
  @Description = @Description_1ed89574,
  @Description_Clear = 1,
  @Category = @Category_1ed89574,
  @Category_Clear = 1,
  @Type = @Type_1ed89574,
  @Length = @Length_1ed89574,
  @Precision = @Precision_1ed89574,
  @Precision_Clear = 1,
  @Scale = @Scale_1ed89574,
  @Scale_Clear = 1,
  @AllowsNull = @AllowsNull_1ed89574,
  @DefaultValue = @DefaultValue_1ed89574,
  @DefaultValue_Clear = 1,
  @IsPrimaryKey = @IsPrimaryKey_1ed89574,
  @IsUniqueKey = @IsUniqueKey_1ed89574,
  @IsReadOnly = @IsReadOnly_1ed89574,
  @IsRequired = @IsRequired_1ed89574,
  @RelatedIntegrationObjectID = @RelatedIntegrationObjectID_1ed89574,
  @RelatedIntegrationObjectID_Clear = 1,
  @RelatedIntegrationObjectFieldName = @RelatedIntegrationObjectFieldName_1ed89574,
  @RelatedIntegrationObjectFieldName_Clear = 1,
  @Sequence = @Sequence_1ed89574,
  @Configuration = @Configuration_1ed89574,
  @Configuration_Clear = 1,
  @Status = @Status_1ed89574,
  @IsCustom = @IsCustom_1ed89574,
  @MetadataSource = @MetadataSource_1ed89574,
  @ID = @ID_1ed89574;

GO

-- Save MJ: Integration Object Fields (core SP call only)
DECLARE @IntegrationObjectID_62f1b8c7 UNIQUEIDENTIFIER,
@Name_62f1b8c7 NVARCHAR(255),
@DisplayName_62f1b8c7 NVARCHAR(255),
@Description_62f1b8c7 NVARCHAR(MAX),
@Category_62f1b8c7 NVARCHAR(100),
@Type_62f1b8c7 NVARCHAR(100),
@Length_62f1b8c7 INT,
@Precision_62f1b8c7 INT,
@Scale_62f1b8c7 INT,
@AllowsNull_62f1b8c7 BIT,
@DefaultValue_62f1b8c7 NVARCHAR(255),
@IsPrimaryKey_62f1b8c7 BIT,
@IsUniqueKey_62f1b8c7 BIT,
@IsReadOnly_62f1b8c7 BIT,
@IsRequired_62f1b8c7 BIT,
@RelatedIntegrationObjectID_62f1b8c7 UNIQUEIDENTIFIER,
@RelatedIntegrationObjectFieldName_62f1b8c7 NVARCHAR(255),
@Sequence_62f1b8c7 INT,
@Configuration_62f1b8c7 NVARCHAR(MAX),
@Status_62f1b8c7 NVARCHAR(25),
@IsCustom_62f1b8c7 BIT,
@MetadataSource_62f1b8c7 NVARCHAR(20),
@ID_62f1b8c7 UNIQUEIDENTIFIER
SET
  @IntegrationObjectID_62f1b8c7 = '41AAF6EC-36F4-48B5-8072-04B92CDD9F05'
SET
  @Name_62f1b8c7 = N'Notes'
SET
  @DisplayName_62f1b8c7 = N'Notes'
SET
  @Type_62f1b8c7 = N'String'
SET
  @Length_62f1b8c7 = 4000
SET
  @AllowsNull_62f1b8c7 = 1
SET
  @IsPrimaryKey_62f1b8c7 = 0
SET
  @IsUniqueKey_62f1b8c7 = 0
SET
  @IsReadOnly_62f1b8c7 = 0
SET
  @IsRequired_62f1b8c7 = 0
SET
  @Sequence_62f1b8c7 = 0
SET
  @Status_62f1b8c7 = N'Active'
SET
  @IsCustom_62f1b8c7 = 0
SET
  @MetadataSource_62f1b8c7 = N'Declared'
SET
  @ID_62f1b8c7 = 'C1DA9C9E-0F42-4BA6-A364-A39B48ED215B' EXEC [__mj].spUpdateIntegrationObjectField @IntegrationObjectID = @IntegrationObjectID_62f1b8c7,
  @Name = @Name_62f1b8c7,
  @DisplayName = @DisplayName_62f1b8c7,
  @Description = @Description_62f1b8c7,
  @Description_Clear = 1,
  @Category = @Category_62f1b8c7,
  @Category_Clear = 1,
  @Type = @Type_62f1b8c7,
  @Length = @Length_62f1b8c7,
  @Precision = @Precision_62f1b8c7,
  @Precision_Clear = 1,
  @Scale = @Scale_62f1b8c7,
  @Scale_Clear = 1,
  @AllowsNull = @AllowsNull_62f1b8c7,
  @DefaultValue = @DefaultValue_62f1b8c7,
  @DefaultValue_Clear = 1,
  @IsPrimaryKey = @IsPrimaryKey_62f1b8c7,
  @IsUniqueKey = @IsUniqueKey_62f1b8c7,
  @IsReadOnly = @IsReadOnly_62f1b8c7,
  @IsRequired = @IsRequired_62f1b8c7,
  @RelatedIntegrationObjectID = @RelatedIntegrationObjectID_62f1b8c7,
  @RelatedIntegrationObjectID_Clear = 1,
  @RelatedIntegrationObjectFieldName = @RelatedIntegrationObjectFieldName_62f1b8c7,
  @RelatedIntegrationObjectFieldName_Clear = 1,
  @Sequence = @Sequence_62f1b8c7,
  @Configuration = @Configuration_62f1b8c7,
  @Configuration_Clear = 1,
  @Status = @Status_62f1b8c7,
  @IsCustom = @IsCustom_62f1b8c7,
  @MetadataSource = @MetadataSource_62f1b8c7,
  @ID = @ID_62f1b8c7;

GO

-- Save MJ: Integration Object Fields (core SP call only)
DECLARE @IntegrationObjectID_128f4ccd UNIQUEIDENTIFIER,
@Name_128f4ccd NVARCHAR(255),
@DisplayName_128f4ccd NVARCHAR(255),
@Description_128f4ccd NVARCHAR(MAX),
@Category_128f4ccd NVARCHAR(100),
@Type_128f4ccd NVARCHAR(100),
@Length_128f4ccd INT,
@Precision_128f4ccd INT,
@Scale_128f4ccd INT,
@AllowsNull_128f4ccd BIT,
@DefaultValue_128f4ccd NVARCHAR(255),
@IsPrimaryKey_128f4ccd BIT,
@IsUniqueKey_128f4ccd BIT,
@IsReadOnly_128f4ccd BIT,
@IsRequired_128f4ccd BIT,
@RelatedIntegrationObjectID_128f4ccd UNIQUEIDENTIFIER,
@RelatedIntegrationObjectFieldName_128f4ccd NVARCHAR(255),
@Sequence_128f4ccd INT,
@Configuration_128f4ccd NVARCHAR(MAX),
@Status_128f4ccd NVARCHAR(25),
@IsCustom_128f4ccd BIT,
@MetadataSource_128f4ccd NVARCHAR(20),
@ID_128f4ccd UNIQUEIDENTIFIER
SET
  @IntegrationObjectID_128f4ccd = 'CE2F7459-4EBD-43CF-80D5-D64AF8267657'
SET
  @Name_128f4ccd = N'Notes'
SET
  @DisplayName_128f4ccd = N'Notes'
SET
  @Type_128f4ccd = N'String'
SET
  @Length_128f4ccd = 4000
SET
  @AllowsNull_128f4ccd = 1
SET
  @IsPrimaryKey_128f4ccd = 0
SET
  @IsUniqueKey_128f4ccd = 0
SET
  @IsReadOnly_128f4ccd = 0
SET
  @IsRequired_128f4ccd = 0
SET
  @Sequence_128f4ccd = 0
SET
  @Status_128f4ccd = N'Active'
SET
  @IsCustom_128f4ccd = 0
SET
  @MetadataSource_128f4ccd = N'Declared'
SET
  @ID_128f4ccd = 'C74618B3-510D-48AF-AC15-8649AB1FE619' EXEC [__mj].spUpdateIntegrationObjectField @IntegrationObjectID = @IntegrationObjectID_128f4ccd,
  @Name = @Name_128f4ccd,
  @DisplayName = @DisplayName_128f4ccd,
  @Description = @Description_128f4ccd,
  @Description_Clear = 1,
  @Category = @Category_128f4ccd,
  @Category_Clear = 1,
  @Type = @Type_128f4ccd,
  @Length = @Length_128f4ccd,
  @Precision = @Precision_128f4ccd,
  @Precision_Clear = 1,
  @Scale = @Scale_128f4ccd,
  @Scale_Clear = 1,
  @AllowsNull = @AllowsNull_128f4ccd,
  @DefaultValue = @DefaultValue_128f4ccd,
  @DefaultValue_Clear = 1,
  @IsPrimaryKey = @IsPrimaryKey_128f4ccd,
  @IsUniqueKey = @IsUniqueKey_128f4ccd,
  @IsReadOnly = @IsReadOnly_128f4ccd,
  @IsRequired = @IsRequired_128f4ccd,
  @RelatedIntegrationObjectID = @RelatedIntegrationObjectID_128f4ccd,
  @RelatedIntegrationObjectID_Clear = 1,
  @RelatedIntegrationObjectFieldName = @RelatedIntegrationObjectFieldName_128f4ccd,
  @RelatedIntegrationObjectFieldName_Clear = 1,
  @Sequence = @Sequence_128f4ccd,
  @Configuration = @Configuration_128f4ccd,
  @Configuration_Clear = 1,
  @Status = @Status_128f4ccd,
  @IsCustom = @IsCustom_128f4ccd,
  @MetadataSource = @MetadataSource_128f4ccd,
  @ID = @ID_128f4ccd;

GO

-- Save MJ: Integration Object Fields (core SP call only)
DECLARE @IntegrationObjectID_fdc4eb8b UNIQUEIDENTIFIER,
@Name_fdc4eb8b NVARCHAR(255),
@DisplayName_fdc4eb8b NVARCHAR(255),
@Description_fdc4eb8b NVARCHAR(MAX),
@Category_fdc4eb8b NVARCHAR(100),
@Type_fdc4eb8b NVARCHAR(100),
@Length_fdc4eb8b INT,
@Precision_fdc4eb8b INT,
@Scale_fdc4eb8b INT,
@AllowsNull_fdc4eb8b BIT,
@DefaultValue_fdc4eb8b NVARCHAR(255),
@IsPrimaryKey_fdc4eb8b BIT,
@IsUniqueKey_fdc4eb8b BIT,
@IsReadOnly_fdc4eb8b BIT,
@IsRequired_fdc4eb8b BIT,
@RelatedIntegrationObjectID_fdc4eb8b UNIQUEIDENTIFIER,
@RelatedIntegrationObjectFieldName_fdc4eb8b NVARCHAR(255),
@Sequence_fdc4eb8b INT,
@Configuration_fdc4eb8b NVARCHAR(MAX),
@Status_fdc4eb8b NVARCHAR(25),
@IsCustom_fdc4eb8b BIT,
@MetadataSource_fdc4eb8b NVARCHAR(20),
@ID_fdc4eb8b UNIQUEIDENTIFIER
SET
  @IntegrationObjectID_fdc4eb8b = '6A7B70F2-9E2D-4948-B362-902C837A51E1'
SET
  @Name_fdc4eb8b = N'ImageUrl'
SET
  @DisplayName_fdc4eb8b = N'ImageUrl'
SET
  @Type_fdc4eb8b = N'String'
SET
  @Length_fdc4eb8b = 2048
SET
  @AllowsNull_fdc4eb8b = 1
SET
  @IsPrimaryKey_fdc4eb8b = 0
SET
  @IsUniqueKey_fdc4eb8b = 0
SET
  @IsReadOnly_fdc4eb8b = 0
SET
  @IsRequired_fdc4eb8b = 0
SET
  @Sequence_fdc4eb8b = 0
SET
  @Status_fdc4eb8b = N'Active'
SET
  @IsCustom_fdc4eb8b = 0
SET
  @MetadataSource_fdc4eb8b = N'Declared'
SET
  @ID_fdc4eb8b = '4E534F42-84CA-487F-A9E1-2FFE8C75A552' EXEC [__mj].spUpdateIntegrationObjectField @IntegrationObjectID = @IntegrationObjectID_fdc4eb8b,
  @Name = @Name_fdc4eb8b,
  @DisplayName = @DisplayName_fdc4eb8b,
  @Description = @Description_fdc4eb8b,
  @Description_Clear = 1,
  @Category = @Category_fdc4eb8b,
  @Category_Clear = 1,
  @Type = @Type_fdc4eb8b,
  @Length = @Length_fdc4eb8b,
  @Precision = @Precision_fdc4eb8b,
  @Precision_Clear = 1,
  @Scale = @Scale_fdc4eb8b,
  @Scale_Clear = 1,
  @AllowsNull = @AllowsNull_fdc4eb8b,
  @DefaultValue = @DefaultValue_fdc4eb8b,
  @DefaultValue_Clear = 1,
  @IsPrimaryKey = @IsPrimaryKey_fdc4eb8b,
  @IsUniqueKey = @IsUniqueKey_fdc4eb8b,
  @IsReadOnly = @IsReadOnly_fdc4eb8b,
  @IsRequired = @IsRequired_fdc4eb8b,
  @RelatedIntegrationObjectID = @RelatedIntegrationObjectID_fdc4eb8b,
  @RelatedIntegrationObjectID_Clear = 1,
  @RelatedIntegrationObjectFieldName = @RelatedIntegrationObjectFieldName_fdc4eb8b,
  @RelatedIntegrationObjectFieldName_Clear = 1,
  @Sequence = @Sequence_fdc4eb8b,
  @Configuration = @Configuration_fdc4eb8b,
  @Configuration_Clear = 1,
  @Status = @Status_fdc4eb8b,
  @IsCustom = @IsCustom_fdc4eb8b,
  @MetadataSource = @MetadataSource_fdc4eb8b,
  @ID = @ID_fdc4eb8b;

GO

-- Save MJ: Integration Object Fields (core SP call only)
DECLARE @IntegrationObjectID_e215c042 UNIQUEIDENTIFIER,
@Name_e215c042 NVARCHAR(255),
@DisplayName_e215c042 NVARCHAR(255),
@Description_e215c042 NVARCHAR(MAX),
@Category_e215c042 NVARCHAR(100),
@Type_e215c042 NVARCHAR(100),
@Length_e215c042 INT,
@Precision_e215c042 INT,
@Scale_e215c042 INT,
@AllowsNull_e215c042 BIT,
@DefaultValue_e215c042 NVARCHAR(255),
@IsPrimaryKey_e215c042 BIT,
@IsUniqueKey_e215c042 BIT,
@IsReadOnly_e215c042 BIT,
@IsRequired_e215c042 BIT,
@RelatedIntegrationObjectID_e215c042 UNIQUEIDENTIFIER,
@RelatedIntegrationObjectFieldName_e215c042 NVARCHAR(255),
@Sequence_e215c042 INT,
@Configuration_e215c042 NVARCHAR(MAX),
@Status_e215c042 NVARCHAR(25),
@IsCustom_e215c042 BIT,
@MetadataSource_e215c042 NVARCHAR(20),
@ID_e215c042 UNIQUEIDENTIFIER
SET
  @IntegrationObjectID_e215c042 = 'BF660360-FF3A-4EE7-84A4-73CE947DD38E'
SET
  @Name_e215c042 = N'Description'
SET
  @DisplayName_e215c042 = N'Description'
SET
  @Type_e215c042 = N'String'
SET
  @Length_e215c042 = 4000
SET
  @AllowsNull_e215c042 = 1
SET
  @IsPrimaryKey_e215c042 = 0
SET
  @IsUniqueKey_e215c042 = 0
SET
  @IsReadOnly_e215c042 = 0
SET
  @IsRequired_e215c042 = 0
SET
  @Sequence_e215c042 = 0
SET
  @Status_e215c042 = N'Active'
SET
  @IsCustom_e215c042 = 0
SET
  @MetadataSource_e215c042 = N'Declared'
SET
  @ID_e215c042 = '70D6A193-64A0-4828-84E2-E2D1DFC109AC' EXEC [__mj].spUpdateIntegrationObjectField @IntegrationObjectID = @IntegrationObjectID_e215c042,
  @Name = @Name_e215c042,
  @DisplayName = @DisplayName_e215c042,
  @Description = @Description_e215c042,
  @Description_Clear = 1,
  @Category = @Category_e215c042,
  @Category_Clear = 1,
  @Type = @Type_e215c042,
  @Length = @Length_e215c042,
  @Precision = @Precision_e215c042,
  @Precision_Clear = 1,
  @Scale = @Scale_e215c042,
  @Scale_Clear = 1,
  @AllowsNull = @AllowsNull_e215c042,
  @DefaultValue = @DefaultValue_e215c042,
  @DefaultValue_Clear = 1,
  @IsPrimaryKey = @IsPrimaryKey_e215c042,
  @IsUniqueKey = @IsUniqueKey_e215c042,
  @IsReadOnly = @IsReadOnly_e215c042,
  @IsRequired = @IsRequired_e215c042,
  @RelatedIntegrationObjectID = @RelatedIntegrationObjectID_e215c042,
  @RelatedIntegrationObjectID_Clear = 1,
  @RelatedIntegrationObjectFieldName = @RelatedIntegrationObjectFieldName_e215c042,
  @RelatedIntegrationObjectFieldName_Clear = 1,
  @Sequence = @Sequence_e215c042,
  @Configuration = @Configuration_e215c042,
  @Configuration_Clear = 1,
  @Status = @Status_e215c042,
  @IsCustom = @IsCustom_e215c042,
  @MetadataSource = @MetadataSource_e215c042,
  @ID = @ID_e215c042;

GO

-- Save MJ: Integration Object Fields (core SP call only)
DECLARE @IntegrationObjectID_21fb1c7d UNIQUEIDENTIFIER,
@Name_21fb1c7d NVARCHAR(255),
@DisplayName_21fb1c7d NVARCHAR(255),
@Description_21fb1c7d NVARCHAR(MAX),
@Category_21fb1c7d NVARCHAR(100),
@Type_21fb1c7d NVARCHAR(100),
@Length_21fb1c7d INT,
@Precision_21fb1c7d INT,
@Scale_21fb1c7d INT,
@AllowsNull_21fb1c7d BIT,
@DefaultValue_21fb1c7d NVARCHAR(255),
@IsPrimaryKey_21fb1c7d BIT,
@IsUniqueKey_21fb1c7d BIT,
@IsReadOnly_21fb1c7d BIT,
@IsRequired_21fb1c7d BIT,
@RelatedIntegrationObjectID_21fb1c7d UNIQUEIDENTIFIER,
@RelatedIntegrationObjectFieldName_21fb1c7d NVARCHAR(255),
@Sequence_21fb1c7d INT,
@Configuration_21fb1c7d NVARCHAR(MAX),
@Status_21fb1c7d NVARCHAR(25),
@IsCustom_21fb1c7d BIT,
@MetadataSource_21fb1c7d NVARCHAR(20),
@ID_21fb1c7d UNIQUEIDENTIFIER
SET
  @IntegrationObjectID_21fb1c7d = '3E5B6F3B-D107-455E-9EC5-92C4A99A5D28'
SET
  @Name_21fb1c7d = N'Notes'
SET
  @DisplayName_21fb1c7d = N'Notes'
SET
  @Type_21fb1c7d = N'String'
SET
  @Length_21fb1c7d = 4000
SET
  @AllowsNull_21fb1c7d = 1
SET
  @IsPrimaryKey_21fb1c7d = 0
SET
  @IsUniqueKey_21fb1c7d = 0
SET
  @IsReadOnly_21fb1c7d = 0
SET
  @IsRequired_21fb1c7d = 0
SET
  @Sequence_21fb1c7d = 0
SET
  @Status_21fb1c7d = N'Active'
SET
  @IsCustom_21fb1c7d = 0
SET
  @MetadataSource_21fb1c7d = N'Declared'
SET
  @ID_21fb1c7d = '7B2788A0-D7FB-4398-9A4F-B7F251DE94E3' EXEC [__mj].spUpdateIntegrationObjectField @IntegrationObjectID = @IntegrationObjectID_21fb1c7d,
  @Name = @Name_21fb1c7d,
  @DisplayName = @DisplayName_21fb1c7d,
  @Description = @Description_21fb1c7d,
  @Description_Clear = 1,
  @Category = @Category_21fb1c7d,
  @Category_Clear = 1,
  @Type = @Type_21fb1c7d,
  @Length = @Length_21fb1c7d,
  @Precision = @Precision_21fb1c7d,
  @Precision_Clear = 1,
  @Scale = @Scale_21fb1c7d,
  @Scale_Clear = 1,
  @AllowsNull = @AllowsNull_21fb1c7d,
  @DefaultValue = @DefaultValue_21fb1c7d,
  @DefaultValue_Clear = 1,
  @IsPrimaryKey = @IsPrimaryKey_21fb1c7d,
  @IsUniqueKey = @IsUniqueKey_21fb1c7d,
  @IsReadOnly = @IsReadOnly_21fb1c7d,
  @IsRequired = @IsRequired_21fb1c7d,
  @RelatedIntegrationObjectID = @RelatedIntegrationObjectID_21fb1c7d,
  @RelatedIntegrationObjectID_Clear = 1,
  @RelatedIntegrationObjectFieldName = @RelatedIntegrationObjectFieldName_21fb1c7d,
  @RelatedIntegrationObjectFieldName_Clear = 1,
  @Sequence = @Sequence_21fb1c7d,
  @Configuration = @Configuration_21fb1c7d,
  @Configuration_Clear = 1,
  @Status = @Status_21fb1c7d,
  @IsCustom = @IsCustom_21fb1c7d,
  @MetadataSource = @MetadataSource_21fb1c7d,
  @ID = @ID_21fb1c7d;

GO

-- Save MJ: Integration Object Fields (core SP call only)
DECLARE @IntegrationObjectID_3fed9ae3 UNIQUEIDENTIFIER,
@Name_3fed9ae3 NVARCHAR(255),
@DisplayName_3fed9ae3 NVARCHAR(255),
@Description_3fed9ae3 NVARCHAR(MAX),
@Category_3fed9ae3 NVARCHAR(100),
@Type_3fed9ae3 NVARCHAR(100),
@Length_3fed9ae3 INT,
@Precision_3fed9ae3 INT,
@Scale_3fed9ae3 INT,
@AllowsNull_3fed9ae3 BIT,
@DefaultValue_3fed9ae3 NVARCHAR(255),
@IsPrimaryKey_3fed9ae3 BIT,
@IsUniqueKey_3fed9ae3 BIT,
@IsReadOnly_3fed9ae3 BIT,
@IsRequired_3fed9ae3 BIT,
@RelatedIntegrationObjectID_3fed9ae3 UNIQUEIDENTIFIER,
@RelatedIntegrationObjectFieldName_3fed9ae3 NVARCHAR(255),
@Sequence_3fed9ae3 INT,
@Configuration_3fed9ae3 NVARCHAR(MAX),
@Status_3fed9ae3 NVARCHAR(25),
@IsCustom_3fed9ae3 BIT,
@MetadataSource_3fed9ae3 NVARCHAR(20),
@ID_3fed9ae3 UNIQUEIDENTIFIER
SET
  @IntegrationObjectID_3fed9ae3 = '3E5B6F3B-D107-455E-9EC5-92C4A99A5D28'
SET
  @Name_3fed9ae3 = N'Instructions'
SET
  @DisplayName_3fed9ae3 = N'Instructions'
SET
  @Type_3fed9ae3 = N'String'
SET
  @Length_3fed9ae3 = 4000
SET
  @AllowsNull_3fed9ae3 = 1
SET
  @IsPrimaryKey_3fed9ae3 = 0
SET
  @IsUniqueKey_3fed9ae3 = 0
SET
  @IsReadOnly_3fed9ae3 = 1
SET
  @IsRequired_3fed9ae3 = 0
SET
  @Sequence_3fed9ae3 = 0
SET
  @Status_3fed9ae3 = N'Active'
SET
  @IsCustom_3fed9ae3 = 0
SET
  @MetadataSource_3fed9ae3 = N'Declared'
SET
  @ID_3fed9ae3 = '7F40C958-466D-49B2-BE48-236D4C328E22' EXEC [__mj].spUpdateIntegrationObjectField @IntegrationObjectID = @IntegrationObjectID_3fed9ae3,
  @Name = @Name_3fed9ae3,
  @DisplayName = @DisplayName_3fed9ae3,
  @Description = @Description_3fed9ae3,
  @Description_Clear = 1,
  @Category = @Category_3fed9ae3,
  @Category_Clear = 1,
  @Type = @Type_3fed9ae3,
  @Length = @Length_3fed9ae3,
  @Precision = @Precision_3fed9ae3,
  @Precision_Clear = 1,
  @Scale = @Scale_3fed9ae3,
  @Scale_Clear = 1,
  @AllowsNull = @AllowsNull_3fed9ae3,
  @DefaultValue = @DefaultValue_3fed9ae3,
  @DefaultValue_Clear = 1,
  @IsPrimaryKey = @IsPrimaryKey_3fed9ae3,
  @IsUniqueKey = @IsUniqueKey_3fed9ae3,
  @IsReadOnly = @IsReadOnly_3fed9ae3,
  @IsRequired = @IsRequired_3fed9ae3,
  @RelatedIntegrationObjectID = @RelatedIntegrationObjectID_3fed9ae3,
  @RelatedIntegrationObjectID_Clear = 1,
  @RelatedIntegrationObjectFieldName = @RelatedIntegrationObjectFieldName_3fed9ae3,
  @RelatedIntegrationObjectFieldName_Clear = 1,
  @Sequence = @Sequence_3fed9ae3,
  @Configuration = @Configuration_3fed9ae3,
  @Configuration_Clear = 1,
  @Status = @Status_3fed9ae3,
  @IsCustom = @IsCustom_3fed9ae3,
  @MetadataSource = @MetadataSource_3fed9ae3,
  @ID = @ID_3fed9ae3;

GO

-- Save MJ: Integration Object Fields (core SP call only)
DECLARE @IntegrationObjectID_9b7d5a76 UNIQUEIDENTIFIER,
@Name_9b7d5a76 NVARCHAR(255),
@DisplayName_9b7d5a76 NVARCHAR(255),
@Description_9b7d5a76 NVARCHAR(MAX),
@Category_9b7d5a76 NVARCHAR(100),
@Type_9b7d5a76 NVARCHAR(100),
@Length_9b7d5a76 INT,
@Precision_9b7d5a76 INT,
@Scale_9b7d5a76 INT,
@AllowsNull_9b7d5a76 BIT,
@DefaultValue_9b7d5a76 NVARCHAR(255),
@IsPrimaryKey_9b7d5a76 BIT,
@IsUniqueKey_9b7d5a76 BIT,
@IsReadOnly_9b7d5a76 BIT,
@IsRequired_9b7d5a76 BIT,
@RelatedIntegrationObjectID_9b7d5a76 UNIQUEIDENTIFIER,
@RelatedIntegrationObjectFieldName_9b7d5a76 NVARCHAR(255),
@Sequence_9b7d5a76 INT,
@Configuration_9b7d5a76 NVARCHAR(MAX),
@Status_9b7d5a76 NVARCHAR(25),
@IsCustom_9b7d5a76 BIT,
@MetadataSource_9b7d5a76 NVARCHAR(20),
@ID_9b7d5a76 UNIQUEIDENTIFIER
SET
  @IntegrationObjectID_9b7d5a76 = 'C25F2978-8DF7-42F5-83FD-57D514B474A1'
SET
  @Name_9b7d5a76 = N'Description'
SET
  @DisplayName_9b7d5a76 = N'Description'
SET
  @Type_9b7d5a76 = N'String'
SET
  @Length_9b7d5a76 = 4000
SET
  @AllowsNull_9b7d5a76 = 1
SET
  @IsPrimaryKey_9b7d5a76 = 0
SET
  @IsUniqueKey_9b7d5a76 = 0
SET
  @IsReadOnly_9b7d5a76 = 0
SET
  @IsRequired_9b7d5a76 = 0
SET
  @Sequence_9b7d5a76 = 0
SET
  @Status_9b7d5a76 = N'Active'
SET
  @IsCustom_9b7d5a76 = 0
SET
  @MetadataSource_9b7d5a76 = N'Declared'
SET
  @ID_9b7d5a76 = '49FB5C13-F937-4EEC-8665-300541B8CABC' EXEC [__mj].spUpdateIntegrationObjectField @IntegrationObjectID = @IntegrationObjectID_9b7d5a76,
  @Name = @Name_9b7d5a76,
  @DisplayName = @DisplayName_9b7d5a76,
  @Description = @Description_9b7d5a76,
  @Description_Clear = 1,
  @Category = @Category_9b7d5a76,
  @Category_Clear = 1,
  @Type = @Type_9b7d5a76,
  @Length = @Length_9b7d5a76,
  @Precision = @Precision_9b7d5a76,
  @Precision_Clear = 1,
  @Scale = @Scale_9b7d5a76,
  @Scale_Clear = 1,
  @AllowsNull = @AllowsNull_9b7d5a76,
  @DefaultValue = @DefaultValue_9b7d5a76,
  @DefaultValue_Clear = 1,
  @IsPrimaryKey = @IsPrimaryKey_9b7d5a76,
  @IsUniqueKey = @IsUniqueKey_9b7d5a76,
  @IsReadOnly = @IsReadOnly_9b7d5a76,
  @IsRequired = @IsRequired_9b7d5a76,
  @RelatedIntegrationObjectID = @RelatedIntegrationObjectID_9b7d5a76,
  @RelatedIntegrationObjectID_Clear = 1,
  @RelatedIntegrationObjectFieldName = @RelatedIntegrationObjectFieldName_9b7d5a76,
  @RelatedIntegrationObjectFieldName_Clear = 1,
  @Sequence = @Sequence_9b7d5a76,
  @Configuration = @Configuration_9b7d5a76,
  @Configuration_Clear = 1,
  @Status = @Status_9b7d5a76,
  @IsCustom = @IsCustom_9b7d5a76,
  @MetadataSource = @MetadataSource_9b7d5a76,
  @ID = @ID_9b7d5a76;

GO

-- Save MJ: Integration Object Fields (core SP call only)
DECLARE @IntegrationObjectID_ae348e67 UNIQUEIDENTIFIER,
@Name_ae348e67 NVARCHAR(255),
@DisplayName_ae348e67 NVARCHAR(255),
@Description_ae348e67 NVARCHAR(MAX),
@Category_ae348e67 NVARCHAR(100),
@Type_ae348e67 NVARCHAR(100),
@Length_ae348e67 INT,
@Precision_ae348e67 INT,
@Scale_ae348e67 INT,
@AllowsNull_ae348e67 BIT,
@DefaultValue_ae348e67 NVARCHAR(255),
@IsPrimaryKey_ae348e67 BIT,
@IsUniqueKey_ae348e67 BIT,
@IsReadOnly_ae348e67 BIT,
@IsRequired_ae348e67 BIT,
@RelatedIntegrationObjectID_ae348e67 UNIQUEIDENTIFIER,
@RelatedIntegrationObjectFieldName_ae348e67 NVARCHAR(255),
@Sequence_ae348e67 INT,
@Configuration_ae348e67 NVARCHAR(MAX),
@Status_ae348e67 NVARCHAR(25),
@IsCustom_ae348e67 BIT,
@MetadataSource_ae348e67 NVARCHAR(20),
@ID_ae348e67 UNIQUEIDENTIFIER
SET
  @IntegrationObjectID_ae348e67 = 'D2926FD8-8018-4986-B5D7-62BA082F99CE'
SET
  @Name_ae348e67 = N'Email'
SET
  @DisplayName_ae348e67 = N'Email'
SET
  @Type_ae348e67 = N'String'
SET
  @Length_ae348e67 = 320
SET
  @AllowsNull_ae348e67 = 1
SET
  @IsPrimaryKey_ae348e67 = 0
SET
  @IsUniqueKey_ae348e67 = 0
SET
  @IsReadOnly_ae348e67 = 0
SET
  @IsRequired_ae348e67 = 0
SET
  @Sequence_ae348e67 = 0
SET
  @Status_ae348e67 = N'Active'
SET
  @IsCustom_ae348e67 = 0
SET
  @MetadataSource_ae348e67 = N'Declared'
SET
  @ID_ae348e67 = '80464726-6F1E-404E-879D-AC5564285E65' EXEC [__mj].spUpdateIntegrationObjectField @IntegrationObjectID = @IntegrationObjectID_ae348e67,
  @Name = @Name_ae348e67,
  @DisplayName = @DisplayName_ae348e67,
  @Description = @Description_ae348e67,
  @Description_Clear = 1,
  @Category = @Category_ae348e67,
  @Category_Clear = 1,
  @Type = @Type_ae348e67,
  @Length = @Length_ae348e67,
  @Precision = @Precision_ae348e67,
  @Precision_Clear = 1,
  @Scale = @Scale_ae348e67,
  @Scale_Clear = 1,
  @AllowsNull = @AllowsNull_ae348e67,
  @DefaultValue = @DefaultValue_ae348e67,
  @DefaultValue_Clear = 1,
  @IsPrimaryKey = @IsPrimaryKey_ae348e67,
  @IsUniqueKey = @IsUniqueKey_ae348e67,
  @IsReadOnly = @IsReadOnly_ae348e67,
  @IsRequired = @IsRequired_ae348e67,
  @RelatedIntegrationObjectID = @RelatedIntegrationObjectID_ae348e67,
  @RelatedIntegrationObjectID_Clear = 1,
  @RelatedIntegrationObjectFieldName = @RelatedIntegrationObjectFieldName_ae348e67,
  @RelatedIntegrationObjectFieldName_Clear = 1,
  @Sequence = @Sequence_ae348e67,
  @Configuration = @Configuration_ae348e67,
  @Configuration_Clear = 1,
  @Status = @Status_ae348e67,
  @IsCustom = @IsCustom_ae348e67,
  @MetadataSource = @MetadataSource_ae348e67,
  @ID = @ID_ae348e67;

GO

-- Save MJ: Integration Object Fields (core SP call only)
DECLARE @IntegrationObjectID_42a917b4 UNIQUEIDENTIFIER,
@Name_42a917b4 NVARCHAR(255),
@DisplayName_42a917b4 NVARCHAR(255),
@Description_42a917b4 NVARCHAR(MAX),
@Category_42a917b4 NVARCHAR(100),
@Type_42a917b4 NVARCHAR(100),
@Length_42a917b4 INT,
@Precision_42a917b4 INT,
@Scale_42a917b4 INT,
@AllowsNull_42a917b4 BIT,
@DefaultValue_42a917b4 NVARCHAR(255),
@IsPrimaryKey_42a917b4 BIT,
@IsUniqueKey_42a917b4 BIT,
@IsReadOnly_42a917b4 BIT,
@IsRequired_42a917b4 BIT,
@RelatedIntegrationObjectID_42a917b4 UNIQUEIDENTIFIER,
@RelatedIntegrationObjectFieldName_42a917b4 NVARCHAR(255),
@Sequence_42a917b4 INT,
@Configuration_42a917b4 NVARCHAR(MAX),
@Status_42a917b4 NVARCHAR(25),
@IsCustom_42a917b4 BIT,
@MetadataSource_42a917b4 NVARCHAR(20),
@ID_42a917b4 UNIQUEIDENTIFIER
SET
  @IntegrationObjectID_42a917b4 = '39C059DB-A3F3-4E4B-8BB2-C8525407D048'
SET
  @Name_42a917b4 = N'Description'
SET
  @DisplayName_42a917b4 = N'Description'
SET
  @Type_42a917b4 = N'String'
SET
  @Length_42a917b4 = 4000
SET
  @AllowsNull_42a917b4 = 1
SET
  @IsPrimaryKey_42a917b4 = 0
SET
  @IsUniqueKey_42a917b4 = 0
SET
  @IsReadOnly_42a917b4 = 0
SET
  @IsRequired_42a917b4 = 0
SET
  @Sequence_42a917b4 = 0
SET
  @Status_42a917b4 = N'Active'
SET
  @IsCustom_42a917b4 = 0
SET
  @MetadataSource_42a917b4 = N'Declared'
SET
  @ID_42a917b4 = '19DDA757-BD88-4362-93D9-BDD40C1B7155' EXEC [__mj].spUpdateIntegrationObjectField @IntegrationObjectID = @IntegrationObjectID_42a917b4,
  @Name = @Name_42a917b4,
  @DisplayName = @DisplayName_42a917b4,
  @Description = @Description_42a917b4,
  @Description_Clear = 1,
  @Category = @Category_42a917b4,
  @Category_Clear = 1,
  @Type = @Type_42a917b4,
  @Length = @Length_42a917b4,
  @Precision = @Precision_42a917b4,
  @Precision_Clear = 1,
  @Scale = @Scale_42a917b4,
  @Scale_Clear = 1,
  @AllowsNull = @AllowsNull_42a917b4,
  @DefaultValue = @DefaultValue_42a917b4,
  @DefaultValue_Clear = 1,
  @IsPrimaryKey = @IsPrimaryKey_42a917b4,
  @IsUniqueKey = @IsUniqueKey_42a917b4,
  @IsReadOnly = @IsReadOnly_42a917b4,
  @IsRequired = @IsRequired_42a917b4,
  @RelatedIntegrationObjectID = @RelatedIntegrationObjectID_42a917b4,
  @RelatedIntegrationObjectID_Clear = 1,
  @RelatedIntegrationObjectFieldName = @RelatedIntegrationObjectFieldName_42a917b4,
  @RelatedIntegrationObjectFieldName_Clear = 1,
  @Sequence = @Sequence_42a917b4,
  @Configuration = @Configuration_42a917b4,
  @Configuration_Clear = 1,
  @Status = @Status_42a917b4,
  @IsCustom = @IsCustom_42a917b4,
  @MetadataSource = @MetadataSource_42a917b4,
  @ID = @ID_42a917b4;

GO

-- Save MJ: Integration Object Fields (core SP call only)
DECLARE @IntegrationObjectID_2c8548e5 UNIQUEIDENTIFIER,
@Name_2c8548e5 NVARCHAR(255),
@DisplayName_2c8548e5 NVARCHAR(255),
@Description_2c8548e5 NVARCHAR(MAX),
@Category_2c8548e5 NVARCHAR(100),
@Type_2c8548e5 NVARCHAR(100),
@Length_2c8548e5 INT,
@Precision_2c8548e5 INT,
@Scale_2c8548e5 INT,
@AllowsNull_2c8548e5 BIT,
@DefaultValue_2c8548e5 NVARCHAR(255),
@IsPrimaryKey_2c8548e5 BIT,
@IsUniqueKey_2c8548e5 BIT,
@IsReadOnly_2c8548e5 BIT,
@IsRequired_2c8548e5 BIT,
@RelatedIntegrationObjectID_2c8548e5 UNIQUEIDENTIFIER,
@RelatedIntegrationObjectFieldName_2c8548e5 NVARCHAR(255),
@Sequence_2c8548e5 INT,
@Configuration_2c8548e5 NVARCHAR(MAX),
@Status_2c8548e5 NVARCHAR(25),
@IsCustom_2c8548e5 BIT,
@MetadataSource_2c8548e5 NVARCHAR(20),
@ID_2c8548e5 UNIQUEIDENTIFIER
SET
  @IntegrationObjectID_2c8548e5 = '5020922A-C104-4D7B-9CB0-3CDC331DBF83'
SET
  @Name_2c8548e5 = N'EmailAddress'
SET
  @DisplayName_2c8548e5 = N'EmailAddress'
SET
  @Type_2c8548e5 = N'String'
SET
  @Length_2c8548e5 = 320
SET
  @AllowsNull_2c8548e5 = 1
SET
  @IsPrimaryKey_2c8548e5 = 0
SET
  @IsUniqueKey_2c8548e5 = 0
SET
  @IsReadOnly_2c8548e5 = 0
SET
  @IsRequired_2c8548e5 = 0
SET
  @Sequence_2c8548e5 = 0
SET
  @Status_2c8548e5 = N'Active'
SET
  @IsCustom_2c8548e5 = 0
SET
  @MetadataSource_2c8548e5 = N'Declared'
SET
  @ID_2c8548e5 = '239334D8-740D-4E91-8751-9ADFABF6FFAA' EXEC [__mj].spUpdateIntegrationObjectField @IntegrationObjectID = @IntegrationObjectID_2c8548e5,
  @Name = @Name_2c8548e5,
  @DisplayName = @DisplayName_2c8548e5,
  @Description = @Description_2c8548e5,
  @Description_Clear = 1,
  @Category = @Category_2c8548e5,
  @Category_Clear = 1,
  @Type = @Type_2c8548e5,
  @Length = @Length_2c8548e5,
  @Precision = @Precision_2c8548e5,
  @Precision_Clear = 1,
  @Scale = @Scale_2c8548e5,
  @Scale_Clear = 1,
  @AllowsNull = @AllowsNull_2c8548e5,
  @DefaultValue = @DefaultValue_2c8548e5,
  @DefaultValue_Clear = 1,
  @IsPrimaryKey = @IsPrimaryKey_2c8548e5,
  @IsUniqueKey = @IsUniqueKey_2c8548e5,
  @IsReadOnly = @IsReadOnly_2c8548e5,
  @IsRequired = @IsRequired_2c8548e5,
  @RelatedIntegrationObjectID = @RelatedIntegrationObjectID_2c8548e5,
  @RelatedIntegrationObjectID_Clear = 1,
  @RelatedIntegrationObjectFieldName = @RelatedIntegrationObjectFieldName_2c8548e5,
  @RelatedIntegrationObjectFieldName_Clear = 1,
  @Sequence = @Sequence_2c8548e5,
  @Configuration = @Configuration_2c8548e5,
  @Configuration_Clear = 1,
  @Status = @Status_2c8548e5,
  @IsCustom = @IsCustom_2c8548e5,
  @MetadataSource = @MetadataSource_2c8548e5,
  @ID = @ID_2c8548e5;

GO

-- Save MJ: Integration Object Fields (core SP call only)
DECLARE @IntegrationObjectID_ac9f8860 UNIQUEIDENTIFIER,
@Name_ac9f8860 NVARCHAR(255),
@DisplayName_ac9f8860 NVARCHAR(255),
@Description_ac9f8860 NVARCHAR(MAX),
@Category_ac9f8860 NVARCHAR(100),
@Type_ac9f8860 NVARCHAR(100),
@Length_ac9f8860 INT,
@Precision_ac9f8860 INT,
@Scale_ac9f8860 INT,
@AllowsNull_ac9f8860 BIT,
@DefaultValue_ac9f8860 NVARCHAR(255),
@IsPrimaryKey_ac9f8860 BIT,
@IsUniqueKey_ac9f8860 BIT,
@IsReadOnly_ac9f8860 BIT,
@IsRequired_ac9f8860 BIT,
@RelatedIntegrationObjectID_ac9f8860 UNIQUEIDENTIFIER,
@RelatedIntegrationObjectFieldName_ac9f8860 NVARCHAR(255),
@Sequence_ac9f8860 INT,
@Configuration_ac9f8860 NVARCHAR(MAX),
@Status_ac9f8860 NVARCHAR(25),
@IsCustom_ac9f8860 BIT,
@MetadataSource_ac9f8860 NVARCHAR(20),
@ID_ac9f8860 UNIQUEIDENTIFIER
SET
  @IntegrationObjectID_ac9f8860 = 'C99E8825-F34A-4BC9-8D56-08BAE5F109CC'
SET
  @Name_ac9f8860 = N'Description'
SET
  @DisplayName_ac9f8860 = N'Description'
SET
  @Type_ac9f8860 = N'String'
SET
  @Length_ac9f8860 = 4000
SET
  @AllowsNull_ac9f8860 = 1
SET
  @IsPrimaryKey_ac9f8860 = 0
SET
  @IsUniqueKey_ac9f8860 = 0
SET
  @IsReadOnly_ac9f8860 = 0
SET
  @IsRequired_ac9f8860 = 0
SET
  @Sequence_ac9f8860 = 0
SET
  @Status_ac9f8860 = N'Active'
SET
  @IsCustom_ac9f8860 = 0
SET
  @MetadataSource_ac9f8860 = N'Declared'
SET
  @ID_ac9f8860 = '6D52876C-9C27-410D-BA08-F4829498B517' EXEC [__mj].spUpdateIntegrationObjectField @IntegrationObjectID = @IntegrationObjectID_ac9f8860,
  @Name = @Name_ac9f8860,
  @DisplayName = @DisplayName_ac9f8860,
  @Description = @Description_ac9f8860,
  @Description_Clear = 1,
  @Category = @Category_ac9f8860,
  @Category_Clear = 1,
  @Type = @Type_ac9f8860,
  @Length = @Length_ac9f8860,
  @Precision = @Precision_ac9f8860,
  @Precision_Clear = 1,
  @Scale = @Scale_ac9f8860,
  @Scale_Clear = 1,
  @AllowsNull = @AllowsNull_ac9f8860,
  @DefaultValue = @DefaultValue_ac9f8860,
  @DefaultValue_Clear = 1,
  @IsPrimaryKey = @IsPrimaryKey_ac9f8860,
  @IsUniqueKey = @IsUniqueKey_ac9f8860,
  @IsReadOnly = @IsReadOnly_ac9f8860,
  @IsRequired = @IsRequired_ac9f8860,
  @RelatedIntegrationObjectID = @RelatedIntegrationObjectID_ac9f8860,
  @RelatedIntegrationObjectID_Clear = 1,
  @RelatedIntegrationObjectFieldName = @RelatedIntegrationObjectFieldName_ac9f8860,
  @RelatedIntegrationObjectFieldName_Clear = 1,
  @Sequence = @Sequence_ac9f8860,
  @Configuration = @Configuration_ac9f8860,
  @Configuration_Clear = 1,
  @Status = @Status_ac9f8860,
  @IsCustom = @IsCustom_ac9f8860,
  @MetadataSource = @MetadataSource_ac9f8860,
  @ID = @ID_ac9f8860;

GO

-- Save MJ: Integration Object Fields (core SP call only)
DECLARE @IntegrationObjectID_db9380af UNIQUEIDENTIFIER,
@Name_db9380af NVARCHAR(255),
@DisplayName_db9380af NVARCHAR(255),
@Description_db9380af NVARCHAR(MAX),
@Category_db9380af NVARCHAR(100),
@Type_db9380af NVARCHAR(100),
@Length_db9380af INT,
@Precision_db9380af INT,
@Scale_db9380af INT,
@AllowsNull_db9380af BIT,
@DefaultValue_db9380af NVARCHAR(255),
@IsPrimaryKey_db9380af BIT,
@IsUniqueKey_db9380af BIT,
@IsReadOnly_db9380af BIT,
@IsRequired_db9380af BIT,
@RelatedIntegrationObjectID_db9380af UNIQUEIDENTIFIER,
@RelatedIntegrationObjectFieldName_db9380af NVARCHAR(255),
@Sequence_db9380af INT,
@Configuration_db9380af NVARCHAR(MAX),
@Status_db9380af NVARCHAR(25),
@IsCustom_db9380af BIT,
@MetadataSource_db9380af NVARCHAR(20),
@ID_db9380af UNIQUEIDENTIFIER
SET
  @IntegrationObjectID_db9380af = 'E8E2AC85-3BAF-4FCC-BF94-05FCA2973638'
SET
  @Name_db9380af = N'WebSite'
SET
  @DisplayName_db9380af = N'WebSite'
SET
  @Type_db9380af = N'String'
SET
  @Length_db9380af = 2048
SET
  @AllowsNull_db9380af = 1
SET
  @IsPrimaryKey_db9380af = 0
SET
  @IsUniqueKey_db9380af = 0
SET
  @IsReadOnly_db9380af = 0
SET
  @IsRequired_db9380af = 0
SET
  @Sequence_db9380af = 0
SET
  @Status_db9380af = N'Active'
SET
  @IsCustom_db9380af = 0
SET
  @MetadataSource_db9380af = N'Declared'
SET
  @ID_db9380af = '9871C7E5-DAC0-4C9D-B019-0E27D58339E7' EXEC [__mj].spUpdateIntegrationObjectField @IntegrationObjectID = @IntegrationObjectID_db9380af,
  @Name = @Name_db9380af,
  @DisplayName = @DisplayName_db9380af,
  @Description = @Description_db9380af,
  @Description_Clear = 1,
  @Category = @Category_db9380af,
  @Category_Clear = 1,
  @Type = @Type_db9380af,
  @Length = @Length_db9380af,
  @Precision = @Precision_db9380af,
  @Precision_Clear = 1,
  @Scale = @Scale_db9380af,
  @Scale_Clear = 1,
  @AllowsNull = @AllowsNull_db9380af,
  @DefaultValue = @DefaultValue_db9380af,
  @DefaultValue_Clear = 1,
  @IsPrimaryKey = @IsPrimaryKey_db9380af,
  @IsUniqueKey = @IsUniqueKey_db9380af,
  @IsReadOnly = @IsReadOnly_db9380af,
  @IsRequired = @IsRequired_db9380af,
  @RelatedIntegrationObjectID = @RelatedIntegrationObjectID_db9380af,
  @RelatedIntegrationObjectID_Clear = 1,
  @RelatedIntegrationObjectFieldName = @RelatedIntegrationObjectFieldName_db9380af,
  @RelatedIntegrationObjectFieldName_Clear = 1,
  @Sequence = @Sequence_db9380af,
  @Configuration = @Configuration_db9380af,
  @Configuration_Clear = 1,
  @Status = @Status_db9380af,
  @IsCustom = @IsCustom_db9380af,
  @MetadataSource = @MetadataSource_db9380af,
  @ID = @ID_db9380af;

GO

-- Save MJ: Integration Object Fields (core SP call only)
DECLARE @IntegrationObjectID_87b952ef UNIQUEIDENTIFIER,
@Name_87b952ef NVARCHAR(255),
@DisplayName_87b952ef NVARCHAR(255),
@Description_87b952ef NVARCHAR(MAX),
@Category_87b952ef NVARCHAR(100),
@Type_87b952ef NVARCHAR(100),
@Length_87b952ef INT,
@Precision_87b952ef INT,
@Scale_87b952ef INT,
@AllowsNull_87b952ef BIT,
@DefaultValue_87b952ef NVARCHAR(255),
@IsPrimaryKey_87b952ef BIT,
@IsUniqueKey_87b952ef BIT,
@IsReadOnly_87b952ef BIT,
@IsRequired_87b952ef BIT,
@RelatedIntegrationObjectID_87b952ef UNIQUEIDENTIFIER,
@RelatedIntegrationObjectFieldName_87b952ef NVARCHAR(255),
@Sequence_87b952ef INT,
@Configuration_87b952ef NVARCHAR(MAX),
@Status_87b952ef NVARCHAR(25),
@IsCustom_87b952ef BIT,
@MetadataSource_87b952ef NVARCHAR(20),
@ID_87b952ef UNIQUEIDENTIFIER
SET
  @IntegrationObjectID_87b952ef = 'E8E2AC85-3BAF-4FCC-BF94-05FCA2973638'
SET
  @Name_87b952ef = N'EmailAddress'
SET
  @DisplayName_87b952ef = N'EmailAddress'
SET
  @Type_87b952ef = N'String'
SET
  @Length_87b952ef = 320
SET
  @AllowsNull_87b952ef = 1
SET
  @IsPrimaryKey_87b952ef = 0
SET
  @IsUniqueKey_87b952ef = 0
SET
  @IsReadOnly_87b952ef = 0
SET
  @IsRequired_87b952ef = 0
SET
  @Sequence_87b952ef = 0
SET
  @Status_87b952ef = N'Active'
SET
  @IsCustom_87b952ef = 0
SET
  @MetadataSource_87b952ef = N'Declared'
SET
  @ID_87b952ef = 'F95F6E91-2C55-4888-B7FB-3D9B0DF6F435' EXEC [__mj].spUpdateIntegrationObjectField @IntegrationObjectID = @IntegrationObjectID_87b952ef,
  @Name = @Name_87b952ef,
  @DisplayName = @DisplayName_87b952ef,
  @Description = @Description_87b952ef,
  @Description_Clear = 1,
  @Category = @Category_87b952ef,
  @Category_Clear = 1,
  @Type = @Type_87b952ef,
  @Length = @Length_87b952ef,
  @Precision = @Precision_87b952ef,
  @Precision_Clear = 1,
  @Scale = @Scale_87b952ef,
  @Scale_Clear = 1,
  @AllowsNull = @AllowsNull_87b952ef,
  @DefaultValue = @DefaultValue_87b952ef,
  @DefaultValue_Clear = 1,
  @IsPrimaryKey = @IsPrimaryKey_87b952ef,
  @IsUniqueKey = @IsUniqueKey_87b952ef,
  @IsReadOnly = @IsReadOnly_87b952ef,
  @IsRequired = @IsRequired_87b952ef,
  @RelatedIntegrationObjectID = @RelatedIntegrationObjectID_87b952ef,
  @RelatedIntegrationObjectID_Clear = 1,
  @RelatedIntegrationObjectFieldName = @RelatedIntegrationObjectFieldName_87b952ef,
  @RelatedIntegrationObjectFieldName_Clear = 1,
  @Sequence = @Sequence_87b952ef,
  @Configuration = @Configuration_87b952ef,
  @Configuration_Clear = 1,
  @Status = @Status_87b952ef,
  @IsCustom = @IsCustom_87b952ef,
  @MetadataSource = @MetadataSource_87b952ef,
  @ID = @ID_87b952ef;

GO

-- Save MJ: Integration Object Fields (core SP call only)
DECLARE @IntegrationObjectID_75fd4860 UNIQUEIDENTIFIER,
@Name_75fd4860 NVARCHAR(255),
@DisplayName_75fd4860 NVARCHAR(255),
@Description_75fd4860 NVARCHAR(MAX),
@Category_75fd4860 NVARCHAR(100),
@Type_75fd4860 NVARCHAR(100),
@Length_75fd4860 INT,
@Precision_75fd4860 INT,
@Scale_75fd4860 INT,
@AllowsNull_75fd4860 BIT,
@DefaultValue_75fd4860 NVARCHAR(255),
@IsPrimaryKey_75fd4860 BIT,
@IsUniqueKey_75fd4860 BIT,
@IsReadOnly_75fd4860 BIT,
@IsRequired_75fd4860 BIT,
@RelatedIntegrationObjectID_75fd4860 UNIQUEIDENTIFIER,
@RelatedIntegrationObjectFieldName_75fd4860 NVARCHAR(255),
@Sequence_75fd4860 INT,
@Configuration_75fd4860 NVARCHAR(MAX),
@Status_75fd4860 NVARCHAR(25),
@IsCustom_75fd4860 BIT,
@MetadataSource_75fd4860 NVARCHAR(20),
@ID_75fd4860 UNIQUEIDENTIFIER
SET
  @IntegrationObjectID_75fd4860 = 'E8E2AC85-3BAF-4FCC-BF94-05FCA2973638'
SET
  @Name_75fd4860 = N'Description'
SET
  @DisplayName_75fd4860 = N'Description'
SET
  @Type_75fd4860 = N'String'
SET
  @Length_75fd4860 = 4000
SET
  @AllowsNull_75fd4860 = 1
SET
  @IsPrimaryKey_75fd4860 = 0
SET
  @IsUniqueKey_75fd4860 = 0
SET
  @IsReadOnly_75fd4860 = 0
SET
  @IsRequired_75fd4860 = 0
SET
  @Sequence_75fd4860 = 0
SET
  @Status_75fd4860 = N'Active'
SET
  @IsCustom_75fd4860 = 0
SET
  @MetadataSource_75fd4860 = N'Declared'
SET
  @ID_75fd4860 = 'B0495687-1FB6-49DF-A38A-42373A57E0DD' EXEC [__mj].spUpdateIntegrationObjectField @IntegrationObjectID = @IntegrationObjectID_75fd4860,
  @Name = @Name_75fd4860,
  @DisplayName = @DisplayName_75fd4860,
  @Description = @Description_75fd4860,
  @Description_Clear = 1,
  @Category = @Category_75fd4860,
  @Category_Clear = 1,
  @Type = @Type_75fd4860,
  @Length = @Length_75fd4860,
  @Precision = @Precision_75fd4860,
  @Precision_Clear = 1,
  @Scale = @Scale_75fd4860,
  @Scale_Clear = 1,
  @AllowsNull = @AllowsNull_75fd4860,
  @DefaultValue = @DefaultValue_75fd4860,
  @DefaultValue_Clear = 1,
  @IsPrimaryKey = @IsPrimaryKey_75fd4860,
  @IsUniqueKey = @IsUniqueKey_75fd4860,
  @IsReadOnly = @IsReadOnly_75fd4860,
  @IsRequired = @IsRequired_75fd4860,
  @RelatedIntegrationObjectID = @RelatedIntegrationObjectID_75fd4860,
  @RelatedIntegrationObjectID_Clear = 1,
  @RelatedIntegrationObjectFieldName = @RelatedIntegrationObjectFieldName_75fd4860,
  @RelatedIntegrationObjectFieldName_Clear = 1,
  @Sequence = @Sequence_75fd4860,
  @Configuration = @Configuration_75fd4860,
  @Configuration_Clear = 1,
  @Status = @Status_75fd4860,
  @IsCustom = @IsCustom_75fd4860,
  @MetadataSource = @MetadataSource_75fd4860,
  @ID = @ID_75fd4860;

GO

-- Save MJ: Integration Object Fields (core SP call only)
DECLARE @IntegrationObjectID_b858de56 UNIQUEIDENTIFIER,
@Name_b858de56 NVARCHAR(255),
@DisplayName_b858de56 NVARCHAR(255),
@Description_b858de56 NVARCHAR(MAX),
@Category_b858de56 NVARCHAR(100),
@Type_b858de56 NVARCHAR(100),
@Length_b858de56 INT,
@Precision_b858de56 INT,
@Scale_b858de56 INT,
@AllowsNull_b858de56 BIT,
@DefaultValue_b858de56 NVARCHAR(255),
@IsPrimaryKey_b858de56 BIT,
@IsUniqueKey_b858de56 BIT,
@IsReadOnly_b858de56 BIT,
@IsRequired_b858de56 BIT,
@RelatedIntegrationObjectID_b858de56 UNIQUEIDENTIFIER,
@RelatedIntegrationObjectFieldName_b858de56 NVARCHAR(255),
@Sequence_b858de56 INT,
@Configuration_b858de56 NVARCHAR(MAX),
@Status_b858de56 NVARCHAR(25),
@IsCustom_b858de56 BIT,
@MetadataSource_b858de56 NVARCHAR(20),
@ID_b858de56 UNIQUEIDENTIFIER
SET
  @IntegrationObjectID_b858de56 = 'E8E2AC85-3BAF-4FCC-BF94-05FCA2973638'
SET
  @Name_b858de56 = N'Comments'
SET
  @DisplayName_b858de56 = N'Comments'
SET
  @Type_b858de56 = N'String'
SET
  @Length_b858de56 = 4000
SET
  @AllowsNull_b858de56 = 1
SET
  @IsPrimaryKey_b858de56 = 0
SET
  @IsUniqueKey_b858de56 = 0
SET
  @IsReadOnly_b858de56 = 0
SET
  @IsRequired_b858de56 = 0
SET
  @Sequence_b858de56 = 0
SET
  @Status_b858de56 = N'Active'
SET
  @IsCustom_b858de56 = 0
SET
  @MetadataSource_b858de56 = N'Declared'
SET
  @ID_b858de56 = 'DB4AB445-9BB2-44C9-A2E4-4A72CB0F42E6' EXEC [__mj].spUpdateIntegrationObjectField @IntegrationObjectID = @IntegrationObjectID_b858de56,
  @Name = @Name_b858de56,
  @DisplayName = @DisplayName_b858de56,
  @Description = @Description_b858de56,
  @Description_Clear = 1,
  @Category = @Category_b858de56,
  @Category_Clear = 1,
  @Type = @Type_b858de56,
  @Length = @Length_b858de56,
  @Precision = @Precision_b858de56,
  @Precision_Clear = 1,
  @Scale = @Scale_b858de56,
  @Scale_Clear = 1,
  @AllowsNull = @AllowsNull_b858de56,
  @DefaultValue = @DefaultValue_b858de56,
  @DefaultValue_Clear = 1,
  @IsPrimaryKey = @IsPrimaryKey_b858de56,
  @IsUniqueKey = @IsUniqueKey_b858de56,
  @IsReadOnly = @IsReadOnly_b858de56,
  @IsRequired = @IsRequired_b858de56,
  @RelatedIntegrationObjectID = @RelatedIntegrationObjectID_b858de56,
  @RelatedIntegrationObjectID_Clear = 1,
  @RelatedIntegrationObjectFieldName = @RelatedIntegrationObjectFieldName_b858de56,
  @RelatedIntegrationObjectFieldName_Clear = 1,
  @Sequence = @Sequence_b858de56,
  @Configuration = @Configuration_b858de56,
  @Configuration_Clear = 1,
  @Status = @Status_b858de56,
  @IsCustom = @IsCustom_b858de56,
  @MetadataSource = @MetadataSource_b858de56,
  @ID = @ID_b858de56;

GO

-- Save MJ: Integration Object Fields (core SP call only)
DECLARE @IntegrationObjectID_e4ab1423 UNIQUEIDENTIFIER,
@Name_e4ab1423 NVARCHAR(255),
@DisplayName_e4ab1423 NVARCHAR(255),
@Description_e4ab1423 NVARCHAR(MAX),
@Category_e4ab1423 NVARCHAR(100),
@Type_e4ab1423 NVARCHAR(100),
@Length_e4ab1423 INT,
@Precision_e4ab1423 INT,
@Scale_e4ab1423 INT,
@AllowsNull_e4ab1423 BIT,
@DefaultValue_e4ab1423 NVARCHAR(255),
@IsPrimaryKey_e4ab1423 BIT,
@IsUniqueKey_e4ab1423 BIT,
@IsReadOnly_e4ab1423 BIT,
@IsRequired_e4ab1423 BIT,
@RelatedIntegrationObjectID_e4ab1423 UNIQUEIDENTIFIER,
@RelatedIntegrationObjectFieldName_e4ab1423 NVARCHAR(255),
@Sequence_e4ab1423 INT,
@Configuration_e4ab1423 NVARCHAR(MAX),
@Status_e4ab1423 NVARCHAR(25),
@IsCustom_e4ab1423 BIT,
@MetadataSource_e4ab1423 NVARCHAR(20),
@ID_e4ab1423 UNIQUEIDENTIFIER
SET
  @IntegrationObjectID_e4ab1423 = 'FB957A57-6B2C-4DCC-B54A-044081BA8CDE'
SET
  @Name_e4ab1423 = N'Description'
SET
  @DisplayName_e4ab1423 = N'Description'
SET
  @Type_e4ab1423 = N'String'
SET
  @Length_e4ab1423 = 4000
SET
  @AllowsNull_e4ab1423 = 1
SET
  @IsPrimaryKey_e4ab1423 = 0
SET
  @IsUniqueKey_e4ab1423 = 0
SET
  @IsReadOnly_e4ab1423 = 0
SET
  @IsRequired_e4ab1423 = 0
SET
  @Sequence_e4ab1423 = 0
SET
  @Status_e4ab1423 = N'Active'
SET
  @IsCustom_e4ab1423 = 0
SET
  @MetadataSource_e4ab1423 = N'Declared'
SET
  @ID_e4ab1423 = '493DE738-792C-4A0A-A922-A3A30000C56F' EXEC [__mj].spUpdateIntegrationObjectField @IntegrationObjectID = @IntegrationObjectID_e4ab1423,
  @Name = @Name_e4ab1423,
  @DisplayName = @DisplayName_e4ab1423,
  @Description = @Description_e4ab1423,
  @Description_Clear = 1,
  @Category = @Category_e4ab1423,
  @Category_Clear = 1,
  @Type = @Type_e4ab1423,
  @Length = @Length_e4ab1423,
  @Precision = @Precision_e4ab1423,
  @Precision_Clear = 1,
  @Scale = @Scale_e4ab1423,
  @Scale_Clear = 1,
  @AllowsNull = @AllowsNull_e4ab1423,
  @DefaultValue = @DefaultValue_e4ab1423,
  @DefaultValue_Clear = 1,
  @IsPrimaryKey = @IsPrimaryKey_e4ab1423,
  @IsUniqueKey = @IsUniqueKey_e4ab1423,
  @IsReadOnly = @IsReadOnly_e4ab1423,
  @IsRequired = @IsRequired_e4ab1423,
  @RelatedIntegrationObjectID = @RelatedIntegrationObjectID_e4ab1423,
  @RelatedIntegrationObjectID_Clear = 1,
  @RelatedIntegrationObjectFieldName = @RelatedIntegrationObjectFieldName_e4ab1423,
  @RelatedIntegrationObjectFieldName_Clear = 1,
  @Sequence = @Sequence_e4ab1423,
  @Configuration = @Configuration_e4ab1423,
  @Configuration_Clear = 1,
  @Status = @Status_e4ab1423,
  @IsCustom = @IsCustom_e4ab1423,
  @MetadataSource = @MetadataSource_e4ab1423,
  @ID = @ID_e4ab1423;

GO

-- Save MJ: Integration Object Fields (core SP call only)
DECLARE @IntegrationObjectID_aedb6d30 UNIQUEIDENTIFIER,
@Name_aedb6d30 NVARCHAR(255),
@DisplayName_aedb6d30 NVARCHAR(255),
@Description_aedb6d30 NVARCHAR(MAX),
@Category_aedb6d30 NVARCHAR(100),
@Type_aedb6d30 NVARCHAR(100),
@Length_aedb6d30 INT,
@Precision_aedb6d30 INT,
@Scale_aedb6d30 INT,
@AllowsNull_aedb6d30 BIT,
@DefaultValue_aedb6d30 NVARCHAR(255),
@IsPrimaryKey_aedb6d30 BIT,
@IsUniqueKey_aedb6d30 BIT,
@IsReadOnly_aedb6d30 BIT,
@IsRequired_aedb6d30 BIT,
@RelatedIntegrationObjectID_aedb6d30 UNIQUEIDENTIFIER,
@RelatedIntegrationObjectFieldName_aedb6d30 NVARCHAR(255),
@Sequence_aedb6d30 INT,
@Configuration_aedb6d30 NVARCHAR(MAX),
@Status_aedb6d30 NVARCHAR(25),
@IsCustom_aedb6d30 BIT,
@MetadataSource_aedb6d30 NVARCHAR(20),
@ID_aedb6d30 UNIQUEIDENTIFIER
SET
  @IntegrationObjectID_aedb6d30 = '848860D1-17AA-4F0D-B1D8-747C25CBC737'
SET
  @Name_aedb6d30 = N'Description'
SET
  @DisplayName_aedb6d30 = N'Description'
SET
  @Type_aedb6d30 = N'String'
SET
  @Length_aedb6d30 = 4000
SET
  @AllowsNull_aedb6d30 = 1
SET
  @IsPrimaryKey_aedb6d30 = 0
SET
  @IsUniqueKey_aedb6d30 = 0
SET
  @IsReadOnly_aedb6d30 = 0
SET
  @IsRequired_aedb6d30 = 0
SET
  @Sequence_aedb6d30 = 0
SET
  @Status_aedb6d30 = N'Active'
SET
  @IsCustom_aedb6d30 = 0
SET
  @MetadataSource_aedb6d30 = N'Declared'
SET
  @ID_aedb6d30 = 'BAA8C85A-D87D-4A74-86B5-7CA4F93AA6F8' EXEC [__mj].spUpdateIntegrationObjectField @IntegrationObjectID = @IntegrationObjectID_aedb6d30,
  @Name = @Name_aedb6d30,
  @DisplayName = @DisplayName_aedb6d30,
  @Description = @Description_aedb6d30,
  @Description_Clear = 1,
  @Category = @Category_aedb6d30,
  @Category_Clear = 1,
  @Type = @Type_aedb6d30,
  @Length = @Length_aedb6d30,
  @Precision = @Precision_aedb6d30,
  @Precision_Clear = 1,
  @Scale = @Scale_aedb6d30,
  @Scale_Clear = 1,
  @AllowsNull = @AllowsNull_aedb6d30,
  @DefaultValue = @DefaultValue_aedb6d30,
  @DefaultValue_Clear = 1,
  @IsPrimaryKey = @IsPrimaryKey_aedb6d30,
  @IsUniqueKey = @IsUniqueKey_aedb6d30,
  @IsReadOnly = @IsReadOnly_aedb6d30,
  @IsRequired = @IsRequired_aedb6d30,
  @RelatedIntegrationObjectID = @RelatedIntegrationObjectID_aedb6d30,
  @RelatedIntegrationObjectID_Clear = 1,
  @RelatedIntegrationObjectFieldName = @RelatedIntegrationObjectFieldName_aedb6d30,
  @RelatedIntegrationObjectFieldName_Clear = 1,
  @Sequence = @Sequence_aedb6d30,
  @Configuration = @Configuration_aedb6d30,
  @Configuration_Clear = 1,
  @Status = @Status_aedb6d30,
  @IsCustom = @IsCustom_aedb6d30,
  @MetadataSource = @MetadataSource_aedb6d30,
  @ID = @ID_aedb6d30;

GO

-- Save MJ: Integration Object Fields (core SP call only)
DECLARE @IntegrationObjectID_001c410e UNIQUEIDENTIFIER,
@Name_001c410e NVARCHAR(255),
@DisplayName_001c410e NVARCHAR(255),
@Description_001c410e NVARCHAR(MAX),
@Category_001c410e NVARCHAR(100),
@Type_001c410e NVARCHAR(100),
@Length_001c410e INT,
@Precision_001c410e INT,
@Scale_001c410e INT,
@AllowsNull_001c410e BIT,
@DefaultValue_001c410e NVARCHAR(255),
@IsPrimaryKey_001c410e BIT,
@IsUniqueKey_001c410e BIT,
@IsReadOnly_001c410e BIT,
@IsRequired_001c410e BIT,
@RelatedIntegrationObjectID_001c410e UNIQUEIDENTIFIER,
@RelatedIntegrationObjectFieldName_001c410e NVARCHAR(255),
@Sequence_001c410e INT,
@Configuration_001c410e NVARCHAR(MAX),
@Status_001c410e NVARCHAR(25),
@IsCustom_001c410e BIT,
@MetadataSource_001c410e NVARCHAR(20),
@ID_001c410e UNIQUEIDENTIFIER
SET
  @IntegrationObjectID_001c410e = 'D4FF26FA-4AC7-4C15-B9F2-372810834B2C'
SET
  @Name_001c410e = N'Description'
SET
  @DisplayName_001c410e = N'Description'
SET
  @Type_001c410e = N'String'
SET
  @Length_001c410e = 4000
SET
  @AllowsNull_001c410e = 1
SET
  @IsPrimaryKey_001c410e = 0
SET
  @IsUniqueKey_001c410e = 0
SET
  @IsReadOnly_001c410e = 0
SET
  @IsRequired_001c410e = 0
SET
  @Sequence_001c410e = 0
SET
  @Status_001c410e = N'Active'
SET
  @IsCustom_001c410e = 0
SET
  @MetadataSource_001c410e = N'Declared'
SET
  @ID_001c410e = 'B9E0E37D-CB76-4CBA-A629-5B070930CC36' EXEC [__mj].spUpdateIntegrationObjectField @IntegrationObjectID = @IntegrationObjectID_001c410e,
  @Name = @Name_001c410e,
  @DisplayName = @DisplayName_001c410e,
  @Description = @Description_001c410e,
  @Description_Clear = 1,
  @Category = @Category_001c410e,
  @Category_Clear = 1,
  @Type = @Type_001c410e,
  @Length = @Length_001c410e,
  @Precision = @Precision_001c410e,
  @Precision_Clear = 1,
  @Scale = @Scale_001c410e,
  @Scale_Clear = 1,
  @AllowsNull = @AllowsNull_001c410e,
  @DefaultValue = @DefaultValue_001c410e,
  @DefaultValue_Clear = 1,
  @IsPrimaryKey = @IsPrimaryKey_001c410e,
  @IsUniqueKey = @IsUniqueKey_001c410e,
  @IsReadOnly = @IsReadOnly_001c410e,
  @IsRequired = @IsRequired_001c410e,
  @RelatedIntegrationObjectID = @RelatedIntegrationObjectID_001c410e,
  @RelatedIntegrationObjectID_Clear = 1,
  @RelatedIntegrationObjectFieldName = @RelatedIntegrationObjectFieldName_001c410e,
  @RelatedIntegrationObjectFieldName_Clear = 1,
  @Sequence = @Sequence_001c410e,
  @Configuration = @Configuration_001c410e,
  @Configuration_Clear = 1,
  @Status = @Status_001c410e,
  @IsCustom = @IsCustom_001c410e,
  @MetadataSource = @MetadataSource_001c410e,
  @ID = @ID_001c410e;

GO

-- Save MJ: Integration Object Fields (core SP call only)
DECLARE @IntegrationObjectID_b36d03b8 UNIQUEIDENTIFIER,
@Name_b36d03b8 NVARCHAR(255),
@DisplayName_b36d03b8 NVARCHAR(255),
@Description_b36d03b8 NVARCHAR(MAX),
@Category_b36d03b8 NVARCHAR(100),
@Type_b36d03b8 NVARCHAR(100),
@Length_b36d03b8 INT,
@Precision_b36d03b8 INT,
@Scale_b36d03b8 INT,
@AllowsNull_b36d03b8 BIT,
@DefaultValue_b36d03b8 NVARCHAR(255),
@IsPrimaryKey_b36d03b8 BIT,
@IsUniqueKey_b36d03b8 BIT,
@IsReadOnly_b36d03b8 BIT,
@IsRequired_b36d03b8 BIT,
@RelatedIntegrationObjectID_b36d03b8 UNIQUEIDENTIFIER,
@RelatedIntegrationObjectFieldName_b36d03b8 NVARCHAR(255),
@Sequence_b36d03b8 INT,
@Configuration_b36d03b8 NVARCHAR(MAX),
@Status_b36d03b8 NVARCHAR(25),
@IsCustom_b36d03b8 BIT,
@MetadataSource_b36d03b8 NVARCHAR(20),
@ID_b36d03b8 UNIQUEIDENTIFIER
SET
  @IntegrationObjectID_b36d03b8 = '1A7A4769-C445-4B21-A414-3E5168B95BD6'
SET
  @Name_b36d03b8 = N'Description'
SET
  @DisplayName_b36d03b8 = N'Description'
SET
  @Type_b36d03b8 = N'String'
SET
  @Length_b36d03b8 = 4000
SET
  @AllowsNull_b36d03b8 = 1
SET
  @IsPrimaryKey_b36d03b8 = 0
SET
  @IsUniqueKey_b36d03b8 = 0
SET
  @IsReadOnly_b36d03b8 = 0
SET
  @IsRequired_b36d03b8 = 0
SET
  @Sequence_b36d03b8 = 0
SET
  @Status_b36d03b8 = N'Active'
SET
  @IsCustom_b36d03b8 = 0
SET
  @MetadataSource_b36d03b8 = N'Declared'
SET
  @ID_b36d03b8 = '4406D644-D2C1-4CDB-A597-FE9C4E8910A9' EXEC [__mj].spUpdateIntegrationObjectField @IntegrationObjectID = @IntegrationObjectID_b36d03b8,
  @Name = @Name_b36d03b8,
  @DisplayName = @DisplayName_b36d03b8,
  @Description = @Description_b36d03b8,
  @Description_Clear = 1,
  @Category = @Category_b36d03b8,
  @Category_Clear = 1,
  @Type = @Type_b36d03b8,
  @Length = @Length_b36d03b8,
  @Precision = @Precision_b36d03b8,
  @Precision_Clear = 1,
  @Scale = @Scale_b36d03b8,
  @Scale_Clear = 1,
  @AllowsNull = @AllowsNull_b36d03b8,
  @DefaultValue = @DefaultValue_b36d03b8,
  @DefaultValue_Clear = 1,
  @IsPrimaryKey = @IsPrimaryKey_b36d03b8,
  @IsUniqueKey = @IsUniqueKey_b36d03b8,
  @IsReadOnly = @IsReadOnly_b36d03b8,
  @IsRequired = @IsRequired_b36d03b8,
  @RelatedIntegrationObjectID = @RelatedIntegrationObjectID_b36d03b8,
  @RelatedIntegrationObjectID_Clear = 1,
  @RelatedIntegrationObjectFieldName = @RelatedIntegrationObjectFieldName_b36d03b8,
  @RelatedIntegrationObjectFieldName_Clear = 1,
  @Sequence = @Sequence_b36d03b8,
  @Configuration = @Configuration_b36d03b8,
  @Configuration_Clear = 1,
  @Status = @Status_b36d03b8,
  @IsCustom = @IsCustom_b36d03b8,
  @MetadataSource = @MetadataSource_b36d03b8,
  @ID = @ID_b36d03b8;

GO

-- Save MJ: Integration Object Fields (core SP call only)
DECLARE @IntegrationObjectID_9dcdfd75 UNIQUEIDENTIFIER,
@Name_9dcdfd75 NVARCHAR(255),
@DisplayName_9dcdfd75 NVARCHAR(255),
@Description_9dcdfd75 NVARCHAR(MAX),
@Category_9dcdfd75 NVARCHAR(100),
@Type_9dcdfd75 NVARCHAR(100),
@Length_9dcdfd75 INT,
@Precision_9dcdfd75 INT,
@Scale_9dcdfd75 INT,
@AllowsNull_9dcdfd75 BIT,
@DefaultValue_9dcdfd75 NVARCHAR(255),
@IsPrimaryKey_9dcdfd75 BIT,
@IsUniqueKey_9dcdfd75 BIT,
@IsReadOnly_9dcdfd75 BIT,
@IsRequired_9dcdfd75 BIT,
@RelatedIntegrationObjectID_9dcdfd75 UNIQUEIDENTIFIER,
@RelatedIntegrationObjectFieldName_9dcdfd75 NVARCHAR(255),
@Sequence_9dcdfd75 INT,
@Configuration_9dcdfd75 NVARCHAR(MAX),
@Status_9dcdfd75 NVARCHAR(25),
@IsCustom_9dcdfd75 BIT,
@MetadataSource_9dcdfd75 NVARCHAR(20),
@ID_9dcdfd75 UNIQUEIDENTIFIER
SET
  @IntegrationObjectID_9dcdfd75 = 'B99A3011-3DE5-41A9-AD20-FDF2DE978B3F'
SET
  @Name_9dcdfd75 = N'EmailAddress'
SET
  @DisplayName_9dcdfd75 = N'EmailAddress'
SET
  @Type_9dcdfd75 = N'String'
SET
  @Length_9dcdfd75 = 320
SET
  @AllowsNull_9dcdfd75 = 1
SET
  @IsPrimaryKey_9dcdfd75 = 0
SET
  @IsUniqueKey_9dcdfd75 = 0
SET
  @IsReadOnly_9dcdfd75 = 0
SET
  @IsRequired_9dcdfd75 = 0
SET
  @Sequence_9dcdfd75 = 0
SET
  @Status_9dcdfd75 = N'Active'
SET
  @IsCustom_9dcdfd75 = 0
SET
  @MetadataSource_9dcdfd75 = N'Declared'
SET
  @ID_9dcdfd75 = '85042D75-6883-46B7-A070-178F7A438128' EXEC [__mj].spUpdateIntegrationObjectField @IntegrationObjectID = @IntegrationObjectID_9dcdfd75,
  @Name = @Name_9dcdfd75,
  @DisplayName = @DisplayName_9dcdfd75,
  @Description = @Description_9dcdfd75,
  @Description_Clear = 1,
  @Category = @Category_9dcdfd75,
  @Category_Clear = 1,
  @Type = @Type_9dcdfd75,
  @Length = @Length_9dcdfd75,
  @Precision = @Precision_9dcdfd75,
  @Precision_Clear = 1,
  @Scale = @Scale_9dcdfd75,
  @Scale_Clear = 1,
  @AllowsNull = @AllowsNull_9dcdfd75,
  @DefaultValue = @DefaultValue_9dcdfd75,
  @DefaultValue_Clear = 1,
  @IsPrimaryKey = @IsPrimaryKey_9dcdfd75,
  @IsUniqueKey = @IsUniqueKey_9dcdfd75,
  @IsReadOnly = @IsReadOnly_9dcdfd75,
  @IsRequired = @IsRequired_9dcdfd75,
  @RelatedIntegrationObjectID = @RelatedIntegrationObjectID_9dcdfd75,
  @RelatedIntegrationObjectID_Clear = 1,
  @RelatedIntegrationObjectFieldName = @RelatedIntegrationObjectFieldName_9dcdfd75,
  @RelatedIntegrationObjectFieldName_Clear = 1,
  @Sequence = @Sequence_9dcdfd75,
  @Configuration = @Configuration_9dcdfd75,
  @Configuration_Clear = 1,
  @Status = @Status_9dcdfd75,
  @IsCustom = @IsCustom_9dcdfd75,
  @MetadataSource = @MetadataSource_9dcdfd75,
  @ID = @ID_9dcdfd75;

GO

-- Save MJ: Integration Object Fields (core SP call only)
DECLARE @IntegrationObjectID_5eac17e7 UNIQUEIDENTIFIER,
@Name_5eac17e7 NVARCHAR(255),
@DisplayName_5eac17e7 NVARCHAR(255),
@Description_5eac17e7 NVARCHAR(MAX),
@Category_5eac17e7 NVARCHAR(100),
@Type_5eac17e7 NVARCHAR(100),
@Length_5eac17e7 INT,
@Precision_5eac17e7 INT,
@Scale_5eac17e7 INT,
@AllowsNull_5eac17e7 BIT,
@DefaultValue_5eac17e7 NVARCHAR(255),
@IsPrimaryKey_5eac17e7 BIT,
@IsUniqueKey_5eac17e7 BIT,
@IsReadOnly_5eac17e7 BIT,
@IsRequired_5eac17e7 BIT,
@RelatedIntegrationObjectID_5eac17e7 UNIQUEIDENTIFIER,
@RelatedIntegrationObjectFieldName_5eac17e7 NVARCHAR(255),
@Sequence_5eac17e7 INT,
@Configuration_5eac17e7 NVARCHAR(MAX),
@Status_5eac17e7 NVARCHAR(25),
@IsCustom_5eac17e7 BIT,
@MetadataSource_5eac17e7 NVARCHAR(20),
@ID_5eac17e7 UNIQUEIDENTIFIER
SET
  @IntegrationObjectID_5eac17e7 = 'B99A3011-3DE5-41A9-AD20-FDF2DE978B3F'
SET
  @Name_5eac17e7 = N'Notes'
SET
  @DisplayName_5eac17e7 = N'Notes'
SET
  @Type_5eac17e7 = N'String'
SET
  @Length_5eac17e7 = 4000
SET
  @AllowsNull_5eac17e7 = 1
SET
  @IsPrimaryKey_5eac17e7 = 0
SET
  @IsUniqueKey_5eac17e7 = 0
SET
  @IsReadOnly_5eac17e7 = 0
SET
  @IsRequired_5eac17e7 = 0
SET
  @Sequence_5eac17e7 = 0
SET
  @Status_5eac17e7 = N'Active'
SET
  @IsCustom_5eac17e7 = 0
SET
  @MetadataSource_5eac17e7 = N'Declared'
SET
  @ID_5eac17e7 = '21B22032-C1A9-426A-8257-8C072AFCB2C1' EXEC [__mj].spUpdateIntegrationObjectField @IntegrationObjectID = @IntegrationObjectID_5eac17e7,
  @Name = @Name_5eac17e7,
  @DisplayName = @DisplayName_5eac17e7,
  @Description = @Description_5eac17e7,
  @Description_Clear = 1,
  @Category = @Category_5eac17e7,
  @Category_Clear = 1,
  @Type = @Type_5eac17e7,
  @Length = @Length_5eac17e7,
  @Precision = @Precision_5eac17e7,
  @Precision_Clear = 1,
  @Scale = @Scale_5eac17e7,
  @Scale_Clear = 1,
  @AllowsNull = @AllowsNull_5eac17e7,
  @DefaultValue = @DefaultValue_5eac17e7,
  @DefaultValue_Clear = 1,
  @IsPrimaryKey = @IsPrimaryKey_5eac17e7,
  @IsUniqueKey = @IsUniqueKey_5eac17e7,
  @IsReadOnly = @IsReadOnly_5eac17e7,
  @IsRequired = @IsRequired_5eac17e7,
  @RelatedIntegrationObjectID = @RelatedIntegrationObjectID_5eac17e7,
  @RelatedIntegrationObjectID_Clear = 1,
  @RelatedIntegrationObjectFieldName = @RelatedIntegrationObjectFieldName_5eac17e7,
  @RelatedIntegrationObjectFieldName_Clear = 1,
  @Sequence = @Sequence_5eac17e7,
  @Configuration = @Configuration_5eac17e7,
  @Configuration_Clear = 1,
  @Status = @Status_5eac17e7,
  @IsCustom = @IsCustom_5eac17e7,
  @MetadataSource = @MetadataSource_5eac17e7,
  @ID = @ID_5eac17e7;

GO

-- Save MJ: Integration Object Fields (core SP call only)
DECLARE @IntegrationObjectID_ec5ee41b UNIQUEIDENTIFIER,
@Name_ec5ee41b NVARCHAR(255),
@DisplayName_ec5ee41b NVARCHAR(255),
@Description_ec5ee41b NVARCHAR(MAX),
@Category_ec5ee41b NVARCHAR(100),
@Type_ec5ee41b NVARCHAR(100),
@Length_ec5ee41b INT,
@Precision_ec5ee41b INT,
@Scale_ec5ee41b INT,
@AllowsNull_ec5ee41b BIT,
@DefaultValue_ec5ee41b NVARCHAR(255),
@IsPrimaryKey_ec5ee41b BIT,
@IsUniqueKey_ec5ee41b BIT,
@IsReadOnly_ec5ee41b BIT,
@IsRequired_ec5ee41b BIT,
@RelatedIntegrationObjectID_ec5ee41b UNIQUEIDENTIFIER,
@RelatedIntegrationObjectFieldName_ec5ee41b NVARCHAR(255),
@Sequence_ec5ee41b INT,
@Configuration_ec5ee41b NVARCHAR(MAX),
@Status_ec5ee41b NVARCHAR(25),
@IsCustom_ec5ee41b BIT,
@MetadataSource_ec5ee41b NVARCHAR(20),
@ID_ec5ee41b UNIQUEIDENTIFIER
SET
  @IntegrationObjectID_ec5ee41b = '8D0F5923-364F-4D27-A5D6-D5A778CE2BA9'
SET
  @Name_ec5ee41b = N'Description'
SET
  @DisplayName_ec5ee41b = N'Description'
SET
  @Type_ec5ee41b = N'String'
SET
  @Length_ec5ee41b = 4000
SET
  @AllowsNull_ec5ee41b = 1
SET
  @IsPrimaryKey_ec5ee41b = 0
SET
  @IsUniqueKey_ec5ee41b = 0
SET
  @IsReadOnly_ec5ee41b = 0
SET
  @IsRequired_ec5ee41b = 0
SET
  @Sequence_ec5ee41b = 0
SET
  @Status_ec5ee41b = N'Active'
SET
  @IsCustom_ec5ee41b = 0
SET
  @MetadataSource_ec5ee41b = N'Declared'
SET
  @ID_ec5ee41b = 'B4D8F239-D7C2-4C09-856C-DE63C0851D53' EXEC [__mj].spUpdateIntegrationObjectField @IntegrationObjectID = @IntegrationObjectID_ec5ee41b,
  @Name = @Name_ec5ee41b,
  @DisplayName = @DisplayName_ec5ee41b,
  @Description = @Description_ec5ee41b,
  @Description_Clear = 1,
  @Category = @Category_ec5ee41b,
  @Category_Clear = 1,
  @Type = @Type_ec5ee41b,
  @Length = @Length_ec5ee41b,
  @Precision = @Precision_ec5ee41b,
  @Precision_Clear = 1,
  @Scale = @Scale_ec5ee41b,
  @Scale_Clear = 1,
  @AllowsNull = @AllowsNull_ec5ee41b,
  @DefaultValue = @DefaultValue_ec5ee41b,
  @DefaultValue_Clear = 1,
  @IsPrimaryKey = @IsPrimaryKey_ec5ee41b,
  @IsUniqueKey = @IsUniqueKey_ec5ee41b,
  @IsReadOnly = @IsReadOnly_ec5ee41b,
  @IsRequired = @IsRequired_ec5ee41b,
  @RelatedIntegrationObjectID = @RelatedIntegrationObjectID_ec5ee41b,
  @RelatedIntegrationObjectID_Clear = 1,
  @RelatedIntegrationObjectFieldName = @RelatedIntegrationObjectFieldName_ec5ee41b,
  @RelatedIntegrationObjectFieldName_Clear = 1,
  @Sequence = @Sequence_ec5ee41b,
  @Configuration = @Configuration_ec5ee41b,
  @Configuration_Clear = 1,
  @Status = @Status_ec5ee41b,
  @IsCustom = @IsCustom_ec5ee41b,
  @MetadataSource = @MetadataSource_ec5ee41b,
  @ID = @ID_ec5ee41b;

GO

-- Save MJ: Integration Object Fields (core SP call only)
DECLARE @IntegrationObjectID_495fc818 UNIQUEIDENTIFIER,
@Name_495fc818 NVARCHAR(255),
@DisplayName_495fc818 NVARCHAR(255),
@Description_495fc818 NVARCHAR(MAX),
@Category_495fc818 NVARCHAR(100),
@Type_495fc818 NVARCHAR(100),
@Length_495fc818 INT,
@Precision_495fc818 INT,
@Scale_495fc818 INT,
@AllowsNull_495fc818 BIT,
@DefaultValue_495fc818 NVARCHAR(255),
@IsPrimaryKey_495fc818 BIT,
@IsUniqueKey_495fc818 BIT,
@IsReadOnly_495fc818 BIT,
@IsRequired_495fc818 BIT,
@RelatedIntegrationObjectID_495fc818 UNIQUEIDENTIFIER,
@RelatedIntegrationObjectFieldName_495fc818 NVARCHAR(255),
@Sequence_495fc818 INT,
@Configuration_495fc818 NVARCHAR(MAX),
@Status_495fc818 NVARCHAR(25),
@IsCustom_495fc818 BIT,
@MetadataSource_495fc818 NVARCHAR(20),
@ID_495fc818 UNIQUEIDENTIFIER
SET
  @IntegrationObjectID_495fc818 = 'B64D7479-A528-406C-9063-2B11934994F2'
SET
  @Name_495fc818 = N'Description'
SET
  @DisplayName_495fc818 = N'Description'
SET
  @Type_495fc818 = N'String'
SET
  @Length_495fc818 = 4000
SET
  @AllowsNull_495fc818 = 1
SET
  @IsPrimaryKey_495fc818 = 0
SET
  @IsUniqueKey_495fc818 = 0
SET
  @IsReadOnly_495fc818 = 0
SET
  @IsRequired_495fc818 = 0
SET
  @Sequence_495fc818 = 0
SET
  @Status_495fc818 = N'Active'
SET
  @IsCustom_495fc818 = 0
SET
  @MetadataSource_495fc818 = N'Declared'
SET
  @ID_495fc818 = 'A9A78050-AD24-4841-BD07-8F98BC15290A' EXEC [__mj].spUpdateIntegrationObjectField @IntegrationObjectID = @IntegrationObjectID_495fc818,
  @Name = @Name_495fc818,
  @DisplayName = @DisplayName_495fc818,
  @Description = @Description_495fc818,
  @Description_Clear = 1,
  @Category = @Category_495fc818,
  @Category_Clear = 1,
  @Type = @Type_495fc818,
  @Length = @Length_495fc818,
  @Precision = @Precision_495fc818,
  @Precision_Clear = 1,
  @Scale = @Scale_495fc818,
  @Scale_Clear = 1,
  @AllowsNull = @AllowsNull_495fc818,
  @DefaultValue = @DefaultValue_495fc818,
  @DefaultValue_Clear = 1,
  @IsPrimaryKey = @IsPrimaryKey_495fc818,
  @IsUniqueKey = @IsUniqueKey_495fc818,
  @IsReadOnly = @IsReadOnly_495fc818,
  @IsRequired = @IsRequired_495fc818,
  @RelatedIntegrationObjectID = @RelatedIntegrationObjectID_495fc818,
  @RelatedIntegrationObjectID_Clear = 1,
  @RelatedIntegrationObjectFieldName = @RelatedIntegrationObjectFieldName_495fc818,
  @RelatedIntegrationObjectFieldName_Clear = 1,
  @Sequence = @Sequence_495fc818,
  @Configuration = @Configuration_495fc818,
  @Configuration_Clear = 1,
  @Status = @Status_495fc818,
  @IsCustom = @IsCustom_495fc818,
  @MetadataSource = @MetadataSource_495fc818,
  @ID = @ID_495fc818;

GO


-- End of SQL Logging Session
-- Session ID: 3d4233ae-94aa-4025-8750-53882dd90386
-- Completed: 2026-07-04T02:06:04.730Z
-- Duration: 813ms
-- Total Statements: 27
