-- MongoDB Connector — connector metadata seed (generated by `mj sync push`)
-- Seeds the core __mj integration catalog (Integration / IntegrationObject / IntegrationObjectField + Actions).
-- Do not hand-edit; regenerate from ../metadata via `mj sync push` + `scripts/wrap-migration.mjs`.

-- SQL Logging Session
-- Session ID: 8711d300-7541-4352-8ae3-7a545d63d662
-- Started: 2026-07-10T00:55:06.932Z
-- Description: MetadataSync push operation
-- Generated by MemberJunction

-- Save MJ: Integrations (core SP call only)
DECLARE @Name_618a0ea6 NVARCHAR(100),
@Description_618a0ea6 NVARCHAR(255),
@NavigationBaseURL_618a0ea6 NVARCHAR(500),
@ClassName_618a0ea6 NVARCHAR(100),
@ImportPath_618a0ea6 NVARCHAR(100),
@BatchMaxRequestCount_618a0ea6 INT,
@BatchRequestWaitTime_618a0ea6 INT,
@ID_618a0ea6 UNIQUEIDENTIFIER,
@CredentialTypeID_618a0ea6 UNIQUEIDENTIFIER,
@Icon_618a0ea6 NVARCHAR(MAX),
@Configuration_618a0ea6 NVARCHAR(MAX)
SET
  @Name_618a0ea6 = N'MongoDB'
SET
  @Description_618a0ea6 = N'Ingest data from an external MongoDB via a shared MJ: External Data Sources connection. Schema is discovered at connection time; the connector delegates connectivity to the EDS ''MongoExternalDriver'' driver.'
SET
  @ClassName_618a0ea6 = N'MongoConnector'
SET
  @ImportPath_618a0ea6 = N'@memberjunction/connector-mongodb'
SET
  @BatchMaxRequestCount_618a0ea6 = -1
SET
  @BatchRequestWaitTime_618a0ea6 = -1
SET
  @ID_618a0ea6 = '9ea17cc6-7090-42b5-b0f3-6131da3f735a'
SET
  @Icon_618a0ea6 = N'fa-solid fa-leaf'
SET
  @Configuration_618a0ea6 = N'{
  "connectionModel": "external-data-source",
  "note": "Bind this connection to a shared ''MJ: External Data Sources'' row by setting Configuration.externalDataSourceID on the CompanyIntegration. Host + credentials live on that EDS row (credentials via CredentialEngine); objects/fields are discovered at connection time. Requires @memberjunction/external-data-sources + @memberjunction/external-data-source-mongodb >= 5.46.0."
}' EXEC [__mj].spCreateIntegration @Name = @Name_618a0ea6,
  @Description = @Description_618a0ea6,
  @NavigationBaseURL = @NavigationBaseURL_618a0ea6,
  @NavigationBaseURL_Clear = 1,
  @ClassName = @ClassName_618a0ea6,
  @ImportPath = @ImportPath_618a0ea6,
  @BatchMaxRequestCount = @BatchMaxRequestCount_618a0ea6,
  @BatchRequestWaitTime = @BatchRequestWaitTime_618a0ea6,
  @ID = @ID_618a0ea6,
  @CredentialTypeID = @CredentialTypeID_618a0ea6,
  @CredentialTypeID_Clear = 1,
  @Icon = @Icon_618a0ea6,
  @Configuration = @Configuration_618a0ea6;

GO


-- End of SQL Logging Session
-- Session ID: 8711d300-7541-4352-8ae3-7a545d63d662
-- Completed: 2026-07-10T00:55:07.112Z
-- Duration: 180ms
-- Total Statements: 1
