-- WordPress Connector — WP Activity Log objects (additive delta, generated by `mj sync push`)
--
-- Adds the two ActivityLog* objects to the __mj integration catalog on top of the 1.0.0 seed in
-- V202608212225__wordpress__Metadata.sql. Additive ONLY: it creates 2 IntegrationObject rows and
-- their 28 IntegrationObjectField rows and touches NOTHING that migration already seeded, so a
-- tenant already on 1.0.0 upgrades without a catalog reset.
--
-- These objects are NOT part of the WordPress REST API. WP Activity Log keeps its events in the
-- custom tables wsal_occurrences / wsal_metadata and registers no REST routes of its own, so they
-- are served by the companion plugin in Platform/WordPress/wp-plugin/mj-wsal-bridge, which the site
-- must have installed for these objects to return anything.
--
-- Do not hand-edit; the statements below are the generator's own output, sliced to the new records.

-- Save MJ: Integration Objects (core SP call only)
DECLARE @ID_7201745e UNIQUEIDENTIFIER,
@IntegrationID_7201745e UNIQUEIDENTIFIER,
@Name_7201745e NVARCHAR(255),
@DisplayName_7201745e NVARCHAR(255),
@Description_7201745e NVARCHAR(MAX),
@Category_7201745e NVARCHAR(100),
@APIPath_7201745e NVARCHAR(500),
@ResponseDataKey_7201745e NVARCHAR(255),
@DefaultPageSize_7201745e INT,
@SupportsPagination_7201745e BIT,
@PaginationType_7201745e NVARCHAR(20),
@SupportsIncrementalSync_7201745e BIT,
@SupportsWrite_7201745e BIT,
@DefaultQueryParams_7201745e NVARCHAR(MAX),
@Configuration_7201745e NVARCHAR(MAX),
@Sequence_7201745e INT,
@Status_7201745e NVARCHAR(25),
@WriteAPIPath_7201745e NVARCHAR(500),
@WriteMethod_7201745e NVARCHAR(10),
@DeleteMethod_7201745e NVARCHAR(10),
@IsCustom_7201745e BIT,
@CreateAPIPath_7201745e NVARCHAR(MAX),
@CreateMethod_7201745e NVARCHAR(20),
@CreateBodyShape_7201745e NVARCHAR(50),
@CreateBodyKey_7201745e NVARCHAR(100),
@CreateIDLocation_7201745e NVARCHAR(20),
@UpdateAPIPath_7201745e NVARCHAR(MAX),
@UpdateMethod_7201745e NVARCHAR(20),
@UpdateBodyShape_7201745e NVARCHAR(50),
@UpdateBodyKey_7201745e NVARCHAR(100),
@UpdateIDLocation_7201745e NVARCHAR(20),
@DeleteAPIPath_7201745e NVARCHAR(MAX),
@DeleteIDLocation_7201745e NVARCHAR(20),
@IncrementalWatermarkField_7201745e NVARCHAR(255),
@MetadataSource_7201745e NVARCHAR(20),
@SupportsCreate_7201745e BIT,
@SupportsUpdate_7201745e BIT,
@SupportsDelete_7201745e BIT,
@SyncStrategy_7201745e NVARCHAR(50),
@ContentHashApplicable_7201745e BIT,
@StableOrderingKey_7201745e NVARCHAR(255)
SET
  @ID_7201745e = '1b6aaa3c-002c-4e1a-8c82-0900d33fe02a'
SET
  @IntegrationID_7201745e = '301B572A-FE48-4600-A8A2-8D5E92646048'
SET
  @Name_7201745e = N'ActivityLogEvent'
SET
  @DisplayName_7201745e = N'Activity Log Event'
SET
  @Description_7201745e = N'WP Activity Log events, flattened one row per logged event with its metadata pivoted in. Served by the MJ bridge plugin at mj-wsal/v1, because WP Activity Log itself registers no REST routes.'
SET
  @Category_7201745e = N'WP Activity Log'
SET
  @APIPath_7201745e = N'/mj-wsal/v1/events'
SET
  @DefaultPageSize_7201745e = 100
SET
  @SupportsPagination_7201745e = 1
SET
  @PaginationType_7201745e = N'PageNumber'
SET
  @SupportsIncrementalSync_7201745e = 1
SET
  @SupportsWrite_7201745e = 0
SET
  @Configuration_7201745e = N'{
  "namespace": "mj-wsal/v1",
  "listPath": "/mj-wsal/v1/events",
  "getOnePath": null,
  "routes": [
    "GET /mj-wsal/v1/events"
  ],
  "responseShape": "array",
  "pkField": "id",
  "pkEvidence": "Tier1-source — the bridge projects wsal_occurrences.id, which is that table''s bigint AUTO_INCREMENT PRIMARY KEY.",
  "pagination": {
    "type": "PageNumber",
    "pageParam": "page",
    "sizeParam": "per_page",
    "maxPageSize": 100,
    "totalHeader": "X-WP-Total",
    "totalPagesHeader": "X-WP-TotalPages"
  },
  "paginationNote": "The bridge registers page/per_page (per_page max 100, matching core) and emits X-WP-Total / X-WP-TotalPages. Rows are ordered by (created_on, id) — a total order, so no row can be skipped or repeated across an offset boundary.",
  "incrementalWatermark": {
    "field": "created_at",
    "filterParam": "after",
    "beforeParam": "before",
    "datesAreGmt": true,
    "orderby": "created_on",
    "note": "Watermarked on created_at (ISO-8601 UTC) rather than the raw created_on double: a bare epoch number is ambiguous to date parsers (seconds vs milliseconds), and reading these seconds as milliseconds would date every event to January 1970. The `after` bound is INCLUSIVE because created_on is not unique — an exclusive bound would drop every event sharing the last synced timestamp. A re-delivered boundary event dedupes on id."
  },
  "incrementalNote": null,
  "contextGatedFields": [],
  "customFieldSurface": [
    "meta"
  ],
  "requiresCompanionPlugin": {
    "plugin": "MJ WP Activity Log Bridge (Platform/WordPress/wp-plugin/mj-wsal-bridge)",
    "reason": "WP Activity Log stores events in the custom tables wsal_occurrences and wsal_metadata and registers ZERO REST routes — verified against WSAL 5.6.6, which contains no register_rest_route or rest_api_init call anywhere. Without the bridge installed this namespace is absent from the site route index and the object cannot be read.",
    "minimumWsalVersion": "5.0.0",
    "requiredCapability": "manage_options (manage_network_options on multisite)"
  }
}'
SET
  @Sequence_7201745e = 0
SET
  @Status_7201745e = N'Active'
SET
  @WriteMethod_7201745e = N'POST'
SET
  @DeleteMethod_7201745e = N'DELETE'
SET
  @IsCustom_7201745e = 0
SET
  @IncrementalWatermarkField_7201745e = N'created_at'
SET
  @MetadataSource_7201745e = N'Declared'
SET
  @SupportsCreate_7201745e = 0
SET
  @SupportsUpdate_7201745e = 0
SET
  @SupportsDelete_7201745e = 0
SET
  @SyncStrategy_7201745e = N'WatermarkIncremental'
SET
  @ContentHashApplicable_7201745e = 0
SET
  @StableOrderingKey_7201745e = N'id' EXEC [__mj].spCreateIntegrationObject @ID = @ID_7201745e,
  @IntegrationID = @IntegrationID_7201745e,
  @Name = @Name_7201745e,
  @DisplayName = @DisplayName_7201745e,
  @Description = @Description_7201745e,
  @Category = @Category_7201745e,
  @APIPath = @APIPath_7201745e,
  @ResponseDataKey = @ResponseDataKey_7201745e,
  @ResponseDataKey_Clear = 1,
  @DefaultPageSize = @DefaultPageSize_7201745e,
  @SupportsPagination = @SupportsPagination_7201745e,
  @PaginationType = @PaginationType_7201745e,
  @SupportsIncrementalSync = @SupportsIncrementalSync_7201745e,
  @SupportsWrite = @SupportsWrite_7201745e,
  @DefaultQueryParams = @DefaultQueryParams_7201745e,
  @DefaultQueryParams_Clear = 1,
  @Configuration = @Configuration_7201745e,
  @Sequence = @Sequence_7201745e,
  @Status = @Status_7201745e,
  @WriteAPIPath = @WriteAPIPath_7201745e,
  @WriteAPIPath_Clear = 1,
  @WriteMethod = @WriteMethod_7201745e,
  @DeleteMethod = @DeleteMethod_7201745e,
  @IsCustom = @IsCustom_7201745e,
  @CreateAPIPath = @CreateAPIPath_7201745e,
  @CreateAPIPath_Clear = 1,
  @CreateMethod = @CreateMethod_7201745e,
  @CreateMethod_Clear = 1,
  @CreateBodyShape = @CreateBodyShape_7201745e,
  @CreateBodyShape_Clear = 1,
  @CreateBodyKey = @CreateBodyKey_7201745e,
  @CreateBodyKey_Clear = 1,
  @CreateIDLocation = @CreateIDLocation_7201745e,
  @CreateIDLocation_Clear = 1,
  @UpdateAPIPath = @UpdateAPIPath_7201745e,
  @UpdateAPIPath_Clear = 1,
  @UpdateMethod = @UpdateMethod_7201745e,
  @UpdateMethod_Clear = 1,
  @UpdateBodyShape = @UpdateBodyShape_7201745e,
  @UpdateBodyShape_Clear = 1,
  @UpdateBodyKey = @UpdateBodyKey_7201745e,
  @UpdateBodyKey_Clear = 1,
  @UpdateIDLocation = @UpdateIDLocation_7201745e,
  @UpdateIDLocation_Clear = 1,
  @DeleteAPIPath = @DeleteAPIPath_7201745e,
  @DeleteAPIPath_Clear = 1,
  @DeleteIDLocation = @DeleteIDLocation_7201745e,
  @DeleteIDLocation_Clear = 1,
  @IncrementalWatermarkField = @IncrementalWatermarkField_7201745e,
  @MetadataSource = @MetadataSource_7201745e,
  @SupportsCreate = @SupportsCreate_7201745e,
  @SupportsUpdate = @SupportsUpdate_7201745e,
  @SupportsDelete = @SupportsDelete_7201745e,
  @SyncStrategy = @SyncStrategy_7201745e,
  @ContentHashApplicable = @ContentHashApplicable_7201745e,
  @StableOrderingKey = @StableOrderingKey_7201745e;

GO

-- Save MJ: Integration Objects (core SP call only)
DECLARE @ID_50aca4a9 UNIQUEIDENTIFIER,
@IntegrationID_50aca4a9 UNIQUEIDENTIFIER,
@Name_50aca4a9 NVARCHAR(255),
@DisplayName_50aca4a9 NVARCHAR(255),
@Description_50aca4a9 NVARCHAR(MAX),
@Category_50aca4a9 NVARCHAR(100),
@APIPath_50aca4a9 NVARCHAR(500),
@ResponseDataKey_50aca4a9 NVARCHAR(255),
@DefaultPageSize_50aca4a9 INT,
@SupportsPagination_50aca4a9 BIT,
@PaginationType_50aca4a9 NVARCHAR(20),
@SupportsIncrementalSync_50aca4a9 BIT,
@SupportsWrite_50aca4a9 BIT,
@DefaultQueryParams_50aca4a9 NVARCHAR(MAX),
@Configuration_50aca4a9 NVARCHAR(MAX),
@Sequence_50aca4a9 INT,
@Status_50aca4a9 NVARCHAR(25),
@WriteAPIPath_50aca4a9 NVARCHAR(500),
@WriteMethod_50aca4a9 NVARCHAR(10),
@DeleteMethod_50aca4a9 NVARCHAR(10),
@IsCustom_50aca4a9 BIT,
@CreateAPIPath_50aca4a9 NVARCHAR(MAX),
@CreateMethod_50aca4a9 NVARCHAR(20),
@CreateBodyShape_50aca4a9 NVARCHAR(50),
@CreateBodyKey_50aca4a9 NVARCHAR(100),
@CreateIDLocation_50aca4a9 NVARCHAR(20),
@UpdateAPIPath_50aca4a9 NVARCHAR(MAX),
@UpdateMethod_50aca4a9 NVARCHAR(20),
@UpdateBodyShape_50aca4a9 NVARCHAR(50),
@UpdateBodyKey_50aca4a9 NVARCHAR(100),
@UpdateIDLocation_50aca4a9 NVARCHAR(20),
@DeleteAPIPath_50aca4a9 NVARCHAR(MAX),
@DeleteIDLocation_50aca4a9 NVARCHAR(20),
@IncrementalWatermarkField_50aca4a9 NVARCHAR(255),
@MetadataSource_50aca4a9 NVARCHAR(20),
@SupportsCreate_50aca4a9 BIT,
@SupportsUpdate_50aca4a9 BIT,
@SupportsDelete_50aca4a9 BIT,
@SyncStrategy_50aca4a9 NVARCHAR(50),
@ContentHashApplicable_50aca4a9 BIT,
@StableOrderingKey_50aca4a9 NVARCHAR(255)
SET
  @ID_50aca4a9 = 'fb9e1b85-6b87-4561-b332-c264ecf2d87b'
SET
  @IntegrationID_50aca4a9 = '301B572A-FE48-4600-A8A2-8D5E92646048'
SET
  @Name_50aca4a9 = N'ActivityLogEventType'
SET
  @DisplayName_50aca4a9 = N'Activity Log Event Type'
SET
  @Description_50aca4a9 = N'The activity log event-type catalog: every event ID the installed plugin set can emit, with its label, severity and category. A slow-moving dimension for interpreting ActivityLogEvent.alert_id.'
SET
  @Category_50aca4a9 = N'WP Activity Log'
SET
  @APIPath_50aca4a9 = N'/mj-wsal/v1/event-types'
SET
  @DefaultPageSize_50aca4a9 = 100
SET
  @SupportsPagination_50aca4a9 = 1
SET
  @PaginationType_50aca4a9 = N'PageNumber'
SET
  @SupportsIncrementalSync_50aca4a9 = 0
SET
  @SupportsWrite_50aca4a9 = 0
SET
  @Configuration_50aca4a9 = N'{
  "namespace": "mj-wsal/v1",
  "listPath": "/mj-wsal/v1/event-types",
  "getOnePath": null,
  "routes": [
    "GET /mj-wsal/v1/event-types"
  ],
  "responseShape": "array",
  "pkField": "alert_id",
  "pkEvidence": "Tier1-source — the bridge keys the catalog by the plugin''s own alert code, which Alert_Manager rejects duplicates of at registration time.",
  "pagination": {
    "type": "PageNumber",
    "pageParam": "page",
    "sizeParam": "per_page",
    "maxPageSize": 100,
    "totalHeader": "X-WP-Total",
    "totalPagesHeader": "X-WP-TotalPages"
  },
  "paginationNote": "Paginated like the events route, though the catalog is small (order hundreds of rows) and slow-moving. Paginating it is what makes it a discoverable collection: the connector treats a GET route registering per_page as a listable object.",
  "incrementalWatermark": null,
  "incrementalNote": "The catalog is a static definition set with no timestamps of any kind — it changes only when a plugin is installed, updated or removed. Full-pulled and hash-diffed rather than given a synthesised watermark.",
  "contextGatedFields": [],
  "customFieldSurface": [],
  "requiresCompanionPlugin": {
    "plugin": "MJ WP Activity Log Bridge (Platform/WordPress/wp-plugin/mj-wsal-bridge)",
    "reason": "Read through the plugin''s own Alert_Manager, so third-party sensors (WooCommerce, Gravity Forms, Yoast and the rest) that register their own event types are included automatically and labels track the installed version.",
    "minimumWsalVersion": "5.0.0",
    "requiredCapability": "manage_options (manage_network_options on multisite)"
  }
}'
SET
  @Sequence_50aca4a9 = 0
SET
  @Status_50aca4a9 = N'Active'
SET
  @WriteMethod_50aca4a9 = N'POST'
SET
  @DeleteMethod_50aca4a9 = N'DELETE'
SET
  @IsCustom_50aca4a9 = 0
SET
  @MetadataSource_50aca4a9 = N'Declared'
SET
  @SupportsCreate_50aca4a9 = 0
SET
  @SupportsUpdate_50aca4a9 = 0
SET
  @SupportsDelete_50aca4a9 = 0
SET
  @SyncStrategy_50aca4a9 = N'FullPullHashDiff'
SET
  @ContentHashApplicable_50aca4a9 = 1
SET
  @StableOrderingKey_50aca4a9 = N'alert_id' EXEC [__mj].spCreateIntegrationObject @ID = @ID_50aca4a9,
  @IntegrationID = @IntegrationID_50aca4a9,
  @Name = @Name_50aca4a9,
  @DisplayName = @DisplayName_50aca4a9,
  @Description = @Description_50aca4a9,
  @Category = @Category_50aca4a9,
  @APIPath = @APIPath_50aca4a9,
  @ResponseDataKey = @ResponseDataKey_50aca4a9,
  @ResponseDataKey_Clear = 1,
  @DefaultPageSize = @DefaultPageSize_50aca4a9,
  @SupportsPagination = @SupportsPagination_50aca4a9,
  @PaginationType = @PaginationType_50aca4a9,
  @SupportsIncrementalSync = @SupportsIncrementalSync_50aca4a9,
  @SupportsWrite = @SupportsWrite_50aca4a9,
  @DefaultQueryParams = @DefaultQueryParams_50aca4a9,
  @DefaultQueryParams_Clear = 1,
  @Configuration = @Configuration_50aca4a9,
  @Sequence = @Sequence_50aca4a9,
  @Status = @Status_50aca4a9,
  @WriteAPIPath = @WriteAPIPath_50aca4a9,
  @WriteAPIPath_Clear = 1,
  @WriteMethod = @WriteMethod_50aca4a9,
  @DeleteMethod = @DeleteMethod_50aca4a9,
  @IsCustom = @IsCustom_50aca4a9,
  @CreateAPIPath = @CreateAPIPath_50aca4a9,
  @CreateAPIPath_Clear = 1,
  @CreateMethod = @CreateMethod_50aca4a9,
  @CreateMethod_Clear = 1,
  @CreateBodyShape = @CreateBodyShape_50aca4a9,
  @CreateBodyShape_Clear = 1,
  @CreateBodyKey = @CreateBodyKey_50aca4a9,
  @CreateBodyKey_Clear = 1,
  @CreateIDLocation = @CreateIDLocation_50aca4a9,
  @CreateIDLocation_Clear = 1,
  @UpdateAPIPath = @UpdateAPIPath_50aca4a9,
  @UpdateAPIPath_Clear = 1,
  @UpdateMethod = @UpdateMethod_50aca4a9,
  @UpdateMethod_Clear = 1,
  @UpdateBodyShape = @UpdateBodyShape_50aca4a9,
  @UpdateBodyShape_Clear = 1,
  @UpdateBodyKey = @UpdateBodyKey_50aca4a9,
  @UpdateBodyKey_Clear = 1,
  @UpdateIDLocation = @UpdateIDLocation_50aca4a9,
  @UpdateIDLocation_Clear = 1,
  @DeleteAPIPath = @DeleteAPIPath_50aca4a9,
  @DeleteAPIPath_Clear = 1,
  @DeleteIDLocation = @DeleteIDLocation_50aca4a9,
  @DeleteIDLocation_Clear = 1,
  @IncrementalWatermarkField = @IncrementalWatermarkField_50aca4a9,
  @IncrementalWatermarkField_Clear = 1,
  @MetadataSource = @MetadataSource_50aca4a9,
  @SupportsCreate = @SupportsCreate_50aca4a9,
  @SupportsUpdate = @SupportsUpdate_50aca4a9,
  @SupportsDelete = @SupportsDelete_50aca4a9,
  @SyncStrategy = @SyncStrategy_50aca4a9,
  @ContentHashApplicable = @ContentHashApplicable_50aca4a9,
  @StableOrderingKey = @StableOrderingKey_50aca4a9;

GO

-- Save MJ: Integration Object Fields (core SP call only)
DECLARE @ID_23e809dd UNIQUEIDENTIFIER,
@IntegrationObjectID_23e809dd UNIQUEIDENTIFIER,
@Name_23e809dd NVARCHAR(255),
@DisplayName_23e809dd NVARCHAR(255),
@Description_23e809dd NVARCHAR(MAX),
@Category_23e809dd NVARCHAR(100),
@Type_23e809dd NVARCHAR(100),
@Length_23e809dd INT,
@Precision_23e809dd INT,
@Scale_23e809dd INT,
@AllowsNull_23e809dd BIT,
@DefaultValue_23e809dd NVARCHAR(255),
@IsPrimaryKey_23e809dd BIT,
@IsUniqueKey_23e809dd BIT,
@IsReadOnly_23e809dd BIT,
@IsRequired_23e809dd BIT,
@RelatedIntegrationObjectID_23e809dd UNIQUEIDENTIFIER,
@RelatedIntegrationObjectFieldName_23e809dd NVARCHAR(255),
@Sequence_23e809dd INT,
@Configuration_23e809dd NVARCHAR(MAX),
@Status_23e809dd NVARCHAR(25),
@IsCustom_23e809dd BIT,
@MetadataSource_23e809dd NVARCHAR(20)
SET
  @ID_23e809dd = 'b9664c40-3ab1-4cda-bf25-d4c326d2fc49'
SET
  @IntegrationObjectID_23e809dd = '1B6AAA3C-002C-4E1A-8C82-0900D33FE02A'
SET
  @Name_23e809dd = N'id'
SET
  @DisplayName_23e809dd = N'ID'
SET
  @Description_23e809dd = N'Unique event identifier. Primary key.'
SET
  @Type_23e809dd = N'Integer'
SET
  @AllowsNull_23e809dd = 0
SET
  @IsPrimaryKey_23e809dd = 1
SET
  @IsUniqueKey_23e809dd = 1
SET
  @IsReadOnly_23e809dd = 1
SET
  @IsRequired_23e809dd = 1
SET
  @Sequence_23e809dd = 0
SET
  @Configuration_23e809dd = N'{
  "contexts": [
    "view"
  ]
}'
SET
  @Status_23e809dd = N'Active'
SET
  @IsCustom_23e809dd = 0
SET
  @MetadataSource_23e809dd = N'Declared' EXEC [__mj].spCreateIntegrationObjectField @ID = @ID_23e809dd,
  @IntegrationObjectID = @IntegrationObjectID_23e809dd,
  @Name = @Name_23e809dd,
  @DisplayName = @DisplayName_23e809dd,
  @Description = @Description_23e809dd,
  @Category = @Category_23e809dd,
  @Category_Clear = 1,
  @Type = @Type_23e809dd,
  @Length = @Length_23e809dd,
  @Length_Clear = 1,
  @Precision = @Precision_23e809dd,
  @Precision_Clear = 1,
  @Scale = @Scale_23e809dd,
  @Scale_Clear = 1,
  @AllowsNull = @AllowsNull_23e809dd,
  @DefaultValue = @DefaultValue_23e809dd,
  @DefaultValue_Clear = 1,
  @IsPrimaryKey = @IsPrimaryKey_23e809dd,
  @IsUniqueKey = @IsUniqueKey_23e809dd,
  @IsReadOnly = @IsReadOnly_23e809dd,
  @IsRequired = @IsRequired_23e809dd,
  @RelatedIntegrationObjectID = @RelatedIntegrationObjectID_23e809dd,
  @RelatedIntegrationObjectID_Clear = 1,
  @RelatedIntegrationObjectFieldName = @RelatedIntegrationObjectFieldName_23e809dd,
  @RelatedIntegrationObjectFieldName_Clear = 1,
  @Sequence = @Sequence_23e809dd,
  @Configuration = @Configuration_23e809dd,
  @Status = @Status_23e809dd,
  @IsCustom = @IsCustom_23e809dd,
  @MetadataSource = @MetadataSource_23e809dd;

GO

-- Save MJ: Integration Object Fields (core SP call only)
DECLARE @ID_eb4c7113 UNIQUEIDENTIFIER,
@IntegrationObjectID_eb4c7113 UNIQUEIDENTIFIER,
@Name_eb4c7113 NVARCHAR(255),
@DisplayName_eb4c7113 NVARCHAR(255),
@Description_eb4c7113 NVARCHAR(MAX),
@Category_eb4c7113 NVARCHAR(100),
@Type_eb4c7113 NVARCHAR(100),
@Length_eb4c7113 INT,
@Precision_eb4c7113 INT,
@Scale_eb4c7113 INT,
@AllowsNull_eb4c7113 BIT,
@DefaultValue_eb4c7113 NVARCHAR(255),
@IsPrimaryKey_eb4c7113 BIT,
@IsUniqueKey_eb4c7113 BIT,
@IsReadOnly_eb4c7113 BIT,
@IsRequired_eb4c7113 BIT,
@RelatedIntegrationObjectID_eb4c7113 UNIQUEIDENTIFIER,
@RelatedIntegrationObjectFieldName_eb4c7113 NVARCHAR(255),
@Sequence_eb4c7113 INT,
@Configuration_eb4c7113 NVARCHAR(MAX),
@Status_eb4c7113 NVARCHAR(25),
@IsCustom_eb4c7113 BIT,
@MetadataSource_eb4c7113 NVARCHAR(20)
SET
  @ID_eb4c7113 = 'c8ad08c3-7312-4805-846e-e4e2bcbc61b5'
SET
  @IntegrationObjectID_eb4c7113 = '1B6AAA3C-002C-4E1A-8C82-0900D33FE02A'
SET
  @Name_eb4c7113 = N'site_id'
SET
  @DisplayName_eb4c7113 = N'Site ID'
SET
  @Description_eb4c7113 = N'Multisite network site ID; 1 on a single-site install.'
SET
  @Type_eb4c7113 = N'Integer'
SET
  @AllowsNull_eb4c7113 = 0
SET
  @IsPrimaryKey_eb4c7113 = 0
SET
  @IsUniqueKey_eb4c7113 = 0
SET
  @IsReadOnly_eb4c7113 = 1
SET
  @IsRequired_eb4c7113 = 0
SET
  @Sequence_eb4c7113 = 1
SET
  @Configuration_eb4c7113 = N'{
  "contexts": [
    "view"
  ]
}'
SET
  @Status_eb4c7113 = N'Active'
SET
  @IsCustom_eb4c7113 = 0
SET
  @MetadataSource_eb4c7113 = N'Declared' EXEC [__mj].spCreateIntegrationObjectField @ID = @ID_eb4c7113,
  @IntegrationObjectID = @IntegrationObjectID_eb4c7113,
  @Name = @Name_eb4c7113,
  @DisplayName = @DisplayName_eb4c7113,
  @Description = @Description_eb4c7113,
  @Category = @Category_eb4c7113,
  @Category_Clear = 1,
  @Type = @Type_eb4c7113,
  @Length = @Length_eb4c7113,
  @Length_Clear = 1,
  @Precision = @Precision_eb4c7113,
  @Precision_Clear = 1,
  @Scale = @Scale_eb4c7113,
  @Scale_Clear = 1,
  @AllowsNull = @AllowsNull_eb4c7113,
  @DefaultValue = @DefaultValue_eb4c7113,
  @DefaultValue_Clear = 1,
  @IsPrimaryKey = @IsPrimaryKey_eb4c7113,
  @IsUniqueKey = @IsUniqueKey_eb4c7113,
  @IsReadOnly = @IsReadOnly_eb4c7113,
  @IsRequired = @IsRequired_eb4c7113,
  @RelatedIntegrationObjectID = @RelatedIntegrationObjectID_eb4c7113,
  @RelatedIntegrationObjectID_Clear = 1,
  @RelatedIntegrationObjectFieldName = @RelatedIntegrationObjectFieldName_eb4c7113,
  @RelatedIntegrationObjectFieldName_Clear = 1,
  @Sequence = @Sequence_eb4c7113,
  @Configuration = @Configuration_eb4c7113,
  @Status = @Status_eb4c7113,
  @IsCustom = @IsCustom_eb4c7113,
  @MetadataSource = @MetadataSource_eb4c7113;

GO

-- Save MJ: Integration Object Fields (core SP call only)
DECLARE @ID_f130f541 UNIQUEIDENTIFIER,
@IntegrationObjectID_f130f541 UNIQUEIDENTIFIER,
@Name_f130f541 NVARCHAR(255),
@DisplayName_f130f541 NVARCHAR(255),
@Description_f130f541 NVARCHAR(MAX),
@Category_f130f541 NVARCHAR(100),
@Type_f130f541 NVARCHAR(100),
@Length_f130f541 INT,
@Precision_f130f541 INT,
@Scale_f130f541 INT,
@AllowsNull_f130f541 BIT,
@DefaultValue_f130f541 NVARCHAR(255),
@IsPrimaryKey_f130f541 BIT,
@IsUniqueKey_f130f541 BIT,
@IsReadOnly_f130f541 BIT,
@IsRequired_f130f541 BIT,
@RelatedIntegrationObjectID_f130f541 UNIQUEIDENTIFIER,
@RelatedIntegrationObjectFieldName_f130f541 NVARCHAR(255),
@Sequence_f130f541 INT,
@Configuration_f130f541 NVARCHAR(MAX),
@Status_f130f541 NVARCHAR(25),
@IsCustom_f130f541 BIT,
@MetadataSource_f130f541 NVARCHAR(20)
SET
  @ID_f130f541 = 'a9a1a083-81b5-4c39-8670-f19183fe3751'
SET
  @IntegrationObjectID_f130f541 = '1B6AAA3C-002C-4E1A-8C82-0900D33FE02A'
SET
  @Name_f130f541 = N'alert_id'
SET
  @DisplayName_f130f541 = N'Alert ID'
SET
  @Description_f130f541 = N'WP Activity Log event type ID. Joins to ActivityLogEventType.alert_id.'
SET
  @Type_f130f541 = N'Integer'
SET
  @AllowsNull_f130f541 = 0
SET
  @IsPrimaryKey_f130f541 = 0
SET
  @IsUniqueKey_f130f541 = 0
SET
  @IsReadOnly_f130f541 = 1
SET
  @IsRequired_f130f541 = 0
SET
  @Sequence_f130f541 = 2
SET
  @Configuration_f130f541 = N'{
  "contexts": [
    "view"
  ]
}'
SET
  @Status_f130f541 = N'Active'
SET
  @IsCustom_f130f541 = 0
SET
  @MetadataSource_f130f541 = N'Declared' EXEC [__mj].spCreateIntegrationObjectField @ID = @ID_f130f541,
  @IntegrationObjectID = @IntegrationObjectID_f130f541,
  @Name = @Name_f130f541,
  @DisplayName = @DisplayName_f130f541,
  @Description = @Description_f130f541,
  @Category = @Category_f130f541,
  @Category_Clear = 1,
  @Type = @Type_f130f541,
  @Length = @Length_f130f541,
  @Length_Clear = 1,
  @Precision = @Precision_f130f541,
  @Precision_Clear = 1,
  @Scale = @Scale_f130f541,
  @Scale_Clear = 1,
  @AllowsNull = @AllowsNull_f130f541,
  @DefaultValue = @DefaultValue_f130f541,
  @DefaultValue_Clear = 1,
  @IsPrimaryKey = @IsPrimaryKey_f130f541,
  @IsUniqueKey = @IsUniqueKey_f130f541,
  @IsReadOnly = @IsReadOnly_f130f541,
  @IsRequired = @IsRequired_f130f541,
  @RelatedIntegrationObjectID = @RelatedIntegrationObjectID_f130f541,
  @RelatedIntegrationObjectID_Clear = 1,
  @RelatedIntegrationObjectFieldName = @RelatedIntegrationObjectFieldName_f130f541,
  @RelatedIntegrationObjectFieldName_Clear = 1,
  @Sequence = @Sequence_f130f541,
  @Configuration = @Configuration_f130f541,
  @Status = @Status_f130f541,
  @IsCustom = @IsCustom_f130f541,
  @MetadataSource = @MetadataSource_f130f541;

GO

-- Save MJ: Integration Object Fields (core SP call only)
DECLARE @ID_b0232fb9 UNIQUEIDENTIFIER,
@IntegrationObjectID_b0232fb9 UNIQUEIDENTIFIER,
@Name_b0232fb9 NVARCHAR(255),
@DisplayName_b0232fb9 NVARCHAR(255),
@Description_b0232fb9 NVARCHAR(MAX),
@Category_b0232fb9 NVARCHAR(100),
@Type_b0232fb9 NVARCHAR(100),
@Length_b0232fb9 INT,
@Precision_b0232fb9 INT,
@Scale_b0232fb9 INT,
@AllowsNull_b0232fb9 BIT,
@DefaultValue_b0232fb9 NVARCHAR(255),
@IsPrimaryKey_b0232fb9 BIT,
@IsUniqueKey_b0232fb9 BIT,
@IsReadOnly_b0232fb9 BIT,
@IsRequired_b0232fb9 BIT,
@RelatedIntegrationObjectID_b0232fb9 UNIQUEIDENTIFIER,
@RelatedIntegrationObjectFieldName_b0232fb9 NVARCHAR(255),
@Sequence_b0232fb9 INT,
@Configuration_b0232fb9 NVARCHAR(MAX),
@Status_b0232fb9 NVARCHAR(25),
@IsCustom_b0232fb9 BIT,
@MetadataSource_b0232fb9 NVARCHAR(20)
SET
  @ID_b0232fb9 = '69198ae8-53d7-417a-8610-9729f17655b5'
SET
  @IntegrationObjectID_b0232fb9 = '1B6AAA3C-002C-4E1A-8C82-0900D33FE02A'
SET
  @Name_b0232fb9 = N'alert_label'
SET
  @DisplayName_b0232fb9 = N'Alert Label'
SET
  @Description_b0232fb9 = N'Human-readable name of the event type, resolved from the installed plugin set.'
SET
  @Type_b0232fb9 = N'String'
SET
  @AllowsNull_b0232fb9 = 1
SET
  @IsPrimaryKey_b0232fb9 = 0
SET
  @IsUniqueKey_b0232fb9 = 0
SET
  @IsReadOnly_b0232fb9 = 1
SET
  @IsRequired_b0232fb9 = 0
SET
  @Sequence_b0232fb9 = 3
SET
  @Configuration_b0232fb9 = N'{
  "contexts": [
    "view"
  ]
}'
SET
  @Status_b0232fb9 = N'Active'
SET
  @IsCustom_b0232fb9 = 0
SET
  @MetadataSource_b0232fb9 = N'Declared' EXEC [__mj].spCreateIntegrationObjectField @ID = @ID_b0232fb9,
  @IntegrationObjectID = @IntegrationObjectID_b0232fb9,
  @Name = @Name_b0232fb9,
  @DisplayName = @DisplayName_b0232fb9,
  @Description = @Description_b0232fb9,
  @Category = @Category_b0232fb9,
  @Category_Clear = 1,
  @Type = @Type_b0232fb9,
  @Length = @Length_b0232fb9,
  @Length_Clear = 1,
  @Precision = @Precision_b0232fb9,
  @Precision_Clear = 1,
  @Scale = @Scale_b0232fb9,
  @Scale_Clear = 1,
  @AllowsNull = @AllowsNull_b0232fb9,
  @DefaultValue = @DefaultValue_b0232fb9,
  @DefaultValue_Clear = 1,
  @IsPrimaryKey = @IsPrimaryKey_b0232fb9,
  @IsUniqueKey = @IsUniqueKey_b0232fb9,
  @IsReadOnly = @IsReadOnly_b0232fb9,
  @IsRequired = @IsRequired_b0232fb9,
  @RelatedIntegrationObjectID = @RelatedIntegrationObjectID_b0232fb9,
  @RelatedIntegrationObjectID_Clear = 1,
  @RelatedIntegrationObjectFieldName = @RelatedIntegrationObjectFieldName_b0232fb9,
  @RelatedIntegrationObjectFieldName_Clear = 1,
  @Sequence = @Sequence_b0232fb9,
  @Configuration = @Configuration_b0232fb9,
  @Status = @Status_b0232fb9,
  @IsCustom = @IsCustom_b0232fb9,
  @MetadataSource = @MetadataSource_b0232fb9;

GO

-- Save MJ: Integration Object Fields (core SP call only)
DECLARE @ID_45141675 UNIQUEIDENTIFIER,
@IntegrationObjectID_45141675 UNIQUEIDENTIFIER,
@Name_45141675 NVARCHAR(255),
@DisplayName_45141675 NVARCHAR(255),
@Description_45141675 NVARCHAR(MAX),
@Category_45141675 NVARCHAR(100),
@Type_45141675 NVARCHAR(100),
@Length_45141675 INT,
@Precision_45141675 INT,
@Scale_45141675 INT,
@AllowsNull_45141675 BIT,
@DefaultValue_45141675 NVARCHAR(255),
@IsPrimaryKey_45141675 BIT,
@IsUniqueKey_45141675 BIT,
@IsReadOnly_45141675 BIT,
@IsRequired_45141675 BIT,
@RelatedIntegrationObjectID_45141675 UNIQUEIDENTIFIER,
@RelatedIntegrationObjectFieldName_45141675 NVARCHAR(255),
@Sequence_45141675 INT,
@Configuration_45141675 NVARCHAR(MAX),
@Status_45141675 NVARCHAR(25),
@IsCustom_45141675 BIT,
@MetadataSource_45141675 NVARCHAR(20)
SET
  @ID_45141675 = '0a82633b-3811-46b9-9b88-515fa3ddf9c4'
SET
  @IntegrationObjectID_45141675 = '1B6AAA3C-002C-4E1A-8C82-0900D33FE02A'
SET
  @Name_45141675 = N'created_on'
SET
  @DisplayName_45141675 = N'Created On (Epoch)'
SET
  @Description_45141675 = N'Raw Unix timestamp in SECONDS with sub-second precision, exactly as WP Activity Log stores it.'
SET
  @Type_45141675 = N'Decimal'
SET
  @AllowsNull_45141675 = 0
SET
  @IsPrimaryKey_45141675 = 0
SET
  @IsUniqueKey_45141675 = 0
SET
  @IsReadOnly_45141675 = 1
SET
  @IsRequired_45141675 = 0
SET
  @Sequence_45141675 = 4
SET
  @Configuration_45141675 = N'{
  "contexts": [
    "view"
  ]
}'
SET
  @Status_45141675 = N'Active'
SET
  @IsCustom_45141675 = 0
SET
  @MetadataSource_45141675 = N'Declared' EXEC [__mj].spCreateIntegrationObjectField @ID = @ID_45141675,
  @IntegrationObjectID = @IntegrationObjectID_45141675,
  @Name = @Name_45141675,
  @DisplayName = @DisplayName_45141675,
  @Description = @Description_45141675,
  @Category = @Category_45141675,
  @Category_Clear = 1,
  @Type = @Type_45141675,
  @Length = @Length_45141675,
  @Length_Clear = 1,
  @Precision = @Precision_45141675,
  @Precision_Clear = 1,
  @Scale = @Scale_45141675,
  @Scale_Clear = 1,
  @AllowsNull = @AllowsNull_45141675,
  @DefaultValue = @DefaultValue_45141675,
  @DefaultValue_Clear = 1,
  @IsPrimaryKey = @IsPrimaryKey_45141675,
  @IsUniqueKey = @IsUniqueKey_45141675,
  @IsReadOnly = @IsReadOnly_45141675,
  @IsRequired = @IsRequired_45141675,
  @RelatedIntegrationObjectID = @RelatedIntegrationObjectID_45141675,
  @RelatedIntegrationObjectID_Clear = 1,
  @RelatedIntegrationObjectFieldName = @RelatedIntegrationObjectFieldName_45141675,
  @RelatedIntegrationObjectFieldName_Clear = 1,
  @Sequence = @Sequence_45141675,
  @Configuration = @Configuration_45141675,
  @Status = @Status_45141675,
  @IsCustom = @IsCustom_45141675,
  @MetadataSource = @MetadataSource_45141675;

GO

-- Save MJ: Integration Object Fields (core SP call only)
DECLARE @ID_ae134fd5 UNIQUEIDENTIFIER,
@IntegrationObjectID_ae134fd5 UNIQUEIDENTIFIER,
@Name_ae134fd5 NVARCHAR(255),
@DisplayName_ae134fd5 NVARCHAR(255),
@Description_ae134fd5 NVARCHAR(MAX),
@Category_ae134fd5 NVARCHAR(100),
@Type_ae134fd5 NVARCHAR(100),
@Length_ae134fd5 INT,
@Precision_ae134fd5 INT,
@Scale_ae134fd5 INT,
@AllowsNull_ae134fd5 BIT,
@DefaultValue_ae134fd5 NVARCHAR(255),
@IsPrimaryKey_ae134fd5 BIT,
@IsUniqueKey_ae134fd5 BIT,
@IsReadOnly_ae134fd5 BIT,
@IsRequired_ae134fd5 BIT,
@RelatedIntegrationObjectID_ae134fd5 UNIQUEIDENTIFIER,
@RelatedIntegrationObjectFieldName_ae134fd5 NVARCHAR(255),
@Sequence_ae134fd5 INT,
@Configuration_ae134fd5 NVARCHAR(MAX),
@Status_ae134fd5 NVARCHAR(25),
@IsCustom_ae134fd5 BIT,
@MetadataSource_ae134fd5 NVARCHAR(20)
SET
  @ID_ae134fd5 = '2150206a-4215-4d16-aa64-cc18734c98ef'
SET
  @IntegrationObjectID_ae134fd5 = '1B6AAA3C-002C-4E1A-8C82-0900D33FE02A'
SET
  @Name_ae134fd5 = N'created_at'
SET
  @DisplayName_ae134fd5 = N'Created At'
SET
  @Description_ae134fd5 = N'The same instant as an ISO-8601 UTC datetime. This is the incremental watermark field.'
SET
  @Type_ae134fd5 = N'Datetime'
SET
  @AllowsNull_ae134fd5 = 0
SET
  @IsPrimaryKey_ae134fd5 = 0
SET
  @IsUniqueKey_ae134fd5 = 0
SET
  @IsReadOnly_ae134fd5 = 1
SET
  @IsRequired_ae134fd5 = 0
SET
  @Sequence_ae134fd5 = 5
SET
  @Configuration_ae134fd5 = N'{
  "contexts": [
    "view"
  ]
}'
SET
  @Status_ae134fd5 = N'Active'
SET
  @IsCustom_ae134fd5 = 0
SET
  @MetadataSource_ae134fd5 = N'Declared' EXEC [__mj].spCreateIntegrationObjectField @ID = @ID_ae134fd5,
  @IntegrationObjectID = @IntegrationObjectID_ae134fd5,
  @Name = @Name_ae134fd5,
  @DisplayName = @DisplayName_ae134fd5,
  @Description = @Description_ae134fd5,
  @Category = @Category_ae134fd5,
  @Category_Clear = 1,
  @Type = @Type_ae134fd5,
  @Length = @Length_ae134fd5,
  @Length_Clear = 1,
  @Precision = @Precision_ae134fd5,
  @Precision_Clear = 1,
  @Scale = @Scale_ae134fd5,
  @Scale_Clear = 1,
  @AllowsNull = @AllowsNull_ae134fd5,
  @DefaultValue = @DefaultValue_ae134fd5,
  @DefaultValue_Clear = 1,
  @IsPrimaryKey = @IsPrimaryKey_ae134fd5,
  @IsUniqueKey = @IsUniqueKey_ae134fd5,
  @IsReadOnly = @IsReadOnly_ae134fd5,
  @IsRequired = @IsRequired_ae134fd5,
  @RelatedIntegrationObjectID = @RelatedIntegrationObjectID_ae134fd5,
  @RelatedIntegrationObjectID_Clear = 1,
  @RelatedIntegrationObjectFieldName = @RelatedIntegrationObjectFieldName_ae134fd5,
  @RelatedIntegrationObjectFieldName_Clear = 1,
  @Sequence = @Sequence_ae134fd5,
  @Configuration = @Configuration_ae134fd5,
  @Status = @Status_ae134fd5,
  @IsCustom = @IsCustom_ae134fd5,
  @MetadataSource = @MetadataSource_ae134fd5;

GO

-- Save MJ: Integration Object Fields (core SP call only)
DECLARE @ID_1342c895 UNIQUEIDENTIFIER,
@IntegrationObjectID_1342c895 UNIQUEIDENTIFIER,
@Name_1342c895 NVARCHAR(255),
@DisplayName_1342c895 NVARCHAR(255),
@Description_1342c895 NVARCHAR(MAX),
@Category_1342c895 NVARCHAR(100),
@Type_1342c895 NVARCHAR(100),
@Length_1342c895 INT,
@Precision_1342c895 INT,
@Scale_1342c895 INT,
@AllowsNull_1342c895 BIT,
@DefaultValue_1342c895 NVARCHAR(255),
@IsPrimaryKey_1342c895 BIT,
@IsUniqueKey_1342c895 BIT,
@IsReadOnly_1342c895 BIT,
@IsRequired_1342c895 BIT,
@RelatedIntegrationObjectID_1342c895 UNIQUEIDENTIFIER,
@RelatedIntegrationObjectFieldName_1342c895 NVARCHAR(255),
@Sequence_1342c895 INT,
@Configuration_1342c895 NVARCHAR(MAX),
@Status_1342c895 NVARCHAR(25),
@IsCustom_1342c895 BIT,
@MetadataSource_1342c895 NVARCHAR(20)
SET
  @ID_1342c895 = '275d0167-d5cf-4983-a38f-0e3aa6009a39'
SET
  @IntegrationObjectID_1342c895 = '1B6AAA3C-002C-4E1A-8C82-0900D33FE02A'
SET
  @Name_1342c895 = N'severity'
SET
  @DisplayName_1342c895 = N'Severity'
SET
  @Description_1342c895 = N'Raw numeric severity level as stored by the plugin: 500, 400, 300, 250 or 200.'
SET
  @Type_1342c895 = N'String'
SET
  @AllowsNull_1342c895 = 1
SET
  @IsPrimaryKey_1342c895 = 0
SET
  @IsUniqueKey_1342c895 = 0
SET
  @IsReadOnly_1342c895 = 1
SET
  @IsRequired_1342c895 = 0
SET
  @Sequence_1342c895 = 6
SET
  @Configuration_1342c895 = N'{
  "contexts": [
    "view"
  ]
}'
SET
  @Status_1342c895 = N'Active'
SET
  @IsCustom_1342c895 = 0
SET
  @MetadataSource_1342c895 = N'Declared' EXEC [__mj].spCreateIntegrationObjectField @ID = @ID_1342c895,
  @IntegrationObjectID = @IntegrationObjectID_1342c895,
  @Name = @Name_1342c895,
  @DisplayName = @DisplayName_1342c895,
  @Description = @Description_1342c895,
  @Category = @Category_1342c895,
  @Category_Clear = 1,
  @Type = @Type_1342c895,
  @Length = @Length_1342c895,
  @Length_Clear = 1,
  @Precision = @Precision_1342c895,
  @Precision_Clear = 1,
  @Scale = @Scale_1342c895,
  @Scale_Clear = 1,
  @AllowsNull = @AllowsNull_1342c895,
  @DefaultValue = @DefaultValue_1342c895,
  @DefaultValue_Clear = 1,
  @IsPrimaryKey = @IsPrimaryKey_1342c895,
  @IsUniqueKey = @IsUniqueKey_1342c895,
  @IsReadOnly = @IsReadOnly_1342c895,
  @IsRequired = @IsRequired_1342c895,
  @RelatedIntegrationObjectID = @RelatedIntegrationObjectID_1342c895,
  @RelatedIntegrationObjectID_Clear = 1,
  @RelatedIntegrationObjectFieldName = @RelatedIntegrationObjectFieldName_1342c895,
  @RelatedIntegrationObjectFieldName_Clear = 1,
  @Sequence = @Sequence_1342c895,
  @Configuration = @Configuration_1342c895,
  @Status = @Status_1342c895,
  @IsCustom = @IsCustom_1342c895,
  @MetadataSource = @MetadataSource_1342c895;

GO

-- Save MJ: Integration Object Fields (core SP call only)
DECLARE @ID_9bc2705c UNIQUEIDENTIFIER,
@IntegrationObjectID_9bc2705c UNIQUEIDENTIFIER,
@Name_9bc2705c NVARCHAR(255),
@DisplayName_9bc2705c NVARCHAR(255),
@Description_9bc2705c NVARCHAR(MAX),
@Category_9bc2705c NVARCHAR(100),
@Type_9bc2705c NVARCHAR(100),
@Length_9bc2705c INT,
@Precision_9bc2705c INT,
@Scale_9bc2705c INT,
@AllowsNull_9bc2705c BIT,
@DefaultValue_9bc2705c NVARCHAR(255),
@IsPrimaryKey_9bc2705c BIT,
@IsUniqueKey_9bc2705c BIT,
@IsReadOnly_9bc2705c BIT,
@IsRequired_9bc2705c BIT,
@RelatedIntegrationObjectID_9bc2705c UNIQUEIDENTIFIER,
@RelatedIntegrationObjectFieldName_9bc2705c NVARCHAR(255),
@Sequence_9bc2705c INT,
@Configuration_9bc2705c NVARCHAR(MAX),
@Status_9bc2705c NVARCHAR(25),
@IsCustom_9bc2705c BIT,
@MetadataSource_9bc2705c NVARCHAR(20)
SET
  @ID_9bc2705c = '62640cd4-25fb-4399-85c7-d5c9da821b10'
SET
  @IntegrationObjectID_9bc2705c = '1B6AAA3C-002C-4E1A-8C82-0900D33FE02A'
SET
  @Name_9bc2705c = N'severity_label'
SET
  @DisplayName_9bc2705c = N'Severity Label'
SET
  @Description_9bc2705c = N'Severity resolved to a name: Critical, High, Medium, Low, Informational or Unknown.'
SET
  @Type_9bc2705c = N'String'
SET
  @AllowsNull_9bc2705c = 1
SET
  @IsPrimaryKey_9bc2705c = 0
SET
  @IsUniqueKey_9bc2705c = 0
SET
  @IsReadOnly_9bc2705c = 1
SET
  @IsRequired_9bc2705c = 0
SET
  @Sequence_9bc2705c = 7
SET
  @Configuration_9bc2705c = N'{
  "contexts": [
    "view"
  ]
}'
SET
  @Status_9bc2705c = N'Active'
SET
  @IsCustom_9bc2705c = 0
SET
  @MetadataSource_9bc2705c = N'Declared' EXEC [__mj].spCreateIntegrationObjectField @ID = @ID_9bc2705c,
  @IntegrationObjectID = @IntegrationObjectID_9bc2705c,
  @Name = @Name_9bc2705c,
  @DisplayName = @DisplayName_9bc2705c,
  @Description = @Description_9bc2705c,
  @Category = @Category_9bc2705c,
  @Category_Clear = 1,
  @Type = @Type_9bc2705c,
  @Length = @Length_9bc2705c,
  @Length_Clear = 1,
  @Precision = @Precision_9bc2705c,
  @Precision_Clear = 1,
  @Scale = @Scale_9bc2705c,
  @Scale_Clear = 1,
  @AllowsNull = @AllowsNull_9bc2705c,
  @DefaultValue = @DefaultValue_9bc2705c,
  @DefaultValue_Clear = 1,
  @IsPrimaryKey = @IsPrimaryKey_9bc2705c,
  @IsUniqueKey = @IsUniqueKey_9bc2705c,
  @IsReadOnly = @IsReadOnly_9bc2705c,
  @IsRequired = @IsRequired_9bc2705c,
  @RelatedIntegrationObjectID = @RelatedIntegrationObjectID_9bc2705c,
  @RelatedIntegrationObjectID_Clear = 1,
  @RelatedIntegrationObjectFieldName = @RelatedIntegrationObjectFieldName_9bc2705c,
  @RelatedIntegrationObjectFieldName_Clear = 1,
  @Sequence = @Sequence_9bc2705c,
  @Configuration = @Configuration_9bc2705c,
  @Status = @Status_9bc2705c,
  @IsCustom = @IsCustom_9bc2705c,
  @MetadataSource = @MetadataSource_9bc2705c;

GO

-- Save MJ: Integration Object Fields (core SP call only)
DECLARE @ID_093d6c52 UNIQUEIDENTIFIER,
@IntegrationObjectID_093d6c52 UNIQUEIDENTIFIER,
@Name_093d6c52 NVARCHAR(255),
@DisplayName_093d6c52 NVARCHAR(255),
@Description_093d6c52 NVARCHAR(MAX),
@Category_093d6c52 NVARCHAR(100),
@Type_093d6c52 NVARCHAR(100),
@Length_093d6c52 INT,
@Precision_093d6c52 INT,
@Scale_093d6c52 INT,
@AllowsNull_093d6c52 BIT,
@DefaultValue_093d6c52 NVARCHAR(255),
@IsPrimaryKey_093d6c52 BIT,
@IsUniqueKey_093d6c52 BIT,
@IsReadOnly_093d6c52 BIT,
@IsRequired_093d6c52 BIT,
@RelatedIntegrationObjectID_093d6c52 UNIQUEIDENTIFIER,
@RelatedIntegrationObjectFieldName_093d6c52 NVARCHAR(255),
@Sequence_093d6c52 INT,
@Configuration_093d6c52 NVARCHAR(MAX),
@Status_093d6c52 NVARCHAR(25),
@IsCustom_093d6c52 BIT,
@MetadataSource_093d6c52 NVARCHAR(20)
SET
  @ID_093d6c52 = 'd2ec5b7f-2495-4087-bcf0-c87347ac9810'
SET
  @IntegrationObjectID_093d6c52 = '1B6AAA3C-002C-4E1A-8C82-0900D33FE02A'
SET
  @Name_093d6c52 = N'object'
SET
  @DisplayName_093d6c52 = N'Object'
SET
  @Description_093d6c52 = N'Subject of the activity, e.g. user, post or plugin.'
SET
  @Type_093d6c52 = N'String'
SET
  @AllowsNull_093d6c52 = 1
SET
  @IsPrimaryKey_093d6c52 = 0
SET
  @IsUniqueKey_093d6c52 = 0
SET
  @IsReadOnly_093d6c52 = 1
SET
  @IsRequired_093d6c52 = 0
SET
  @Sequence_093d6c52 = 8
SET
  @Configuration_093d6c52 = N'{
  "contexts": [
    "view"
  ]
}'
SET
  @Status_093d6c52 = N'Active'
SET
  @IsCustom_093d6c52 = 0
SET
  @MetadataSource_093d6c52 = N'Declared' EXEC [__mj].spCreateIntegrationObjectField @ID = @ID_093d6c52,
  @IntegrationObjectID = @IntegrationObjectID_093d6c52,
  @Name = @Name_093d6c52,
  @DisplayName = @DisplayName_093d6c52,
  @Description = @Description_093d6c52,
  @Category = @Category_093d6c52,
  @Category_Clear = 1,
  @Type = @Type_093d6c52,
  @Length = @Length_093d6c52,
  @Length_Clear = 1,
  @Precision = @Precision_093d6c52,
  @Precision_Clear = 1,
  @Scale = @Scale_093d6c52,
  @Scale_Clear = 1,
  @AllowsNull = @AllowsNull_093d6c52,
  @DefaultValue = @DefaultValue_093d6c52,
  @DefaultValue_Clear = 1,
  @IsPrimaryKey = @IsPrimaryKey_093d6c52,
  @IsUniqueKey = @IsUniqueKey_093d6c52,
  @IsReadOnly = @IsReadOnly_093d6c52,
  @IsRequired = @IsRequired_093d6c52,
  @RelatedIntegrationObjectID = @RelatedIntegrationObjectID_093d6c52,
  @RelatedIntegrationObjectID_Clear = 1,
  @RelatedIntegrationObjectFieldName = @RelatedIntegrationObjectFieldName_093d6c52,
  @RelatedIntegrationObjectFieldName_Clear = 1,
  @Sequence = @Sequence_093d6c52,
  @Configuration = @Configuration_093d6c52,
  @Status = @Status_093d6c52,
  @IsCustom = @IsCustom_093d6c52,
  @MetadataSource = @MetadataSource_093d6c52;

GO

-- Save MJ: Integration Object Fields (core SP call only)
DECLARE @ID_56f5e53d UNIQUEIDENTIFIER,
@IntegrationObjectID_56f5e53d UNIQUEIDENTIFIER,
@Name_56f5e53d NVARCHAR(255),
@DisplayName_56f5e53d NVARCHAR(255),
@Description_56f5e53d NVARCHAR(MAX),
@Category_56f5e53d NVARCHAR(100),
@Type_56f5e53d NVARCHAR(100),
@Length_56f5e53d INT,
@Precision_56f5e53d INT,
@Scale_56f5e53d INT,
@AllowsNull_56f5e53d BIT,
@DefaultValue_56f5e53d NVARCHAR(255),
@IsPrimaryKey_56f5e53d BIT,
@IsUniqueKey_56f5e53d BIT,
@IsReadOnly_56f5e53d BIT,
@IsRequired_56f5e53d BIT,
@RelatedIntegrationObjectID_56f5e53d UNIQUEIDENTIFIER,
@RelatedIntegrationObjectFieldName_56f5e53d NVARCHAR(255),
@Sequence_56f5e53d INT,
@Configuration_56f5e53d NVARCHAR(MAX),
@Status_56f5e53d NVARCHAR(25),
@IsCustom_56f5e53d BIT,
@MetadataSource_56f5e53d NVARCHAR(20)
SET
  @ID_56f5e53d = 'ba435b7d-340c-4038-8f19-6ed068dcfbf9'
SET
  @IntegrationObjectID_56f5e53d = '1B6AAA3C-002C-4E1A-8C82-0900D33FE02A'
SET
  @Name_56f5e53d = N'event_type'
SET
  @DisplayName_56f5e53d = N'Event Type'
SET
  @Description_56f5e53d = N'Classification of the activity, e.g. login, modified or deleted.'
SET
  @Type_56f5e53d = N'String'
SET
  @AllowsNull_56f5e53d = 1
SET
  @IsPrimaryKey_56f5e53d = 0
SET
  @IsUniqueKey_56f5e53d = 0
SET
  @IsReadOnly_56f5e53d = 1
SET
  @IsRequired_56f5e53d = 0
SET
  @Sequence_56f5e53d = 9
SET
  @Configuration_56f5e53d = N'{
  "contexts": [
    "view"
  ]
}'
SET
  @Status_56f5e53d = N'Active'
SET
  @IsCustom_56f5e53d = 0
SET
  @MetadataSource_56f5e53d = N'Declared' EXEC [__mj].spCreateIntegrationObjectField @ID = @ID_56f5e53d,
  @IntegrationObjectID = @IntegrationObjectID_56f5e53d,
  @Name = @Name_56f5e53d,
  @DisplayName = @DisplayName_56f5e53d,
  @Description = @Description_56f5e53d,
  @Category = @Category_56f5e53d,
  @Category_Clear = 1,
  @Type = @Type_56f5e53d,
  @Length = @Length_56f5e53d,
  @Length_Clear = 1,
  @Precision = @Precision_56f5e53d,
  @Precision_Clear = 1,
  @Scale = @Scale_56f5e53d,
  @Scale_Clear = 1,
  @AllowsNull = @AllowsNull_56f5e53d,
  @DefaultValue = @DefaultValue_56f5e53d,
  @DefaultValue_Clear = 1,
  @IsPrimaryKey = @IsPrimaryKey_56f5e53d,
  @IsUniqueKey = @IsUniqueKey_56f5e53d,
  @IsReadOnly = @IsReadOnly_56f5e53d,
  @IsRequired = @IsRequired_56f5e53d,
  @RelatedIntegrationObjectID = @RelatedIntegrationObjectID_56f5e53d,
  @RelatedIntegrationObjectID_Clear = 1,
  @RelatedIntegrationObjectFieldName = @RelatedIntegrationObjectFieldName_56f5e53d,
  @RelatedIntegrationObjectFieldName_Clear = 1,
  @Sequence = @Sequence_56f5e53d,
  @Configuration = @Configuration_56f5e53d,
  @Status = @Status_56f5e53d,
  @IsCustom = @IsCustom_56f5e53d,
  @MetadataSource = @MetadataSource_56f5e53d;

GO

-- Save MJ: Integration Object Fields (core SP call only)
DECLARE @ID_f58d9cf3 UNIQUEIDENTIFIER,
@IntegrationObjectID_f58d9cf3 UNIQUEIDENTIFIER,
@Name_f58d9cf3 NVARCHAR(255),
@DisplayName_f58d9cf3 NVARCHAR(255),
@Description_f58d9cf3 NVARCHAR(MAX),
@Category_f58d9cf3 NVARCHAR(100),
@Type_f58d9cf3 NVARCHAR(100),
@Length_f58d9cf3 INT,
@Precision_f58d9cf3 INT,
@Scale_f58d9cf3 INT,
@AllowsNull_f58d9cf3 BIT,
@DefaultValue_f58d9cf3 NVARCHAR(255),
@IsPrimaryKey_f58d9cf3 BIT,
@IsUniqueKey_f58d9cf3 BIT,
@IsReadOnly_f58d9cf3 BIT,
@IsRequired_f58d9cf3 BIT,
@RelatedIntegrationObjectID_f58d9cf3 UNIQUEIDENTIFIER,
@RelatedIntegrationObjectFieldName_f58d9cf3 NVARCHAR(255),
@Sequence_f58d9cf3 INT,
@Configuration_f58d9cf3 NVARCHAR(MAX),
@Status_f58d9cf3 NVARCHAR(25),
@IsCustom_f58d9cf3 BIT,
@MetadataSource_f58d9cf3 NVARCHAR(20)
SET
  @ID_f58d9cf3 = 'cc4e4400-b43d-4b3d-bcdb-2641e8520389'
SET
  @IntegrationObjectID_f58d9cf3 = '1B6AAA3C-002C-4E1A-8C82-0900D33FE02A'
SET
  @Name_f58d9cf3 = N'username'
SET
  @DisplayName_f58d9cf3 = N'Username'
SET
  @Description_f58d9cf3 = N'WordPress username responsible for the event.'
SET
  @Type_f58d9cf3 = N'String'
SET
  @AllowsNull_f58d9cf3 = 1
SET
  @IsPrimaryKey_f58d9cf3 = 0
SET
  @IsUniqueKey_f58d9cf3 = 0
SET
  @IsReadOnly_f58d9cf3 = 1
SET
  @IsRequired_f58d9cf3 = 0
SET
  @Sequence_f58d9cf3 = 10
SET
  @Configuration_f58d9cf3 = N'{
  "contexts": [
    "view"
  ]
}'
SET
  @Status_f58d9cf3 = N'Active'
SET
  @IsCustom_f58d9cf3 = 0
SET
  @MetadataSource_f58d9cf3 = N'Declared' EXEC [__mj].spCreateIntegrationObjectField @ID = @ID_f58d9cf3,
  @IntegrationObjectID = @IntegrationObjectID_f58d9cf3,
  @Name = @Name_f58d9cf3,
  @DisplayName = @DisplayName_f58d9cf3,
  @Description = @Description_f58d9cf3,
  @Category = @Category_f58d9cf3,
  @Category_Clear = 1,
  @Type = @Type_f58d9cf3,
  @Length = @Length_f58d9cf3,
  @Length_Clear = 1,
  @Precision = @Precision_f58d9cf3,
  @Precision_Clear = 1,
  @Scale = @Scale_f58d9cf3,
  @Scale_Clear = 1,
  @AllowsNull = @AllowsNull_f58d9cf3,
  @DefaultValue = @DefaultValue_f58d9cf3,
  @DefaultValue_Clear = 1,
  @IsPrimaryKey = @IsPrimaryKey_f58d9cf3,
  @IsUniqueKey = @IsUniqueKey_f58d9cf3,
  @IsReadOnly = @IsReadOnly_f58d9cf3,
  @IsRequired = @IsRequired_f58d9cf3,
  @RelatedIntegrationObjectID = @RelatedIntegrationObjectID_f58d9cf3,
  @RelatedIntegrationObjectID_Clear = 1,
  @RelatedIntegrationObjectFieldName = @RelatedIntegrationObjectFieldName_f58d9cf3,
  @RelatedIntegrationObjectFieldName_Clear = 1,
  @Sequence = @Sequence_f58d9cf3,
  @Configuration = @Configuration_f58d9cf3,
  @Status = @Status_f58d9cf3,
  @IsCustom = @IsCustom_f58d9cf3,
  @MetadataSource = @MetadataSource_f58d9cf3;

GO

-- Save MJ: Integration Object Fields (core SP call only)
DECLARE @ID_0673d2a6 UNIQUEIDENTIFIER,
@IntegrationObjectID_0673d2a6 UNIQUEIDENTIFIER,
@Name_0673d2a6 NVARCHAR(255),
@DisplayName_0673d2a6 NVARCHAR(255),
@Description_0673d2a6 NVARCHAR(MAX),
@Category_0673d2a6 NVARCHAR(100),
@Type_0673d2a6 NVARCHAR(100),
@Length_0673d2a6 INT,
@Precision_0673d2a6 INT,
@Scale_0673d2a6 INT,
@AllowsNull_0673d2a6 BIT,
@DefaultValue_0673d2a6 NVARCHAR(255),
@IsPrimaryKey_0673d2a6 BIT,
@IsUniqueKey_0673d2a6 BIT,
@IsReadOnly_0673d2a6 BIT,
@IsRequired_0673d2a6 BIT,
@RelatedIntegrationObjectID_0673d2a6 UNIQUEIDENTIFIER,
@RelatedIntegrationObjectFieldName_0673d2a6 NVARCHAR(255),
@Sequence_0673d2a6 INT,
@Configuration_0673d2a6 NVARCHAR(MAX),
@Status_0673d2a6 NVARCHAR(25),
@IsCustom_0673d2a6 BIT,
@MetadataSource_0673d2a6 NVARCHAR(20)
SET
  @ID_0673d2a6 = '3d14316e-4350-415d-af2c-642545d2e304'
SET
  @IntegrationObjectID_0673d2a6 = '1B6AAA3C-002C-4E1A-8C82-0900D33FE02A'
SET
  @Name_0673d2a6 = N'user_id'
SET
  @DisplayName_0673d2a6 = N'User ID'
SET
  @Description_0673d2a6 = N'WordPress user ID responsible for the event; null for anonymous events.'
SET
  @Type_0673d2a6 = N'Integer'
SET
  @AllowsNull_0673d2a6 = 1
SET
  @IsPrimaryKey_0673d2a6 = 0
SET
  @IsUniqueKey_0673d2a6 = 0
SET
  @IsReadOnly_0673d2a6 = 1
SET
  @IsRequired_0673d2a6 = 0
SET
  @Sequence_0673d2a6 = 11
SET
  @Configuration_0673d2a6 = N'{
  "contexts": [
    "view"
  ]
}'
SET
  @Status_0673d2a6 = N'Active'
SET
  @IsCustom_0673d2a6 = 0
SET
  @MetadataSource_0673d2a6 = N'Declared' EXEC [__mj].spCreateIntegrationObjectField @ID = @ID_0673d2a6,
  @IntegrationObjectID = @IntegrationObjectID_0673d2a6,
  @Name = @Name_0673d2a6,
  @DisplayName = @DisplayName_0673d2a6,
  @Description = @Description_0673d2a6,
  @Category = @Category_0673d2a6,
  @Category_Clear = 1,
  @Type = @Type_0673d2a6,
  @Length = @Length_0673d2a6,
  @Length_Clear = 1,
  @Precision = @Precision_0673d2a6,
  @Precision_Clear = 1,
  @Scale = @Scale_0673d2a6,
  @Scale_Clear = 1,
  @AllowsNull = @AllowsNull_0673d2a6,
  @DefaultValue = @DefaultValue_0673d2a6,
  @DefaultValue_Clear = 1,
  @IsPrimaryKey = @IsPrimaryKey_0673d2a6,
  @IsUniqueKey = @IsUniqueKey_0673d2a6,
  @IsReadOnly = @IsReadOnly_0673d2a6,
  @IsRequired = @IsRequired_0673d2a6,
  @RelatedIntegrationObjectID = @RelatedIntegrationObjectID_0673d2a6,
  @RelatedIntegrationObjectID_Clear = 1,
  @RelatedIntegrationObjectFieldName = @RelatedIntegrationObjectFieldName_0673d2a6,
  @RelatedIntegrationObjectFieldName_Clear = 1,
  @Sequence = @Sequence_0673d2a6,
  @Configuration = @Configuration_0673d2a6,
  @Status = @Status_0673d2a6,
  @IsCustom = @IsCustom_0673d2a6,
  @MetadataSource = @MetadataSource_0673d2a6;

GO

-- Save MJ: Integration Object Fields (core SP call only)
DECLARE @ID_74812ea2 UNIQUEIDENTIFIER,
@IntegrationObjectID_74812ea2 UNIQUEIDENTIFIER,
@Name_74812ea2 NVARCHAR(255),
@DisplayName_74812ea2 NVARCHAR(255),
@Description_74812ea2 NVARCHAR(MAX),
@Category_74812ea2 NVARCHAR(100),
@Type_74812ea2 NVARCHAR(100),
@Length_74812ea2 INT,
@Precision_74812ea2 INT,
@Scale_74812ea2 INT,
@AllowsNull_74812ea2 BIT,
@DefaultValue_74812ea2 NVARCHAR(255),
@IsPrimaryKey_74812ea2 BIT,
@IsUniqueKey_74812ea2 BIT,
@IsReadOnly_74812ea2 BIT,
@IsRequired_74812ea2 BIT,
@RelatedIntegrationObjectID_74812ea2 UNIQUEIDENTIFIER,
@RelatedIntegrationObjectFieldName_74812ea2 NVARCHAR(255),
@Sequence_74812ea2 INT,
@Configuration_74812ea2 NVARCHAR(MAX),
@Status_74812ea2 NVARCHAR(25),
@IsCustom_74812ea2 BIT,
@MetadataSource_74812ea2 NVARCHAR(20)
SET
  @ID_74812ea2 = '48a99ef2-4665-4bd7-959b-306c65bf5930'
SET
  @IntegrationObjectID_74812ea2 = '1B6AAA3C-002C-4E1A-8C82-0900D33FE02A'
SET
  @Name_74812ea2 = N'user_roles'
SET
  @DisplayName_74812ea2 = N'User Roles'
SET
  @Description_74812ea2 = N'Roles held by the user at the time of the event.'
SET
  @Type_74812ea2 = N'String'
SET
  @AllowsNull_74812ea2 = 1
SET
  @IsPrimaryKey_74812ea2 = 0
SET
  @IsUniqueKey_74812ea2 = 0
SET
  @IsReadOnly_74812ea2 = 1
SET
  @IsRequired_74812ea2 = 0
SET
  @Sequence_74812ea2 = 12
SET
  @Configuration_74812ea2 = N'{
  "contexts": [
    "view"
  ]
}'
SET
  @Status_74812ea2 = N'Active'
SET
  @IsCustom_74812ea2 = 0
SET
  @MetadataSource_74812ea2 = N'Declared' EXEC [__mj].spCreateIntegrationObjectField @ID = @ID_74812ea2,
  @IntegrationObjectID = @IntegrationObjectID_74812ea2,
  @Name = @Name_74812ea2,
  @DisplayName = @DisplayName_74812ea2,
  @Description = @Description_74812ea2,
  @Category = @Category_74812ea2,
  @Category_Clear = 1,
  @Type = @Type_74812ea2,
  @Length = @Length_74812ea2,
  @Length_Clear = 1,
  @Precision = @Precision_74812ea2,
  @Precision_Clear = 1,
  @Scale = @Scale_74812ea2,
  @Scale_Clear = 1,
  @AllowsNull = @AllowsNull_74812ea2,
  @DefaultValue = @DefaultValue_74812ea2,
  @DefaultValue_Clear = 1,
  @IsPrimaryKey = @IsPrimaryKey_74812ea2,
  @IsUniqueKey = @IsUniqueKey_74812ea2,
  @IsReadOnly = @IsReadOnly_74812ea2,
  @IsRequired = @IsRequired_74812ea2,
  @RelatedIntegrationObjectID = @RelatedIntegrationObjectID_74812ea2,
  @RelatedIntegrationObjectID_Clear = 1,
  @RelatedIntegrationObjectFieldName = @RelatedIntegrationObjectFieldName_74812ea2,
  @RelatedIntegrationObjectFieldName_Clear = 1,
  @Sequence = @Sequence_74812ea2,
  @Configuration = @Configuration_74812ea2,
  @Status = @Status_74812ea2,
  @IsCustom = @IsCustom_74812ea2,
  @MetadataSource = @MetadataSource_74812ea2;

GO

-- Save MJ: Integration Object Fields (core SP call only)
DECLARE @ID_65d10fe2 UNIQUEIDENTIFIER,
@IntegrationObjectID_65d10fe2 UNIQUEIDENTIFIER,
@Name_65d10fe2 NVARCHAR(255),
@DisplayName_65d10fe2 NVARCHAR(255),
@Description_65d10fe2 NVARCHAR(MAX),
@Category_65d10fe2 NVARCHAR(100),
@Type_65d10fe2 NVARCHAR(100),
@Length_65d10fe2 INT,
@Precision_65d10fe2 INT,
@Scale_65d10fe2 INT,
@AllowsNull_65d10fe2 BIT,
@DefaultValue_65d10fe2 NVARCHAR(255),
@IsPrimaryKey_65d10fe2 BIT,
@IsUniqueKey_65d10fe2 BIT,
@IsReadOnly_65d10fe2 BIT,
@IsRequired_65d10fe2 BIT,
@RelatedIntegrationObjectID_65d10fe2 UNIQUEIDENTIFIER,
@RelatedIntegrationObjectFieldName_65d10fe2 NVARCHAR(255),
@Sequence_65d10fe2 INT,
@Configuration_65d10fe2 NVARCHAR(MAX),
@Status_65d10fe2 NVARCHAR(25),
@IsCustom_65d10fe2 BIT,
@MetadataSource_65d10fe2 NVARCHAR(20)
SET
  @ID_65d10fe2 = '01b518b3-7af1-4d8f-b63b-307aacdb82f4'
SET
  @IntegrationObjectID_65d10fe2 = '1B6AAA3C-002C-4E1A-8C82-0900D33FE02A'
SET
  @Name_65d10fe2 = N'client_ip'
SET
  @DisplayName_65d10fe2 = N'Client IP'
SET
  @Description_65d10fe2 = N'Source IP address the activity originated from.'
SET
  @Type_65d10fe2 = N'String'
SET
  @AllowsNull_65d10fe2 = 1
SET
  @IsPrimaryKey_65d10fe2 = 0
SET
  @IsUniqueKey_65d10fe2 = 0
SET
  @IsReadOnly_65d10fe2 = 1
SET
  @IsRequired_65d10fe2 = 0
SET
  @Sequence_65d10fe2 = 13
SET
  @Configuration_65d10fe2 = N'{
  "contexts": [
    "view"
  ]
}'
SET
  @Status_65d10fe2 = N'Active'
SET
  @IsCustom_65d10fe2 = 0
SET
  @MetadataSource_65d10fe2 = N'Declared' EXEC [__mj].spCreateIntegrationObjectField @ID = @ID_65d10fe2,
  @IntegrationObjectID = @IntegrationObjectID_65d10fe2,
  @Name = @Name_65d10fe2,
  @DisplayName = @DisplayName_65d10fe2,
  @Description = @Description_65d10fe2,
  @Category = @Category_65d10fe2,
  @Category_Clear = 1,
  @Type = @Type_65d10fe2,
  @Length = @Length_65d10fe2,
  @Length_Clear = 1,
  @Precision = @Precision_65d10fe2,
  @Precision_Clear = 1,
  @Scale = @Scale_65d10fe2,
  @Scale_Clear = 1,
  @AllowsNull = @AllowsNull_65d10fe2,
  @DefaultValue = @DefaultValue_65d10fe2,
  @DefaultValue_Clear = 1,
  @IsPrimaryKey = @IsPrimaryKey_65d10fe2,
  @IsUniqueKey = @IsUniqueKey_65d10fe2,
  @IsReadOnly = @IsReadOnly_65d10fe2,
  @IsRequired = @IsRequired_65d10fe2,
  @RelatedIntegrationObjectID = @RelatedIntegrationObjectID_65d10fe2,
  @RelatedIntegrationObjectID_Clear = 1,
  @RelatedIntegrationObjectFieldName = @RelatedIntegrationObjectFieldName_65d10fe2,
  @RelatedIntegrationObjectFieldName_Clear = 1,
  @Sequence = @Sequence_65d10fe2,
  @Configuration = @Configuration_65d10fe2,
  @Status = @Status_65d10fe2,
  @IsCustom = @IsCustom_65d10fe2,
  @MetadataSource = @MetadataSource_65d10fe2;

GO

-- Save MJ: Integration Object Fields (core SP call only)
DECLARE @ID_50e6c733 UNIQUEIDENTIFIER,
@IntegrationObjectID_50e6c733 UNIQUEIDENTIFIER,
@Name_50e6c733 NVARCHAR(255),
@DisplayName_50e6c733 NVARCHAR(255),
@Description_50e6c733 NVARCHAR(MAX),
@Category_50e6c733 NVARCHAR(100),
@Type_50e6c733 NVARCHAR(100),
@Length_50e6c733 INT,
@Precision_50e6c733 INT,
@Scale_50e6c733 INT,
@AllowsNull_50e6c733 BIT,
@DefaultValue_50e6c733 NVARCHAR(255),
@IsPrimaryKey_50e6c733 BIT,
@IsUniqueKey_50e6c733 BIT,
@IsReadOnly_50e6c733 BIT,
@IsRequired_50e6c733 BIT,
@RelatedIntegrationObjectID_50e6c733 UNIQUEIDENTIFIER,
@RelatedIntegrationObjectFieldName_50e6c733 NVARCHAR(255),
@Sequence_50e6c733 INT,
@Configuration_50e6c733 NVARCHAR(MAX),
@Status_50e6c733 NVARCHAR(25),
@IsCustom_50e6c733 BIT,
@MetadataSource_50e6c733 NVARCHAR(20)
SET
  @ID_50e6c733 = 'a5d041c3-a044-452c-84cc-b2f154dfe48e'
SET
  @IntegrationObjectID_50e6c733 = '1B6AAA3C-002C-4E1A-8C82-0900D33FE02A'
SET
  @Name_50e6c733 = N'user_agent'
SET
  @DisplayName_50e6c733 = N'User Agent'
SET
  @Description_50e6c733 = N'Browser user agent string captured with the event.'
SET
  @Type_50e6c733 = N'String'
SET
  @AllowsNull_50e6c733 = 1
SET
  @IsPrimaryKey_50e6c733 = 0
SET
  @IsUniqueKey_50e6c733 = 0
SET
  @IsReadOnly_50e6c733 = 1
SET
  @IsRequired_50e6c733 = 0
SET
  @Sequence_50e6c733 = 14
SET
  @Configuration_50e6c733 = N'{
  "contexts": [
    "view"
  ]
}'
SET
  @Status_50e6c733 = N'Active'
SET
  @IsCustom_50e6c733 = 0
SET
  @MetadataSource_50e6c733 = N'Declared' EXEC [__mj].spCreateIntegrationObjectField @ID = @ID_50e6c733,
  @IntegrationObjectID = @IntegrationObjectID_50e6c733,
  @Name = @Name_50e6c733,
  @DisplayName = @DisplayName_50e6c733,
  @Description = @Description_50e6c733,
  @Category = @Category_50e6c733,
  @Category_Clear = 1,
  @Type = @Type_50e6c733,
  @Length = @Length_50e6c733,
  @Length_Clear = 1,
  @Precision = @Precision_50e6c733,
  @Precision_Clear = 1,
  @Scale = @Scale_50e6c733,
  @Scale_Clear = 1,
  @AllowsNull = @AllowsNull_50e6c733,
  @DefaultValue = @DefaultValue_50e6c733,
  @DefaultValue_Clear = 1,
  @IsPrimaryKey = @IsPrimaryKey_50e6c733,
  @IsUniqueKey = @IsUniqueKey_50e6c733,
  @IsReadOnly = @IsReadOnly_50e6c733,
  @IsRequired = @IsRequired_50e6c733,
  @RelatedIntegrationObjectID = @RelatedIntegrationObjectID_50e6c733,
  @RelatedIntegrationObjectID_Clear = 1,
  @RelatedIntegrationObjectFieldName = @RelatedIntegrationObjectFieldName_50e6c733,
  @RelatedIntegrationObjectFieldName_Clear = 1,
  @Sequence = @Sequence_50e6c733,
  @Configuration = @Configuration_50e6c733,
  @Status = @Status_50e6c733,
  @IsCustom = @IsCustom_50e6c733,
  @MetadataSource = @MetadataSource_50e6c733;

GO

-- Save MJ: Integration Object Fields (core SP call only)
DECLARE @ID_c634e516 UNIQUEIDENTIFIER,
@IntegrationObjectID_c634e516 UNIQUEIDENTIFIER,
@Name_c634e516 NVARCHAR(255),
@DisplayName_c634e516 NVARCHAR(255),
@Description_c634e516 NVARCHAR(MAX),
@Category_c634e516 NVARCHAR(100),
@Type_c634e516 NVARCHAR(100),
@Length_c634e516 INT,
@Precision_c634e516 INT,
@Scale_c634e516 INT,
@AllowsNull_c634e516 BIT,
@DefaultValue_c634e516 NVARCHAR(255),
@IsPrimaryKey_c634e516 BIT,
@IsUniqueKey_c634e516 BIT,
@IsReadOnly_c634e516 BIT,
@IsRequired_c634e516 BIT,
@RelatedIntegrationObjectID_c634e516 UNIQUEIDENTIFIER,
@RelatedIntegrationObjectFieldName_c634e516 NVARCHAR(255),
@Sequence_c634e516 INT,
@Configuration_c634e516 NVARCHAR(MAX),
@Status_c634e516 NVARCHAR(25),
@IsCustom_c634e516 BIT,
@MetadataSource_c634e516 NVARCHAR(20)
SET
  @ID_c634e516 = '1b9e12a3-4ca9-4c0f-96de-f05d3ce76416'
SET
  @IntegrationObjectID_c634e516 = '1B6AAA3C-002C-4E1A-8C82-0900D33FE02A'
SET
  @Name_c634e516 = N'session_id'
SET
  @DisplayName_c634e516 = N'Session ID'
SET
  @Description_c634e516 = N'Identifier of the session the event belongs to.'
SET
  @Type_c634e516 = N'String'
SET
  @AllowsNull_c634e516 = 1
SET
  @IsPrimaryKey_c634e516 = 0
SET
  @IsUniqueKey_c634e516 = 0
SET
  @IsReadOnly_c634e516 = 1
SET
  @IsRequired_c634e516 = 0
SET
  @Sequence_c634e516 = 15
SET
  @Configuration_c634e516 = N'{
  "contexts": [
    "view"
  ]
}'
SET
  @Status_c634e516 = N'Active'
SET
  @IsCustom_c634e516 = 0
SET
  @MetadataSource_c634e516 = N'Declared' EXEC [__mj].spCreateIntegrationObjectField @ID = @ID_c634e516,
  @IntegrationObjectID = @IntegrationObjectID_c634e516,
  @Name = @Name_c634e516,
  @DisplayName = @DisplayName_c634e516,
  @Description = @Description_c634e516,
  @Category = @Category_c634e516,
  @Category_Clear = 1,
  @Type = @Type_c634e516,
  @Length = @Length_c634e516,
  @Length_Clear = 1,
  @Precision = @Precision_c634e516,
  @Precision_Clear = 1,
  @Scale = @Scale_c634e516,
  @Scale_Clear = 1,
  @AllowsNull = @AllowsNull_c634e516,
  @DefaultValue = @DefaultValue_c634e516,
  @DefaultValue_Clear = 1,
  @IsPrimaryKey = @IsPrimaryKey_c634e516,
  @IsUniqueKey = @IsUniqueKey_c634e516,
  @IsReadOnly = @IsReadOnly_c634e516,
  @IsRequired = @IsRequired_c634e516,
  @RelatedIntegrationObjectID = @RelatedIntegrationObjectID_c634e516,
  @RelatedIntegrationObjectID_Clear = 1,
  @RelatedIntegrationObjectFieldName = @RelatedIntegrationObjectFieldName_c634e516,
  @RelatedIntegrationObjectFieldName_Clear = 1,
  @Sequence = @Sequence_c634e516,
  @Configuration = @Configuration_c634e516,
  @Status = @Status_c634e516,
  @IsCustom = @IsCustom_c634e516,
  @MetadataSource = @MetadataSource_c634e516;

GO

-- Save MJ: Integration Object Fields (core SP call only)
DECLARE @ID_ead7ec5a UNIQUEIDENTIFIER,
@IntegrationObjectID_ead7ec5a UNIQUEIDENTIFIER,
@Name_ead7ec5a NVARCHAR(255),
@DisplayName_ead7ec5a NVARCHAR(255),
@Description_ead7ec5a NVARCHAR(MAX),
@Category_ead7ec5a NVARCHAR(100),
@Type_ead7ec5a NVARCHAR(100),
@Length_ead7ec5a INT,
@Precision_ead7ec5a INT,
@Scale_ead7ec5a INT,
@AllowsNull_ead7ec5a BIT,
@DefaultValue_ead7ec5a NVARCHAR(255),
@IsPrimaryKey_ead7ec5a BIT,
@IsUniqueKey_ead7ec5a BIT,
@IsReadOnly_ead7ec5a BIT,
@IsRequired_ead7ec5a BIT,
@RelatedIntegrationObjectID_ead7ec5a UNIQUEIDENTIFIER,
@RelatedIntegrationObjectFieldName_ead7ec5a NVARCHAR(255),
@Sequence_ead7ec5a INT,
@Configuration_ead7ec5a NVARCHAR(MAX),
@Status_ead7ec5a NVARCHAR(25),
@IsCustom_ead7ec5a BIT,
@MetadataSource_ead7ec5a NVARCHAR(20)
SET
  @ID_ead7ec5a = 'db762596-31df-4a51-b278-d40558d5aaf5'
SET
  @IntegrationObjectID_ead7ec5a = '1B6AAA3C-002C-4E1A-8C82-0900D33FE02A'
SET
  @Name_ead7ec5a = N'post_id'
SET
  @DisplayName_ead7ec5a = N'Post ID'
SET
  @Description_ead7ec5a = N'Associated post ID; 0 when the event is not post-related.'
SET
  @Type_ead7ec5a = N'Integer'
SET
  @AllowsNull_ead7ec5a = 1
SET
  @IsPrimaryKey_ead7ec5a = 0
SET
  @IsUniqueKey_ead7ec5a = 0
SET
  @IsReadOnly_ead7ec5a = 1
SET
  @IsRequired_ead7ec5a = 0
SET
  @Sequence_ead7ec5a = 16
SET
  @Configuration_ead7ec5a = N'{
  "contexts": [
    "view"
  ]
}'
SET
  @Status_ead7ec5a = N'Active'
SET
  @IsCustom_ead7ec5a = 0
SET
  @MetadataSource_ead7ec5a = N'Declared' EXEC [__mj].spCreateIntegrationObjectField @ID = @ID_ead7ec5a,
  @IntegrationObjectID = @IntegrationObjectID_ead7ec5a,
  @Name = @Name_ead7ec5a,
  @DisplayName = @DisplayName_ead7ec5a,
  @Description = @Description_ead7ec5a,
  @Category = @Category_ead7ec5a,
  @Category_Clear = 1,
  @Type = @Type_ead7ec5a,
  @Length = @Length_ead7ec5a,
  @Length_Clear = 1,
  @Precision = @Precision_ead7ec5a,
  @Precision_Clear = 1,
  @Scale = @Scale_ead7ec5a,
  @Scale_Clear = 1,
  @AllowsNull = @AllowsNull_ead7ec5a,
  @DefaultValue = @DefaultValue_ead7ec5a,
  @DefaultValue_Clear = 1,
  @IsPrimaryKey = @IsPrimaryKey_ead7ec5a,
  @IsUniqueKey = @IsUniqueKey_ead7ec5a,
  @IsReadOnly = @IsReadOnly_ead7ec5a,
  @IsRequired = @IsRequired_ead7ec5a,
  @RelatedIntegrationObjectID = @RelatedIntegrationObjectID_ead7ec5a,
  @RelatedIntegrationObjectID_Clear = 1,
  @RelatedIntegrationObjectFieldName = @RelatedIntegrationObjectFieldName_ead7ec5a,
  @RelatedIntegrationObjectFieldName_Clear = 1,
  @Sequence = @Sequence_ead7ec5a,
  @Configuration = @Configuration_ead7ec5a,
  @Status = @Status_ead7ec5a,
  @IsCustom = @IsCustom_ead7ec5a,
  @MetadataSource = @MetadataSource_ead7ec5a;

GO

-- Save MJ: Integration Object Fields (core SP call only)
DECLARE @ID_d96d94c5 UNIQUEIDENTIFIER,
@IntegrationObjectID_d96d94c5 UNIQUEIDENTIFIER,
@Name_d96d94c5 NVARCHAR(255),
@DisplayName_d96d94c5 NVARCHAR(255),
@Description_d96d94c5 NVARCHAR(MAX),
@Category_d96d94c5 NVARCHAR(100),
@Type_d96d94c5 NVARCHAR(100),
@Length_d96d94c5 INT,
@Precision_d96d94c5 INT,
@Scale_d96d94c5 INT,
@AllowsNull_d96d94c5 BIT,
@DefaultValue_d96d94c5 NVARCHAR(255),
@IsPrimaryKey_d96d94c5 BIT,
@IsUniqueKey_d96d94c5 BIT,
@IsReadOnly_d96d94c5 BIT,
@IsRequired_d96d94c5 BIT,
@RelatedIntegrationObjectID_d96d94c5 UNIQUEIDENTIFIER,
@RelatedIntegrationObjectFieldName_d96d94c5 NVARCHAR(255),
@Sequence_d96d94c5 INT,
@Configuration_d96d94c5 NVARCHAR(MAX),
@Status_d96d94c5 NVARCHAR(25),
@IsCustom_d96d94c5 BIT,
@MetadataSource_d96d94c5 NVARCHAR(20)
SET
  @ID_d96d94c5 = '052c5b24-f6c0-467e-b72a-d8aabb23e417'
SET
  @IntegrationObjectID_d96d94c5 = '1B6AAA3C-002C-4E1A-8C82-0900D33FE02A'
SET
  @Name_d96d94c5 = N'post_type'
SET
  @DisplayName_d96d94c5 = N'Post Type'
SET
  @Description_d96d94c5 = N'Associated post type.'
SET
  @Type_d96d94c5 = N'String'
SET
  @AllowsNull_d96d94c5 = 1
SET
  @IsPrimaryKey_d96d94c5 = 0
SET
  @IsUniqueKey_d96d94c5 = 0
SET
  @IsReadOnly_d96d94c5 = 1
SET
  @IsRequired_d96d94c5 = 0
SET
  @Sequence_d96d94c5 = 17
SET
  @Configuration_d96d94c5 = N'{
  "contexts": [
    "view"
  ]
}'
SET
  @Status_d96d94c5 = N'Active'
SET
  @IsCustom_d96d94c5 = 0
SET
  @MetadataSource_d96d94c5 = N'Declared' EXEC [__mj].spCreateIntegrationObjectField @ID = @ID_d96d94c5,
  @IntegrationObjectID = @IntegrationObjectID_d96d94c5,
  @Name = @Name_d96d94c5,
  @DisplayName = @DisplayName_d96d94c5,
  @Description = @Description_d96d94c5,
  @Category = @Category_d96d94c5,
  @Category_Clear = 1,
  @Type = @Type_d96d94c5,
  @Length = @Length_d96d94c5,
  @Length_Clear = 1,
  @Precision = @Precision_d96d94c5,
  @Precision_Clear = 1,
  @Scale = @Scale_d96d94c5,
  @Scale_Clear = 1,
  @AllowsNull = @AllowsNull_d96d94c5,
  @DefaultValue = @DefaultValue_d96d94c5,
  @DefaultValue_Clear = 1,
  @IsPrimaryKey = @IsPrimaryKey_d96d94c5,
  @IsUniqueKey = @IsUniqueKey_d96d94c5,
  @IsReadOnly = @IsReadOnly_d96d94c5,
  @IsRequired = @IsRequired_d96d94c5,
  @RelatedIntegrationObjectID = @RelatedIntegrationObjectID_d96d94c5,
  @RelatedIntegrationObjectID_Clear = 1,
  @RelatedIntegrationObjectFieldName = @RelatedIntegrationObjectFieldName_d96d94c5,
  @RelatedIntegrationObjectFieldName_Clear = 1,
  @Sequence = @Sequence_d96d94c5,
  @Configuration = @Configuration_d96d94c5,
  @Status = @Status_d96d94c5,
  @IsCustom = @IsCustom_d96d94c5,
  @MetadataSource = @MetadataSource_d96d94c5;

GO

-- Save MJ: Integration Object Fields (core SP call only)
DECLARE @ID_c8f00a10 UNIQUEIDENTIFIER,
@IntegrationObjectID_c8f00a10 UNIQUEIDENTIFIER,
@Name_c8f00a10 NVARCHAR(255),
@DisplayName_c8f00a10 NVARCHAR(255),
@Description_c8f00a10 NVARCHAR(MAX),
@Category_c8f00a10 NVARCHAR(100),
@Type_c8f00a10 NVARCHAR(100),
@Length_c8f00a10 INT,
@Precision_c8f00a10 INT,
@Scale_c8f00a10 INT,
@AllowsNull_c8f00a10 BIT,
@DefaultValue_c8f00a10 NVARCHAR(255),
@IsPrimaryKey_c8f00a10 BIT,
@IsUniqueKey_c8f00a10 BIT,
@IsReadOnly_c8f00a10 BIT,
@IsRequired_c8f00a10 BIT,
@RelatedIntegrationObjectID_c8f00a10 UNIQUEIDENTIFIER,
@RelatedIntegrationObjectFieldName_c8f00a10 NVARCHAR(255),
@Sequence_c8f00a10 INT,
@Configuration_c8f00a10 NVARCHAR(MAX),
@Status_c8f00a10 NVARCHAR(25),
@IsCustom_c8f00a10 BIT,
@MetadataSource_c8f00a10 NVARCHAR(20)
SET
  @ID_c8f00a10 = '811c26a6-c1fa-47b3-8b73-b403d591d21a'
SET
  @IntegrationObjectID_c8f00a10 = '1B6AAA3C-002C-4E1A-8C82-0900D33FE02A'
SET
  @Name_c8f00a10 = N'post_status'
SET
  @DisplayName_c8f00a10 = N'Post Status'
SET
  @Description_c8f00a10 = N'Associated post status at the time of the event.'
SET
  @Type_c8f00a10 = N'String'
SET
  @AllowsNull_c8f00a10 = 1
SET
  @IsPrimaryKey_c8f00a10 = 0
SET
  @IsUniqueKey_c8f00a10 = 0
SET
  @IsReadOnly_c8f00a10 = 1
SET
  @IsRequired_c8f00a10 = 0
SET
  @Sequence_c8f00a10 = 18
SET
  @Configuration_c8f00a10 = N'{
  "contexts": [
    "view"
  ]
}'
SET
  @Status_c8f00a10 = N'Active'
SET
  @IsCustom_c8f00a10 = 0
SET
  @MetadataSource_c8f00a10 = N'Declared' EXEC [__mj].spCreateIntegrationObjectField @ID = @ID_c8f00a10,
  @IntegrationObjectID = @IntegrationObjectID_c8f00a10,
  @Name = @Name_c8f00a10,
  @DisplayName = @DisplayName_c8f00a10,
  @Description = @Description_c8f00a10,
  @Category = @Category_c8f00a10,
  @Category_Clear = 1,
  @Type = @Type_c8f00a10,
  @Length = @Length_c8f00a10,
  @Length_Clear = 1,
  @Precision = @Precision_c8f00a10,
  @Precision_Clear = 1,
  @Scale = @Scale_c8f00a10,
  @Scale_Clear = 1,
  @AllowsNull = @AllowsNull_c8f00a10,
  @DefaultValue = @DefaultValue_c8f00a10,
  @DefaultValue_Clear = 1,
  @IsPrimaryKey = @IsPrimaryKey_c8f00a10,
  @IsUniqueKey = @IsUniqueKey_c8f00a10,
  @IsReadOnly = @IsReadOnly_c8f00a10,
  @IsRequired = @IsRequired_c8f00a10,
  @RelatedIntegrationObjectID = @RelatedIntegrationObjectID_c8f00a10,
  @RelatedIntegrationObjectID_Clear = 1,
  @RelatedIntegrationObjectFieldName = @RelatedIntegrationObjectFieldName_c8f00a10,
  @RelatedIntegrationObjectFieldName_Clear = 1,
  @Sequence = @Sequence_c8f00a10,
  @Configuration = @Configuration_c8f00a10,
  @Status = @Status_c8f00a10,
  @IsCustom = @IsCustom_c8f00a10,
  @MetadataSource = @MetadataSource_c8f00a10;

GO

-- Save MJ: Integration Object Fields (core SP call only)
DECLARE @ID_b001d186 UNIQUEIDENTIFIER,
@IntegrationObjectID_b001d186 UNIQUEIDENTIFIER,
@Name_b001d186 NVARCHAR(255),
@DisplayName_b001d186 NVARCHAR(255),
@Description_b001d186 NVARCHAR(MAX),
@Category_b001d186 NVARCHAR(100),
@Type_b001d186 NVARCHAR(100),
@Length_b001d186 INT,
@Precision_b001d186 INT,
@Scale_b001d186 INT,
@AllowsNull_b001d186 BIT,
@DefaultValue_b001d186 NVARCHAR(255),
@IsPrimaryKey_b001d186 BIT,
@IsUniqueKey_b001d186 BIT,
@IsReadOnly_b001d186 BIT,
@IsRequired_b001d186 BIT,
@RelatedIntegrationObjectID_b001d186 UNIQUEIDENTIFIER,
@RelatedIntegrationObjectFieldName_b001d186 NVARCHAR(255),
@Sequence_b001d186 INT,
@Configuration_b001d186 NVARCHAR(MAX),
@Status_b001d186 NVARCHAR(25),
@IsCustom_b001d186 BIT,
@MetadataSource_b001d186 NVARCHAR(20)
SET
  @ID_b001d186 = '857ac7ac-23f2-4f29-bc8a-8ea45f7a0bd7'
SET
  @IntegrationObjectID_b001d186 = '1B6AAA3C-002C-4E1A-8C82-0900D33FE02A'
SET
  @Name_b001d186 = N'meta'
SET
  @DisplayName_b001d186 = N'Metadata'
SET
  @Description_b001d186 = N'Event metadata pivoted from the plugin name/value table into a single object. Keys vary by event type.'
SET
  @Type_b001d186 = N'json'
SET
  @AllowsNull_b001d186 = 1
SET
  @IsPrimaryKey_b001d186 = 0
SET
  @IsUniqueKey_b001d186 = 0
SET
  @IsReadOnly_b001d186 = 1
SET
  @IsRequired_b001d186 = 0
SET
  @Sequence_b001d186 = 19
SET
  @Configuration_b001d186 = N'{
  "contexts": [
    "view"
  ]
}'
SET
  @Status_b001d186 = N'Active'
SET
  @IsCustom_b001d186 = 0
SET
  @MetadataSource_b001d186 = N'Declared' EXEC [__mj].spCreateIntegrationObjectField @ID = @ID_b001d186,
  @IntegrationObjectID = @IntegrationObjectID_b001d186,
  @Name = @Name_b001d186,
  @DisplayName = @DisplayName_b001d186,
  @Description = @Description_b001d186,
  @Category = @Category_b001d186,
  @Category_Clear = 1,
  @Type = @Type_b001d186,
  @Length = @Length_b001d186,
  @Length_Clear = 1,
  @Precision = @Precision_b001d186,
  @Precision_Clear = 1,
  @Scale = @Scale_b001d186,
  @Scale_Clear = 1,
  @AllowsNull = @AllowsNull_b001d186,
  @DefaultValue = @DefaultValue_b001d186,
  @DefaultValue_Clear = 1,
  @IsPrimaryKey = @IsPrimaryKey_b001d186,
  @IsUniqueKey = @IsUniqueKey_b001d186,
  @IsReadOnly = @IsReadOnly_b001d186,
  @IsRequired = @IsRequired_b001d186,
  @RelatedIntegrationObjectID = @RelatedIntegrationObjectID_b001d186,
  @RelatedIntegrationObjectID_Clear = 1,
  @RelatedIntegrationObjectFieldName = @RelatedIntegrationObjectFieldName_b001d186,
  @RelatedIntegrationObjectFieldName_Clear = 1,
  @Sequence = @Sequence_b001d186,
  @Configuration = @Configuration_b001d186,
  @Status = @Status_b001d186,
  @IsCustom = @IsCustom_b001d186,
  @MetadataSource = @MetadataSource_b001d186;

GO

-- Save MJ: Integration Object Fields (core SP call only)
DECLARE @ID_22241a1b UNIQUEIDENTIFIER,
@IntegrationObjectID_22241a1b UNIQUEIDENTIFIER,
@Name_22241a1b NVARCHAR(255),
@DisplayName_22241a1b NVARCHAR(255),
@Description_22241a1b NVARCHAR(MAX),
@Category_22241a1b NVARCHAR(100),
@Type_22241a1b NVARCHAR(100),
@Length_22241a1b INT,
@Precision_22241a1b INT,
@Scale_22241a1b INT,
@AllowsNull_22241a1b BIT,
@DefaultValue_22241a1b NVARCHAR(255),
@IsPrimaryKey_22241a1b BIT,
@IsUniqueKey_22241a1b BIT,
@IsReadOnly_22241a1b BIT,
@IsRequired_22241a1b BIT,
@RelatedIntegrationObjectID_22241a1b UNIQUEIDENTIFIER,
@RelatedIntegrationObjectFieldName_22241a1b NVARCHAR(255),
@Sequence_22241a1b INT,
@Configuration_22241a1b NVARCHAR(MAX),
@Status_22241a1b NVARCHAR(25),
@IsCustom_22241a1b BIT,
@MetadataSource_22241a1b NVARCHAR(20)
SET
  @ID_22241a1b = '81106de0-473b-4541-8f7b-6165561dad5e'
SET
  @IntegrationObjectID_22241a1b = 'FB9E1B85-6B87-4561-B332-C264ECF2D87B'
SET
  @Name_22241a1b = N'alert_id'
SET
  @DisplayName_22241a1b = N'Alert ID'
SET
  @Description_22241a1b = N'WP Activity Log event type ID. Primary key.'
SET
  @Type_22241a1b = N'Integer'
SET
  @AllowsNull_22241a1b = 0
SET
  @IsPrimaryKey_22241a1b = 1
SET
  @IsUniqueKey_22241a1b = 1
SET
  @IsReadOnly_22241a1b = 1
SET
  @IsRequired_22241a1b = 1
SET
  @Sequence_22241a1b = 0
SET
  @Configuration_22241a1b = N'{
  "contexts": [
    "view"
  ]
}'
SET
  @Status_22241a1b = N'Active'
SET
  @IsCustom_22241a1b = 0
SET
  @MetadataSource_22241a1b = N'Declared' EXEC [__mj].spCreateIntegrationObjectField @ID = @ID_22241a1b,
  @IntegrationObjectID = @IntegrationObjectID_22241a1b,
  @Name = @Name_22241a1b,
  @DisplayName = @DisplayName_22241a1b,
  @Description = @Description_22241a1b,
  @Category = @Category_22241a1b,
  @Category_Clear = 1,
  @Type = @Type_22241a1b,
  @Length = @Length_22241a1b,
  @Length_Clear = 1,
  @Precision = @Precision_22241a1b,
  @Precision_Clear = 1,
  @Scale = @Scale_22241a1b,
  @Scale_Clear = 1,
  @AllowsNull = @AllowsNull_22241a1b,
  @DefaultValue = @DefaultValue_22241a1b,
  @DefaultValue_Clear = 1,
  @IsPrimaryKey = @IsPrimaryKey_22241a1b,
  @IsUniqueKey = @IsUniqueKey_22241a1b,
  @IsReadOnly = @IsReadOnly_22241a1b,
  @IsRequired = @IsRequired_22241a1b,
  @RelatedIntegrationObjectID = @RelatedIntegrationObjectID_22241a1b,
  @RelatedIntegrationObjectID_Clear = 1,
  @RelatedIntegrationObjectFieldName = @RelatedIntegrationObjectFieldName_22241a1b,
  @RelatedIntegrationObjectFieldName_Clear = 1,
  @Sequence = @Sequence_22241a1b,
  @Configuration = @Configuration_22241a1b,
  @Status = @Status_22241a1b,
  @IsCustom = @IsCustom_22241a1b,
  @MetadataSource = @MetadataSource_22241a1b;

GO

-- Save MJ: Integration Object Fields (core SP call only)
DECLARE @ID_13275329 UNIQUEIDENTIFIER,
@IntegrationObjectID_13275329 UNIQUEIDENTIFIER,
@Name_13275329 NVARCHAR(255),
@DisplayName_13275329 NVARCHAR(255),
@Description_13275329 NVARCHAR(MAX),
@Category_13275329 NVARCHAR(100),
@Type_13275329 NVARCHAR(100),
@Length_13275329 INT,
@Precision_13275329 INT,
@Scale_13275329 INT,
@AllowsNull_13275329 BIT,
@DefaultValue_13275329 NVARCHAR(255),
@IsPrimaryKey_13275329 BIT,
@IsUniqueKey_13275329 BIT,
@IsReadOnly_13275329 BIT,
@IsRequired_13275329 BIT,
@RelatedIntegrationObjectID_13275329 UNIQUEIDENTIFIER,
@RelatedIntegrationObjectFieldName_13275329 NVARCHAR(255),
@Sequence_13275329 INT,
@Configuration_13275329 NVARCHAR(MAX),
@Status_13275329 NVARCHAR(25),
@IsCustom_13275329 BIT,
@MetadataSource_13275329 NVARCHAR(20)
SET
  @ID_13275329 = '2497fd94-cfb2-44da-95a1-dd49c53039a5'
SET
  @IntegrationObjectID_13275329 = 'FB9E1B85-6B87-4561-B332-C264ECF2D87B'
SET
  @Name_13275329 = N'label'
SET
  @DisplayName_13275329 = N'Label'
SET
  @Description_13275329 = N'Short human-readable name of the event type.'
SET
  @Type_13275329 = N'String'
SET
  @AllowsNull_13275329 = 1
SET
  @IsPrimaryKey_13275329 = 0
SET
  @IsUniqueKey_13275329 = 0
SET
  @IsReadOnly_13275329 = 1
SET
  @IsRequired_13275329 = 0
SET
  @Sequence_13275329 = 1
SET
  @Configuration_13275329 = N'{
  "contexts": [
    "view"
  ]
}'
SET
  @Status_13275329 = N'Active'
SET
  @IsCustom_13275329 = 0
SET
  @MetadataSource_13275329 = N'Declared' EXEC [__mj].spCreateIntegrationObjectField @ID = @ID_13275329,
  @IntegrationObjectID = @IntegrationObjectID_13275329,
  @Name = @Name_13275329,
  @DisplayName = @DisplayName_13275329,
  @Description = @Description_13275329,
  @Category = @Category_13275329,
  @Category_Clear = 1,
  @Type = @Type_13275329,
  @Length = @Length_13275329,
  @Length_Clear = 1,
  @Precision = @Precision_13275329,
  @Precision_Clear = 1,
  @Scale = @Scale_13275329,
  @Scale_Clear = 1,
  @AllowsNull = @AllowsNull_13275329,
  @DefaultValue = @DefaultValue_13275329,
  @DefaultValue_Clear = 1,
  @IsPrimaryKey = @IsPrimaryKey_13275329,
  @IsUniqueKey = @IsUniqueKey_13275329,
  @IsReadOnly = @IsReadOnly_13275329,
  @IsRequired = @IsRequired_13275329,
  @RelatedIntegrationObjectID = @RelatedIntegrationObjectID_13275329,
  @RelatedIntegrationObjectID_Clear = 1,
  @RelatedIntegrationObjectFieldName = @RelatedIntegrationObjectFieldName_13275329,
  @RelatedIntegrationObjectFieldName_Clear = 1,
  @Sequence = @Sequence_13275329,
  @Configuration = @Configuration_13275329,
  @Status = @Status_13275329,
  @IsCustom = @IsCustom_13275329,
  @MetadataSource = @MetadataSource_13275329;

GO

-- Save MJ: Integration Object Fields (core SP call only)
DECLARE @ID_c4cbe92f UNIQUEIDENTIFIER,
@IntegrationObjectID_c4cbe92f UNIQUEIDENTIFIER,
@Name_c4cbe92f NVARCHAR(255),
@DisplayName_c4cbe92f NVARCHAR(255),
@Description_c4cbe92f NVARCHAR(MAX),
@Category_c4cbe92f NVARCHAR(100),
@Type_c4cbe92f NVARCHAR(100),
@Length_c4cbe92f INT,
@Precision_c4cbe92f INT,
@Scale_c4cbe92f INT,
@AllowsNull_c4cbe92f BIT,
@DefaultValue_c4cbe92f NVARCHAR(255),
@IsPrimaryKey_c4cbe92f BIT,
@IsUniqueKey_c4cbe92f BIT,
@IsReadOnly_c4cbe92f BIT,
@IsRequired_c4cbe92f BIT,
@RelatedIntegrationObjectID_c4cbe92f UNIQUEIDENTIFIER,
@RelatedIntegrationObjectFieldName_c4cbe92f NVARCHAR(255),
@Sequence_c4cbe92f INT,
@Configuration_c4cbe92f NVARCHAR(MAX),
@Status_c4cbe92f NVARCHAR(25),
@IsCustom_c4cbe92f BIT,
@MetadataSource_c4cbe92f NVARCHAR(20)
SET
  @ID_c4cbe92f = '4ee0f696-df4d-4511-98e1-e1d29fbe8b54'
SET
  @IntegrationObjectID_c4cbe92f = 'FB9E1B85-6B87-4561-B332-C264ECF2D87B'
SET
  @Name_c4cbe92f = N'message'
SET
  @DisplayName_c4cbe92f = N'Message Template'
SET
  @Description_c4cbe92f = N'Message template the plugin renders for this event type.'
SET
  @Type_c4cbe92f = N'String'
SET
  @AllowsNull_c4cbe92f = 1
SET
  @IsPrimaryKey_c4cbe92f = 0
SET
  @IsUniqueKey_c4cbe92f = 0
SET
  @IsReadOnly_c4cbe92f = 1
SET
  @IsRequired_c4cbe92f = 0
SET
  @Sequence_c4cbe92f = 2
SET
  @Configuration_c4cbe92f = N'{
  "contexts": [
    "view"
  ]
}'
SET
  @Status_c4cbe92f = N'Active'
SET
  @IsCustom_c4cbe92f = 0
SET
  @MetadataSource_c4cbe92f = N'Declared' EXEC [__mj].spCreateIntegrationObjectField @ID = @ID_c4cbe92f,
  @IntegrationObjectID = @IntegrationObjectID_c4cbe92f,
  @Name = @Name_c4cbe92f,
  @DisplayName = @DisplayName_c4cbe92f,
  @Description = @Description_c4cbe92f,
  @Category = @Category_c4cbe92f,
  @Category_Clear = 1,
  @Type = @Type_c4cbe92f,
  @Length = @Length_c4cbe92f,
  @Length_Clear = 1,
  @Precision = @Precision_c4cbe92f,
  @Precision_Clear = 1,
  @Scale = @Scale_c4cbe92f,
  @Scale_Clear = 1,
  @AllowsNull = @AllowsNull_c4cbe92f,
  @DefaultValue = @DefaultValue_c4cbe92f,
  @DefaultValue_Clear = 1,
  @IsPrimaryKey = @IsPrimaryKey_c4cbe92f,
  @IsUniqueKey = @IsUniqueKey_c4cbe92f,
  @IsReadOnly = @IsReadOnly_c4cbe92f,
  @IsRequired = @IsRequired_c4cbe92f,
  @RelatedIntegrationObjectID = @RelatedIntegrationObjectID_c4cbe92f,
  @RelatedIntegrationObjectID_Clear = 1,
  @RelatedIntegrationObjectFieldName = @RelatedIntegrationObjectFieldName_c4cbe92f,
  @RelatedIntegrationObjectFieldName_Clear = 1,
  @Sequence = @Sequence_c4cbe92f,
  @Configuration = @Configuration_c4cbe92f,
  @Status = @Status_c4cbe92f,
  @IsCustom = @IsCustom_c4cbe92f,
  @MetadataSource = @MetadataSource_c4cbe92f;

GO

-- Save MJ: Integration Object Fields (core SP call only)
DECLARE @ID_fe5cb55b UNIQUEIDENTIFIER,
@IntegrationObjectID_fe5cb55b UNIQUEIDENTIFIER,
@Name_fe5cb55b NVARCHAR(255),
@DisplayName_fe5cb55b NVARCHAR(255),
@Description_fe5cb55b NVARCHAR(MAX),
@Category_fe5cb55b NVARCHAR(100),
@Type_fe5cb55b NVARCHAR(100),
@Length_fe5cb55b INT,
@Precision_fe5cb55b INT,
@Scale_fe5cb55b INT,
@AllowsNull_fe5cb55b BIT,
@DefaultValue_fe5cb55b NVARCHAR(255),
@IsPrimaryKey_fe5cb55b BIT,
@IsUniqueKey_fe5cb55b BIT,
@IsReadOnly_fe5cb55b BIT,
@IsRequired_fe5cb55b BIT,
@RelatedIntegrationObjectID_fe5cb55b UNIQUEIDENTIFIER,
@RelatedIntegrationObjectFieldName_fe5cb55b NVARCHAR(255),
@Sequence_fe5cb55b INT,
@Configuration_fe5cb55b NVARCHAR(MAX),
@Status_fe5cb55b NVARCHAR(25),
@IsCustom_fe5cb55b BIT,
@MetadataSource_fe5cb55b NVARCHAR(20)
SET
  @ID_fe5cb55b = '92965b4e-08df-4c0d-89f1-a8d8aa58308d'
SET
  @IntegrationObjectID_fe5cb55b = 'FB9E1B85-6B87-4561-B332-C264ECF2D87B'
SET
  @Name_fe5cb55b = N'severity'
SET
  @DisplayName_fe5cb55b = N'Severity'
SET
  @Description_fe5cb55b = N'Declared severity level for this event type.'
SET
  @Type_fe5cb55b = N'String'
SET
  @AllowsNull_fe5cb55b = 1
SET
  @IsPrimaryKey_fe5cb55b = 0
SET
  @IsUniqueKey_fe5cb55b = 0
SET
  @IsReadOnly_fe5cb55b = 1
SET
  @IsRequired_fe5cb55b = 0
SET
  @Sequence_fe5cb55b = 3
SET
  @Configuration_fe5cb55b = N'{
  "contexts": [
    "view"
  ]
}'
SET
  @Status_fe5cb55b = N'Active'
SET
  @IsCustom_fe5cb55b = 0
SET
  @MetadataSource_fe5cb55b = N'Declared' EXEC [__mj].spCreateIntegrationObjectField @ID = @ID_fe5cb55b,
  @IntegrationObjectID = @IntegrationObjectID_fe5cb55b,
  @Name = @Name_fe5cb55b,
  @DisplayName = @DisplayName_fe5cb55b,
  @Description = @Description_fe5cb55b,
  @Category = @Category_fe5cb55b,
  @Category_Clear = 1,
  @Type = @Type_fe5cb55b,
  @Length = @Length_fe5cb55b,
  @Length_Clear = 1,
  @Precision = @Precision_fe5cb55b,
  @Precision_Clear = 1,
  @Scale = @Scale_fe5cb55b,
  @Scale_Clear = 1,
  @AllowsNull = @AllowsNull_fe5cb55b,
  @DefaultValue = @DefaultValue_fe5cb55b,
  @DefaultValue_Clear = 1,
  @IsPrimaryKey = @IsPrimaryKey_fe5cb55b,
  @IsUniqueKey = @IsUniqueKey_fe5cb55b,
  @IsReadOnly = @IsReadOnly_fe5cb55b,
  @IsRequired = @IsRequired_fe5cb55b,
  @RelatedIntegrationObjectID = @RelatedIntegrationObjectID_fe5cb55b,
  @RelatedIntegrationObjectID_Clear = 1,
  @RelatedIntegrationObjectFieldName = @RelatedIntegrationObjectFieldName_fe5cb55b,
  @RelatedIntegrationObjectFieldName_Clear = 1,
  @Sequence = @Sequence_fe5cb55b,
  @Configuration = @Configuration_fe5cb55b,
  @Status = @Status_fe5cb55b,
  @IsCustom = @IsCustom_fe5cb55b,
  @MetadataSource = @MetadataSource_fe5cb55b;

GO

-- Save MJ: Integration Object Fields (core SP call only)
DECLARE @ID_4cefec23 UNIQUEIDENTIFIER,
@IntegrationObjectID_4cefec23 UNIQUEIDENTIFIER,
@Name_4cefec23 NVARCHAR(255),
@DisplayName_4cefec23 NVARCHAR(255),
@Description_4cefec23 NVARCHAR(MAX),
@Category_4cefec23 NVARCHAR(100),
@Type_4cefec23 NVARCHAR(100),
@Length_4cefec23 INT,
@Precision_4cefec23 INT,
@Scale_4cefec23 INT,
@AllowsNull_4cefec23 BIT,
@DefaultValue_4cefec23 NVARCHAR(255),
@IsPrimaryKey_4cefec23 BIT,
@IsUniqueKey_4cefec23 BIT,
@IsReadOnly_4cefec23 BIT,
@IsRequired_4cefec23 BIT,
@RelatedIntegrationObjectID_4cefec23 UNIQUEIDENTIFIER,
@RelatedIntegrationObjectFieldName_4cefec23 NVARCHAR(255),
@Sequence_4cefec23 INT,
@Configuration_4cefec23 NVARCHAR(MAX),
@Status_4cefec23 NVARCHAR(25),
@IsCustom_4cefec23 BIT,
@MetadataSource_4cefec23 NVARCHAR(20)
SET
  @ID_4cefec23 = 'dc9b21a8-e493-4e9c-9be8-6b5bfa5d9ba6'
SET
  @IntegrationObjectID_4cefec23 = 'FB9E1B85-6B87-4561-B332-C264ECF2D87B'
SET
  @Name_4cefec23 = N'category'
SET
  @DisplayName_4cefec23 = N'Category'
SET
  @Description_4cefec23 = N'Top-level grouping the event type belongs to.'
SET
  @Type_4cefec23 = N'String'
SET
  @AllowsNull_4cefec23 = 1
SET
  @IsPrimaryKey_4cefec23 = 0
SET
  @IsUniqueKey_4cefec23 = 0
SET
  @IsReadOnly_4cefec23 = 1
SET
  @IsRequired_4cefec23 = 0
SET
  @Sequence_4cefec23 = 4
SET
  @Configuration_4cefec23 = N'{
  "contexts": [
    "view"
  ]
}'
SET
  @Status_4cefec23 = N'Active'
SET
  @IsCustom_4cefec23 = 0
SET
  @MetadataSource_4cefec23 = N'Declared' EXEC [__mj].spCreateIntegrationObjectField @ID = @ID_4cefec23,
  @IntegrationObjectID = @IntegrationObjectID_4cefec23,
  @Name = @Name_4cefec23,
  @DisplayName = @DisplayName_4cefec23,
  @Description = @Description_4cefec23,
  @Category = @Category_4cefec23,
  @Category_Clear = 1,
  @Type = @Type_4cefec23,
  @Length = @Length_4cefec23,
  @Length_Clear = 1,
  @Precision = @Precision_4cefec23,
  @Precision_Clear = 1,
  @Scale = @Scale_4cefec23,
  @Scale_Clear = 1,
  @AllowsNull = @AllowsNull_4cefec23,
  @DefaultValue = @DefaultValue_4cefec23,
  @DefaultValue_Clear = 1,
  @IsPrimaryKey = @IsPrimaryKey_4cefec23,
  @IsUniqueKey = @IsUniqueKey_4cefec23,
  @IsReadOnly = @IsReadOnly_4cefec23,
  @IsRequired = @IsRequired_4cefec23,
  @RelatedIntegrationObjectID = @RelatedIntegrationObjectID_4cefec23,
  @RelatedIntegrationObjectID_Clear = 1,
  @RelatedIntegrationObjectFieldName = @RelatedIntegrationObjectFieldName_4cefec23,
  @RelatedIntegrationObjectFieldName_Clear = 1,
  @Sequence = @Sequence_4cefec23,
  @Configuration = @Configuration_4cefec23,
  @Status = @Status_4cefec23,
  @IsCustom = @IsCustom_4cefec23,
  @MetadataSource = @MetadataSource_4cefec23;

GO

-- Save MJ: Integration Object Fields (core SP call only)
DECLARE @ID_ea9faeac UNIQUEIDENTIFIER,
@IntegrationObjectID_ea9faeac UNIQUEIDENTIFIER,
@Name_ea9faeac NVARCHAR(255),
@DisplayName_ea9faeac NVARCHAR(255),
@Description_ea9faeac NVARCHAR(MAX),
@Category_ea9faeac NVARCHAR(100),
@Type_ea9faeac NVARCHAR(100),
@Length_ea9faeac INT,
@Precision_ea9faeac INT,
@Scale_ea9faeac INT,
@AllowsNull_ea9faeac BIT,
@DefaultValue_ea9faeac NVARCHAR(255),
@IsPrimaryKey_ea9faeac BIT,
@IsUniqueKey_ea9faeac BIT,
@IsReadOnly_ea9faeac BIT,
@IsRequired_ea9faeac BIT,
@RelatedIntegrationObjectID_ea9faeac UNIQUEIDENTIFIER,
@RelatedIntegrationObjectFieldName_ea9faeac NVARCHAR(255),
@Sequence_ea9faeac INT,
@Configuration_ea9faeac NVARCHAR(MAX),
@Status_ea9faeac NVARCHAR(25),
@IsCustom_ea9faeac BIT,
@MetadataSource_ea9faeac NVARCHAR(20)
SET
  @ID_ea9faeac = '41cb0754-e4df-4f84-bc5c-f2c777663bb4'
SET
  @IntegrationObjectID_ea9faeac = 'FB9E1B85-6B87-4561-B332-C264ECF2D87B'
SET
  @Name_ea9faeac = N'subcategory'
SET
  @DisplayName_ea9faeac = N'Subcategory'
SET
  @Description_ea9faeac = N'Secondary grouping the event type belongs to.'
SET
  @Type_ea9faeac = N'String'
SET
  @AllowsNull_ea9faeac = 1
SET
  @IsPrimaryKey_ea9faeac = 0
SET
  @IsUniqueKey_ea9faeac = 0
SET
  @IsReadOnly_ea9faeac = 1
SET
  @IsRequired_ea9faeac = 0
SET
  @Sequence_ea9faeac = 5
SET
  @Configuration_ea9faeac = N'{
  "contexts": [
    "view"
  ]
}'
SET
  @Status_ea9faeac = N'Active'
SET
  @IsCustom_ea9faeac = 0
SET
  @MetadataSource_ea9faeac = N'Declared' EXEC [__mj].spCreateIntegrationObjectField @ID = @ID_ea9faeac,
  @IntegrationObjectID = @IntegrationObjectID_ea9faeac,
  @Name = @Name_ea9faeac,
  @DisplayName = @DisplayName_ea9faeac,
  @Description = @Description_ea9faeac,
  @Category = @Category_ea9faeac,
  @Category_Clear = 1,
  @Type = @Type_ea9faeac,
  @Length = @Length_ea9faeac,
  @Length_Clear = 1,
  @Precision = @Precision_ea9faeac,
  @Precision_Clear = 1,
  @Scale = @Scale_ea9faeac,
  @Scale_Clear = 1,
  @AllowsNull = @AllowsNull_ea9faeac,
  @DefaultValue = @DefaultValue_ea9faeac,
  @DefaultValue_Clear = 1,
  @IsPrimaryKey = @IsPrimaryKey_ea9faeac,
  @IsUniqueKey = @IsUniqueKey_ea9faeac,
  @IsReadOnly = @IsReadOnly_ea9faeac,
  @IsRequired = @IsRequired_ea9faeac,
  @RelatedIntegrationObjectID = @RelatedIntegrationObjectID_ea9faeac,
  @RelatedIntegrationObjectID_Clear = 1,
  @RelatedIntegrationObjectFieldName = @RelatedIntegrationObjectFieldName_ea9faeac,
  @RelatedIntegrationObjectFieldName_Clear = 1,
  @Sequence = @Sequence_ea9faeac,
  @Configuration = @Configuration_ea9faeac,
  @Status = @Status_ea9faeac,
  @IsCustom = @IsCustom_ea9faeac,
  @MetadataSource = @MetadataSource_ea9faeac;

GO

-- Save MJ: Integration Object Fields (core SP call only)
DECLARE @ID_ddf0aa81 UNIQUEIDENTIFIER,
@IntegrationObjectID_ddf0aa81 UNIQUEIDENTIFIER,
@Name_ddf0aa81 NVARCHAR(255),
@DisplayName_ddf0aa81 NVARCHAR(255),
@Description_ddf0aa81 NVARCHAR(MAX),
@Category_ddf0aa81 NVARCHAR(100),
@Type_ddf0aa81 NVARCHAR(100),
@Length_ddf0aa81 INT,
@Precision_ddf0aa81 INT,
@Scale_ddf0aa81 INT,
@AllowsNull_ddf0aa81 BIT,
@DefaultValue_ddf0aa81 NVARCHAR(255),
@IsPrimaryKey_ddf0aa81 BIT,
@IsUniqueKey_ddf0aa81 BIT,
@IsReadOnly_ddf0aa81 BIT,
@IsRequired_ddf0aa81 BIT,
@RelatedIntegrationObjectID_ddf0aa81 UNIQUEIDENTIFIER,
@RelatedIntegrationObjectFieldName_ddf0aa81 NVARCHAR(255),
@Sequence_ddf0aa81 INT,
@Configuration_ddf0aa81 NVARCHAR(MAX),
@Status_ddf0aa81 NVARCHAR(25),
@IsCustom_ddf0aa81 BIT,
@MetadataSource_ddf0aa81 NVARCHAR(20)
SET
  @ID_ddf0aa81 = 'b613f52d-00c9-4a75-8705-efaa9879e513'
SET
  @IntegrationObjectID_ddf0aa81 = 'FB9E1B85-6B87-4561-B332-C264ECF2D87B'
SET
  @Name_ddf0aa81 = N'object'
SET
  @DisplayName_ddf0aa81 = N'Object'
SET
  @Description_ddf0aa81 = N'Subject this event type concerns.'
SET
  @Type_ddf0aa81 = N'String'
SET
  @AllowsNull_ddf0aa81 = 1
SET
  @IsPrimaryKey_ddf0aa81 = 0
SET
  @IsUniqueKey_ddf0aa81 = 0
SET
  @IsReadOnly_ddf0aa81 = 1
SET
  @IsRequired_ddf0aa81 = 0
SET
  @Sequence_ddf0aa81 = 6
SET
  @Configuration_ddf0aa81 = N'{
  "contexts": [
    "view"
  ]
}'
SET
  @Status_ddf0aa81 = N'Active'
SET
  @IsCustom_ddf0aa81 = 0
SET
  @MetadataSource_ddf0aa81 = N'Declared' EXEC [__mj].spCreateIntegrationObjectField @ID = @ID_ddf0aa81,
  @IntegrationObjectID = @IntegrationObjectID_ddf0aa81,
  @Name = @Name_ddf0aa81,
  @DisplayName = @DisplayName_ddf0aa81,
  @Description = @Description_ddf0aa81,
  @Category = @Category_ddf0aa81,
  @Category_Clear = 1,
  @Type = @Type_ddf0aa81,
  @Length = @Length_ddf0aa81,
  @Length_Clear = 1,
  @Precision = @Precision_ddf0aa81,
  @Precision_Clear = 1,
  @Scale = @Scale_ddf0aa81,
  @Scale_Clear = 1,
  @AllowsNull = @AllowsNull_ddf0aa81,
  @DefaultValue = @DefaultValue_ddf0aa81,
  @DefaultValue_Clear = 1,
  @IsPrimaryKey = @IsPrimaryKey_ddf0aa81,
  @IsUniqueKey = @IsUniqueKey_ddf0aa81,
  @IsReadOnly = @IsReadOnly_ddf0aa81,
  @IsRequired = @IsRequired_ddf0aa81,
  @RelatedIntegrationObjectID = @RelatedIntegrationObjectID_ddf0aa81,
  @RelatedIntegrationObjectID_Clear = 1,
  @RelatedIntegrationObjectFieldName = @RelatedIntegrationObjectFieldName_ddf0aa81,
  @RelatedIntegrationObjectFieldName_Clear = 1,
  @Sequence = @Sequence_ddf0aa81,
  @Configuration = @Configuration_ddf0aa81,
  @Status = @Status_ddf0aa81,
  @IsCustom = @IsCustom_ddf0aa81,
  @MetadataSource = @MetadataSource_ddf0aa81;

GO

-- Save MJ: Integration Object Fields (core SP call only)
DECLARE @ID_3be2e282 UNIQUEIDENTIFIER,
@IntegrationObjectID_3be2e282 UNIQUEIDENTIFIER,
@Name_3be2e282 NVARCHAR(255),
@DisplayName_3be2e282 NVARCHAR(255),
@Description_3be2e282 NVARCHAR(MAX),
@Category_3be2e282 NVARCHAR(100),
@Type_3be2e282 NVARCHAR(100),
@Length_3be2e282 INT,
@Precision_3be2e282 INT,
@Scale_3be2e282 INT,
@AllowsNull_3be2e282 BIT,
@DefaultValue_3be2e282 NVARCHAR(255),
@IsPrimaryKey_3be2e282 BIT,
@IsUniqueKey_3be2e282 BIT,
@IsReadOnly_3be2e282 BIT,
@IsRequired_3be2e282 BIT,
@RelatedIntegrationObjectID_3be2e282 UNIQUEIDENTIFIER,
@RelatedIntegrationObjectFieldName_3be2e282 NVARCHAR(255),
@Sequence_3be2e282 INT,
@Configuration_3be2e282 NVARCHAR(MAX),
@Status_3be2e282 NVARCHAR(25),
@IsCustom_3be2e282 BIT,
@MetadataSource_3be2e282 NVARCHAR(20)
SET
  @ID_3be2e282 = '3184b995-8214-49a5-94f6-bc5975a84063'
SET
  @IntegrationObjectID_3be2e282 = 'FB9E1B85-6B87-4561-B332-C264ECF2D87B'
SET
  @Name_3be2e282 = N'event_type'
SET
  @DisplayName_3be2e282 = N'Event Type'
SET
  @Description_3be2e282 = N'Action this event type represents.'
SET
  @Type_3be2e282 = N'String'
SET
  @AllowsNull_3be2e282 = 1
SET
  @IsPrimaryKey_3be2e282 = 0
SET
  @IsUniqueKey_3be2e282 = 0
SET
  @IsReadOnly_3be2e282 = 1
SET
  @IsRequired_3be2e282 = 0
SET
  @Sequence_3be2e282 = 7
SET
  @Configuration_3be2e282 = N'{
  "contexts": [
    "view"
  ]
}'
SET
  @Status_3be2e282 = N'Active'
SET
  @IsCustom_3be2e282 = 0
SET
  @MetadataSource_3be2e282 = N'Declared' EXEC [__mj].spCreateIntegrationObjectField @ID = @ID_3be2e282,
  @IntegrationObjectID = @IntegrationObjectID_3be2e282,
  @Name = @Name_3be2e282,
  @DisplayName = @DisplayName_3be2e282,
  @Description = @Description_3be2e282,
  @Category = @Category_3be2e282,
  @Category_Clear = 1,
  @Type = @Type_3be2e282,
  @Length = @Length_3be2e282,
  @Length_Clear = 1,
  @Precision = @Precision_3be2e282,
  @Precision_Clear = 1,
  @Scale = @Scale_3be2e282,
  @Scale_Clear = 1,
  @AllowsNull = @AllowsNull_3be2e282,
  @DefaultValue = @DefaultValue_3be2e282,
  @DefaultValue_Clear = 1,
  @IsPrimaryKey = @IsPrimaryKey_3be2e282,
  @IsUniqueKey = @IsUniqueKey_3be2e282,
  @IsReadOnly = @IsReadOnly_3be2e282,
  @IsRequired = @IsRequired_3be2e282,
  @RelatedIntegrationObjectID = @RelatedIntegrationObjectID_3be2e282,
  @RelatedIntegrationObjectID_Clear = 1,
  @RelatedIntegrationObjectFieldName = @RelatedIntegrationObjectFieldName_3be2e282,
  @RelatedIntegrationObjectFieldName_Clear = 1,
  @Sequence = @Sequence_3be2e282,
  @Configuration = @Configuration_3be2e282,
  @Status = @Status_3be2e282,
  @IsCustom = @IsCustom_3be2e282,
  @MetadataSource = @MetadataSource_3be2e282;

GO
