-- SQL Server Connector — connector metadata seed (generated by `mj sync push`)
-- Seeds the core __mj integration catalog (Integration / IntegrationObject / IntegrationObjectField + Actions).
-- Do not hand-edit; regenerate from ../metadata via `mj sync push` + `scripts/wrap-migration.mjs`.

-- SQL Logging Session
-- Session ID: 7653c299-1542-4ff4-aa24-6b805c43d3f4
-- Started: 2026-07-10T00:53:14.701Z
-- Description: MetadataSync push operation
-- Generated by MemberJunction

-- Save MJ: Integrations (core SP call only)
DECLARE @Name_6b8c40cf NVARCHAR(100),
@Description_6b8c40cf NVARCHAR(255),
@NavigationBaseURL_6b8c40cf NVARCHAR(500),
@ClassName_6b8c40cf NVARCHAR(100),
@ImportPath_6b8c40cf NVARCHAR(100),
@BatchMaxRequestCount_6b8c40cf INT,
@BatchRequestWaitTime_6b8c40cf INT,
@ID_6b8c40cf UNIQUEIDENTIFIER,
@CredentialTypeID_6b8c40cf UNIQUEIDENTIFIER,
@Icon_6b8c40cf NVARCHAR(MAX),
@Configuration_6b8c40cf NVARCHAR(MAX)
SET
  @Name_6b8c40cf = N'SQL Server'
SET
  @Description_6b8c40cf = N'Ingest data from an external Microsoft SQL Server (incl. Azure SQL) via a shared MJ: External Data Sources connection. Schema is discovered at connection time; the connector delegates connectivity to the EDS ''SQLServerExternalDriver'' driver.'
SET
  @ClassName_6b8c40cf = N'SQLServerConnector'
SET
  @ImportPath_6b8c40cf = N'@memberjunction/connector-sqlserver'
SET
  @BatchMaxRequestCount_6b8c40cf = -1
SET
  @BatchRequestWaitTime_6b8c40cf = -1
SET
  @ID_6b8c40cf = '770845f3-1a15-495e-b7df-c3348ce38252'
SET
  @Icon_6b8c40cf = N'fa-solid fa-database'
SET
  @Configuration_6b8c40cf = N'{
  "connectionModel": "external-data-source",
  "note": "Bind this connection to a shared ''MJ: External Data Sources'' row by setting Configuration.externalDataSourceID on the CompanyIntegration. Host + credentials live on that EDS row (credentials via CredentialEngine); objects/fields are discovered at connection time. Requires @memberjunction/external-data-sources + @memberjunction/external-data-source-sqlserver >= 5.46.0."
}' EXEC [__mj].spCreateIntegration @Name = @Name_6b8c40cf,
  @Description = @Description_6b8c40cf,
  @NavigationBaseURL = @NavigationBaseURL_6b8c40cf,
  @NavigationBaseURL_Clear = 1,
  @ClassName = @ClassName_6b8c40cf,
  @ImportPath = @ImportPath_6b8c40cf,
  @BatchMaxRequestCount = @BatchMaxRequestCount_6b8c40cf,
  @BatchRequestWaitTime = @BatchRequestWaitTime_6b8c40cf,
  @ID = @ID_6b8c40cf,
  @CredentialTypeID = @CredentialTypeID_6b8c40cf,
  @CredentialTypeID_Clear = 1,
  @Icon = @Icon_6b8c40cf,
  @Configuration = @Configuration_6b8c40cf;

GO


-- End of SQL Logging Session
-- Session ID: 7653c299-1542-4ff4-aa24-6b805c43d3f4
-- Completed: 2026-07-10T00:53:14.968Z
-- Duration: 267ms
-- Total Statements: 1
