-- Stripe Connector — connector metadata seed (generated by `mj sync push`)
-- Seeds the core __mj integration catalog (Integration / IntegrationObject / IntegrationObjectField + Actions).
-- Do not hand-edit; regenerate from ../metadata via `mj sync push` + `scripts/wrap-migration.mjs`.

-- SQL Logging Session
-- Session ID: 63c65528-2f0f-4301-a5d5-75954f4f3c91
-- Started: 2026-07-07T15:47:41.252Z
-- Description: MetadataSync push operation
-- Generated by MemberJunction

-- Save MJ: Integration Objects (core SP call only)
DECLARE @IntegrationID_8e05fc22 UNIQUEIDENTIFIER,
@Name_8e05fc22 NVARCHAR(255),
@DisplayName_8e05fc22 NVARCHAR(255),
@Description_8e05fc22 NVARCHAR(MAX),
@Category_8e05fc22 NVARCHAR(100),
@APIPath_8e05fc22 NVARCHAR(500),
@ResponseDataKey_8e05fc22 NVARCHAR(255),
@DefaultPageSize_8e05fc22 INT,
@SupportsPagination_8e05fc22 BIT,
@PaginationType_8e05fc22 NVARCHAR(20),
@SupportsIncrementalSync_8e05fc22 BIT,
@SupportsWrite_8e05fc22 BIT,
@DefaultQueryParams_8e05fc22 NVARCHAR(MAX),
@Configuration_8e05fc22 NVARCHAR(MAX),
@Sequence_8e05fc22 INT,
@Status_8e05fc22 NVARCHAR(25),
@WriteAPIPath_8e05fc22 NVARCHAR(500),
@WriteMethod_8e05fc22 NVARCHAR(10),
@DeleteMethod_8e05fc22 NVARCHAR(10),
@IsCustom_8e05fc22 BIT,
@CreateAPIPath_8e05fc22 NVARCHAR(MAX),
@CreateMethod_8e05fc22 NVARCHAR(20),
@CreateBodyShape_8e05fc22 NVARCHAR(50),
@CreateBodyKey_8e05fc22 NVARCHAR(100),
@CreateIDLocation_8e05fc22 NVARCHAR(20),
@UpdateAPIPath_8e05fc22 NVARCHAR(MAX),
@UpdateMethod_8e05fc22 NVARCHAR(20),
@UpdateBodyShape_8e05fc22 NVARCHAR(50),
@UpdateBodyKey_8e05fc22 NVARCHAR(100),
@UpdateIDLocation_8e05fc22 NVARCHAR(20),
@DeleteAPIPath_8e05fc22 NVARCHAR(MAX),
@DeleteIDLocation_8e05fc22 NVARCHAR(20),
@IncrementalWatermarkField_8e05fc22 NVARCHAR(255),
@MetadataSource_8e05fc22 NVARCHAR(20),
@SupportsCreate_8e05fc22 BIT,
@SupportsUpdate_8e05fc22 BIT,
@SupportsDelete_8e05fc22 BIT,
@SyncStrategy_8e05fc22 NVARCHAR(50),
@ContentHashApplicable_8e05fc22 BIT,
@StableOrderingKey_8e05fc22 NVARCHAR(255),
@ID_8e05fc22 UNIQUEIDENTIFIER
SET
  @IntegrationID_8e05fc22 = 'F999493B-B4AB-427A-8D20-4A4848CA2EC8'
SET
  @Name_8e05fc22 = N'balance'
SET
  @DisplayName_8e05fc22 = N'Balance'
SET
  @Description_8e05fc22 = N'This is an object representing your Stripe balance. You can retrieve it to see the balance currently on your Stripe account. The top-level `available` and `pending` comprise your "payments balance." Related guide: [Balances and settlement time](ht...'
SET
  @Category_8e05fc22 = N'Core Payments'
SET
  @APIPath_8e05fc22 = N'/v1/balance'
SET
  @DefaultPageSize_8e05fc22 = 10
SET
  @SupportsPagination_8e05fc22 = 0
SET
  @PaginationType_8e05fc22 = N'None'
SET
  @SupportsIncrementalSync_8e05fc22 = 0
SET
  @SupportsWrite_8e05fc22 = 0
SET
  @Configuration_8e05fc22 = N'{
  "listPath": null,
  "getOnePath": "/v1/balance",
  "createPath": null,
  "updatePath": null,
  "deletePath": null,
  "objectDiscriminator": "balance",
  "writeEncoding": null,
  "pagination": null,
  "incrementalWatermark": null
}'
SET
  @Sequence_8e05fc22 = 0
SET
  @Status_8e05fc22 = N'Active'
SET
  @WriteMethod_8e05fc22 = N'POST'
SET
  @DeleteMethod_8e05fc22 = N'DELETE'
SET
  @IsCustom_8e05fc22 = 0
SET
  @MetadataSource_8e05fc22 = N'Declared'
SET
  @SupportsCreate_8e05fc22 = 0
SET
  @SupportsUpdate_8e05fc22 = 0
SET
  @SupportsDelete_8e05fc22 = 0
SET
  @ContentHashApplicable_8e05fc22 = 1
SET
  @ID_8e05fc22 = '451EEF5F-D3BC-4FF2-A7DA-932DD23BD711' EXEC [__mj].spUpdateIntegrationObject @IntegrationID = @IntegrationID_8e05fc22,
  @Name = @Name_8e05fc22,
  @DisplayName = @DisplayName_8e05fc22,
  @Description = @Description_8e05fc22,
  @Category = @Category_8e05fc22,
  @APIPath = @APIPath_8e05fc22,
  @ResponseDataKey = @ResponseDataKey_8e05fc22,
  @ResponseDataKey_Clear = 1,
  @DefaultPageSize = @DefaultPageSize_8e05fc22,
  @SupportsPagination = @SupportsPagination_8e05fc22,
  @PaginationType = @PaginationType_8e05fc22,
  @SupportsIncrementalSync = @SupportsIncrementalSync_8e05fc22,
  @SupportsWrite = @SupportsWrite_8e05fc22,
  @DefaultQueryParams = @DefaultQueryParams_8e05fc22,
  @DefaultQueryParams_Clear = 1,
  @Configuration = @Configuration_8e05fc22,
  @Sequence = @Sequence_8e05fc22,
  @Status = @Status_8e05fc22,
  @WriteAPIPath = @WriteAPIPath_8e05fc22,
  @WriteAPIPath_Clear = 1,
  @WriteMethod = @WriteMethod_8e05fc22,
  @DeleteMethod = @DeleteMethod_8e05fc22,
  @IsCustom = @IsCustom_8e05fc22,
  @CreateAPIPath = @CreateAPIPath_8e05fc22,
  @CreateAPIPath_Clear = 1,
  @CreateMethod = @CreateMethod_8e05fc22,
  @CreateMethod_Clear = 1,
  @CreateBodyShape = @CreateBodyShape_8e05fc22,
  @CreateBodyShape_Clear = 1,
  @CreateBodyKey = @CreateBodyKey_8e05fc22,
  @CreateBodyKey_Clear = 1,
  @CreateIDLocation = @CreateIDLocation_8e05fc22,
  @CreateIDLocation_Clear = 1,
  @UpdateAPIPath = @UpdateAPIPath_8e05fc22,
  @UpdateAPIPath_Clear = 1,
  @UpdateMethod = @UpdateMethod_8e05fc22,
  @UpdateMethod_Clear = 1,
  @UpdateBodyShape = @UpdateBodyShape_8e05fc22,
  @UpdateBodyShape_Clear = 1,
  @UpdateBodyKey = @UpdateBodyKey_8e05fc22,
  @UpdateBodyKey_Clear = 1,
  @UpdateIDLocation = @UpdateIDLocation_8e05fc22,
  @UpdateIDLocation_Clear = 1,
  @DeleteAPIPath = @DeleteAPIPath_8e05fc22,
  @DeleteAPIPath_Clear = 1,
  @DeleteIDLocation = @DeleteIDLocation_8e05fc22,
  @DeleteIDLocation_Clear = 1,
  @IncrementalWatermarkField = @IncrementalWatermarkField_8e05fc22,
  @IncrementalWatermarkField_Clear = 1,
  @MetadataSource = @MetadataSource_8e05fc22,
  @SupportsCreate = @SupportsCreate_8e05fc22,
  @SupportsUpdate = @SupportsUpdate_8e05fc22,
  @SupportsDelete = @SupportsDelete_8e05fc22,
  @SyncStrategy = @SyncStrategy_8e05fc22,
  @SyncStrategy_Clear = 1,
  @ContentHashApplicable = @ContentHashApplicable_8e05fc22,
  @StableOrderingKey = @StableOrderingKey_8e05fc22,
  @StableOrderingKey_Clear = 1,
  @ID = @ID_8e05fc22;

GO

-- Save MJ: Integration Objects (core SP call only)
DECLARE @IntegrationID_1c56d68d UNIQUEIDENTIFIER,
@Name_1c56d68d NVARCHAR(255),
@DisplayName_1c56d68d NVARCHAR(255),
@Description_1c56d68d NVARCHAR(MAX),
@Category_1c56d68d NVARCHAR(100),
@APIPath_1c56d68d NVARCHAR(500),
@ResponseDataKey_1c56d68d NVARCHAR(255),
@DefaultPageSize_1c56d68d INT,
@SupportsPagination_1c56d68d BIT,
@PaginationType_1c56d68d NVARCHAR(20),
@SupportsIncrementalSync_1c56d68d BIT,
@SupportsWrite_1c56d68d BIT,
@DefaultQueryParams_1c56d68d NVARCHAR(MAX),
@Configuration_1c56d68d NVARCHAR(MAX),
@Sequence_1c56d68d INT,
@Status_1c56d68d NVARCHAR(25),
@WriteAPIPath_1c56d68d NVARCHAR(500),
@WriteMethod_1c56d68d NVARCHAR(10),
@DeleteMethod_1c56d68d NVARCHAR(10),
@IsCustom_1c56d68d BIT,
@CreateAPIPath_1c56d68d NVARCHAR(MAX),
@CreateMethod_1c56d68d NVARCHAR(20),
@CreateBodyShape_1c56d68d NVARCHAR(50),
@CreateBodyKey_1c56d68d NVARCHAR(100),
@CreateIDLocation_1c56d68d NVARCHAR(20),
@UpdateAPIPath_1c56d68d NVARCHAR(MAX),
@UpdateMethod_1c56d68d NVARCHAR(20),
@UpdateBodyShape_1c56d68d NVARCHAR(50),
@UpdateBodyKey_1c56d68d NVARCHAR(100),
@UpdateIDLocation_1c56d68d NVARCHAR(20),
@DeleteAPIPath_1c56d68d NVARCHAR(MAX),
@DeleteIDLocation_1c56d68d NVARCHAR(20),
@IncrementalWatermarkField_1c56d68d NVARCHAR(255),
@MetadataSource_1c56d68d NVARCHAR(20),
@SupportsCreate_1c56d68d BIT,
@SupportsUpdate_1c56d68d BIT,
@SupportsDelete_1c56d68d BIT,
@SyncStrategy_1c56d68d NVARCHAR(50),
@ContentHashApplicable_1c56d68d BIT,
@StableOrderingKey_1c56d68d NVARCHAR(255),
@ID_1c56d68d UNIQUEIDENTIFIER
SET
  @IntegrationID_1c56d68d = 'F999493B-B4AB-427A-8D20-4A4848CA2EC8'
SET
  @Name_1c56d68d = N'balance_settings'
SET
  @DisplayName_1c56d68d = N'Balance Settings'
SET
  @Description_1c56d68d = N'Options for customizing account balances and payout settings for a Stripe platform’s connected accounts.'
SET
  @Category_1c56d68d = N'Core Payments'
SET
  @APIPath_1c56d68d = N'/v1/balance_settings'
SET
  @DefaultPageSize_1c56d68d = 10
SET
  @SupportsPagination_1c56d68d = 0
SET
  @PaginationType_1c56d68d = N'None'
SET
  @SupportsIncrementalSync_1c56d68d = 0
SET
  @SupportsWrite_1c56d68d = 1
SET
  @Configuration_1c56d68d = N'{
  "listPath": null,
  "getOnePath": "/v1/balance_settings",
  "createPath": "/v1/balance_settings",
  "updatePath": null,
  "deletePath": null,
  "objectDiscriminator": "balance_settings",
  "writeEncoding": "application/x-www-form-urlencoded (bracket notation for nested fields)",
  "pagination": null,
  "incrementalWatermark": null
}'
SET
  @Sequence_1c56d68d = 0
SET
  @Status_1c56d68d = N'Active'
SET
  @WriteMethod_1c56d68d = N'POST'
SET
  @DeleteMethod_1c56d68d = N'DELETE'
SET
  @IsCustom_1c56d68d = 0
SET
  @CreateAPIPath_1c56d68d = N'/v1/balance_settings'
SET
  @CreateMethod_1c56d68d = N'POST'
SET
  @CreateBodyShape_1c56d68d = N'flat'
SET
  @CreateIDLocation_1c56d68d = N'body'
SET
  @MetadataSource_1c56d68d = N'Declared'
SET
  @SupportsCreate_1c56d68d = 0
SET
  @SupportsUpdate_1c56d68d = 0
SET
  @SupportsDelete_1c56d68d = 0
SET
  @ContentHashApplicable_1c56d68d = 1
SET
  @ID_1c56d68d = '9FF086D5-A77D-46A6-B14F-A961C21007F5' EXEC [__mj].spUpdateIntegrationObject @IntegrationID = @IntegrationID_1c56d68d,
  @Name = @Name_1c56d68d,
  @DisplayName = @DisplayName_1c56d68d,
  @Description = @Description_1c56d68d,
  @Category = @Category_1c56d68d,
  @APIPath = @APIPath_1c56d68d,
  @ResponseDataKey = @ResponseDataKey_1c56d68d,
  @ResponseDataKey_Clear = 1,
  @DefaultPageSize = @DefaultPageSize_1c56d68d,
  @SupportsPagination = @SupportsPagination_1c56d68d,
  @PaginationType = @PaginationType_1c56d68d,
  @SupportsIncrementalSync = @SupportsIncrementalSync_1c56d68d,
  @SupportsWrite = @SupportsWrite_1c56d68d,
  @DefaultQueryParams = @DefaultQueryParams_1c56d68d,
  @DefaultQueryParams_Clear = 1,
  @Configuration = @Configuration_1c56d68d,
  @Sequence = @Sequence_1c56d68d,
  @Status = @Status_1c56d68d,
  @WriteAPIPath = @WriteAPIPath_1c56d68d,
  @WriteAPIPath_Clear = 1,
  @WriteMethod = @WriteMethod_1c56d68d,
  @DeleteMethod = @DeleteMethod_1c56d68d,
  @IsCustom = @IsCustom_1c56d68d,
  @CreateAPIPath = @CreateAPIPath_1c56d68d,
  @CreateMethod = @CreateMethod_1c56d68d,
  @CreateBodyShape = @CreateBodyShape_1c56d68d,
  @CreateBodyKey = @CreateBodyKey_1c56d68d,
  @CreateBodyKey_Clear = 1,
  @CreateIDLocation = @CreateIDLocation_1c56d68d,
  @UpdateAPIPath = @UpdateAPIPath_1c56d68d,
  @UpdateAPIPath_Clear = 1,
  @UpdateMethod = @UpdateMethod_1c56d68d,
  @UpdateMethod_Clear = 1,
  @UpdateBodyShape = @UpdateBodyShape_1c56d68d,
  @UpdateBodyShape_Clear = 1,
  @UpdateBodyKey = @UpdateBodyKey_1c56d68d,
  @UpdateBodyKey_Clear = 1,
  @UpdateIDLocation = @UpdateIDLocation_1c56d68d,
  @UpdateIDLocation_Clear = 1,
  @DeleteAPIPath = @DeleteAPIPath_1c56d68d,
  @DeleteAPIPath_Clear = 1,
  @DeleteIDLocation = @DeleteIDLocation_1c56d68d,
  @DeleteIDLocation_Clear = 1,
  @IncrementalWatermarkField = @IncrementalWatermarkField_1c56d68d,
  @IncrementalWatermarkField_Clear = 1,
  @MetadataSource = @MetadataSource_1c56d68d,
  @SupportsCreate = @SupportsCreate_1c56d68d,
  @SupportsUpdate = @SupportsUpdate_1c56d68d,
  @SupportsDelete = @SupportsDelete_1c56d68d,
  @SyncStrategy = @SyncStrategy_1c56d68d,
  @SyncStrategy_Clear = 1,
  @ContentHashApplicable = @ContentHashApplicable_1c56d68d,
  @StableOrderingKey = @StableOrderingKey_1c56d68d,
  @StableOrderingKey_Clear = 1,
  @ID = @ID_1c56d68d;

GO

-- Save MJ: Integration Objects (core SP call only)
DECLARE @IntegrationID_dba1df05 UNIQUEIDENTIFIER,
@Name_dba1df05 NVARCHAR(255),
@DisplayName_dba1df05 NVARCHAR(255),
@Description_dba1df05 NVARCHAR(MAX),
@Category_dba1df05 NVARCHAR(100),
@APIPath_dba1df05 NVARCHAR(500),
@ResponseDataKey_dba1df05 NVARCHAR(255),
@DefaultPageSize_dba1df05 INT,
@SupportsPagination_dba1df05 BIT,
@PaginationType_dba1df05 NVARCHAR(20),
@SupportsIncrementalSync_dba1df05 BIT,
@SupportsWrite_dba1df05 BIT,
@DefaultQueryParams_dba1df05 NVARCHAR(MAX),
@Configuration_dba1df05 NVARCHAR(MAX),
@Sequence_dba1df05 INT,
@Status_dba1df05 NVARCHAR(25),
@WriteAPIPath_dba1df05 NVARCHAR(500),
@WriteMethod_dba1df05 NVARCHAR(10),
@DeleteMethod_dba1df05 NVARCHAR(10),
@IsCustom_dba1df05 BIT,
@CreateAPIPath_dba1df05 NVARCHAR(MAX),
@CreateMethod_dba1df05 NVARCHAR(20),
@CreateBodyShape_dba1df05 NVARCHAR(50),
@CreateBodyKey_dba1df05 NVARCHAR(100),
@CreateIDLocation_dba1df05 NVARCHAR(20),
@UpdateAPIPath_dba1df05 NVARCHAR(MAX),
@UpdateMethod_dba1df05 NVARCHAR(20),
@UpdateBodyShape_dba1df05 NVARCHAR(50),
@UpdateBodyKey_dba1df05 NVARCHAR(100),
@UpdateIDLocation_dba1df05 NVARCHAR(20),
@DeleteAPIPath_dba1df05 NVARCHAR(MAX),
@DeleteIDLocation_dba1df05 NVARCHAR(20),
@IncrementalWatermarkField_dba1df05 NVARCHAR(255),
@MetadataSource_dba1df05 NVARCHAR(20),
@SupportsCreate_dba1df05 BIT,
@SupportsUpdate_dba1df05 BIT,
@SupportsDelete_dba1df05 BIT,
@SyncStrategy_dba1df05 NVARCHAR(50),
@ContentHashApplicable_dba1df05 BIT,
@StableOrderingKey_dba1df05 NVARCHAR(255),
@ID_dba1df05 UNIQUEIDENTIFIER
SET
  @IntegrationID_dba1df05 = 'F999493B-B4AB-427A-8D20-4A4848CA2EC8'
SET
  @Name_dba1df05 = N'cash_balance'
SET
  @DisplayName_dba1df05 = N'Cash Balance'
SET
  @Description_dba1df05 = N'A customer''s `Cash balance` represents real funds. Customers can add funds to their cash balance by sending a bank transfer. These funds can be used for payment and can eventually be paid out to your bank account.'
SET
  @Category_dba1df05 = N'Core Payments'
SET
  @APIPath_dba1df05 = N'/v1/customers/{customer}/cash_balance'
SET
  @DefaultPageSize_dba1df05 = 10
SET
  @SupportsPagination_dba1df05 = 0
SET
  @PaginationType_dba1df05 = N'None'
SET
  @SupportsIncrementalSync_dba1df05 = 0
SET
  @SupportsWrite_dba1df05 = 1
SET
  @Configuration_dba1df05 = N'{
  "listPath": null,
  "getOnePath": "/v1/customers/{customer}/cash_balance",
  "createPath": "/v1/customers/{customer}/cash_balance",
  "updatePath": null,
  "deletePath": null,
  "objectDiscriminator": "cash_balance",
  "writeEncoding": "application/x-www-form-urlencoded (bracket notation for nested fields)",
  "pagination": null,
  "incrementalWatermark": null,
  "accessPath": {
    "door": "customers",
    "entryPath": "/v1/customers/{customer}/cash_balance",
    "nestingPath": [
      "cash_balance"
    ],
    "depth": 1
  },
  "parentObjectName": "customer",
  "parentObjectIDFieldName": "customer"
}'
SET
  @Sequence_dba1df05 = 0
SET
  @Status_dba1df05 = N'Active'
SET
  @WriteMethod_dba1df05 = N'POST'
SET
  @DeleteMethod_dba1df05 = N'DELETE'
SET
  @IsCustom_dba1df05 = 0
SET
  @CreateAPIPath_dba1df05 = N'/v1/customers/{customer}/cash_balance'
SET
  @CreateMethod_dba1df05 = N'POST'
SET
  @CreateBodyShape_dba1df05 = N'flat'
SET
  @CreateIDLocation_dba1df05 = N'body'
SET
  @MetadataSource_dba1df05 = N'Declared'
SET
  @SupportsCreate_dba1df05 = 0
SET
  @SupportsUpdate_dba1df05 = 0
SET
  @SupportsDelete_dba1df05 = 0
SET
  @ContentHashApplicable_dba1df05 = 1
SET
  @ID_dba1df05 = '0612D076-1FF2-47BF-B929-02A4BCF20A79' EXEC [__mj].spUpdateIntegrationObject @IntegrationID = @IntegrationID_dba1df05,
  @Name = @Name_dba1df05,
  @DisplayName = @DisplayName_dba1df05,
  @Description = @Description_dba1df05,
  @Category = @Category_dba1df05,
  @APIPath = @APIPath_dba1df05,
  @ResponseDataKey = @ResponseDataKey_dba1df05,
  @ResponseDataKey_Clear = 1,
  @DefaultPageSize = @DefaultPageSize_dba1df05,
  @SupportsPagination = @SupportsPagination_dba1df05,
  @PaginationType = @PaginationType_dba1df05,
  @SupportsIncrementalSync = @SupportsIncrementalSync_dba1df05,
  @SupportsWrite = @SupportsWrite_dba1df05,
  @DefaultQueryParams = @DefaultQueryParams_dba1df05,
  @DefaultQueryParams_Clear = 1,
  @Configuration = @Configuration_dba1df05,
  @Sequence = @Sequence_dba1df05,
  @Status = @Status_dba1df05,
  @WriteAPIPath = @WriteAPIPath_dba1df05,
  @WriteAPIPath_Clear = 1,
  @WriteMethod = @WriteMethod_dba1df05,
  @DeleteMethod = @DeleteMethod_dba1df05,
  @IsCustom = @IsCustom_dba1df05,
  @CreateAPIPath = @CreateAPIPath_dba1df05,
  @CreateMethod = @CreateMethod_dba1df05,
  @CreateBodyShape = @CreateBodyShape_dba1df05,
  @CreateBodyKey = @CreateBodyKey_dba1df05,
  @CreateBodyKey_Clear = 1,
  @CreateIDLocation = @CreateIDLocation_dba1df05,
  @UpdateAPIPath = @UpdateAPIPath_dba1df05,
  @UpdateAPIPath_Clear = 1,
  @UpdateMethod = @UpdateMethod_dba1df05,
  @UpdateMethod_Clear = 1,
  @UpdateBodyShape = @UpdateBodyShape_dba1df05,
  @UpdateBodyShape_Clear = 1,
  @UpdateBodyKey = @UpdateBodyKey_dba1df05,
  @UpdateBodyKey_Clear = 1,
  @UpdateIDLocation = @UpdateIDLocation_dba1df05,
  @UpdateIDLocation_Clear = 1,
  @DeleteAPIPath = @DeleteAPIPath_dba1df05,
  @DeleteAPIPath_Clear = 1,
  @DeleteIDLocation = @DeleteIDLocation_dba1df05,
  @DeleteIDLocation_Clear = 1,
  @IncrementalWatermarkField = @IncrementalWatermarkField_dba1df05,
  @IncrementalWatermarkField_Clear = 1,
  @MetadataSource = @MetadataSource_dba1df05,
  @SupportsCreate = @SupportsCreate_dba1df05,
  @SupportsUpdate = @SupportsUpdate_dba1df05,
  @SupportsDelete = @SupportsDelete_dba1df05,
  @SyncStrategy = @SyncStrategy_dba1df05,
  @SyncStrategy_Clear = 1,
  @ContentHashApplicable = @ContentHashApplicable_dba1df05,
  @StableOrderingKey = @StableOrderingKey_dba1df05,
  @StableOrderingKey_Clear = 1,
  @ID = @ID_dba1df05;

GO

-- Save MJ: Integration Objects (core SP call only)
DECLARE @IntegrationID_00703237 UNIQUEIDENTIFIER,
@Name_00703237 NVARCHAR(255),
@DisplayName_00703237 NVARCHAR(255),
@Description_00703237 NVARCHAR(MAX),
@Category_00703237 NVARCHAR(100),
@APIPath_00703237 NVARCHAR(500),
@ResponseDataKey_00703237 NVARCHAR(255),
@DefaultPageSize_00703237 INT,
@SupportsPagination_00703237 BIT,
@PaginationType_00703237 NVARCHAR(20),
@SupportsIncrementalSync_00703237 BIT,
@SupportsWrite_00703237 BIT,
@DefaultQueryParams_00703237 NVARCHAR(MAX),
@Configuration_00703237 NVARCHAR(MAX),
@Sequence_00703237 INT,
@Status_00703237 NVARCHAR(25),
@WriteAPIPath_00703237 NVARCHAR(500),
@WriteMethod_00703237 NVARCHAR(10),
@DeleteMethod_00703237 NVARCHAR(10),
@IsCustom_00703237 BIT,
@CreateAPIPath_00703237 NVARCHAR(MAX),
@CreateMethod_00703237 NVARCHAR(20),
@CreateBodyShape_00703237 NVARCHAR(50),
@CreateBodyKey_00703237 NVARCHAR(100),
@CreateIDLocation_00703237 NVARCHAR(20),
@UpdateAPIPath_00703237 NVARCHAR(MAX),
@UpdateMethod_00703237 NVARCHAR(20),
@UpdateBodyShape_00703237 NVARCHAR(50),
@UpdateBodyKey_00703237 NVARCHAR(100),
@UpdateIDLocation_00703237 NVARCHAR(20),
@DeleteAPIPath_00703237 NVARCHAR(MAX),
@DeleteIDLocation_00703237 NVARCHAR(20),
@IncrementalWatermarkField_00703237 NVARCHAR(255),
@MetadataSource_00703237 NVARCHAR(20),
@SupportsCreate_00703237 BIT,
@SupportsUpdate_00703237 BIT,
@SupportsDelete_00703237 BIT,
@SyncStrategy_00703237 NVARCHAR(50),
@ContentHashApplicable_00703237 BIT,
@StableOrderingKey_00703237 NVARCHAR(255),
@ID_00703237 UNIQUEIDENTIFIER
SET
  @IntegrationID_00703237 = 'F999493B-B4AB-427A-8D20-4A4848CA2EC8'
SET
  @Name_00703237 = N'mandate'
SET
  @DisplayName_00703237 = N'Mandate'
SET
  @Description_00703237 = N'A Mandate is a record of the permission that your customer gives you to debit their payment method.'
SET
  @Category_00703237 = N'Core Payments'
SET
  @APIPath_00703237 = N'/v1/mandates/{mandate}'
SET
  @DefaultPageSize_00703237 = 10
SET
  @SupportsPagination_00703237 = 0
SET
  @PaginationType_00703237 = N'None'
SET
  @SupportsIncrementalSync_00703237 = 0
SET
  @SupportsWrite_00703237 = 0
SET
  @Configuration_00703237 = N'{
  "listPath": null,
  "getOnePath": "/v1/mandates/{mandate}",
  "createPath": null,
  "updatePath": null,
  "deletePath": null,
  "objectDiscriminator": "mandate",
  "writeEncoding": null,
  "pagination": null,
  "incrementalWatermark": null
}'
SET
  @Sequence_00703237 = 0
SET
  @Status_00703237 = N'Active'
SET
  @WriteMethod_00703237 = N'POST'
SET
  @DeleteMethod_00703237 = N'DELETE'
SET
  @IsCustom_00703237 = 0
SET
  @MetadataSource_00703237 = N'Declared'
SET
  @SupportsCreate_00703237 = 0
SET
  @SupportsUpdate_00703237 = 0
SET
  @SupportsDelete_00703237 = 0
SET
  @ContentHashApplicable_00703237 = 1
SET
  @ID_00703237 = 'BB5F8927-0946-490A-A7ED-58F9875496E6' EXEC [__mj].spUpdateIntegrationObject @IntegrationID = @IntegrationID_00703237,
  @Name = @Name_00703237,
  @DisplayName = @DisplayName_00703237,
  @Description = @Description_00703237,
  @Category = @Category_00703237,
  @APIPath = @APIPath_00703237,
  @ResponseDataKey = @ResponseDataKey_00703237,
  @ResponseDataKey_Clear = 1,
  @DefaultPageSize = @DefaultPageSize_00703237,
  @SupportsPagination = @SupportsPagination_00703237,
  @PaginationType = @PaginationType_00703237,
  @SupportsIncrementalSync = @SupportsIncrementalSync_00703237,
  @SupportsWrite = @SupportsWrite_00703237,
  @DefaultQueryParams = @DefaultQueryParams_00703237,
  @DefaultQueryParams_Clear = 1,
  @Configuration = @Configuration_00703237,
  @Sequence = @Sequence_00703237,
  @Status = @Status_00703237,
  @WriteAPIPath = @WriteAPIPath_00703237,
  @WriteAPIPath_Clear = 1,
  @WriteMethod = @WriteMethod_00703237,
  @DeleteMethod = @DeleteMethod_00703237,
  @IsCustom = @IsCustom_00703237,
  @CreateAPIPath = @CreateAPIPath_00703237,
  @CreateAPIPath_Clear = 1,
  @CreateMethod = @CreateMethod_00703237,
  @CreateMethod_Clear = 1,
  @CreateBodyShape = @CreateBodyShape_00703237,
  @CreateBodyShape_Clear = 1,
  @CreateBodyKey = @CreateBodyKey_00703237,
  @CreateBodyKey_Clear = 1,
  @CreateIDLocation = @CreateIDLocation_00703237,
  @CreateIDLocation_Clear = 1,
  @UpdateAPIPath = @UpdateAPIPath_00703237,
  @UpdateAPIPath_Clear = 1,
  @UpdateMethod = @UpdateMethod_00703237,
  @UpdateMethod_Clear = 1,
  @UpdateBodyShape = @UpdateBodyShape_00703237,
  @UpdateBodyShape_Clear = 1,
  @UpdateBodyKey = @UpdateBodyKey_00703237,
  @UpdateBodyKey_Clear = 1,
  @UpdateIDLocation = @UpdateIDLocation_00703237,
  @UpdateIDLocation_Clear = 1,
  @DeleteAPIPath = @DeleteAPIPath_00703237,
  @DeleteAPIPath_Clear = 1,
  @DeleteIDLocation = @DeleteIDLocation_00703237,
  @DeleteIDLocation_Clear = 1,
  @IncrementalWatermarkField = @IncrementalWatermarkField_00703237,
  @IncrementalWatermarkField_Clear = 1,
  @MetadataSource = @MetadataSource_00703237,
  @SupportsCreate = @SupportsCreate_00703237,
  @SupportsUpdate = @SupportsUpdate_00703237,
  @SupportsDelete = @SupportsDelete_00703237,
  @SyncStrategy = @SyncStrategy_00703237,
  @SyncStrategy_Clear = 1,
  @ContentHashApplicable = @ContentHashApplicable_00703237,
  @StableOrderingKey = @StableOrderingKey_00703237,
  @StableOrderingKey_Clear = 1,
  @ID = @ID_00703237;

GO

-- Save MJ: Integration Objects (core SP call only)
DECLARE @IntegrationID_7a8d8fc7 UNIQUEIDENTIFIER,
@Name_7a8d8fc7 NVARCHAR(255),
@DisplayName_7a8d8fc7 NVARCHAR(255),
@Description_7a8d8fc7 NVARCHAR(MAX),
@Category_7a8d8fc7 NVARCHAR(100),
@APIPath_7a8d8fc7 NVARCHAR(500),
@ResponseDataKey_7a8d8fc7 NVARCHAR(255),
@DefaultPageSize_7a8d8fc7 INT,
@SupportsPagination_7a8d8fc7 BIT,
@PaginationType_7a8d8fc7 NVARCHAR(20),
@SupportsIncrementalSync_7a8d8fc7 BIT,
@SupportsWrite_7a8d8fc7 BIT,
@DefaultQueryParams_7a8d8fc7 NVARCHAR(MAX),
@Configuration_7a8d8fc7 NVARCHAR(MAX),
@Sequence_7a8d8fc7 INT,
@Status_7a8d8fc7 NVARCHAR(25),
@WriteAPIPath_7a8d8fc7 NVARCHAR(500),
@WriteMethod_7a8d8fc7 NVARCHAR(10),
@DeleteMethod_7a8d8fc7 NVARCHAR(10),
@IsCustom_7a8d8fc7 BIT,
@CreateAPIPath_7a8d8fc7 NVARCHAR(MAX),
@CreateMethod_7a8d8fc7 NVARCHAR(20),
@CreateBodyShape_7a8d8fc7 NVARCHAR(50),
@CreateBodyKey_7a8d8fc7 NVARCHAR(100),
@CreateIDLocation_7a8d8fc7 NVARCHAR(20),
@UpdateAPIPath_7a8d8fc7 NVARCHAR(MAX),
@UpdateMethod_7a8d8fc7 NVARCHAR(20),
@UpdateBodyShape_7a8d8fc7 NVARCHAR(50),
@UpdateBodyKey_7a8d8fc7 NVARCHAR(100),
@UpdateIDLocation_7a8d8fc7 NVARCHAR(20),
@DeleteAPIPath_7a8d8fc7 NVARCHAR(MAX),
@DeleteIDLocation_7a8d8fc7 NVARCHAR(20),
@IncrementalWatermarkField_7a8d8fc7 NVARCHAR(255),
@MetadataSource_7a8d8fc7 NVARCHAR(20),
@SupportsCreate_7a8d8fc7 BIT,
@SupportsUpdate_7a8d8fc7 BIT,
@SupportsDelete_7a8d8fc7 BIT,
@SyncStrategy_7a8d8fc7 NVARCHAR(50),
@ContentHashApplicable_7a8d8fc7 BIT,
@StableOrderingKey_7a8d8fc7 NVARCHAR(255),
@ID_7a8d8fc7 UNIQUEIDENTIFIER
SET
  @IntegrationID_7a8d8fc7 = 'F999493B-B4AB-427A-8D20-4A4848CA2EC8'
SET
  @Name_7a8d8fc7 = N'payment_record'
SET
  @DisplayName_7a8d8fc7 = N'Payment Record'
SET
  @Description_7a8d8fc7 = N'A Payment Record is a resource that allows you to represent payments that occur on- or off-Stripe. For example, you can create a Payment Record to model a payment made on a different payment processor, in order to mark an Invoice as paid and a Sub...'
SET
  @Category_7a8d8fc7 = N'Core Payments'
SET
  @APIPath_7a8d8fc7 = N'/v1/payment_records/{id}'
SET
  @DefaultPageSize_7a8d8fc7 = 10
SET
  @SupportsPagination_7a8d8fc7 = 0
SET
  @PaginationType_7a8d8fc7 = N'None'
SET
  @SupportsIncrementalSync_7a8d8fc7 = 0
SET
  @SupportsWrite_7a8d8fc7 = 1
SET
  @Configuration_7a8d8fc7 = N'{
  "listPath": null,
  "getOnePath": "/v1/payment_records/{id}",
  "createPath": "/v1/payment_records/report_payment",
  "updatePath": null,
  "deletePath": null,
  "objectDiscriminator": "payment_record",
  "writeEncoding": "application/x-www-form-urlencoded (bracket notation for nested fields)",
  "pagination": null,
  "incrementalWatermark": null
}'
SET
  @Sequence_7a8d8fc7 = 0
SET
  @Status_7a8d8fc7 = N'Active'
SET
  @WriteMethod_7a8d8fc7 = N'POST'
SET
  @DeleteMethod_7a8d8fc7 = N'DELETE'
SET
  @IsCustom_7a8d8fc7 = 0
SET
  @CreateAPIPath_7a8d8fc7 = N'/v1/payment_records/report_payment'
SET
  @CreateMethod_7a8d8fc7 = N'POST'
SET
  @CreateBodyShape_7a8d8fc7 = N'flat'
SET
  @CreateIDLocation_7a8d8fc7 = N'body'
SET
  @MetadataSource_7a8d8fc7 = N'Declared'
SET
  @SupportsCreate_7a8d8fc7 = 0
SET
  @SupportsUpdate_7a8d8fc7 = 0
SET
  @SupportsDelete_7a8d8fc7 = 0
SET
  @ContentHashApplicable_7a8d8fc7 = 1
SET
  @ID_7a8d8fc7 = 'B1739AAC-3C1E-4D2D-B645-4F5C55A10251' EXEC [__mj].spUpdateIntegrationObject @IntegrationID = @IntegrationID_7a8d8fc7,
  @Name = @Name_7a8d8fc7,
  @DisplayName = @DisplayName_7a8d8fc7,
  @Description = @Description_7a8d8fc7,
  @Category = @Category_7a8d8fc7,
  @APIPath = @APIPath_7a8d8fc7,
  @ResponseDataKey = @ResponseDataKey_7a8d8fc7,
  @ResponseDataKey_Clear = 1,
  @DefaultPageSize = @DefaultPageSize_7a8d8fc7,
  @SupportsPagination = @SupportsPagination_7a8d8fc7,
  @PaginationType = @PaginationType_7a8d8fc7,
  @SupportsIncrementalSync = @SupportsIncrementalSync_7a8d8fc7,
  @SupportsWrite = @SupportsWrite_7a8d8fc7,
  @DefaultQueryParams = @DefaultQueryParams_7a8d8fc7,
  @DefaultQueryParams_Clear = 1,
  @Configuration = @Configuration_7a8d8fc7,
  @Sequence = @Sequence_7a8d8fc7,
  @Status = @Status_7a8d8fc7,
  @WriteAPIPath = @WriteAPIPath_7a8d8fc7,
  @WriteAPIPath_Clear = 1,
  @WriteMethod = @WriteMethod_7a8d8fc7,
  @DeleteMethod = @DeleteMethod_7a8d8fc7,
  @IsCustom = @IsCustom_7a8d8fc7,
  @CreateAPIPath = @CreateAPIPath_7a8d8fc7,
  @CreateMethod = @CreateMethod_7a8d8fc7,
  @CreateBodyShape = @CreateBodyShape_7a8d8fc7,
  @CreateBodyKey = @CreateBodyKey_7a8d8fc7,
  @CreateBodyKey_Clear = 1,
  @CreateIDLocation = @CreateIDLocation_7a8d8fc7,
  @UpdateAPIPath = @UpdateAPIPath_7a8d8fc7,
  @UpdateAPIPath_Clear = 1,
  @UpdateMethod = @UpdateMethod_7a8d8fc7,
  @UpdateMethod_Clear = 1,
  @UpdateBodyShape = @UpdateBodyShape_7a8d8fc7,
  @UpdateBodyShape_Clear = 1,
  @UpdateBodyKey = @UpdateBodyKey_7a8d8fc7,
  @UpdateBodyKey_Clear = 1,
  @UpdateIDLocation = @UpdateIDLocation_7a8d8fc7,
  @UpdateIDLocation_Clear = 1,
  @DeleteAPIPath = @DeleteAPIPath_7a8d8fc7,
  @DeleteAPIPath_Clear = 1,
  @DeleteIDLocation = @DeleteIDLocation_7a8d8fc7,
  @DeleteIDLocation_Clear = 1,
  @IncrementalWatermarkField = @IncrementalWatermarkField_7a8d8fc7,
  @IncrementalWatermarkField_Clear = 1,
  @MetadataSource = @MetadataSource_7a8d8fc7,
  @SupportsCreate = @SupportsCreate_7a8d8fc7,
  @SupportsUpdate = @SupportsUpdate_7a8d8fc7,
  @SupportsDelete = @SupportsDelete_7a8d8fc7,
  @SyncStrategy = @SyncStrategy_7a8d8fc7,
  @SyncStrategy_Clear = 1,
  @ContentHashApplicable = @ContentHashApplicable_7a8d8fc7,
  @StableOrderingKey = @StableOrderingKey_7a8d8fc7,
  @StableOrderingKey_Clear = 1,
  @ID = @ID_7a8d8fc7;

GO

-- Save MJ: Integration Objects (core SP call only)
DECLARE @IntegrationID_42d7c832 UNIQUEIDENTIFIER,
@Name_42d7c832 NVARCHAR(255),
@DisplayName_42d7c832 NVARCHAR(255),
@Description_42d7c832 NVARCHAR(MAX),
@Category_42d7c832 NVARCHAR(100),
@APIPath_42d7c832 NVARCHAR(500),
@ResponseDataKey_42d7c832 NVARCHAR(255),
@DefaultPageSize_42d7c832 INT,
@SupportsPagination_42d7c832 BIT,
@PaginationType_42d7c832 NVARCHAR(20),
@SupportsIncrementalSync_42d7c832 BIT,
@SupportsWrite_42d7c832 BIT,
@DefaultQueryParams_42d7c832 NVARCHAR(MAX),
@Configuration_42d7c832 NVARCHAR(MAX),
@Sequence_42d7c832 INT,
@Status_42d7c832 NVARCHAR(25),
@WriteAPIPath_42d7c832 NVARCHAR(500),
@WriteMethod_42d7c832 NVARCHAR(10),
@DeleteMethod_42d7c832 NVARCHAR(10),
@IsCustom_42d7c832 BIT,
@CreateAPIPath_42d7c832 NVARCHAR(MAX),
@CreateMethod_42d7c832 NVARCHAR(20),
@CreateBodyShape_42d7c832 NVARCHAR(50),
@CreateBodyKey_42d7c832 NVARCHAR(100),
@CreateIDLocation_42d7c832 NVARCHAR(20),
@UpdateAPIPath_42d7c832 NVARCHAR(MAX),
@UpdateMethod_42d7c832 NVARCHAR(20),
@UpdateBodyShape_42d7c832 NVARCHAR(50),
@UpdateBodyKey_42d7c832 NVARCHAR(100),
@UpdateIDLocation_42d7c832 NVARCHAR(20),
@DeleteAPIPath_42d7c832 NVARCHAR(MAX),
@DeleteIDLocation_42d7c832 NVARCHAR(20),
@IncrementalWatermarkField_42d7c832 NVARCHAR(255),
@MetadataSource_42d7c832 NVARCHAR(20),
@SupportsCreate_42d7c832 BIT,
@SupportsUpdate_42d7c832 BIT,
@SupportsDelete_42d7c832 BIT,
@SyncStrategy_42d7c832 NVARCHAR(50),
@ContentHashApplicable_42d7c832 BIT,
@StableOrderingKey_42d7c832 NVARCHAR(255),
@ID_42d7c832 UNIQUEIDENTIFIER
SET
  @IntegrationID_42d7c832 = 'F999493B-B4AB-427A-8D20-4A4848CA2EC8'
SET
  @Name_42d7c832 = N'source'
SET
  @DisplayName_42d7c832 = N'Source'
SET
  @Description_42d7c832 = N'`Source` objects allow you to accept a variety of payment methods. They represent a customer''s payment instrument, and can be used with the Stripe API just like a `Card` object: once chargeable, they can be charged, or can be attached to customers...'
SET
  @Category_42d7c832 = N'Core Payments'
SET
  @APIPath_42d7c832 = N'/v1/sources/{source}'
SET
  @DefaultPageSize_42d7c832 = 10
SET
  @SupportsPagination_42d7c832 = 0
SET
  @PaginationType_42d7c832 = N'None'
SET
  @SupportsIncrementalSync_42d7c832 = 0
SET
  @SupportsWrite_42d7c832 = 1
SET
  @Configuration_42d7c832 = N'{
  "listPath": null,
  "getOnePath": "/v1/sources/{source}",
  "createPath": "/v1/sources",
  "updatePath": "/v1/sources/{source}",
  "deletePath": null,
  "objectDiscriminator": "source",
  "writeEncoding": "application/x-www-form-urlencoded (bracket notation for nested fields)",
  "pagination": null,
  "incrementalWatermark": null
}'
SET
  @Sequence_42d7c832 = 0
SET
  @Status_42d7c832 = N'Active'
SET
  @WriteMethod_42d7c832 = N'POST'
SET
  @DeleteMethod_42d7c832 = N'DELETE'
SET
  @IsCustom_42d7c832 = 0
SET
  @CreateAPIPath_42d7c832 = N'/v1/sources'
SET
  @CreateMethod_42d7c832 = N'POST'
SET
  @CreateBodyShape_42d7c832 = N'flat'
SET
  @CreateIDLocation_42d7c832 = N'body'
SET
  @UpdateAPIPath_42d7c832 = N'/v1/sources/{source}'
SET
  @UpdateMethod_42d7c832 = N'POST'
SET
  @UpdateBodyShape_42d7c832 = N'flat'
SET
  @UpdateIDLocation_42d7c832 = N'path'
SET
  @MetadataSource_42d7c832 = N'Declared'
SET
  @SupportsCreate_42d7c832 = 0
SET
  @SupportsUpdate_42d7c832 = 0
SET
  @SupportsDelete_42d7c832 = 0
SET
  @ContentHashApplicable_42d7c832 = 1
SET
  @ID_42d7c832 = '7F4587B2-248F-4495-9A20-CD27FDE3437C' EXEC [__mj].spUpdateIntegrationObject @IntegrationID = @IntegrationID_42d7c832,
  @Name = @Name_42d7c832,
  @DisplayName = @DisplayName_42d7c832,
  @Description = @Description_42d7c832,
  @Category = @Category_42d7c832,
  @APIPath = @APIPath_42d7c832,
  @ResponseDataKey = @ResponseDataKey_42d7c832,
  @ResponseDataKey_Clear = 1,
  @DefaultPageSize = @DefaultPageSize_42d7c832,
  @SupportsPagination = @SupportsPagination_42d7c832,
  @PaginationType = @PaginationType_42d7c832,
  @SupportsIncrementalSync = @SupportsIncrementalSync_42d7c832,
  @SupportsWrite = @SupportsWrite_42d7c832,
  @DefaultQueryParams = @DefaultQueryParams_42d7c832,
  @DefaultQueryParams_Clear = 1,
  @Configuration = @Configuration_42d7c832,
  @Sequence = @Sequence_42d7c832,
  @Status = @Status_42d7c832,
  @WriteAPIPath = @WriteAPIPath_42d7c832,
  @WriteAPIPath_Clear = 1,
  @WriteMethod = @WriteMethod_42d7c832,
  @DeleteMethod = @DeleteMethod_42d7c832,
  @IsCustom = @IsCustom_42d7c832,
  @CreateAPIPath = @CreateAPIPath_42d7c832,
  @CreateMethod = @CreateMethod_42d7c832,
  @CreateBodyShape = @CreateBodyShape_42d7c832,
  @CreateBodyKey = @CreateBodyKey_42d7c832,
  @CreateBodyKey_Clear = 1,
  @CreateIDLocation = @CreateIDLocation_42d7c832,
  @UpdateAPIPath = @UpdateAPIPath_42d7c832,
  @UpdateMethod = @UpdateMethod_42d7c832,
  @UpdateBodyShape = @UpdateBodyShape_42d7c832,
  @UpdateBodyKey = @UpdateBodyKey_42d7c832,
  @UpdateBodyKey_Clear = 1,
  @UpdateIDLocation = @UpdateIDLocation_42d7c832,
  @DeleteAPIPath = @DeleteAPIPath_42d7c832,
  @DeleteAPIPath_Clear = 1,
  @DeleteIDLocation = @DeleteIDLocation_42d7c832,
  @DeleteIDLocation_Clear = 1,
  @IncrementalWatermarkField = @IncrementalWatermarkField_42d7c832,
  @IncrementalWatermarkField_Clear = 1,
  @MetadataSource = @MetadataSource_42d7c832,
  @SupportsCreate = @SupportsCreate_42d7c832,
  @SupportsUpdate = @SupportsUpdate_42d7c832,
  @SupportsDelete = @SupportsDelete_42d7c832,
  @SyncStrategy = @SyncStrategy_42d7c832,
  @SyncStrategy_Clear = 1,
  @ContentHashApplicable = @ContentHashApplicable_42d7c832,
  @StableOrderingKey = @StableOrderingKey_42d7c832,
  @StableOrderingKey_Clear = 1,
  @ID = @ID_42d7c832;

GO

-- Save MJ: Integration Objects (core SP call only)
DECLARE @IntegrationID_48587bfa UNIQUEIDENTIFIER,
@Name_48587bfa NVARCHAR(255),
@DisplayName_48587bfa NVARCHAR(255),
@Description_48587bfa NVARCHAR(MAX),
@Category_48587bfa NVARCHAR(100),
@APIPath_48587bfa NVARCHAR(500),
@ResponseDataKey_48587bfa NVARCHAR(255),
@DefaultPageSize_48587bfa INT,
@SupportsPagination_48587bfa BIT,
@PaginationType_48587bfa NVARCHAR(20),
@SupportsIncrementalSync_48587bfa BIT,
@SupportsWrite_48587bfa BIT,
@DefaultQueryParams_48587bfa NVARCHAR(MAX),
@Configuration_48587bfa NVARCHAR(MAX),
@Sequence_48587bfa INT,
@Status_48587bfa NVARCHAR(25),
@WriteAPIPath_48587bfa NVARCHAR(500),
@WriteMethod_48587bfa NVARCHAR(10),
@DeleteMethod_48587bfa NVARCHAR(10),
@IsCustom_48587bfa BIT,
@CreateAPIPath_48587bfa NVARCHAR(MAX),
@CreateMethod_48587bfa NVARCHAR(20),
@CreateBodyShape_48587bfa NVARCHAR(50),
@CreateBodyKey_48587bfa NVARCHAR(100),
@CreateIDLocation_48587bfa NVARCHAR(20),
@UpdateAPIPath_48587bfa NVARCHAR(MAX),
@UpdateMethod_48587bfa NVARCHAR(20),
@UpdateBodyShape_48587bfa NVARCHAR(50),
@UpdateBodyKey_48587bfa NVARCHAR(100),
@UpdateIDLocation_48587bfa NVARCHAR(20),
@DeleteAPIPath_48587bfa NVARCHAR(MAX),
@DeleteIDLocation_48587bfa NVARCHAR(20),
@IncrementalWatermarkField_48587bfa NVARCHAR(255),
@MetadataSource_48587bfa NVARCHAR(20),
@SupportsCreate_48587bfa BIT,
@SupportsUpdate_48587bfa BIT,
@SupportsDelete_48587bfa BIT,
@SyncStrategy_48587bfa NVARCHAR(50),
@ContentHashApplicable_48587bfa BIT,
@StableOrderingKey_48587bfa NVARCHAR(255),
@ID_48587bfa UNIQUEIDENTIFIER
SET
  @IntegrationID_48587bfa = 'F999493B-B4AB-427A-8D20-4A4848CA2EC8'
SET
  @Name_48587bfa = N'token'
SET
  @DisplayName_48587bfa = N'Token'
SET
  @Description_48587bfa = N'Tokenization is the process Stripe uses to collect sensitive card or bank account details, or personally identifiable information (PII), directly from your customers in a secure manner. A token representing this information is returned to your ser...'
SET
  @Category_48587bfa = N'Core Payments'
SET
  @APIPath_48587bfa = N'/v1/tokens/{token}'
SET
  @DefaultPageSize_48587bfa = 10
SET
  @SupportsPagination_48587bfa = 0
SET
  @PaginationType_48587bfa = N'None'
SET
  @SupportsIncrementalSync_48587bfa = 0
SET
  @SupportsWrite_48587bfa = 1
SET
  @Configuration_48587bfa = N'{
  "listPath": null,
  "getOnePath": "/v1/tokens/{token}",
  "createPath": "/v1/tokens",
  "updatePath": null,
  "deletePath": null,
  "objectDiscriminator": "token",
  "writeEncoding": "application/x-www-form-urlencoded (bracket notation for nested fields)",
  "pagination": null,
  "incrementalWatermark": null
}'
SET
  @Sequence_48587bfa = 0
SET
  @Status_48587bfa = N'Active'
SET
  @WriteMethod_48587bfa = N'POST'
SET
  @DeleteMethod_48587bfa = N'DELETE'
SET
  @IsCustom_48587bfa = 0
SET
  @CreateAPIPath_48587bfa = N'/v1/tokens'
SET
  @CreateMethod_48587bfa = N'POST'
SET
  @CreateBodyShape_48587bfa = N'flat'
SET
  @CreateIDLocation_48587bfa = N'body'
SET
  @MetadataSource_48587bfa = N'Declared'
SET
  @SupportsCreate_48587bfa = 0
SET
  @SupportsUpdate_48587bfa = 0
SET
  @SupportsDelete_48587bfa = 0
SET
  @ContentHashApplicable_48587bfa = 1
SET
  @ID_48587bfa = '566C6A43-F713-44DD-8E44-5F77FB5C520F' EXEC [__mj].spUpdateIntegrationObject @IntegrationID = @IntegrationID_48587bfa,
  @Name = @Name_48587bfa,
  @DisplayName = @DisplayName_48587bfa,
  @Description = @Description_48587bfa,
  @Category = @Category_48587bfa,
  @APIPath = @APIPath_48587bfa,
  @ResponseDataKey = @ResponseDataKey_48587bfa,
  @ResponseDataKey_Clear = 1,
  @DefaultPageSize = @DefaultPageSize_48587bfa,
  @SupportsPagination = @SupportsPagination_48587bfa,
  @PaginationType = @PaginationType_48587bfa,
  @SupportsIncrementalSync = @SupportsIncrementalSync_48587bfa,
  @SupportsWrite = @SupportsWrite_48587bfa,
  @DefaultQueryParams = @DefaultQueryParams_48587bfa,
  @DefaultQueryParams_Clear = 1,
  @Configuration = @Configuration_48587bfa,
  @Sequence = @Sequence_48587bfa,
  @Status = @Status_48587bfa,
  @WriteAPIPath = @WriteAPIPath_48587bfa,
  @WriteAPIPath_Clear = 1,
  @WriteMethod = @WriteMethod_48587bfa,
  @DeleteMethod = @DeleteMethod_48587bfa,
  @IsCustom = @IsCustom_48587bfa,
  @CreateAPIPath = @CreateAPIPath_48587bfa,
  @CreateMethod = @CreateMethod_48587bfa,
  @CreateBodyShape = @CreateBodyShape_48587bfa,
  @CreateBodyKey = @CreateBodyKey_48587bfa,
  @CreateBodyKey_Clear = 1,
  @CreateIDLocation = @CreateIDLocation_48587bfa,
  @UpdateAPIPath = @UpdateAPIPath_48587bfa,
  @UpdateAPIPath_Clear = 1,
  @UpdateMethod = @UpdateMethod_48587bfa,
  @UpdateMethod_Clear = 1,
  @UpdateBodyShape = @UpdateBodyShape_48587bfa,
  @UpdateBodyShape_Clear = 1,
  @UpdateBodyKey = @UpdateBodyKey_48587bfa,
  @UpdateBodyKey_Clear = 1,
  @UpdateIDLocation = @UpdateIDLocation_48587bfa,
  @UpdateIDLocation_Clear = 1,
  @DeleteAPIPath = @DeleteAPIPath_48587bfa,
  @DeleteAPIPath_Clear = 1,
  @DeleteIDLocation = @DeleteIDLocation_48587bfa,
  @DeleteIDLocation_Clear = 1,
  @IncrementalWatermarkField = @IncrementalWatermarkField_48587bfa,
  @IncrementalWatermarkField_Clear = 1,
  @MetadataSource = @MetadataSource_48587bfa,
  @SupportsCreate = @SupportsCreate_48587bfa,
  @SupportsUpdate = @SupportsUpdate_48587bfa,
  @SupportsDelete = @SupportsDelete_48587bfa,
  @SyncStrategy = @SyncStrategy_48587bfa,
  @SyncStrategy_Clear = 1,
  @ContentHashApplicable = @ContentHashApplicable_48587bfa,
  @StableOrderingKey = @StableOrderingKey_48587bfa,
  @StableOrderingKey_Clear = 1,
  @ID = @ID_48587bfa;

GO

-- Save MJ: Integration Object Fields (core SP call only)
DECLARE @IntegrationObjectID_62bfed3a UNIQUEIDENTIFIER,
@Name_62bfed3a NVARCHAR(255),
@DisplayName_62bfed3a NVARCHAR(255),
@Description_62bfed3a NVARCHAR(MAX),
@Category_62bfed3a NVARCHAR(100),
@Type_62bfed3a NVARCHAR(100),
@Length_62bfed3a INT,
@Precision_62bfed3a INT,
@Scale_62bfed3a INT,
@AllowsNull_62bfed3a BIT,
@DefaultValue_62bfed3a NVARCHAR(255),
@IsPrimaryKey_62bfed3a BIT,
@IsUniqueKey_62bfed3a BIT,
@IsReadOnly_62bfed3a BIT,
@IsRequired_62bfed3a BIT,
@RelatedIntegrationObjectID_62bfed3a UNIQUEIDENTIFIER,
@RelatedIntegrationObjectFieldName_62bfed3a NVARCHAR(255),
@Sequence_62bfed3a INT,
@Configuration_62bfed3a NVARCHAR(MAX),
@Status_62bfed3a NVARCHAR(25),
@IsCustom_62bfed3a BIT,
@MetadataSource_62bfed3a NVARCHAR(20),
@ID_62bfed3a UNIQUEIDENTIFIER
SET
  @IntegrationObjectID_62bfed3a = 'E9CED663-C518-439F-A9C2-0CF75AC00609'
SET
  @Name_62bfed3a = N'source'
SET
  @DisplayName_62bfed3a = N'Source'
SET
  @Description_62bfed3a = N'The ID of the source this transaction is attached to.'
SET
  @Type_62bfed3a = N'string'
SET
  @Length_62bfed3a = 5000
SET
  @AllowsNull_62bfed3a = 1
SET
  @IsPrimaryKey_62bfed3a = 0
SET
  @IsUniqueKey_62bfed3a = 0
SET
  @IsReadOnly_62bfed3a = 0
SET
  @IsRequired_62bfed3a = 1
SET
  @RelatedIntegrationObjectID_62bfed3a = '7F4587B2-248F-4495-9A20-CD27FDE3437C'
SET
  @RelatedIntegrationObjectFieldName_62bfed3a = N'id'
SET
  @Sequence_62bfed3a = 12
SET
  @Configuration_62bfed3a = N'{
  "ReferencedType": "source",
  "fkKind": "path-parent"
}'
SET
  @Status_62bfed3a = N'Active'
SET
  @IsCustom_62bfed3a = 0
SET
  @MetadataSource_62bfed3a = N'Declared'
SET
  @ID_62bfed3a = '22A73D77-7174-454B-802C-978C38E184FB' EXEC [__mj].spUpdateIntegrationObjectField @IntegrationObjectID = @IntegrationObjectID_62bfed3a,
  @Name = @Name_62bfed3a,
  @DisplayName = @DisplayName_62bfed3a,
  @Description = @Description_62bfed3a,
  @Category = @Category_62bfed3a,
  @Category_Clear = 1,
  @Type = @Type_62bfed3a,
  @Length = @Length_62bfed3a,
  @Precision = @Precision_62bfed3a,
  @Precision_Clear = 1,
  @Scale = @Scale_62bfed3a,
  @Scale_Clear = 1,
  @AllowsNull = @AllowsNull_62bfed3a,
  @DefaultValue = @DefaultValue_62bfed3a,
  @DefaultValue_Clear = 1,
  @IsPrimaryKey = @IsPrimaryKey_62bfed3a,
  @IsUniqueKey = @IsUniqueKey_62bfed3a,
  @IsReadOnly = @IsReadOnly_62bfed3a,
  @IsRequired = @IsRequired_62bfed3a,
  @RelatedIntegrationObjectID = @RelatedIntegrationObjectID_62bfed3a,
  @RelatedIntegrationObjectFieldName = @RelatedIntegrationObjectFieldName_62bfed3a,
  @Sequence = @Sequence_62bfed3a,
  @Configuration = @Configuration_62bfed3a,
  @Status = @Status_62bfed3a,
  @IsCustom = @IsCustom_62bfed3a,
  @MetadataSource = @MetadataSource_62bfed3a,
  @ID = @ID_62bfed3a;

GO


-- End of SQL Logging Session
-- Session ID: 63c65528-2f0f-4301-a5d5-75954f4f3c91
-- Completed: 2026-07-07T15:47:42.260Z
-- Duration: 1008ms
-- Total Statements: 8
