-- ============================================================================
-- MemberJunction PostgreSQL Migration
-- Converted from SQL Server using TypeScript conversion pipeline
-- ============================================================================

-- Extensions
CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Schema
CREATE SCHEMA IF NOT EXISTS __mj;
SET search_path TO __mj, public;

-- Ensure backslashes in string literals are treated literally (not as escape sequences)
SET standard_conforming_strings = on;

-- NOTE: Earlier converter versions made INTEGER to BOOLEAN cast implicit by
-- modifying the system catalog so SS-style INSERT INTO bool_col VALUES (1)
-- would work. That modification required pg_catalog write privileges, which
-- managed PG (RDS, Aurora, Cloud SQL, Azure) does not grant. As of v5.30 all
-- bulk INSERTs are emitted with native TRUE/FALSE values directly, so the
-- cast modification is no longer needed. Removed to support managed-PG
-- installs out of the box.


-- ===================== Data (INSERT/UPDATE/DELETE) =====================

-- MySQL Connector — connector metadata seed (generated by `mj sync push`)
-- Seeds the core __mj integration catalog (Integration / IntegrationObject / IntegrationObjectField + Actions).
-- Do not hand-edit; regenerate from ../metadata via `mj sync push` + `scripts/wrap-migration.mjs`.

-- SQL Logging Session
-- Session ID: d152ba54-d731-428d-8813-a3a5a85cf0f8
-- Started: 2026-07-10T00:55:15.126Z
-- Description: MetadataSync push operation
-- Generated by MemberJunction

-- Save MJ: Integrations (core SP call only)
DO $mj$
DECLARE
  p_Name_28d60d3f VARCHAR(100);
  p_Description_28d60d3f VARCHAR(255);
  p_NavigationBaseURL_28d60d3f VARCHAR(500);
  p_ClassName_28d60d3f VARCHAR(100);
  p_ImportPath_28d60d3f VARCHAR(100);
  p_BatchMaxRequestCount_28d60d3f INTEGER;
  p_BatchRequestWaitTime_28d60d3f INTEGER;
  p_ID_28d60d3f UUID;
  p_CredentialTypeID_28d60d3f UUID;
  p_Icon_28d60d3f TEXT;
  p_Configuration_28d60d3f TEXT;
BEGIN
  p_Name_28d60d3f := 'MySQL';
  p_Description_28d60d3f := 'Ingest data from an external MySQL, MariaDB, and Aurora-MySQL via a shared MJ: External Data Sources connection. Schema is discovered at connection time; the connector delegates connectivity to the EDS ''MySQLExternalDriver'' driver.';
  p_ClassName_28d60d3f := 'MySQLConnector';
  p_ImportPath_28d60d3f := '@memberjunction/connector-mysql';
  p_BatchMaxRequestCount_28d60d3f := -1;
  p_BatchRequestWaitTime_28d60d3f := -1;
  p_ID_28d60d3f := 'a5ddca2b-8661-4308-af9a-bb0799bbf11f';
  p_Icon_28d60d3f := 'fa-solid fa-database';
  p_Configuration_28d60d3f := '{
  "connectionModel": "external-data-source",
  "note": "Bind this connection to a shared ''MJ: External Data Sources'' row by setting Configuration.externalDataSourceID on the CompanyIntegration. Host + credentials live on that EDS row (credentials via CredentialEngine); objects/fields are discovered at connection time. Requires @memberjunction/external-data-sources + @memberjunction/external-data-source-mysql >= 5.46.0."
}';
  PERFORM __mj."spCreateIntegration"(p_Name := p_Name_28d60d3f, p_Description := p_Description_28d60d3f, p_NavigationBaseURL := p_NavigationBaseURL_28d60d3f, p_NavigationBaseURL_Clear := TRUE, p_ClassName := p_ClassName_28d60d3f, p_ImportPath := p_ImportPath_28d60d3f, p_BatchMaxRequestCount := p_BatchMaxRequestCount_28d60d3f, p_BatchRequestWaitTime := p_BatchRequestWaitTime_28d60d3f, p_ID := p_ID_28d60d3f, p_CredentialTypeID := p_CredentialTypeID_28d60d3f, p_CredentialTypeID_Clear := TRUE, p_Icon := p_Icon_28d60d3f, p_Configuration := p_Configuration_28d60d3f);
END $mj$;


-- ===================== Other =====================

-- End of SQL Logging Session
-- Session ID: d152ba54-d731-428d-8813-a3a5a85cf0f8
-- Completed: 2026-07-10T00:55:15.300Z
-- Duration: 174ms
-- Total Statements: 1
