-- ============================================================================
-- MemberJunction PostgreSQL Migration
-- Converted from SQL Server using TypeScript conversion pipeline
-- ============================================================================

-- Extensions
CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Schema
CREATE SCHEMA IF NOT EXISTS __mj;
SET search_path TO __mj, public;

-- Ensure backslashes in string literals are treated literally (not as escape sequences)
SET standard_conforming_strings = on;

-- NOTE: Earlier converter versions made INTEGER to BOOLEAN cast implicit by
-- modifying the system catalog so SS-style INSERT INTO bool_col VALUES (1)
-- would work. That modification required pg_catalog write privileges, which
-- managed PG (RDS, Aurora, Cloud SQL, Azure) does not grant. As of v5.30 all
-- bulk INSERTs are emitted with native TRUE/FALSE values directly, so the
-- cast modification is no longer needed. Removed to support managed-PG
-- installs out of the box.


-- ===================== Data (INSERT/UPDATE/DELETE) =====================

-- WordPress Connector — WP Activity Log objects (additive delta, generated by `mj sync push`)
--
-- Adds the two ActivityLog* objects to the __mj integration catalog on top of the 1.0.0 seed in
-- V202608212225__wordpress__Metadata.sql. Additive ONLY: it creates 2 IntegrationObject rows and
-- their 28 IntegrationObjectField rows and touches NOTHING that migration already seeded, so a
-- tenant already on 1.0.0 upgrades without a catalog reset.
--
-- These objects are NOT part of the WordPress REST API. WP Activity Log keeps its events in the
-- custom tables wsal_occurrences / wsal_metadata and registers no REST routes of its own, so they
-- are served by the companion plugin in Platform/WordPress/wp-plugin/mj-wsal-bridge, which the site
-- must have installed for these objects to return anything.
--
-- Do not hand-edit; the statements below are the generator's own output, sliced to the new records.

-- Save MJ: Integration Objects (core SP call only)
DO $mj$
DECLARE
  p_ID_1567f3bc UUID;
  p_IntegrationID_1567f3bc UUID;
  p_Name_1567f3bc VARCHAR(255);
  p_DisplayName_1567f3bc VARCHAR(255);
  p_Description_1567f3bc TEXT;
  p_Category_1567f3bc VARCHAR(100);
  p_APIPath_1567f3bc VARCHAR(500);
  p_ResponseDataKey_1567f3bc VARCHAR(255);
  p_DefaultPageSize_1567f3bc INTEGER;
  p_SupportsPagination_1567f3bc BOOLEAN;
  p_PaginationType_1567f3bc VARCHAR(20);
  p_SupportsIncrementalSync_1567f3bc BOOLEAN;
  p_SupportsWrite_1567f3bc BOOLEAN;
  p_DefaultQueryParams_1567f3bc TEXT;
  p_Configuration_1567f3bc TEXT;
  p_Sequence_1567f3bc INTEGER;
  p_Status_1567f3bc VARCHAR(25);
  p_WriteAPIPath_1567f3bc VARCHAR(500);
  p_WriteMethod_1567f3bc VARCHAR(10);
  p_DeleteMethod_1567f3bc VARCHAR(10);
  p_IsCustom_1567f3bc BOOLEAN;
  p_CreateAPIPath_1567f3bc TEXT;
  p_CreateMethod_1567f3bc VARCHAR(20);
  p_CreateBodyShape_1567f3bc VARCHAR(50);
  p_CreateBodyKey_1567f3bc VARCHAR(100);
  p_CreateIDLocation_1567f3bc VARCHAR(20);
  p_UpdateAPIPath_1567f3bc TEXT;
  p_UpdateMethod_1567f3bc VARCHAR(20);
  p_UpdateBodyShape_1567f3bc VARCHAR(50);
  p_UpdateBodyKey_1567f3bc VARCHAR(100);
  p_UpdateIDLocation_1567f3bc VARCHAR(20);
  p_DeleteAPIPath_1567f3bc TEXT;
  p_DeleteIDLocation_1567f3bc VARCHAR(20);
  p_IncrementalWatermarkField_1567f3bc VARCHAR(255);
  p_MetadataSource_1567f3bc VARCHAR(20);
  p_SupportsCreate_1567f3bc BOOLEAN;
  p_SupportsUpdate_1567f3bc BOOLEAN;
  p_SupportsDelete_1567f3bc BOOLEAN;
  p_SyncStrategy_1567f3bc VARCHAR(50);
  p_ContentHashApplicable_1567f3bc BOOLEAN;
  p_StableOrderingKey_1567f3bc VARCHAR(255);
BEGIN
  p_ID_1567f3bc := '1B6AAA3C-002C-4E1A-8C82-0900D33FE02A';
  p_IntegrationID_1567f3bc := '301B572A-FE48-4600-A8A2-8D5E92646048';
  p_Name_1567f3bc := 'ActivityLogEvent';
  p_DisplayName_1567f3bc := 'Activity Log Event';
  p_Description_1567f3bc := 'WP Activity Log events, flattened one row per logged event with its metadata pivoted in. Served by the MJ bridge plugin at mj-wsal/v1, because WP Activity Log itself registers no REST routes.';
  p_Category_1567f3bc := 'WP Activity Log';
  p_APIPath_1567f3bc := '/mj-wsal/v1/events';
  p_DefaultPageSize_1567f3bc := 100;
  p_SupportsPagination_1567f3bc := TRUE;
  p_PaginationType_1567f3bc := 'PageNumber';
  p_SupportsIncrementalSync_1567f3bc := TRUE;
  p_SupportsWrite_1567f3bc := FALSE;
  p_Configuration_1567f3bc := '{
  "namespace": "mj-wsal/v1",
  "listPath": "/mj-wsal/v1/events",
  "getOnePath": null,
  "routes": [
    "GET /mj-wsal/v1/events"
  ],
  "responseShape": "array",
  "pkField": "id",
  "pkEvidence": "Tier1-source — the bridge projects wsal_occurrences.id, which is that table''s bigint AUTO_INCREMENT PRIMARY KEY.",
  "pagination": {
    "type": "PageNumber",
    "pageParam": "page",
    "sizeParam": "per_page",
    "maxPageSize": 100,
    "totalHeader": "X-WP-Total",
    "totalPagesHeader": "X-WP-TotalPages"
  },
  "paginationNote": "The bridge registers page/per_page (per_page max 100, matching core) and emits X-WP-Total / X-WP-TotalPages. Rows are ordered by (created_on, id) — a total order, so no row can be skipped or repeated across an offset boundary.",
  "incrementalWatermark": {
    "field": "created_at",
    "filterParam": "after",
    "beforeParam": "before",
    "datesAreGmt": true,
    "orderby": "created_on",
    "note": "Watermarked on created_at (ISO-8601 UTC) rather than the raw created_on double: a bare epoch number is ambiguous to date parsers (seconds vs milliseconds), and reading these seconds as milliseconds would date every event to January 1970. The `after` bound is INCLUSIVE because created_on is not unique — an exclusive bound would drop every event sharing the last synced timestamp. A re-delivered boundary event dedupes on id."
  },
  "incrementalNote": null,
  "contextGatedFields": [],
  "customFieldSurface": [
    "meta"
  ],
  "requiresCompanionPlugin": {
    "plugin": "MJ WP Activity Log Bridge (Platform/WordPress/wp-plugin/mj-wsal-bridge)",
    "reason": "WP Activity Log stores events in the custom tables wsal_occurrences and wsal_metadata and registers ZERO REST routes — verified against WSAL 5.6.6, which contains no register_rest_route or rest_api_init call anywhere. Without the bridge installed this namespace is absent from the site route index and the object cannot be read.",
    "minimumWsalVersion": "5.0.0",
    "requiredCapability": "manage_options (manage_network_options on multisite)"
  }
}';
  p_Sequence_1567f3bc := 0;
  p_Status_1567f3bc := 'Active';
  p_WriteMethod_1567f3bc := 'POST';
  p_DeleteMethod_1567f3bc := 'DELETE';
  p_IsCustom_1567f3bc := FALSE;
  p_IncrementalWatermarkField_1567f3bc := 'created_at';
  p_MetadataSource_1567f3bc := 'Declared';
  p_SupportsCreate_1567f3bc := FALSE;
  p_SupportsUpdate_1567f3bc := FALSE;
  p_SupportsDelete_1567f3bc := FALSE;
  p_SyncStrategy_1567f3bc := 'WatermarkIncremental';
  p_ContentHashApplicable_1567f3bc := FALSE;
  p_StableOrderingKey_1567f3bc := 'id';
  PERFORM __mj."spCreateIntegrationObject"(p_ID := p_ID_1567f3bc, p_IntegrationID := p_IntegrationID_1567f3bc, p_Name := p_Name_1567f3bc, p_DisplayName := p_DisplayName_1567f3bc, p_Description := p_Description_1567f3bc, p_Category := p_Category_1567f3bc, p_APIPath := p_APIPath_1567f3bc, p_ResponseDataKey := p_ResponseDataKey_1567f3bc, p_ResponseDataKey_Clear := TRUE, p_DefaultPageSize := p_DefaultPageSize_1567f3bc, p_SupportsPagination := p_SupportsPagination_1567f3bc, p_PaginationType := p_PaginationType_1567f3bc, p_SupportsIncrementalSync := p_SupportsIncrementalSync_1567f3bc, p_SupportsWrite := p_SupportsWrite_1567f3bc, p_DefaultQueryParams := p_DefaultQueryParams_1567f3bc, p_DefaultQueryParams_Clear := TRUE, p_Configuration := p_Configuration_1567f3bc, p_Sequence := p_Sequence_1567f3bc, p_Status := p_Status_1567f3bc, p_WriteAPIPath := p_WriteAPIPath_1567f3bc, p_WriteAPIPath_Clear := TRUE, p_WriteMethod := p_WriteMethod_1567f3bc, p_DeleteMethod := p_DeleteMethod_1567f3bc, p_IsCustom := p_IsCustom_1567f3bc, p_CreateAPIPath := p_CreateAPIPath_1567f3bc, p_CreateAPIPath_Clear := TRUE, p_CreateMethod := p_CreateMethod_1567f3bc, p_CreateMethod_Clear := TRUE, p_CreateBodyShape := p_CreateBodyShape_1567f3bc, p_CreateBodyShape_Clear := TRUE, p_CreateBodyKey := p_CreateBodyKey_1567f3bc, p_CreateBodyKey_Clear := TRUE, p_CreateIDLocation := p_CreateIDLocation_1567f3bc, p_CreateIDLocation_Clear := TRUE, p_UpdateAPIPath := p_UpdateAPIPath_1567f3bc, p_UpdateAPIPath_Clear := TRUE, p_UpdateMethod := p_UpdateMethod_1567f3bc, p_UpdateMethod_Clear := TRUE, p_UpdateBodyShape := p_UpdateBodyShape_1567f3bc, p_UpdateBodyShape_Clear := TRUE, p_UpdateBodyKey := p_UpdateBodyKey_1567f3bc, p_UpdateBodyKey_Clear := TRUE, p_UpdateIDLocation := p_UpdateIDLocation_1567f3bc, p_UpdateIDLocation_Clear := TRUE, p_DeleteAPIPath := p_DeleteAPIPath_1567f3bc, p_DeleteAPIPath_Clear := TRUE, p_DeleteIDLocation := p_DeleteIDLocation_1567f3bc, p_DeleteIDLocation_Clear := TRUE, p_IncrementalWatermarkField := p_IncrementalWatermarkField_1567f3bc, p_MetadataSource := p_MetadataSource_1567f3bc, p_SupportsCreate := p_SupportsCreate_1567f3bc, p_SupportsUpdate := p_SupportsUpdate_1567f3bc, p_SupportsDelete := p_SupportsDelete_1567f3bc, p_SyncStrategy := p_SyncStrategy_1567f3bc, p_ContentHashApplicable := p_ContentHashApplicable_1567f3bc, p_StableOrderingKey := p_StableOrderingKey_1567f3bc);
END $mj$;

-- Save MJ: Integration Objects (core SP call only)
DO $mj$
DECLARE
  p_ID_c821642f UUID;
  p_IntegrationID_c821642f UUID;
  p_Name_c821642f VARCHAR(255);
  p_DisplayName_c821642f VARCHAR(255);
  p_Description_c821642f TEXT;
  p_Category_c821642f VARCHAR(100);
  p_APIPath_c821642f VARCHAR(500);
  p_ResponseDataKey_c821642f VARCHAR(255);
  p_DefaultPageSize_c821642f INTEGER;
  p_SupportsPagination_c821642f BOOLEAN;
  p_PaginationType_c821642f VARCHAR(20);
  p_SupportsIncrementalSync_c821642f BOOLEAN;
  p_SupportsWrite_c821642f BOOLEAN;
  p_DefaultQueryParams_c821642f TEXT;
  p_Configuration_c821642f TEXT;
  p_Sequence_c821642f INTEGER;
  p_Status_c821642f VARCHAR(25);
  p_WriteAPIPath_c821642f VARCHAR(500);
  p_WriteMethod_c821642f VARCHAR(10);
  p_DeleteMethod_c821642f VARCHAR(10);
  p_IsCustom_c821642f BOOLEAN;
  p_CreateAPIPath_c821642f TEXT;
  p_CreateMethod_c821642f VARCHAR(20);
  p_CreateBodyShape_c821642f VARCHAR(50);
  p_CreateBodyKey_c821642f VARCHAR(100);
  p_CreateIDLocation_c821642f VARCHAR(20);
  p_UpdateAPIPath_c821642f TEXT;
  p_UpdateMethod_c821642f VARCHAR(20);
  p_UpdateBodyShape_c821642f VARCHAR(50);
  p_UpdateBodyKey_c821642f VARCHAR(100);
  p_UpdateIDLocation_c821642f VARCHAR(20);
  p_DeleteAPIPath_c821642f TEXT;
  p_DeleteIDLocation_c821642f VARCHAR(20);
  p_IncrementalWatermarkField_c821642f VARCHAR(255);
  p_MetadataSource_c821642f VARCHAR(20);
  p_SupportsCreate_c821642f BOOLEAN;
  p_SupportsUpdate_c821642f BOOLEAN;
  p_SupportsDelete_c821642f BOOLEAN;
  p_SyncStrategy_c821642f VARCHAR(50);
  p_ContentHashApplicable_c821642f BOOLEAN;
  p_StableOrderingKey_c821642f VARCHAR(255);
BEGIN
  p_ID_c821642f := 'FB9E1B85-6B87-4561-B332-C264ECF2D87B';
  p_IntegrationID_c821642f := '301B572A-FE48-4600-A8A2-8D5E92646048';
  p_Name_c821642f := 'ActivityLogEventType';
  p_DisplayName_c821642f := 'Activity Log Event Type';
  p_Description_c821642f := 'The activity log event-type catalog: every event ID the installed plugin set can emit, with its label, severity and category. A slow-moving dimension for interpreting ActivityLogEvent.alert_id.';
  p_Category_c821642f := 'WP Activity Log';
  p_APIPath_c821642f := '/mj-wsal/v1/event-types';
  p_DefaultPageSize_c821642f := 100;
  p_SupportsPagination_c821642f := TRUE;
  p_PaginationType_c821642f := 'PageNumber';
  p_SupportsIncrementalSync_c821642f := FALSE;
  p_SupportsWrite_c821642f := FALSE;
  p_Configuration_c821642f := '{
  "namespace": "mj-wsal/v1",
  "listPath": "/mj-wsal/v1/event-types",
  "getOnePath": null,
  "routes": [
    "GET /mj-wsal/v1/event-types"
  ],
  "responseShape": "array",
  "pkField": "alert_id",
  "pkEvidence": "Tier1-source — the bridge keys the catalog by the plugin''s own alert code, which Alert_Manager rejects duplicates of at registration time.",
  "pagination": {
    "type": "PageNumber",
    "pageParam": "page",
    "sizeParam": "per_page",
    "maxPageSize": 100,
    "totalHeader": "X-WP-Total",
    "totalPagesHeader": "X-WP-TotalPages"
  },
  "paginationNote": "Paginated like the events route, though the catalog is small (order hundreds of rows) and slow-moving. Paginating it is what makes it a discoverable collection: the connector treats a GET route registering per_page as a listable object.",
  "incrementalWatermark": null,
  "incrementalNote": "The catalog is a static definition set with no timestamps of any kind — it changes only when a plugin is installed, updated or removed. Full-pulled and hash-diffed rather than given a synthesised watermark.",
  "contextGatedFields": [],
  "customFieldSurface": [],
  "requiresCompanionPlugin": {
    "plugin": "MJ WP Activity Log Bridge (Platform/WordPress/wp-plugin/mj-wsal-bridge)",
    "reason": "Read through the plugin''s own Alert_Manager, so third-party sensors (WooCommerce, Gravity Forms, Yoast and the rest) that register their own event types are included automatically and labels track the installed version.",
    "minimumWsalVersion": "5.0.0",
    "requiredCapability": "manage_options (manage_network_options on multisite)"
  }
}';
  p_Sequence_c821642f := 0;
  p_Status_c821642f := 'Active';
  p_WriteMethod_c821642f := 'POST';
  p_DeleteMethod_c821642f := 'DELETE';
  p_IsCustom_c821642f := FALSE;
  p_MetadataSource_c821642f := 'Declared';
  p_SupportsCreate_c821642f := FALSE;
  p_SupportsUpdate_c821642f := FALSE;
  p_SupportsDelete_c821642f := FALSE;
  p_SyncStrategy_c821642f := 'FullPullHashDiff';
  p_ContentHashApplicable_c821642f := TRUE;
  p_StableOrderingKey_c821642f := 'alert_id';
  PERFORM __mj."spCreateIntegrationObject"(p_ID := p_ID_c821642f, p_IntegrationID := p_IntegrationID_c821642f, p_Name := p_Name_c821642f, p_DisplayName := p_DisplayName_c821642f, p_Description := p_Description_c821642f, p_Category := p_Category_c821642f, p_APIPath := p_APIPath_c821642f, p_ResponseDataKey := p_ResponseDataKey_c821642f, p_ResponseDataKey_Clear := TRUE, p_DefaultPageSize := p_DefaultPageSize_c821642f, p_SupportsPagination := p_SupportsPagination_c821642f, p_PaginationType := p_PaginationType_c821642f, p_SupportsIncrementalSync := p_SupportsIncrementalSync_c821642f, p_SupportsWrite := p_SupportsWrite_c821642f, p_DefaultQueryParams := p_DefaultQueryParams_c821642f, p_DefaultQueryParams_Clear := TRUE, p_Configuration := p_Configuration_c821642f, p_Sequence := p_Sequence_c821642f, p_Status := p_Status_c821642f, p_WriteAPIPath := p_WriteAPIPath_c821642f, p_WriteAPIPath_Clear := TRUE, p_WriteMethod := p_WriteMethod_c821642f, p_DeleteMethod := p_DeleteMethod_c821642f, p_IsCustom := p_IsCustom_c821642f, p_CreateAPIPath := p_CreateAPIPath_c821642f, p_CreateAPIPath_Clear := TRUE, p_CreateMethod := p_CreateMethod_c821642f, p_CreateMethod_Clear := TRUE, p_CreateBodyShape := p_CreateBodyShape_c821642f, p_CreateBodyShape_Clear := TRUE, p_CreateBodyKey := p_CreateBodyKey_c821642f, p_CreateBodyKey_Clear := TRUE, p_CreateIDLocation := p_CreateIDLocation_c821642f, p_CreateIDLocation_Clear := TRUE, p_UpdateAPIPath := p_UpdateAPIPath_c821642f, p_UpdateAPIPath_Clear := TRUE, p_UpdateMethod := p_UpdateMethod_c821642f, p_UpdateMethod_Clear := TRUE, p_UpdateBodyShape := p_UpdateBodyShape_c821642f, p_UpdateBodyShape_Clear := TRUE, p_UpdateBodyKey := p_UpdateBodyKey_c821642f, p_UpdateBodyKey_Clear := TRUE, p_UpdateIDLocation := p_UpdateIDLocation_c821642f, p_UpdateIDLocation_Clear := TRUE, p_DeleteAPIPath := p_DeleteAPIPath_c821642f, p_DeleteAPIPath_Clear := TRUE, p_DeleteIDLocation := p_DeleteIDLocation_c821642f, p_DeleteIDLocation_Clear := TRUE, p_IncrementalWatermarkField := p_IncrementalWatermarkField_c821642f, p_IncrementalWatermarkField_Clear := TRUE, p_MetadataSource := p_MetadataSource_c821642f, p_SupportsCreate := p_SupportsCreate_c821642f, p_SupportsUpdate := p_SupportsUpdate_c821642f, p_SupportsDelete := p_SupportsDelete_c821642f, p_SyncStrategy := p_SyncStrategy_c821642f, p_ContentHashApplicable := p_ContentHashApplicable_c821642f, p_StableOrderingKey := p_StableOrderingKey_c821642f);
END $mj$;

-- Save MJ: Integration Object Fields (core SP call only)
DO $mj$
DECLARE
  p_ID_87431f7f UUID;
  p_IntegrationObjectID_87431f7f UUID;
  p_Name_87431f7f VARCHAR(255);
  p_DisplayName_87431f7f VARCHAR(255);
  p_Description_87431f7f TEXT;
  p_Category_87431f7f VARCHAR(100);
  p_Type_87431f7f VARCHAR(100);
  p_Length_87431f7f INTEGER;
  p_Precision_87431f7f INTEGER;
  p_Scale_87431f7f INTEGER;
  p_AllowsNull_87431f7f BOOLEAN;
  p_DefaultValue_87431f7f VARCHAR(255);
  p_IsPrimaryKey_87431f7f BOOLEAN;
  p_IsUniqueKey_87431f7f BOOLEAN;
  p_IsReadOnly_87431f7f BOOLEAN;
  p_IsRequired_87431f7f BOOLEAN;
  p_RelatedIntegrationObjectID_87431f7f UUID;
  p_RelatedIntegrationObjectFieldName_87431f7f VARCHAR(255);
  p_Sequence_87431f7f INTEGER;
  p_Configuration_87431f7f TEXT;
  p_Status_87431f7f VARCHAR(25);
  p_IsCustom_87431f7f BOOLEAN;
  p_MetadataSource_87431f7f VARCHAR(20);
BEGIN
  p_ID_87431f7f := 'B9664C40-3AB1-4CDA-BF25-D4C326D2FC49';
  p_IntegrationObjectID_87431f7f := '1B6AAA3C-002C-4E1A-8C82-0900D33FE02A';
  p_Name_87431f7f := 'id';
  p_DisplayName_87431f7f := 'ID';
  p_Description_87431f7f := 'Unique event identifier. Primary key.';
  p_Type_87431f7f := 'Integer';
  p_AllowsNull_87431f7f := FALSE;
  p_IsPrimaryKey_87431f7f := TRUE;
  p_IsUniqueKey_87431f7f := TRUE;
  p_IsReadOnly_87431f7f := TRUE;
  p_IsRequired_87431f7f := TRUE;
  p_Sequence_87431f7f := 0;
  p_Configuration_87431f7f := '{
  "contexts": [
    "view"
  ]
}';
  p_Status_87431f7f := 'Active';
  p_IsCustom_87431f7f := FALSE;
  p_MetadataSource_87431f7f := 'Declared';
  PERFORM __mj."spCreateIntegrationObjectField"(p_ID := p_ID_87431f7f, p_IntegrationObjectID := p_IntegrationObjectID_87431f7f, p_Name := p_Name_87431f7f, p_DisplayName := p_DisplayName_87431f7f, p_Description := p_Description_87431f7f, p_Category := p_Category_87431f7f, p_Category_Clear := TRUE, p_Type := p_Type_87431f7f, p_Length := p_Length_87431f7f, p_Length_Clear := TRUE, p_Precision := p_Precision_87431f7f, p_Precision_Clear := TRUE, p_Scale := p_Scale_87431f7f, p_Scale_Clear := TRUE, p_AllowsNull := p_AllowsNull_87431f7f, p_DefaultValue := p_DefaultValue_87431f7f, p_DefaultValue_Clear := TRUE, p_IsPrimaryKey := p_IsPrimaryKey_87431f7f, p_IsUniqueKey := p_IsUniqueKey_87431f7f, p_IsReadOnly := p_IsReadOnly_87431f7f, p_IsRequired := p_IsRequired_87431f7f, p_RelatedIntegrationObjectID := p_RelatedIntegrationObjectID_87431f7f, p_RelatedIntegrationObjectID_Clear := TRUE, p_RelatedIntegrationObjectFieldName := p_RelatedIntegrationObjectFieldName_87431f7f, p_RelatedIntegrationObjectFieldName_Clear := TRUE, p_Sequence := p_Sequence_87431f7f, p_Configuration := p_Configuration_87431f7f, p_Status := p_Status_87431f7f, p_IsCustom := p_IsCustom_87431f7f, p_MetadataSource := p_MetadataSource_87431f7f);
END $mj$;

-- Save MJ: Integration Object Fields (core SP call only)
DO $mj$
DECLARE
  p_ID_cec44b6d UUID;
  p_IntegrationObjectID_cec44b6d UUID;
  p_Name_cec44b6d VARCHAR(255);
  p_DisplayName_cec44b6d VARCHAR(255);
  p_Description_cec44b6d TEXT;
  p_Category_cec44b6d VARCHAR(100);
  p_Type_cec44b6d VARCHAR(100);
  p_Length_cec44b6d INTEGER;
  p_Precision_cec44b6d INTEGER;
  p_Scale_cec44b6d INTEGER;
  p_AllowsNull_cec44b6d BOOLEAN;
  p_DefaultValue_cec44b6d VARCHAR(255);
  p_IsPrimaryKey_cec44b6d BOOLEAN;
  p_IsUniqueKey_cec44b6d BOOLEAN;
  p_IsReadOnly_cec44b6d BOOLEAN;
  p_IsRequired_cec44b6d BOOLEAN;
  p_RelatedIntegrationObjectID_cec44b6d UUID;
  p_RelatedIntegrationObjectFieldName_cec44b6d VARCHAR(255);
  p_Sequence_cec44b6d INTEGER;
  p_Configuration_cec44b6d TEXT;
  p_Status_cec44b6d VARCHAR(25);
  p_IsCustom_cec44b6d BOOLEAN;
  p_MetadataSource_cec44b6d VARCHAR(20);
BEGIN
  p_ID_cec44b6d := 'C8AD08C3-7312-4805-846E-E4E2BCBC61B5';
  p_IntegrationObjectID_cec44b6d := '1B6AAA3C-002C-4E1A-8C82-0900D33FE02A';
  p_Name_cec44b6d := 'site_id';
  p_DisplayName_cec44b6d := 'Site ID';
  p_Description_cec44b6d := 'Multisite network site ID; 1 on a single-site install.';
  p_Type_cec44b6d := 'Integer';
  p_AllowsNull_cec44b6d := FALSE;
  p_IsPrimaryKey_cec44b6d := FALSE;
  p_IsUniqueKey_cec44b6d := FALSE;
  p_IsReadOnly_cec44b6d := TRUE;
  p_IsRequired_cec44b6d := FALSE;
  p_Sequence_cec44b6d := 1;
  p_Configuration_cec44b6d := '{
  "contexts": [
    "view"
  ]
}';
  p_Status_cec44b6d := 'Active';
  p_IsCustom_cec44b6d := FALSE;
  p_MetadataSource_cec44b6d := 'Declared';
  PERFORM __mj."spCreateIntegrationObjectField"(p_ID := p_ID_cec44b6d, p_IntegrationObjectID := p_IntegrationObjectID_cec44b6d, p_Name := p_Name_cec44b6d, p_DisplayName := p_DisplayName_cec44b6d, p_Description := p_Description_cec44b6d, p_Category := p_Category_cec44b6d, p_Category_Clear := TRUE, p_Type := p_Type_cec44b6d, p_Length := p_Length_cec44b6d, p_Length_Clear := TRUE, p_Precision := p_Precision_cec44b6d, p_Precision_Clear := TRUE, p_Scale := p_Scale_cec44b6d, p_Scale_Clear := TRUE, p_AllowsNull := p_AllowsNull_cec44b6d, p_DefaultValue := p_DefaultValue_cec44b6d, p_DefaultValue_Clear := TRUE, p_IsPrimaryKey := p_IsPrimaryKey_cec44b6d, p_IsUniqueKey := p_IsUniqueKey_cec44b6d, p_IsReadOnly := p_IsReadOnly_cec44b6d, p_IsRequired := p_IsRequired_cec44b6d, p_RelatedIntegrationObjectID := p_RelatedIntegrationObjectID_cec44b6d, p_RelatedIntegrationObjectID_Clear := TRUE, p_RelatedIntegrationObjectFieldName := p_RelatedIntegrationObjectFieldName_cec44b6d, p_RelatedIntegrationObjectFieldName_Clear := TRUE, p_Sequence := p_Sequence_cec44b6d, p_Configuration := p_Configuration_cec44b6d, p_Status := p_Status_cec44b6d, p_IsCustom := p_IsCustom_cec44b6d, p_MetadataSource := p_MetadataSource_cec44b6d);
END $mj$;

-- Save MJ: Integration Object Fields (core SP call only)
DO $mj$
DECLARE
  p_ID_b9e071aa UUID;
  p_IntegrationObjectID_b9e071aa UUID;
  p_Name_b9e071aa VARCHAR(255);
  p_DisplayName_b9e071aa VARCHAR(255);
  p_Description_b9e071aa TEXT;
  p_Category_b9e071aa VARCHAR(100);
  p_Type_b9e071aa VARCHAR(100);
  p_Length_b9e071aa INTEGER;
  p_Precision_b9e071aa INTEGER;
  p_Scale_b9e071aa INTEGER;
  p_AllowsNull_b9e071aa BOOLEAN;
  p_DefaultValue_b9e071aa VARCHAR(255);
  p_IsPrimaryKey_b9e071aa BOOLEAN;
  p_IsUniqueKey_b9e071aa BOOLEAN;
  p_IsReadOnly_b9e071aa BOOLEAN;
  p_IsRequired_b9e071aa BOOLEAN;
  p_RelatedIntegrationObjectID_b9e071aa UUID;
  p_RelatedIntegrationObjectFieldName_b9e071aa VARCHAR(255);
  p_Sequence_b9e071aa INTEGER;
  p_Configuration_b9e071aa TEXT;
  p_Status_b9e071aa VARCHAR(25);
  p_IsCustom_b9e071aa BOOLEAN;
  p_MetadataSource_b9e071aa VARCHAR(20);
BEGIN
  p_ID_b9e071aa := 'A9A1A083-81B5-4C39-8670-F19183FE3751';
  p_IntegrationObjectID_b9e071aa := '1B6AAA3C-002C-4E1A-8C82-0900D33FE02A';
  p_Name_b9e071aa := 'alert_id';
  p_DisplayName_b9e071aa := 'Alert ID';
  p_Description_b9e071aa := 'WP Activity Log event type ID. Joins to ActivityLogEventType.alert_id.';
  p_Type_b9e071aa := 'Integer';
  p_AllowsNull_b9e071aa := FALSE;
  p_IsPrimaryKey_b9e071aa := FALSE;
  p_IsUniqueKey_b9e071aa := FALSE;
  p_IsReadOnly_b9e071aa := TRUE;
  p_IsRequired_b9e071aa := FALSE;
  p_Sequence_b9e071aa := 2;
  p_Configuration_b9e071aa := '{
  "contexts": [
    "view"
  ]
}';
  p_Status_b9e071aa := 'Active';
  p_IsCustom_b9e071aa := FALSE;
  p_MetadataSource_b9e071aa := 'Declared';
  PERFORM __mj."spCreateIntegrationObjectField"(p_ID := p_ID_b9e071aa, p_IntegrationObjectID := p_IntegrationObjectID_b9e071aa, p_Name := p_Name_b9e071aa, p_DisplayName := p_DisplayName_b9e071aa, p_Description := p_Description_b9e071aa, p_Category := p_Category_b9e071aa, p_Category_Clear := TRUE, p_Type := p_Type_b9e071aa, p_Length := p_Length_b9e071aa, p_Length_Clear := TRUE, p_Precision := p_Precision_b9e071aa, p_Precision_Clear := TRUE, p_Scale := p_Scale_b9e071aa, p_Scale_Clear := TRUE, p_AllowsNull := p_AllowsNull_b9e071aa, p_DefaultValue := p_DefaultValue_b9e071aa, p_DefaultValue_Clear := TRUE, p_IsPrimaryKey := p_IsPrimaryKey_b9e071aa, p_IsUniqueKey := p_IsUniqueKey_b9e071aa, p_IsReadOnly := p_IsReadOnly_b9e071aa, p_IsRequired := p_IsRequired_b9e071aa, p_RelatedIntegrationObjectID := p_RelatedIntegrationObjectID_b9e071aa, p_RelatedIntegrationObjectID_Clear := TRUE, p_RelatedIntegrationObjectFieldName := p_RelatedIntegrationObjectFieldName_b9e071aa, p_RelatedIntegrationObjectFieldName_Clear := TRUE, p_Sequence := p_Sequence_b9e071aa, p_Configuration := p_Configuration_b9e071aa, p_Status := p_Status_b9e071aa, p_IsCustom := p_IsCustom_b9e071aa, p_MetadataSource := p_MetadataSource_b9e071aa);
END $mj$;

-- Save MJ: Integration Object Fields (core SP call only)
DO $mj$
DECLARE
  p_ID_94f154ed UUID;
  p_IntegrationObjectID_94f154ed UUID;
  p_Name_94f154ed VARCHAR(255);
  p_DisplayName_94f154ed VARCHAR(255);
  p_Description_94f154ed TEXT;
  p_Category_94f154ed VARCHAR(100);
  p_Type_94f154ed VARCHAR(100);
  p_Length_94f154ed INTEGER;
  p_Precision_94f154ed INTEGER;
  p_Scale_94f154ed INTEGER;
  p_AllowsNull_94f154ed BOOLEAN;
  p_DefaultValue_94f154ed VARCHAR(255);
  p_IsPrimaryKey_94f154ed BOOLEAN;
  p_IsUniqueKey_94f154ed BOOLEAN;
  p_IsReadOnly_94f154ed BOOLEAN;
  p_IsRequired_94f154ed BOOLEAN;
  p_RelatedIntegrationObjectID_94f154ed UUID;
  p_RelatedIntegrationObjectFieldName_94f154ed VARCHAR(255);
  p_Sequence_94f154ed INTEGER;
  p_Configuration_94f154ed TEXT;
  p_Status_94f154ed VARCHAR(25);
  p_IsCustom_94f154ed BOOLEAN;
  p_MetadataSource_94f154ed VARCHAR(20);
BEGIN
  p_ID_94f154ed := '69198AE8-53D7-417A-8610-9729F17655B5';
  p_IntegrationObjectID_94f154ed := '1B6AAA3C-002C-4E1A-8C82-0900D33FE02A';
  p_Name_94f154ed := 'alert_label';
  p_DisplayName_94f154ed := 'Alert Label';
  p_Description_94f154ed := 'Human-readable name of the event type, resolved from the installed plugin set.';
  p_Type_94f154ed := 'String';
  p_AllowsNull_94f154ed := TRUE;
  p_IsPrimaryKey_94f154ed := FALSE;
  p_IsUniqueKey_94f154ed := FALSE;
  p_IsReadOnly_94f154ed := TRUE;
  p_IsRequired_94f154ed := FALSE;
  p_Sequence_94f154ed := 3;
  p_Configuration_94f154ed := '{
  "contexts": [
    "view"
  ]
}';
  p_Status_94f154ed := 'Active';
  p_IsCustom_94f154ed := FALSE;
  p_MetadataSource_94f154ed := 'Declared';
  PERFORM __mj."spCreateIntegrationObjectField"(p_ID := p_ID_94f154ed, p_IntegrationObjectID := p_IntegrationObjectID_94f154ed, p_Name := p_Name_94f154ed, p_DisplayName := p_DisplayName_94f154ed, p_Description := p_Description_94f154ed, p_Category := p_Category_94f154ed, p_Category_Clear := TRUE, p_Type := p_Type_94f154ed, p_Length := p_Length_94f154ed, p_Length_Clear := TRUE, p_Precision := p_Precision_94f154ed, p_Precision_Clear := TRUE, p_Scale := p_Scale_94f154ed, p_Scale_Clear := TRUE, p_AllowsNull := p_AllowsNull_94f154ed, p_DefaultValue := p_DefaultValue_94f154ed, p_DefaultValue_Clear := TRUE, p_IsPrimaryKey := p_IsPrimaryKey_94f154ed, p_IsUniqueKey := p_IsUniqueKey_94f154ed, p_IsReadOnly := p_IsReadOnly_94f154ed, p_IsRequired := p_IsRequired_94f154ed, p_RelatedIntegrationObjectID := p_RelatedIntegrationObjectID_94f154ed, p_RelatedIntegrationObjectID_Clear := TRUE, p_RelatedIntegrationObjectFieldName := p_RelatedIntegrationObjectFieldName_94f154ed, p_RelatedIntegrationObjectFieldName_Clear := TRUE, p_Sequence := p_Sequence_94f154ed, p_Configuration := p_Configuration_94f154ed, p_Status := p_Status_94f154ed, p_IsCustom := p_IsCustom_94f154ed, p_MetadataSource := p_MetadataSource_94f154ed);
END $mj$;

-- Save MJ: Integration Object Fields (core SP call only)
DO $mj$
DECLARE
  p_ID_3ff8d976 UUID;
  p_IntegrationObjectID_3ff8d976 UUID;
  p_Name_3ff8d976 VARCHAR(255);
  p_DisplayName_3ff8d976 VARCHAR(255);
  p_Description_3ff8d976 TEXT;
  p_Category_3ff8d976 VARCHAR(100);
  p_Type_3ff8d976 VARCHAR(100);
  p_Length_3ff8d976 INTEGER;
  p_Precision_3ff8d976 INTEGER;
  p_Scale_3ff8d976 INTEGER;
  p_AllowsNull_3ff8d976 BOOLEAN;
  p_DefaultValue_3ff8d976 VARCHAR(255);
  p_IsPrimaryKey_3ff8d976 BOOLEAN;
  p_IsUniqueKey_3ff8d976 BOOLEAN;
  p_IsReadOnly_3ff8d976 BOOLEAN;
  p_IsRequired_3ff8d976 BOOLEAN;
  p_RelatedIntegrationObjectID_3ff8d976 UUID;
  p_RelatedIntegrationObjectFieldName_3ff8d976 VARCHAR(255);
  p_Sequence_3ff8d976 INTEGER;
  p_Configuration_3ff8d976 TEXT;
  p_Status_3ff8d976 VARCHAR(25);
  p_IsCustom_3ff8d976 BOOLEAN;
  p_MetadataSource_3ff8d976 VARCHAR(20);
BEGIN
  p_ID_3ff8d976 := '0A82633B-3811-46B9-9B88-515FA3DDF9C4';
  p_IntegrationObjectID_3ff8d976 := '1B6AAA3C-002C-4E1A-8C82-0900D33FE02A';
  p_Name_3ff8d976 := 'created_on';
  p_DisplayName_3ff8d976 := 'Created On (Epoch)';
  p_Description_3ff8d976 := 'Raw Unix timestamp in SECONDS with sub-second precision, exactly as WP Activity Log stores it.';
  p_Type_3ff8d976 := 'Decimal';
  p_AllowsNull_3ff8d976 := FALSE;
  p_IsPrimaryKey_3ff8d976 := FALSE;
  p_IsUniqueKey_3ff8d976 := FALSE;
  p_IsReadOnly_3ff8d976 := TRUE;
  p_IsRequired_3ff8d976 := FALSE;
  p_Sequence_3ff8d976 := 4;
  p_Configuration_3ff8d976 := '{
  "contexts": [
    "view"
  ]
}';
  p_Status_3ff8d976 := 'Active';
  p_IsCustom_3ff8d976 := FALSE;
  p_MetadataSource_3ff8d976 := 'Declared';
  PERFORM __mj."spCreateIntegrationObjectField"(p_ID := p_ID_3ff8d976, p_IntegrationObjectID := p_IntegrationObjectID_3ff8d976, p_Name := p_Name_3ff8d976, p_DisplayName := p_DisplayName_3ff8d976, p_Description := p_Description_3ff8d976, p_Category := p_Category_3ff8d976, p_Category_Clear := TRUE, p_Type := p_Type_3ff8d976, p_Length := p_Length_3ff8d976, p_Length_Clear := TRUE, p_Precision := p_Precision_3ff8d976, p_Precision_Clear := TRUE, p_Scale := p_Scale_3ff8d976, p_Scale_Clear := TRUE, p_AllowsNull := p_AllowsNull_3ff8d976, p_DefaultValue := p_DefaultValue_3ff8d976, p_DefaultValue_Clear := TRUE, p_IsPrimaryKey := p_IsPrimaryKey_3ff8d976, p_IsUniqueKey := p_IsUniqueKey_3ff8d976, p_IsReadOnly := p_IsReadOnly_3ff8d976, p_IsRequired := p_IsRequired_3ff8d976, p_RelatedIntegrationObjectID := p_RelatedIntegrationObjectID_3ff8d976, p_RelatedIntegrationObjectID_Clear := TRUE, p_RelatedIntegrationObjectFieldName := p_RelatedIntegrationObjectFieldName_3ff8d976, p_RelatedIntegrationObjectFieldName_Clear := TRUE, p_Sequence := p_Sequence_3ff8d976, p_Configuration := p_Configuration_3ff8d976, p_Status := p_Status_3ff8d976, p_IsCustom := p_IsCustom_3ff8d976, p_MetadataSource := p_MetadataSource_3ff8d976);
END $mj$;

-- Save MJ: Integration Object Fields (core SP call only)
DO $mj$
DECLARE
  p_ID_27a183a6 UUID;
  p_IntegrationObjectID_27a183a6 UUID;
  p_Name_27a183a6 VARCHAR(255);
  p_DisplayName_27a183a6 VARCHAR(255);
  p_Description_27a183a6 TEXT;
  p_Category_27a183a6 VARCHAR(100);
  p_Type_27a183a6 VARCHAR(100);
  p_Length_27a183a6 INTEGER;
  p_Precision_27a183a6 INTEGER;
  p_Scale_27a183a6 INTEGER;
  p_AllowsNull_27a183a6 BOOLEAN;
  p_DefaultValue_27a183a6 VARCHAR(255);
  p_IsPrimaryKey_27a183a6 BOOLEAN;
  p_IsUniqueKey_27a183a6 BOOLEAN;
  p_IsReadOnly_27a183a6 BOOLEAN;
  p_IsRequired_27a183a6 BOOLEAN;
  p_RelatedIntegrationObjectID_27a183a6 UUID;
  p_RelatedIntegrationObjectFieldName_27a183a6 VARCHAR(255);
  p_Sequence_27a183a6 INTEGER;
  p_Configuration_27a183a6 TEXT;
  p_Status_27a183a6 VARCHAR(25);
  p_IsCustom_27a183a6 BOOLEAN;
  p_MetadataSource_27a183a6 VARCHAR(20);
BEGIN
  p_ID_27a183a6 := '2150206A-4215-4D16-AA64-CC18734C98EF';
  p_IntegrationObjectID_27a183a6 := '1B6AAA3C-002C-4E1A-8C82-0900D33FE02A';
  p_Name_27a183a6 := 'created_at';
  p_DisplayName_27a183a6 := 'Created At';
  p_Description_27a183a6 := 'The same instant as an ISO-8601 UTC datetime. This is the incremental watermark field.';
  p_Type_27a183a6 := 'Datetime';
  p_AllowsNull_27a183a6 := FALSE;
  p_IsPrimaryKey_27a183a6 := FALSE;
  p_IsUniqueKey_27a183a6 := FALSE;
  p_IsReadOnly_27a183a6 := TRUE;
  p_IsRequired_27a183a6 := FALSE;
  p_Sequence_27a183a6 := 5;
  p_Configuration_27a183a6 := '{
  "contexts": [
    "view"
  ]
}';
  p_Status_27a183a6 := 'Active';
  p_IsCustom_27a183a6 := FALSE;
  p_MetadataSource_27a183a6 := 'Declared';
  PERFORM __mj."spCreateIntegrationObjectField"(p_ID := p_ID_27a183a6, p_IntegrationObjectID := p_IntegrationObjectID_27a183a6, p_Name := p_Name_27a183a6, p_DisplayName := p_DisplayName_27a183a6, p_Description := p_Description_27a183a6, p_Category := p_Category_27a183a6, p_Category_Clear := TRUE, p_Type := p_Type_27a183a6, p_Length := p_Length_27a183a6, p_Length_Clear := TRUE, p_Precision := p_Precision_27a183a6, p_Precision_Clear := TRUE, p_Scale := p_Scale_27a183a6, p_Scale_Clear := TRUE, p_AllowsNull := p_AllowsNull_27a183a6, p_DefaultValue := p_DefaultValue_27a183a6, p_DefaultValue_Clear := TRUE, p_IsPrimaryKey := p_IsPrimaryKey_27a183a6, p_IsUniqueKey := p_IsUniqueKey_27a183a6, p_IsReadOnly := p_IsReadOnly_27a183a6, p_IsRequired := p_IsRequired_27a183a6, p_RelatedIntegrationObjectID := p_RelatedIntegrationObjectID_27a183a6, p_RelatedIntegrationObjectID_Clear := TRUE, p_RelatedIntegrationObjectFieldName := p_RelatedIntegrationObjectFieldName_27a183a6, p_RelatedIntegrationObjectFieldName_Clear := TRUE, p_Sequence := p_Sequence_27a183a6, p_Configuration := p_Configuration_27a183a6, p_Status := p_Status_27a183a6, p_IsCustom := p_IsCustom_27a183a6, p_MetadataSource := p_MetadataSource_27a183a6);
END $mj$;

-- Save MJ: Integration Object Fields (core SP call only)
DO $mj$
DECLARE
  p_ID_bc61171c UUID;
  p_IntegrationObjectID_bc61171c UUID;
  p_Name_bc61171c VARCHAR(255);
  p_DisplayName_bc61171c VARCHAR(255);
  p_Description_bc61171c TEXT;
  p_Category_bc61171c VARCHAR(100);
  p_Type_bc61171c VARCHAR(100);
  p_Length_bc61171c INTEGER;
  p_Precision_bc61171c INTEGER;
  p_Scale_bc61171c INTEGER;
  p_AllowsNull_bc61171c BOOLEAN;
  p_DefaultValue_bc61171c VARCHAR(255);
  p_IsPrimaryKey_bc61171c BOOLEAN;
  p_IsUniqueKey_bc61171c BOOLEAN;
  p_IsReadOnly_bc61171c BOOLEAN;
  p_IsRequired_bc61171c BOOLEAN;
  p_RelatedIntegrationObjectID_bc61171c UUID;
  p_RelatedIntegrationObjectFieldName_bc61171c VARCHAR(255);
  p_Sequence_bc61171c INTEGER;
  p_Configuration_bc61171c TEXT;
  p_Status_bc61171c VARCHAR(25);
  p_IsCustom_bc61171c BOOLEAN;
  p_MetadataSource_bc61171c VARCHAR(20);
BEGIN
  p_ID_bc61171c := '275D0167-D5CF-4983-A38F-0E3AA6009A39';
  p_IntegrationObjectID_bc61171c := '1B6AAA3C-002C-4E1A-8C82-0900D33FE02A';
  p_Name_bc61171c := 'severity';
  p_DisplayName_bc61171c := 'Severity';
  p_Description_bc61171c := 'Raw numeric severity level as stored by the plugin: 500, 400, 300, 250 or 200.';
  p_Type_bc61171c := 'String';
  p_AllowsNull_bc61171c := TRUE;
  p_IsPrimaryKey_bc61171c := FALSE;
  p_IsUniqueKey_bc61171c := FALSE;
  p_IsReadOnly_bc61171c := TRUE;
  p_IsRequired_bc61171c := FALSE;
  p_Sequence_bc61171c := 6;
  p_Configuration_bc61171c := '{
  "contexts": [
    "view"
  ]
}';
  p_Status_bc61171c := 'Active';
  p_IsCustom_bc61171c := FALSE;
  p_MetadataSource_bc61171c := 'Declared';
  PERFORM __mj."spCreateIntegrationObjectField"(p_ID := p_ID_bc61171c, p_IntegrationObjectID := p_IntegrationObjectID_bc61171c, p_Name := p_Name_bc61171c, p_DisplayName := p_DisplayName_bc61171c, p_Description := p_Description_bc61171c, p_Category := p_Category_bc61171c, p_Category_Clear := TRUE, p_Type := p_Type_bc61171c, p_Length := p_Length_bc61171c, p_Length_Clear := TRUE, p_Precision := p_Precision_bc61171c, p_Precision_Clear := TRUE, p_Scale := p_Scale_bc61171c, p_Scale_Clear := TRUE, p_AllowsNull := p_AllowsNull_bc61171c, p_DefaultValue := p_DefaultValue_bc61171c, p_DefaultValue_Clear := TRUE, p_IsPrimaryKey := p_IsPrimaryKey_bc61171c, p_IsUniqueKey := p_IsUniqueKey_bc61171c, p_IsReadOnly := p_IsReadOnly_bc61171c, p_IsRequired := p_IsRequired_bc61171c, p_RelatedIntegrationObjectID := p_RelatedIntegrationObjectID_bc61171c, p_RelatedIntegrationObjectID_Clear := TRUE, p_RelatedIntegrationObjectFieldName := p_RelatedIntegrationObjectFieldName_bc61171c, p_RelatedIntegrationObjectFieldName_Clear := TRUE, p_Sequence := p_Sequence_bc61171c, p_Configuration := p_Configuration_bc61171c, p_Status := p_Status_bc61171c, p_IsCustom := p_IsCustom_bc61171c, p_MetadataSource := p_MetadataSource_bc61171c);
END $mj$;

-- Save MJ: Integration Object Fields (core SP call only)
DO $mj$
DECLARE
  p_ID_0c2863f3 UUID;
  p_IntegrationObjectID_0c2863f3 UUID;
  p_Name_0c2863f3 VARCHAR(255);
  p_DisplayName_0c2863f3 VARCHAR(255);
  p_Description_0c2863f3 TEXT;
  p_Category_0c2863f3 VARCHAR(100);
  p_Type_0c2863f3 VARCHAR(100);
  p_Length_0c2863f3 INTEGER;
  p_Precision_0c2863f3 INTEGER;
  p_Scale_0c2863f3 INTEGER;
  p_AllowsNull_0c2863f3 BOOLEAN;
  p_DefaultValue_0c2863f3 VARCHAR(255);
  p_IsPrimaryKey_0c2863f3 BOOLEAN;
  p_IsUniqueKey_0c2863f3 BOOLEAN;
  p_IsReadOnly_0c2863f3 BOOLEAN;
  p_IsRequired_0c2863f3 BOOLEAN;
  p_RelatedIntegrationObjectID_0c2863f3 UUID;
  p_RelatedIntegrationObjectFieldName_0c2863f3 VARCHAR(255);
  p_Sequence_0c2863f3 INTEGER;
  p_Configuration_0c2863f3 TEXT;
  p_Status_0c2863f3 VARCHAR(25);
  p_IsCustom_0c2863f3 BOOLEAN;
  p_MetadataSource_0c2863f3 VARCHAR(20);
BEGIN
  p_ID_0c2863f3 := '62640CD4-25FB-4399-85C7-D5C9DA821B10';
  p_IntegrationObjectID_0c2863f3 := '1B6AAA3C-002C-4E1A-8C82-0900D33FE02A';
  p_Name_0c2863f3 := 'severity_label';
  p_DisplayName_0c2863f3 := 'Severity Label';
  p_Description_0c2863f3 := 'Severity resolved to a name: Critical, High, Medium, Low, Informational or Unknown.';
  p_Type_0c2863f3 := 'String';
  p_AllowsNull_0c2863f3 := TRUE;
  p_IsPrimaryKey_0c2863f3 := FALSE;
  p_IsUniqueKey_0c2863f3 := FALSE;
  p_IsReadOnly_0c2863f3 := TRUE;
  p_IsRequired_0c2863f3 := FALSE;
  p_Sequence_0c2863f3 := 7;
  p_Configuration_0c2863f3 := '{
  "contexts": [
    "view"
  ]
}';
  p_Status_0c2863f3 := 'Active';
  p_IsCustom_0c2863f3 := FALSE;
  p_MetadataSource_0c2863f3 := 'Declared';
  PERFORM __mj."spCreateIntegrationObjectField"(p_ID := p_ID_0c2863f3, p_IntegrationObjectID := p_IntegrationObjectID_0c2863f3, p_Name := p_Name_0c2863f3, p_DisplayName := p_DisplayName_0c2863f3, p_Description := p_Description_0c2863f3, p_Category := p_Category_0c2863f3, p_Category_Clear := TRUE, p_Type := p_Type_0c2863f3, p_Length := p_Length_0c2863f3, p_Length_Clear := TRUE, p_Precision := p_Precision_0c2863f3, p_Precision_Clear := TRUE, p_Scale := p_Scale_0c2863f3, p_Scale_Clear := TRUE, p_AllowsNull := p_AllowsNull_0c2863f3, p_DefaultValue := p_DefaultValue_0c2863f3, p_DefaultValue_Clear := TRUE, p_IsPrimaryKey := p_IsPrimaryKey_0c2863f3, p_IsUniqueKey := p_IsUniqueKey_0c2863f3, p_IsReadOnly := p_IsReadOnly_0c2863f3, p_IsRequired := p_IsRequired_0c2863f3, p_RelatedIntegrationObjectID := p_RelatedIntegrationObjectID_0c2863f3, p_RelatedIntegrationObjectID_Clear := TRUE, p_RelatedIntegrationObjectFieldName := p_RelatedIntegrationObjectFieldName_0c2863f3, p_RelatedIntegrationObjectFieldName_Clear := TRUE, p_Sequence := p_Sequence_0c2863f3, p_Configuration := p_Configuration_0c2863f3, p_Status := p_Status_0c2863f3, p_IsCustom := p_IsCustom_0c2863f3, p_MetadataSource := p_MetadataSource_0c2863f3);
END $mj$;

-- Save MJ: Integration Object Fields (core SP call only)
DO $mj$
DECLARE
  p_ID_40ca04b1 UUID;
  p_IntegrationObjectID_40ca04b1 UUID;
  p_Name_40ca04b1 VARCHAR(255);
  p_DisplayName_40ca04b1 VARCHAR(255);
  p_Description_40ca04b1 TEXT;
  p_Category_40ca04b1 VARCHAR(100);
  p_Type_40ca04b1 VARCHAR(100);
  p_Length_40ca04b1 INTEGER;
  p_Precision_40ca04b1 INTEGER;
  p_Scale_40ca04b1 INTEGER;
  p_AllowsNull_40ca04b1 BOOLEAN;
  p_DefaultValue_40ca04b1 VARCHAR(255);
  p_IsPrimaryKey_40ca04b1 BOOLEAN;
  p_IsUniqueKey_40ca04b1 BOOLEAN;
  p_IsReadOnly_40ca04b1 BOOLEAN;
  p_IsRequired_40ca04b1 BOOLEAN;
  p_RelatedIntegrationObjectID_40ca04b1 UUID;
  p_RelatedIntegrationObjectFieldName_40ca04b1 VARCHAR(255);
  p_Sequence_40ca04b1 INTEGER;
  p_Configuration_40ca04b1 TEXT;
  p_Status_40ca04b1 VARCHAR(25);
  p_IsCustom_40ca04b1 BOOLEAN;
  p_MetadataSource_40ca04b1 VARCHAR(20);
BEGIN
  p_ID_40ca04b1 := 'D2EC5B7F-2495-4087-BCF0-C87347AC9810';
  p_IntegrationObjectID_40ca04b1 := '1B6AAA3C-002C-4E1A-8C82-0900D33FE02A';
  p_Name_40ca04b1 := 'object';
  p_DisplayName_40ca04b1 := 'Object';
  p_Description_40ca04b1 := 'Subject of the activity, e.g. user, post or plugin.';
  p_Type_40ca04b1 := 'String';
  p_AllowsNull_40ca04b1 := TRUE;
  p_IsPrimaryKey_40ca04b1 := FALSE;
  p_IsUniqueKey_40ca04b1 := FALSE;
  p_IsReadOnly_40ca04b1 := TRUE;
  p_IsRequired_40ca04b1 := FALSE;
  p_Sequence_40ca04b1 := 8;
  p_Configuration_40ca04b1 := '{
  "contexts": [
    "view"
  ]
}';
  p_Status_40ca04b1 := 'Active';
  p_IsCustom_40ca04b1 := FALSE;
  p_MetadataSource_40ca04b1 := 'Declared';
  PERFORM __mj."spCreateIntegrationObjectField"(p_ID := p_ID_40ca04b1, p_IntegrationObjectID := p_IntegrationObjectID_40ca04b1, p_Name := p_Name_40ca04b1, p_DisplayName := p_DisplayName_40ca04b1, p_Description := p_Description_40ca04b1, p_Category := p_Category_40ca04b1, p_Category_Clear := TRUE, p_Type := p_Type_40ca04b1, p_Length := p_Length_40ca04b1, p_Length_Clear := TRUE, p_Precision := p_Precision_40ca04b1, p_Precision_Clear := TRUE, p_Scale := p_Scale_40ca04b1, p_Scale_Clear := TRUE, p_AllowsNull := p_AllowsNull_40ca04b1, p_DefaultValue := p_DefaultValue_40ca04b1, p_DefaultValue_Clear := TRUE, p_IsPrimaryKey := p_IsPrimaryKey_40ca04b1, p_IsUniqueKey := p_IsUniqueKey_40ca04b1, p_IsReadOnly := p_IsReadOnly_40ca04b1, p_IsRequired := p_IsRequired_40ca04b1, p_RelatedIntegrationObjectID := p_RelatedIntegrationObjectID_40ca04b1, p_RelatedIntegrationObjectID_Clear := TRUE, p_RelatedIntegrationObjectFieldName := p_RelatedIntegrationObjectFieldName_40ca04b1, p_RelatedIntegrationObjectFieldName_Clear := TRUE, p_Sequence := p_Sequence_40ca04b1, p_Configuration := p_Configuration_40ca04b1, p_Status := p_Status_40ca04b1, p_IsCustom := p_IsCustom_40ca04b1, p_MetadataSource := p_MetadataSource_40ca04b1);
END $mj$;

-- Save MJ: Integration Object Fields (core SP call only)
DO $mj$
DECLARE
  p_ID_9b1aa014 UUID;
  p_IntegrationObjectID_9b1aa014 UUID;
  p_Name_9b1aa014 VARCHAR(255);
  p_DisplayName_9b1aa014 VARCHAR(255);
  p_Description_9b1aa014 TEXT;
  p_Category_9b1aa014 VARCHAR(100);
  p_Type_9b1aa014 VARCHAR(100);
  p_Length_9b1aa014 INTEGER;
  p_Precision_9b1aa014 INTEGER;
  p_Scale_9b1aa014 INTEGER;
  p_AllowsNull_9b1aa014 BOOLEAN;
  p_DefaultValue_9b1aa014 VARCHAR(255);
  p_IsPrimaryKey_9b1aa014 BOOLEAN;
  p_IsUniqueKey_9b1aa014 BOOLEAN;
  p_IsReadOnly_9b1aa014 BOOLEAN;
  p_IsRequired_9b1aa014 BOOLEAN;
  p_RelatedIntegrationObjectID_9b1aa014 UUID;
  p_RelatedIntegrationObjectFieldName_9b1aa014 VARCHAR(255);
  p_Sequence_9b1aa014 INTEGER;
  p_Configuration_9b1aa014 TEXT;
  p_Status_9b1aa014 VARCHAR(25);
  p_IsCustom_9b1aa014 BOOLEAN;
  p_MetadataSource_9b1aa014 VARCHAR(20);
BEGIN
  p_ID_9b1aa014 := 'BA435B7D-340C-4038-8F19-6ED068DCFBF9';
  p_IntegrationObjectID_9b1aa014 := '1B6AAA3C-002C-4E1A-8C82-0900D33FE02A';
  p_Name_9b1aa014 := 'event_type';
  p_DisplayName_9b1aa014 := 'Event Type';
  p_Description_9b1aa014 := 'Classification of the activity, e.g. login, modified or deleted.';
  p_Type_9b1aa014 := 'String';
  p_AllowsNull_9b1aa014 := TRUE;
  p_IsPrimaryKey_9b1aa014 := FALSE;
  p_IsUniqueKey_9b1aa014 := FALSE;
  p_IsReadOnly_9b1aa014 := TRUE;
  p_IsRequired_9b1aa014 := FALSE;
  p_Sequence_9b1aa014 := 9;
  p_Configuration_9b1aa014 := '{
  "contexts": [
    "view"
  ]
}';
  p_Status_9b1aa014 := 'Active';
  p_IsCustom_9b1aa014 := FALSE;
  p_MetadataSource_9b1aa014 := 'Declared';
  PERFORM __mj."spCreateIntegrationObjectField"(p_ID := p_ID_9b1aa014, p_IntegrationObjectID := p_IntegrationObjectID_9b1aa014, p_Name := p_Name_9b1aa014, p_DisplayName := p_DisplayName_9b1aa014, p_Description := p_Description_9b1aa014, p_Category := p_Category_9b1aa014, p_Category_Clear := TRUE, p_Type := p_Type_9b1aa014, p_Length := p_Length_9b1aa014, p_Length_Clear := TRUE, p_Precision := p_Precision_9b1aa014, p_Precision_Clear := TRUE, p_Scale := p_Scale_9b1aa014, p_Scale_Clear := TRUE, p_AllowsNull := p_AllowsNull_9b1aa014, p_DefaultValue := p_DefaultValue_9b1aa014, p_DefaultValue_Clear := TRUE, p_IsPrimaryKey := p_IsPrimaryKey_9b1aa014, p_IsUniqueKey := p_IsUniqueKey_9b1aa014, p_IsReadOnly := p_IsReadOnly_9b1aa014, p_IsRequired := p_IsRequired_9b1aa014, p_RelatedIntegrationObjectID := p_RelatedIntegrationObjectID_9b1aa014, p_RelatedIntegrationObjectID_Clear := TRUE, p_RelatedIntegrationObjectFieldName := p_RelatedIntegrationObjectFieldName_9b1aa014, p_RelatedIntegrationObjectFieldName_Clear := TRUE, p_Sequence := p_Sequence_9b1aa014, p_Configuration := p_Configuration_9b1aa014, p_Status := p_Status_9b1aa014, p_IsCustom := p_IsCustom_9b1aa014, p_MetadataSource := p_MetadataSource_9b1aa014);
END $mj$;

-- Save MJ: Integration Object Fields (core SP call only)
DO $mj$
DECLARE
  p_ID_86a43cc4 UUID;
  p_IntegrationObjectID_86a43cc4 UUID;
  p_Name_86a43cc4 VARCHAR(255);
  p_DisplayName_86a43cc4 VARCHAR(255);
  p_Description_86a43cc4 TEXT;
  p_Category_86a43cc4 VARCHAR(100);
  p_Type_86a43cc4 VARCHAR(100);
  p_Length_86a43cc4 INTEGER;
  p_Precision_86a43cc4 INTEGER;
  p_Scale_86a43cc4 INTEGER;
  p_AllowsNull_86a43cc4 BOOLEAN;
  p_DefaultValue_86a43cc4 VARCHAR(255);
  p_IsPrimaryKey_86a43cc4 BOOLEAN;
  p_IsUniqueKey_86a43cc4 BOOLEAN;
  p_IsReadOnly_86a43cc4 BOOLEAN;
  p_IsRequired_86a43cc4 BOOLEAN;
  p_RelatedIntegrationObjectID_86a43cc4 UUID;
  p_RelatedIntegrationObjectFieldName_86a43cc4 VARCHAR(255);
  p_Sequence_86a43cc4 INTEGER;
  p_Configuration_86a43cc4 TEXT;
  p_Status_86a43cc4 VARCHAR(25);
  p_IsCustom_86a43cc4 BOOLEAN;
  p_MetadataSource_86a43cc4 VARCHAR(20);
BEGIN
  p_ID_86a43cc4 := 'CC4E4400-B43D-4B3D-BCDB-2641E8520389';
  p_IntegrationObjectID_86a43cc4 := '1B6AAA3C-002C-4E1A-8C82-0900D33FE02A';
  p_Name_86a43cc4 := 'username';
  p_DisplayName_86a43cc4 := 'Username';
  p_Description_86a43cc4 := 'WordPress username responsible for the event.';
  p_Type_86a43cc4 := 'String';
  p_AllowsNull_86a43cc4 := TRUE;
  p_IsPrimaryKey_86a43cc4 := FALSE;
  p_IsUniqueKey_86a43cc4 := FALSE;
  p_IsReadOnly_86a43cc4 := TRUE;
  p_IsRequired_86a43cc4 := FALSE;
  p_Sequence_86a43cc4 := 10;
  p_Configuration_86a43cc4 := '{
  "contexts": [
    "view"
  ]
}';
  p_Status_86a43cc4 := 'Active';
  p_IsCustom_86a43cc4 := FALSE;
  p_MetadataSource_86a43cc4 := 'Declared';
  PERFORM __mj."spCreateIntegrationObjectField"(p_ID := p_ID_86a43cc4, p_IntegrationObjectID := p_IntegrationObjectID_86a43cc4, p_Name := p_Name_86a43cc4, p_DisplayName := p_DisplayName_86a43cc4, p_Description := p_Description_86a43cc4, p_Category := p_Category_86a43cc4, p_Category_Clear := TRUE, p_Type := p_Type_86a43cc4, p_Length := p_Length_86a43cc4, p_Length_Clear := TRUE, p_Precision := p_Precision_86a43cc4, p_Precision_Clear := TRUE, p_Scale := p_Scale_86a43cc4, p_Scale_Clear := TRUE, p_AllowsNull := p_AllowsNull_86a43cc4, p_DefaultValue := p_DefaultValue_86a43cc4, p_DefaultValue_Clear := TRUE, p_IsPrimaryKey := p_IsPrimaryKey_86a43cc4, p_IsUniqueKey := p_IsUniqueKey_86a43cc4, p_IsReadOnly := p_IsReadOnly_86a43cc4, p_IsRequired := p_IsRequired_86a43cc4, p_RelatedIntegrationObjectID := p_RelatedIntegrationObjectID_86a43cc4, p_RelatedIntegrationObjectID_Clear := TRUE, p_RelatedIntegrationObjectFieldName := p_RelatedIntegrationObjectFieldName_86a43cc4, p_RelatedIntegrationObjectFieldName_Clear := TRUE, p_Sequence := p_Sequence_86a43cc4, p_Configuration := p_Configuration_86a43cc4, p_Status := p_Status_86a43cc4, p_IsCustom := p_IsCustom_86a43cc4, p_MetadataSource := p_MetadataSource_86a43cc4);
END $mj$;

-- Save MJ: Integration Object Fields (core SP call only)
DO $mj$
DECLARE
  p_ID_d5fee1dc UUID;
  p_IntegrationObjectID_d5fee1dc UUID;
  p_Name_d5fee1dc VARCHAR(255);
  p_DisplayName_d5fee1dc VARCHAR(255);
  p_Description_d5fee1dc TEXT;
  p_Category_d5fee1dc VARCHAR(100);
  p_Type_d5fee1dc VARCHAR(100);
  p_Length_d5fee1dc INTEGER;
  p_Precision_d5fee1dc INTEGER;
  p_Scale_d5fee1dc INTEGER;
  p_AllowsNull_d5fee1dc BOOLEAN;
  p_DefaultValue_d5fee1dc VARCHAR(255);
  p_IsPrimaryKey_d5fee1dc BOOLEAN;
  p_IsUniqueKey_d5fee1dc BOOLEAN;
  p_IsReadOnly_d5fee1dc BOOLEAN;
  p_IsRequired_d5fee1dc BOOLEAN;
  p_RelatedIntegrationObjectID_d5fee1dc UUID;
  p_RelatedIntegrationObjectFieldName_d5fee1dc VARCHAR(255);
  p_Sequence_d5fee1dc INTEGER;
  p_Configuration_d5fee1dc TEXT;
  p_Status_d5fee1dc VARCHAR(25);
  p_IsCustom_d5fee1dc BOOLEAN;
  p_MetadataSource_d5fee1dc VARCHAR(20);
BEGIN
  p_ID_d5fee1dc := '3D14316E-4350-415D-AF2C-642545D2E304';
  p_IntegrationObjectID_d5fee1dc := '1B6AAA3C-002C-4E1A-8C82-0900D33FE02A';
  p_Name_d5fee1dc := 'user_id';
  p_DisplayName_d5fee1dc := 'User ID';
  p_Description_d5fee1dc := 'WordPress user ID responsible for the event; null for anonymous events.';
  p_Type_d5fee1dc := 'Integer';
  p_AllowsNull_d5fee1dc := TRUE;
  p_IsPrimaryKey_d5fee1dc := FALSE;
  p_IsUniqueKey_d5fee1dc := FALSE;
  p_IsReadOnly_d5fee1dc := TRUE;
  p_IsRequired_d5fee1dc := FALSE;
  p_Sequence_d5fee1dc := 11;
  p_Configuration_d5fee1dc := '{
  "contexts": [
    "view"
  ]
}';
  p_Status_d5fee1dc := 'Active';
  p_IsCustom_d5fee1dc := FALSE;
  p_MetadataSource_d5fee1dc := 'Declared';
  PERFORM __mj."spCreateIntegrationObjectField"(p_ID := p_ID_d5fee1dc, p_IntegrationObjectID := p_IntegrationObjectID_d5fee1dc, p_Name := p_Name_d5fee1dc, p_DisplayName := p_DisplayName_d5fee1dc, p_Description := p_Description_d5fee1dc, p_Category := p_Category_d5fee1dc, p_Category_Clear := TRUE, p_Type := p_Type_d5fee1dc, p_Length := p_Length_d5fee1dc, p_Length_Clear := TRUE, p_Precision := p_Precision_d5fee1dc, p_Precision_Clear := TRUE, p_Scale := p_Scale_d5fee1dc, p_Scale_Clear := TRUE, p_AllowsNull := p_AllowsNull_d5fee1dc, p_DefaultValue := p_DefaultValue_d5fee1dc, p_DefaultValue_Clear := TRUE, p_IsPrimaryKey := p_IsPrimaryKey_d5fee1dc, p_IsUniqueKey := p_IsUniqueKey_d5fee1dc, p_IsReadOnly := p_IsReadOnly_d5fee1dc, p_IsRequired := p_IsRequired_d5fee1dc, p_RelatedIntegrationObjectID := p_RelatedIntegrationObjectID_d5fee1dc, p_RelatedIntegrationObjectID_Clear := TRUE, p_RelatedIntegrationObjectFieldName := p_RelatedIntegrationObjectFieldName_d5fee1dc, p_RelatedIntegrationObjectFieldName_Clear := TRUE, p_Sequence := p_Sequence_d5fee1dc, p_Configuration := p_Configuration_d5fee1dc, p_Status := p_Status_d5fee1dc, p_IsCustom := p_IsCustom_d5fee1dc, p_MetadataSource := p_MetadataSource_d5fee1dc);
END $mj$;

-- Save MJ: Integration Object Fields (core SP call only)
DO $mj$
DECLARE
  p_ID_015a44f9 UUID;
  p_IntegrationObjectID_015a44f9 UUID;
  p_Name_015a44f9 VARCHAR(255);
  p_DisplayName_015a44f9 VARCHAR(255);
  p_Description_015a44f9 TEXT;
  p_Category_015a44f9 VARCHAR(100);
  p_Type_015a44f9 VARCHAR(100);
  p_Length_015a44f9 INTEGER;
  p_Precision_015a44f9 INTEGER;
  p_Scale_015a44f9 INTEGER;
  p_AllowsNull_015a44f9 BOOLEAN;
  p_DefaultValue_015a44f9 VARCHAR(255);
  p_IsPrimaryKey_015a44f9 BOOLEAN;
  p_IsUniqueKey_015a44f9 BOOLEAN;
  p_IsReadOnly_015a44f9 BOOLEAN;
  p_IsRequired_015a44f9 BOOLEAN;
  p_RelatedIntegrationObjectID_015a44f9 UUID;
  p_RelatedIntegrationObjectFieldName_015a44f9 VARCHAR(255);
  p_Sequence_015a44f9 INTEGER;
  p_Configuration_015a44f9 TEXT;
  p_Status_015a44f9 VARCHAR(25);
  p_IsCustom_015a44f9 BOOLEAN;
  p_MetadataSource_015a44f9 VARCHAR(20);
BEGIN
  p_ID_015a44f9 := '48A99EF2-4665-4BD7-959B-306C65BF5930';
  p_IntegrationObjectID_015a44f9 := '1B6AAA3C-002C-4E1A-8C82-0900D33FE02A';
  p_Name_015a44f9 := 'user_roles';
  p_DisplayName_015a44f9 := 'User Roles';
  p_Description_015a44f9 := 'Roles held by the user at the time of the event.';
  p_Type_015a44f9 := 'String';
  p_AllowsNull_015a44f9 := TRUE;
  p_IsPrimaryKey_015a44f9 := FALSE;
  p_IsUniqueKey_015a44f9 := FALSE;
  p_IsReadOnly_015a44f9 := TRUE;
  p_IsRequired_015a44f9 := FALSE;
  p_Sequence_015a44f9 := 12;
  p_Configuration_015a44f9 := '{
  "contexts": [
    "view"
  ]
}';
  p_Status_015a44f9 := 'Active';
  p_IsCustom_015a44f9 := FALSE;
  p_MetadataSource_015a44f9 := 'Declared';
  PERFORM __mj."spCreateIntegrationObjectField"(p_ID := p_ID_015a44f9, p_IntegrationObjectID := p_IntegrationObjectID_015a44f9, p_Name := p_Name_015a44f9, p_DisplayName := p_DisplayName_015a44f9, p_Description := p_Description_015a44f9, p_Category := p_Category_015a44f9, p_Category_Clear := TRUE, p_Type := p_Type_015a44f9, p_Length := p_Length_015a44f9, p_Length_Clear := TRUE, p_Precision := p_Precision_015a44f9, p_Precision_Clear := TRUE, p_Scale := p_Scale_015a44f9, p_Scale_Clear := TRUE, p_AllowsNull := p_AllowsNull_015a44f9, p_DefaultValue := p_DefaultValue_015a44f9, p_DefaultValue_Clear := TRUE, p_IsPrimaryKey := p_IsPrimaryKey_015a44f9, p_IsUniqueKey := p_IsUniqueKey_015a44f9, p_IsReadOnly := p_IsReadOnly_015a44f9, p_IsRequired := p_IsRequired_015a44f9, p_RelatedIntegrationObjectID := p_RelatedIntegrationObjectID_015a44f9, p_RelatedIntegrationObjectID_Clear := TRUE, p_RelatedIntegrationObjectFieldName := p_RelatedIntegrationObjectFieldName_015a44f9, p_RelatedIntegrationObjectFieldName_Clear := TRUE, p_Sequence := p_Sequence_015a44f9, p_Configuration := p_Configuration_015a44f9, p_Status := p_Status_015a44f9, p_IsCustom := p_IsCustom_015a44f9, p_MetadataSource := p_MetadataSource_015a44f9);
END $mj$;

-- Save MJ: Integration Object Fields (core SP call only)
DO $mj$
DECLARE
  p_ID_509d216f UUID;
  p_IntegrationObjectID_509d216f UUID;
  p_Name_509d216f VARCHAR(255);
  p_DisplayName_509d216f VARCHAR(255);
  p_Description_509d216f TEXT;
  p_Category_509d216f VARCHAR(100);
  p_Type_509d216f VARCHAR(100);
  p_Length_509d216f INTEGER;
  p_Precision_509d216f INTEGER;
  p_Scale_509d216f INTEGER;
  p_AllowsNull_509d216f BOOLEAN;
  p_DefaultValue_509d216f VARCHAR(255);
  p_IsPrimaryKey_509d216f BOOLEAN;
  p_IsUniqueKey_509d216f BOOLEAN;
  p_IsReadOnly_509d216f BOOLEAN;
  p_IsRequired_509d216f BOOLEAN;
  p_RelatedIntegrationObjectID_509d216f UUID;
  p_RelatedIntegrationObjectFieldName_509d216f VARCHAR(255);
  p_Sequence_509d216f INTEGER;
  p_Configuration_509d216f TEXT;
  p_Status_509d216f VARCHAR(25);
  p_IsCustom_509d216f BOOLEAN;
  p_MetadataSource_509d216f VARCHAR(20);
BEGIN
  p_ID_509d216f := '01B518B3-7AF1-4D8F-B63B-307AACDB82F4';
  p_IntegrationObjectID_509d216f := '1B6AAA3C-002C-4E1A-8C82-0900D33FE02A';
  p_Name_509d216f := 'client_ip';
  p_DisplayName_509d216f := 'Client IP';
  p_Description_509d216f := 'Source IP address the activity originated from.';
  p_Type_509d216f := 'String';
  p_AllowsNull_509d216f := TRUE;
  p_IsPrimaryKey_509d216f := FALSE;
  p_IsUniqueKey_509d216f := FALSE;
  p_IsReadOnly_509d216f := TRUE;
  p_IsRequired_509d216f := FALSE;
  p_Sequence_509d216f := 13;
  p_Configuration_509d216f := '{
  "contexts": [
    "view"
  ]
}';
  p_Status_509d216f := 'Active';
  p_IsCustom_509d216f := FALSE;
  p_MetadataSource_509d216f := 'Declared';
  PERFORM __mj."spCreateIntegrationObjectField"(p_ID := p_ID_509d216f, p_IntegrationObjectID := p_IntegrationObjectID_509d216f, p_Name := p_Name_509d216f, p_DisplayName := p_DisplayName_509d216f, p_Description := p_Description_509d216f, p_Category := p_Category_509d216f, p_Category_Clear := TRUE, p_Type := p_Type_509d216f, p_Length := p_Length_509d216f, p_Length_Clear := TRUE, p_Precision := p_Precision_509d216f, p_Precision_Clear := TRUE, p_Scale := p_Scale_509d216f, p_Scale_Clear := TRUE, p_AllowsNull := p_AllowsNull_509d216f, p_DefaultValue := p_DefaultValue_509d216f, p_DefaultValue_Clear := TRUE, p_IsPrimaryKey := p_IsPrimaryKey_509d216f, p_IsUniqueKey := p_IsUniqueKey_509d216f, p_IsReadOnly := p_IsReadOnly_509d216f, p_IsRequired := p_IsRequired_509d216f, p_RelatedIntegrationObjectID := p_RelatedIntegrationObjectID_509d216f, p_RelatedIntegrationObjectID_Clear := TRUE, p_RelatedIntegrationObjectFieldName := p_RelatedIntegrationObjectFieldName_509d216f, p_RelatedIntegrationObjectFieldName_Clear := TRUE, p_Sequence := p_Sequence_509d216f, p_Configuration := p_Configuration_509d216f, p_Status := p_Status_509d216f, p_IsCustom := p_IsCustom_509d216f, p_MetadataSource := p_MetadataSource_509d216f);
END $mj$;

-- Save MJ: Integration Object Fields (core SP call only)
DO $mj$
DECLARE
  p_ID_80d3faa8 UUID;
  p_IntegrationObjectID_80d3faa8 UUID;
  p_Name_80d3faa8 VARCHAR(255);
  p_DisplayName_80d3faa8 VARCHAR(255);
  p_Description_80d3faa8 TEXT;
  p_Category_80d3faa8 VARCHAR(100);
  p_Type_80d3faa8 VARCHAR(100);
  p_Length_80d3faa8 INTEGER;
  p_Precision_80d3faa8 INTEGER;
  p_Scale_80d3faa8 INTEGER;
  p_AllowsNull_80d3faa8 BOOLEAN;
  p_DefaultValue_80d3faa8 VARCHAR(255);
  p_IsPrimaryKey_80d3faa8 BOOLEAN;
  p_IsUniqueKey_80d3faa8 BOOLEAN;
  p_IsReadOnly_80d3faa8 BOOLEAN;
  p_IsRequired_80d3faa8 BOOLEAN;
  p_RelatedIntegrationObjectID_80d3faa8 UUID;
  p_RelatedIntegrationObjectFieldName_80d3faa8 VARCHAR(255);
  p_Sequence_80d3faa8 INTEGER;
  p_Configuration_80d3faa8 TEXT;
  p_Status_80d3faa8 VARCHAR(25);
  p_IsCustom_80d3faa8 BOOLEAN;
  p_MetadataSource_80d3faa8 VARCHAR(20);
BEGIN
  p_ID_80d3faa8 := 'A5D041C3-A044-452C-84CC-B2F154DFE48E';
  p_IntegrationObjectID_80d3faa8 := '1B6AAA3C-002C-4E1A-8C82-0900D33FE02A';
  p_Name_80d3faa8 := 'user_agent';
  p_DisplayName_80d3faa8 := 'User Agent';
  p_Description_80d3faa8 := 'Browser user agent string captured with the event.';
  p_Type_80d3faa8 := 'String';
  p_AllowsNull_80d3faa8 := TRUE;
  p_IsPrimaryKey_80d3faa8 := FALSE;
  p_IsUniqueKey_80d3faa8 := FALSE;
  p_IsReadOnly_80d3faa8 := TRUE;
  p_IsRequired_80d3faa8 := FALSE;
  p_Sequence_80d3faa8 := 14;
  p_Configuration_80d3faa8 := '{
  "contexts": [
    "view"
  ]
}';
  p_Status_80d3faa8 := 'Active';
  p_IsCustom_80d3faa8 := FALSE;
  p_MetadataSource_80d3faa8 := 'Declared';
  PERFORM __mj."spCreateIntegrationObjectField"(p_ID := p_ID_80d3faa8, p_IntegrationObjectID := p_IntegrationObjectID_80d3faa8, p_Name := p_Name_80d3faa8, p_DisplayName := p_DisplayName_80d3faa8, p_Description := p_Description_80d3faa8, p_Category := p_Category_80d3faa8, p_Category_Clear := TRUE, p_Type := p_Type_80d3faa8, p_Length := p_Length_80d3faa8, p_Length_Clear := TRUE, p_Precision := p_Precision_80d3faa8, p_Precision_Clear := TRUE, p_Scale := p_Scale_80d3faa8, p_Scale_Clear := TRUE, p_AllowsNull := p_AllowsNull_80d3faa8, p_DefaultValue := p_DefaultValue_80d3faa8, p_DefaultValue_Clear := TRUE, p_IsPrimaryKey := p_IsPrimaryKey_80d3faa8, p_IsUniqueKey := p_IsUniqueKey_80d3faa8, p_IsReadOnly := p_IsReadOnly_80d3faa8, p_IsRequired := p_IsRequired_80d3faa8, p_RelatedIntegrationObjectID := p_RelatedIntegrationObjectID_80d3faa8, p_RelatedIntegrationObjectID_Clear := TRUE, p_RelatedIntegrationObjectFieldName := p_RelatedIntegrationObjectFieldName_80d3faa8, p_RelatedIntegrationObjectFieldName_Clear := TRUE, p_Sequence := p_Sequence_80d3faa8, p_Configuration := p_Configuration_80d3faa8, p_Status := p_Status_80d3faa8, p_IsCustom := p_IsCustom_80d3faa8, p_MetadataSource := p_MetadataSource_80d3faa8);
END $mj$;

-- Save MJ: Integration Object Fields (core SP call only)
DO $mj$
DECLARE
  p_ID_812ba870 UUID;
  p_IntegrationObjectID_812ba870 UUID;
  p_Name_812ba870 VARCHAR(255);
  p_DisplayName_812ba870 VARCHAR(255);
  p_Description_812ba870 TEXT;
  p_Category_812ba870 VARCHAR(100);
  p_Type_812ba870 VARCHAR(100);
  p_Length_812ba870 INTEGER;
  p_Precision_812ba870 INTEGER;
  p_Scale_812ba870 INTEGER;
  p_AllowsNull_812ba870 BOOLEAN;
  p_DefaultValue_812ba870 VARCHAR(255);
  p_IsPrimaryKey_812ba870 BOOLEAN;
  p_IsUniqueKey_812ba870 BOOLEAN;
  p_IsReadOnly_812ba870 BOOLEAN;
  p_IsRequired_812ba870 BOOLEAN;
  p_RelatedIntegrationObjectID_812ba870 UUID;
  p_RelatedIntegrationObjectFieldName_812ba870 VARCHAR(255);
  p_Sequence_812ba870 INTEGER;
  p_Configuration_812ba870 TEXT;
  p_Status_812ba870 VARCHAR(25);
  p_IsCustom_812ba870 BOOLEAN;
  p_MetadataSource_812ba870 VARCHAR(20);
BEGIN
  p_ID_812ba870 := '1B9E12A3-4CA9-4C0F-96DE-F05D3CE76416';
  p_IntegrationObjectID_812ba870 := '1B6AAA3C-002C-4E1A-8C82-0900D33FE02A';
  p_Name_812ba870 := 'session_id';
  p_DisplayName_812ba870 := 'Session ID';
  p_Description_812ba870 := 'Identifier of the session the event belongs to.';
  p_Type_812ba870 := 'String';
  p_AllowsNull_812ba870 := TRUE;
  p_IsPrimaryKey_812ba870 := FALSE;
  p_IsUniqueKey_812ba870 := FALSE;
  p_IsReadOnly_812ba870 := TRUE;
  p_IsRequired_812ba870 := FALSE;
  p_Sequence_812ba870 := 15;
  p_Configuration_812ba870 := '{
  "contexts": [
    "view"
  ]
}';
  p_Status_812ba870 := 'Active';
  p_IsCustom_812ba870 := FALSE;
  p_MetadataSource_812ba870 := 'Declared';
  PERFORM __mj."spCreateIntegrationObjectField"(p_ID := p_ID_812ba870, p_IntegrationObjectID := p_IntegrationObjectID_812ba870, p_Name := p_Name_812ba870, p_DisplayName := p_DisplayName_812ba870, p_Description := p_Description_812ba870, p_Category := p_Category_812ba870, p_Category_Clear := TRUE, p_Type := p_Type_812ba870, p_Length := p_Length_812ba870, p_Length_Clear := TRUE, p_Precision := p_Precision_812ba870, p_Precision_Clear := TRUE, p_Scale := p_Scale_812ba870, p_Scale_Clear := TRUE, p_AllowsNull := p_AllowsNull_812ba870, p_DefaultValue := p_DefaultValue_812ba870, p_DefaultValue_Clear := TRUE, p_IsPrimaryKey := p_IsPrimaryKey_812ba870, p_IsUniqueKey := p_IsUniqueKey_812ba870, p_IsReadOnly := p_IsReadOnly_812ba870, p_IsRequired := p_IsRequired_812ba870, p_RelatedIntegrationObjectID := p_RelatedIntegrationObjectID_812ba870, p_RelatedIntegrationObjectID_Clear := TRUE, p_RelatedIntegrationObjectFieldName := p_RelatedIntegrationObjectFieldName_812ba870, p_RelatedIntegrationObjectFieldName_Clear := TRUE, p_Sequence := p_Sequence_812ba870, p_Configuration := p_Configuration_812ba870, p_Status := p_Status_812ba870, p_IsCustom := p_IsCustom_812ba870, p_MetadataSource := p_MetadataSource_812ba870);
END $mj$;

-- Save MJ: Integration Object Fields (core SP call only)
DO $mj$
DECLARE
  p_ID_39eb628d UUID;
  p_IntegrationObjectID_39eb628d UUID;
  p_Name_39eb628d VARCHAR(255);
  p_DisplayName_39eb628d VARCHAR(255);
  p_Description_39eb628d TEXT;
  p_Category_39eb628d VARCHAR(100);
  p_Type_39eb628d VARCHAR(100);
  p_Length_39eb628d INTEGER;
  p_Precision_39eb628d INTEGER;
  p_Scale_39eb628d INTEGER;
  p_AllowsNull_39eb628d BOOLEAN;
  p_DefaultValue_39eb628d VARCHAR(255);
  p_IsPrimaryKey_39eb628d BOOLEAN;
  p_IsUniqueKey_39eb628d BOOLEAN;
  p_IsReadOnly_39eb628d BOOLEAN;
  p_IsRequired_39eb628d BOOLEAN;
  p_RelatedIntegrationObjectID_39eb628d UUID;
  p_RelatedIntegrationObjectFieldName_39eb628d VARCHAR(255);
  p_Sequence_39eb628d INTEGER;
  p_Configuration_39eb628d TEXT;
  p_Status_39eb628d VARCHAR(25);
  p_IsCustom_39eb628d BOOLEAN;
  p_MetadataSource_39eb628d VARCHAR(20);
BEGIN
  p_ID_39eb628d := 'DB762596-31DF-4A51-B278-D40558D5AAF5';
  p_IntegrationObjectID_39eb628d := '1B6AAA3C-002C-4E1A-8C82-0900D33FE02A';
  p_Name_39eb628d := 'post_id';
  p_DisplayName_39eb628d := 'Post ID';
  p_Description_39eb628d := 'Associated post ID; 0 when the event is not post-related.';
  p_Type_39eb628d := 'Integer';
  p_AllowsNull_39eb628d := TRUE;
  p_IsPrimaryKey_39eb628d := FALSE;
  p_IsUniqueKey_39eb628d := FALSE;
  p_IsReadOnly_39eb628d := TRUE;
  p_IsRequired_39eb628d := FALSE;
  p_Sequence_39eb628d := 16;
  p_Configuration_39eb628d := '{
  "contexts": [
    "view"
  ]
}';
  p_Status_39eb628d := 'Active';
  p_IsCustom_39eb628d := FALSE;
  p_MetadataSource_39eb628d := 'Declared';
  PERFORM __mj."spCreateIntegrationObjectField"(p_ID := p_ID_39eb628d, p_IntegrationObjectID := p_IntegrationObjectID_39eb628d, p_Name := p_Name_39eb628d, p_DisplayName := p_DisplayName_39eb628d, p_Description := p_Description_39eb628d, p_Category := p_Category_39eb628d, p_Category_Clear := TRUE, p_Type := p_Type_39eb628d, p_Length := p_Length_39eb628d, p_Length_Clear := TRUE, p_Precision := p_Precision_39eb628d, p_Precision_Clear := TRUE, p_Scale := p_Scale_39eb628d, p_Scale_Clear := TRUE, p_AllowsNull := p_AllowsNull_39eb628d, p_DefaultValue := p_DefaultValue_39eb628d, p_DefaultValue_Clear := TRUE, p_IsPrimaryKey := p_IsPrimaryKey_39eb628d, p_IsUniqueKey := p_IsUniqueKey_39eb628d, p_IsReadOnly := p_IsReadOnly_39eb628d, p_IsRequired := p_IsRequired_39eb628d, p_RelatedIntegrationObjectID := p_RelatedIntegrationObjectID_39eb628d, p_RelatedIntegrationObjectID_Clear := TRUE, p_RelatedIntegrationObjectFieldName := p_RelatedIntegrationObjectFieldName_39eb628d, p_RelatedIntegrationObjectFieldName_Clear := TRUE, p_Sequence := p_Sequence_39eb628d, p_Configuration := p_Configuration_39eb628d, p_Status := p_Status_39eb628d, p_IsCustom := p_IsCustom_39eb628d, p_MetadataSource := p_MetadataSource_39eb628d);
END $mj$;

-- Save MJ: Integration Object Fields (core SP call only)
DO $mj$
DECLARE
  p_ID_5fe93507 UUID;
  p_IntegrationObjectID_5fe93507 UUID;
  p_Name_5fe93507 VARCHAR(255);
  p_DisplayName_5fe93507 VARCHAR(255);
  p_Description_5fe93507 TEXT;
  p_Category_5fe93507 VARCHAR(100);
  p_Type_5fe93507 VARCHAR(100);
  p_Length_5fe93507 INTEGER;
  p_Precision_5fe93507 INTEGER;
  p_Scale_5fe93507 INTEGER;
  p_AllowsNull_5fe93507 BOOLEAN;
  p_DefaultValue_5fe93507 VARCHAR(255);
  p_IsPrimaryKey_5fe93507 BOOLEAN;
  p_IsUniqueKey_5fe93507 BOOLEAN;
  p_IsReadOnly_5fe93507 BOOLEAN;
  p_IsRequired_5fe93507 BOOLEAN;
  p_RelatedIntegrationObjectID_5fe93507 UUID;
  p_RelatedIntegrationObjectFieldName_5fe93507 VARCHAR(255);
  p_Sequence_5fe93507 INTEGER;
  p_Configuration_5fe93507 TEXT;
  p_Status_5fe93507 VARCHAR(25);
  p_IsCustom_5fe93507 BOOLEAN;
  p_MetadataSource_5fe93507 VARCHAR(20);
BEGIN
  p_ID_5fe93507 := '052C5B24-F6C0-467E-B72A-D8AABB23E417';
  p_IntegrationObjectID_5fe93507 := '1B6AAA3C-002C-4E1A-8C82-0900D33FE02A';
  p_Name_5fe93507 := 'post_type';
  p_DisplayName_5fe93507 := 'Post Type';
  p_Description_5fe93507 := 'Associated post type.';
  p_Type_5fe93507 := 'String';
  p_AllowsNull_5fe93507 := TRUE;
  p_IsPrimaryKey_5fe93507 := FALSE;
  p_IsUniqueKey_5fe93507 := FALSE;
  p_IsReadOnly_5fe93507 := TRUE;
  p_IsRequired_5fe93507 := FALSE;
  p_Sequence_5fe93507 := 17;
  p_Configuration_5fe93507 := '{
  "contexts": [
    "view"
  ]
}';
  p_Status_5fe93507 := 'Active';
  p_IsCustom_5fe93507 := FALSE;
  p_MetadataSource_5fe93507 := 'Declared';
  PERFORM __mj."spCreateIntegrationObjectField"(p_ID := p_ID_5fe93507, p_IntegrationObjectID := p_IntegrationObjectID_5fe93507, p_Name := p_Name_5fe93507, p_DisplayName := p_DisplayName_5fe93507, p_Description := p_Description_5fe93507, p_Category := p_Category_5fe93507, p_Category_Clear := TRUE, p_Type := p_Type_5fe93507, p_Length := p_Length_5fe93507, p_Length_Clear := TRUE, p_Precision := p_Precision_5fe93507, p_Precision_Clear := TRUE, p_Scale := p_Scale_5fe93507, p_Scale_Clear := TRUE, p_AllowsNull := p_AllowsNull_5fe93507, p_DefaultValue := p_DefaultValue_5fe93507, p_DefaultValue_Clear := TRUE, p_IsPrimaryKey := p_IsPrimaryKey_5fe93507, p_IsUniqueKey := p_IsUniqueKey_5fe93507, p_IsReadOnly := p_IsReadOnly_5fe93507, p_IsRequired := p_IsRequired_5fe93507, p_RelatedIntegrationObjectID := p_RelatedIntegrationObjectID_5fe93507, p_RelatedIntegrationObjectID_Clear := TRUE, p_RelatedIntegrationObjectFieldName := p_RelatedIntegrationObjectFieldName_5fe93507, p_RelatedIntegrationObjectFieldName_Clear := TRUE, p_Sequence := p_Sequence_5fe93507, p_Configuration := p_Configuration_5fe93507, p_Status := p_Status_5fe93507, p_IsCustom := p_IsCustom_5fe93507, p_MetadataSource := p_MetadataSource_5fe93507);
END $mj$;

-- Save MJ: Integration Object Fields (core SP call only)
DO $mj$
DECLARE
  p_ID_3faa397d UUID;
  p_IntegrationObjectID_3faa397d UUID;
  p_Name_3faa397d VARCHAR(255);
  p_DisplayName_3faa397d VARCHAR(255);
  p_Description_3faa397d TEXT;
  p_Category_3faa397d VARCHAR(100);
  p_Type_3faa397d VARCHAR(100);
  p_Length_3faa397d INTEGER;
  p_Precision_3faa397d INTEGER;
  p_Scale_3faa397d INTEGER;
  p_AllowsNull_3faa397d BOOLEAN;
  p_DefaultValue_3faa397d VARCHAR(255);
  p_IsPrimaryKey_3faa397d BOOLEAN;
  p_IsUniqueKey_3faa397d BOOLEAN;
  p_IsReadOnly_3faa397d BOOLEAN;
  p_IsRequired_3faa397d BOOLEAN;
  p_RelatedIntegrationObjectID_3faa397d UUID;
  p_RelatedIntegrationObjectFieldName_3faa397d VARCHAR(255);
  p_Sequence_3faa397d INTEGER;
  p_Configuration_3faa397d TEXT;
  p_Status_3faa397d VARCHAR(25);
  p_IsCustom_3faa397d BOOLEAN;
  p_MetadataSource_3faa397d VARCHAR(20);
BEGIN
  p_ID_3faa397d := '811C26A6-C1FA-47B3-8B73-B403D591D21A';
  p_IntegrationObjectID_3faa397d := '1B6AAA3C-002C-4E1A-8C82-0900D33FE02A';
  p_Name_3faa397d := 'post_status';
  p_DisplayName_3faa397d := 'Post Status';
  p_Description_3faa397d := 'Associated post status at the time of the event.';
  p_Type_3faa397d := 'String';
  p_AllowsNull_3faa397d := TRUE;
  p_IsPrimaryKey_3faa397d := FALSE;
  p_IsUniqueKey_3faa397d := FALSE;
  p_IsReadOnly_3faa397d := TRUE;
  p_IsRequired_3faa397d := FALSE;
  p_Sequence_3faa397d := 18;
  p_Configuration_3faa397d := '{
  "contexts": [
    "view"
  ]
}';
  p_Status_3faa397d := 'Active';
  p_IsCustom_3faa397d := FALSE;
  p_MetadataSource_3faa397d := 'Declared';
  PERFORM __mj."spCreateIntegrationObjectField"(p_ID := p_ID_3faa397d, p_IntegrationObjectID := p_IntegrationObjectID_3faa397d, p_Name := p_Name_3faa397d, p_DisplayName := p_DisplayName_3faa397d, p_Description := p_Description_3faa397d, p_Category := p_Category_3faa397d, p_Category_Clear := TRUE, p_Type := p_Type_3faa397d, p_Length := p_Length_3faa397d, p_Length_Clear := TRUE, p_Precision := p_Precision_3faa397d, p_Precision_Clear := TRUE, p_Scale := p_Scale_3faa397d, p_Scale_Clear := TRUE, p_AllowsNull := p_AllowsNull_3faa397d, p_DefaultValue := p_DefaultValue_3faa397d, p_DefaultValue_Clear := TRUE, p_IsPrimaryKey := p_IsPrimaryKey_3faa397d, p_IsUniqueKey := p_IsUniqueKey_3faa397d, p_IsReadOnly := p_IsReadOnly_3faa397d, p_IsRequired := p_IsRequired_3faa397d, p_RelatedIntegrationObjectID := p_RelatedIntegrationObjectID_3faa397d, p_RelatedIntegrationObjectID_Clear := TRUE, p_RelatedIntegrationObjectFieldName := p_RelatedIntegrationObjectFieldName_3faa397d, p_RelatedIntegrationObjectFieldName_Clear := TRUE, p_Sequence := p_Sequence_3faa397d, p_Configuration := p_Configuration_3faa397d, p_Status := p_Status_3faa397d, p_IsCustom := p_IsCustom_3faa397d, p_MetadataSource := p_MetadataSource_3faa397d);
END $mj$;

-- Save MJ: Integration Object Fields (core SP call only)
DO $mj$
DECLARE
  p_ID_d03bf348 UUID;
  p_IntegrationObjectID_d03bf348 UUID;
  p_Name_d03bf348 VARCHAR(255);
  p_DisplayName_d03bf348 VARCHAR(255);
  p_Description_d03bf348 TEXT;
  p_Category_d03bf348 VARCHAR(100);
  p_Type_d03bf348 VARCHAR(100);
  p_Length_d03bf348 INTEGER;
  p_Precision_d03bf348 INTEGER;
  p_Scale_d03bf348 INTEGER;
  p_AllowsNull_d03bf348 BOOLEAN;
  p_DefaultValue_d03bf348 VARCHAR(255);
  p_IsPrimaryKey_d03bf348 BOOLEAN;
  p_IsUniqueKey_d03bf348 BOOLEAN;
  p_IsReadOnly_d03bf348 BOOLEAN;
  p_IsRequired_d03bf348 BOOLEAN;
  p_RelatedIntegrationObjectID_d03bf348 UUID;
  p_RelatedIntegrationObjectFieldName_d03bf348 VARCHAR(255);
  p_Sequence_d03bf348 INTEGER;
  p_Configuration_d03bf348 TEXT;
  p_Status_d03bf348 VARCHAR(25);
  p_IsCustom_d03bf348 BOOLEAN;
  p_MetadataSource_d03bf348 VARCHAR(20);
BEGIN
  p_ID_d03bf348 := '857AC7AC-23F2-4F29-BC8A-8EA45F7A0BD7';
  p_IntegrationObjectID_d03bf348 := '1B6AAA3C-002C-4E1A-8C82-0900D33FE02A';
  p_Name_d03bf348 := 'meta';
  p_DisplayName_d03bf348 := 'Metadata';
  p_Description_d03bf348 := 'Event metadata pivoted from the plugin name/value table into a single object. Keys vary by event type.';
  p_Type_d03bf348 := 'json';
  p_AllowsNull_d03bf348 := TRUE;
  p_IsPrimaryKey_d03bf348 := FALSE;
  p_IsUniqueKey_d03bf348 := FALSE;
  p_IsReadOnly_d03bf348 := TRUE;
  p_IsRequired_d03bf348 := FALSE;
  p_Sequence_d03bf348 := 19;
  p_Configuration_d03bf348 := '{
  "contexts": [
    "view"
  ]
}';
  p_Status_d03bf348 := 'Active';
  p_IsCustom_d03bf348 := FALSE;
  p_MetadataSource_d03bf348 := 'Declared';
  PERFORM __mj."spCreateIntegrationObjectField"(p_ID := p_ID_d03bf348, p_IntegrationObjectID := p_IntegrationObjectID_d03bf348, p_Name := p_Name_d03bf348, p_DisplayName := p_DisplayName_d03bf348, p_Description := p_Description_d03bf348, p_Category := p_Category_d03bf348, p_Category_Clear := TRUE, p_Type := p_Type_d03bf348, p_Length := p_Length_d03bf348, p_Length_Clear := TRUE, p_Precision := p_Precision_d03bf348, p_Precision_Clear := TRUE, p_Scale := p_Scale_d03bf348, p_Scale_Clear := TRUE, p_AllowsNull := p_AllowsNull_d03bf348, p_DefaultValue := p_DefaultValue_d03bf348, p_DefaultValue_Clear := TRUE, p_IsPrimaryKey := p_IsPrimaryKey_d03bf348, p_IsUniqueKey := p_IsUniqueKey_d03bf348, p_IsReadOnly := p_IsReadOnly_d03bf348, p_IsRequired := p_IsRequired_d03bf348, p_RelatedIntegrationObjectID := p_RelatedIntegrationObjectID_d03bf348, p_RelatedIntegrationObjectID_Clear := TRUE, p_RelatedIntegrationObjectFieldName := p_RelatedIntegrationObjectFieldName_d03bf348, p_RelatedIntegrationObjectFieldName_Clear := TRUE, p_Sequence := p_Sequence_d03bf348, p_Configuration := p_Configuration_d03bf348, p_Status := p_Status_d03bf348, p_IsCustom := p_IsCustom_d03bf348, p_MetadataSource := p_MetadataSource_d03bf348);
END $mj$;

-- Save MJ: Integration Object Fields (core SP call only)
DO $mj$
DECLARE
  p_ID_eceb899b UUID;
  p_IntegrationObjectID_eceb899b UUID;
  p_Name_eceb899b VARCHAR(255);
  p_DisplayName_eceb899b VARCHAR(255);
  p_Description_eceb899b TEXT;
  p_Category_eceb899b VARCHAR(100);
  p_Type_eceb899b VARCHAR(100);
  p_Length_eceb899b INTEGER;
  p_Precision_eceb899b INTEGER;
  p_Scale_eceb899b INTEGER;
  p_AllowsNull_eceb899b BOOLEAN;
  p_DefaultValue_eceb899b VARCHAR(255);
  p_IsPrimaryKey_eceb899b BOOLEAN;
  p_IsUniqueKey_eceb899b BOOLEAN;
  p_IsReadOnly_eceb899b BOOLEAN;
  p_IsRequired_eceb899b BOOLEAN;
  p_RelatedIntegrationObjectID_eceb899b UUID;
  p_RelatedIntegrationObjectFieldName_eceb899b VARCHAR(255);
  p_Sequence_eceb899b INTEGER;
  p_Configuration_eceb899b TEXT;
  p_Status_eceb899b VARCHAR(25);
  p_IsCustom_eceb899b BOOLEAN;
  p_MetadataSource_eceb899b VARCHAR(20);
BEGIN
  p_ID_eceb899b := '81106DE0-473B-4541-8F7B-6165561DAD5E';
  p_IntegrationObjectID_eceb899b := 'FB9E1B85-6B87-4561-B332-C264ECF2D87B';
  p_Name_eceb899b := 'alert_id';
  p_DisplayName_eceb899b := 'Alert ID';
  p_Description_eceb899b := 'WP Activity Log event type ID. Primary key.';
  p_Type_eceb899b := 'Integer';
  p_AllowsNull_eceb899b := FALSE;
  p_IsPrimaryKey_eceb899b := TRUE;
  p_IsUniqueKey_eceb899b := TRUE;
  p_IsReadOnly_eceb899b := TRUE;
  p_IsRequired_eceb899b := TRUE;
  p_Sequence_eceb899b := 0;
  p_Configuration_eceb899b := '{
  "contexts": [
    "view"
  ]
}';
  p_Status_eceb899b := 'Active';
  p_IsCustom_eceb899b := FALSE;
  p_MetadataSource_eceb899b := 'Declared';
  PERFORM __mj."spCreateIntegrationObjectField"(p_ID := p_ID_eceb899b, p_IntegrationObjectID := p_IntegrationObjectID_eceb899b, p_Name := p_Name_eceb899b, p_DisplayName := p_DisplayName_eceb899b, p_Description := p_Description_eceb899b, p_Category := p_Category_eceb899b, p_Category_Clear := TRUE, p_Type := p_Type_eceb899b, p_Length := p_Length_eceb899b, p_Length_Clear := TRUE, p_Precision := p_Precision_eceb899b, p_Precision_Clear := TRUE, p_Scale := p_Scale_eceb899b, p_Scale_Clear := TRUE, p_AllowsNull := p_AllowsNull_eceb899b, p_DefaultValue := p_DefaultValue_eceb899b, p_DefaultValue_Clear := TRUE, p_IsPrimaryKey := p_IsPrimaryKey_eceb899b, p_IsUniqueKey := p_IsUniqueKey_eceb899b, p_IsReadOnly := p_IsReadOnly_eceb899b, p_IsRequired := p_IsRequired_eceb899b, p_RelatedIntegrationObjectID := p_RelatedIntegrationObjectID_eceb899b, p_RelatedIntegrationObjectID_Clear := TRUE, p_RelatedIntegrationObjectFieldName := p_RelatedIntegrationObjectFieldName_eceb899b, p_RelatedIntegrationObjectFieldName_Clear := TRUE, p_Sequence := p_Sequence_eceb899b, p_Configuration := p_Configuration_eceb899b, p_Status := p_Status_eceb899b, p_IsCustom := p_IsCustom_eceb899b, p_MetadataSource := p_MetadataSource_eceb899b);
END $mj$;

-- Save MJ: Integration Object Fields (core SP call only)
DO $mj$
DECLARE
  p_ID_4618087a UUID;
  p_IntegrationObjectID_4618087a UUID;
  p_Name_4618087a VARCHAR(255);
  p_DisplayName_4618087a VARCHAR(255);
  p_Description_4618087a TEXT;
  p_Category_4618087a VARCHAR(100);
  p_Type_4618087a VARCHAR(100);
  p_Length_4618087a INTEGER;
  p_Precision_4618087a INTEGER;
  p_Scale_4618087a INTEGER;
  p_AllowsNull_4618087a BOOLEAN;
  p_DefaultValue_4618087a VARCHAR(255);
  p_IsPrimaryKey_4618087a BOOLEAN;
  p_IsUniqueKey_4618087a BOOLEAN;
  p_IsReadOnly_4618087a BOOLEAN;
  p_IsRequired_4618087a BOOLEAN;
  p_RelatedIntegrationObjectID_4618087a UUID;
  p_RelatedIntegrationObjectFieldName_4618087a VARCHAR(255);
  p_Sequence_4618087a INTEGER;
  p_Configuration_4618087a TEXT;
  p_Status_4618087a VARCHAR(25);
  p_IsCustom_4618087a BOOLEAN;
  p_MetadataSource_4618087a VARCHAR(20);
BEGIN
  p_ID_4618087a := '2497FD94-CFB2-44DA-95A1-DD49C53039A5';
  p_IntegrationObjectID_4618087a := 'FB9E1B85-6B87-4561-B332-C264ECF2D87B';
  p_Name_4618087a := 'label';
  p_DisplayName_4618087a := 'Label';
  p_Description_4618087a := 'Short human-readable name of the event type.';
  p_Type_4618087a := 'String';
  p_AllowsNull_4618087a := TRUE;
  p_IsPrimaryKey_4618087a := FALSE;
  p_IsUniqueKey_4618087a := FALSE;
  p_IsReadOnly_4618087a := TRUE;
  p_IsRequired_4618087a := FALSE;
  p_Sequence_4618087a := 1;
  p_Configuration_4618087a := '{
  "contexts": [
    "view"
  ]
}';
  p_Status_4618087a := 'Active';
  p_IsCustom_4618087a := FALSE;
  p_MetadataSource_4618087a := 'Declared';
  PERFORM __mj."spCreateIntegrationObjectField"(p_ID := p_ID_4618087a, p_IntegrationObjectID := p_IntegrationObjectID_4618087a, p_Name := p_Name_4618087a, p_DisplayName := p_DisplayName_4618087a, p_Description := p_Description_4618087a, p_Category := p_Category_4618087a, p_Category_Clear := TRUE, p_Type := p_Type_4618087a, p_Length := p_Length_4618087a, p_Length_Clear := TRUE, p_Precision := p_Precision_4618087a, p_Precision_Clear := TRUE, p_Scale := p_Scale_4618087a, p_Scale_Clear := TRUE, p_AllowsNull := p_AllowsNull_4618087a, p_DefaultValue := p_DefaultValue_4618087a, p_DefaultValue_Clear := TRUE, p_IsPrimaryKey := p_IsPrimaryKey_4618087a, p_IsUniqueKey := p_IsUniqueKey_4618087a, p_IsReadOnly := p_IsReadOnly_4618087a, p_IsRequired := p_IsRequired_4618087a, p_RelatedIntegrationObjectID := p_RelatedIntegrationObjectID_4618087a, p_RelatedIntegrationObjectID_Clear := TRUE, p_RelatedIntegrationObjectFieldName := p_RelatedIntegrationObjectFieldName_4618087a, p_RelatedIntegrationObjectFieldName_Clear := TRUE, p_Sequence := p_Sequence_4618087a, p_Configuration := p_Configuration_4618087a, p_Status := p_Status_4618087a, p_IsCustom := p_IsCustom_4618087a, p_MetadataSource := p_MetadataSource_4618087a);
END $mj$;

-- Save MJ: Integration Object Fields (core SP call only)
DO $mj$
DECLARE
  p_ID_44f26643 UUID;
  p_IntegrationObjectID_44f26643 UUID;
  p_Name_44f26643 VARCHAR(255);
  p_DisplayName_44f26643 VARCHAR(255);
  p_Description_44f26643 TEXT;
  p_Category_44f26643 VARCHAR(100);
  p_Type_44f26643 VARCHAR(100);
  p_Length_44f26643 INTEGER;
  p_Precision_44f26643 INTEGER;
  p_Scale_44f26643 INTEGER;
  p_AllowsNull_44f26643 BOOLEAN;
  p_DefaultValue_44f26643 VARCHAR(255);
  p_IsPrimaryKey_44f26643 BOOLEAN;
  p_IsUniqueKey_44f26643 BOOLEAN;
  p_IsReadOnly_44f26643 BOOLEAN;
  p_IsRequired_44f26643 BOOLEAN;
  p_RelatedIntegrationObjectID_44f26643 UUID;
  p_RelatedIntegrationObjectFieldName_44f26643 VARCHAR(255);
  p_Sequence_44f26643 INTEGER;
  p_Configuration_44f26643 TEXT;
  p_Status_44f26643 VARCHAR(25);
  p_IsCustom_44f26643 BOOLEAN;
  p_MetadataSource_44f26643 VARCHAR(20);
BEGIN
  p_ID_44f26643 := '4EE0F696-DF4D-4511-98E1-E1D29FBE8B54';
  p_IntegrationObjectID_44f26643 := 'FB9E1B85-6B87-4561-B332-C264ECF2D87B';
  p_Name_44f26643 := 'message';
  p_DisplayName_44f26643 := 'Message Template';
  p_Description_44f26643 := 'Message template the plugin renders for this event type. Prose: WSAL templates run to several hundred characters, well past the 255 default.';
  p_Type_44f26643 := 'String';
  p_Length_44f26643 := 4000;
  p_AllowsNull_44f26643 := TRUE;
  p_IsPrimaryKey_44f26643 := FALSE;
  p_IsUniqueKey_44f26643 := FALSE;
  p_IsReadOnly_44f26643 := TRUE;
  p_IsRequired_44f26643 := FALSE;
  p_Sequence_44f26643 := 2;
  p_Configuration_44f26643 := '{
  "contexts": [
    "view"
  ]
}';
  p_Status_44f26643 := 'Active';
  p_IsCustom_44f26643 := FALSE;
  p_MetadataSource_44f26643 := 'Declared';
  PERFORM __mj."spCreateIntegrationObjectField"(p_ID := p_ID_44f26643, p_IntegrationObjectID := p_IntegrationObjectID_44f26643, p_Name := p_Name_44f26643, p_DisplayName := p_DisplayName_44f26643, p_Description := p_Description_44f26643, p_Category := p_Category_44f26643, p_Category_Clear := TRUE, p_Type := p_Type_44f26643, p_Length := p_Length_44f26643, p_Precision := p_Precision_44f26643, p_Precision_Clear := TRUE, p_Scale := p_Scale_44f26643, p_Scale_Clear := TRUE, p_AllowsNull := p_AllowsNull_44f26643, p_DefaultValue := p_DefaultValue_44f26643, p_DefaultValue_Clear := TRUE, p_IsPrimaryKey := p_IsPrimaryKey_44f26643, p_IsUniqueKey := p_IsUniqueKey_44f26643, p_IsReadOnly := p_IsReadOnly_44f26643, p_IsRequired := p_IsRequired_44f26643, p_RelatedIntegrationObjectID := p_RelatedIntegrationObjectID_44f26643, p_RelatedIntegrationObjectID_Clear := TRUE, p_RelatedIntegrationObjectFieldName := p_RelatedIntegrationObjectFieldName_44f26643, p_RelatedIntegrationObjectFieldName_Clear := TRUE, p_Sequence := p_Sequence_44f26643, p_Configuration := p_Configuration_44f26643, p_Status := p_Status_44f26643, p_IsCustom := p_IsCustom_44f26643, p_MetadataSource := p_MetadataSource_44f26643);
END $mj$;

-- Save MJ: Integration Object Fields (core SP call only)
DO $mj$
DECLARE
  p_ID_1354c3ac UUID;
  p_IntegrationObjectID_1354c3ac UUID;
  p_Name_1354c3ac VARCHAR(255);
  p_DisplayName_1354c3ac VARCHAR(255);
  p_Description_1354c3ac TEXT;
  p_Category_1354c3ac VARCHAR(100);
  p_Type_1354c3ac VARCHAR(100);
  p_Length_1354c3ac INTEGER;
  p_Precision_1354c3ac INTEGER;
  p_Scale_1354c3ac INTEGER;
  p_AllowsNull_1354c3ac BOOLEAN;
  p_DefaultValue_1354c3ac VARCHAR(255);
  p_IsPrimaryKey_1354c3ac BOOLEAN;
  p_IsUniqueKey_1354c3ac BOOLEAN;
  p_IsReadOnly_1354c3ac BOOLEAN;
  p_IsRequired_1354c3ac BOOLEAN;
  p_RelatedIntegrationObjectID_1354c3ac UUID;
  p_RelatedIntegrationObjectFieldName_1354c3ac VARCHAR(255);
  p_Sequence_1354c3ac INTEGER;
  p_Configuration_1354c3ac TEXT;
  p_Status_1354c3ac VARCHAR(25);
  p_IsCustom_1354c3ac BOOLEAN;
  p_MetadataSource_1354c3ac VARCHAR(20);
BEGIN
  p_ID_1354c3ac := '92965B4E-08DF-4C0D-89F1-A8D8AA58308D';
  p_IntegrationObjectID_1354c3ac := 'FB9E1B85-6B87-4561-B332-C264ECF2D87B';
  p_Name_1354c3ac := 'severity';
  p_DisplayName_1354c3ac := 'Severity';
  p_Description_1354c3ac := 'Declared severity level for this event type.';
  p_Type_1354c3ac := 'String';
  p_AllowsNull_1354c3ac := TRUE;
  p_IsPrimaryKey_1354c3ac := FALSE;
  p_IsUniqueKey_1354c3ac := FALSE;
  p_IsReadOnly_1354c3ac := TRUE;
  p_IsRequired_1354c3ac := FALSE;
  p_Sequence_1354c3ac := 3;
  p_Configuration_1354c3ac := '{
  "contexts": [
    "view"
  ]
}';
  p_Status_1354c3ac := 'Active';
  p_IsCustom_1354c3ac := FALSE;
  p_MetadataSource_1354c3ac := 'Declared';
  PERFORM __mj."spCreateIntegrationObjectField"(p_ID := p_ID_1354c3ac, p_IntegrationObjectID := p_IntegrationObjectID_1354c3ac, p_Name := p_Name_1354c3ac, p_DisplayName := p_DisplayName_1354c3ac, p_Description := p_Description_1354c3ac, p_Category := p_Category_1354c3ac, p_Category_Clear := TRUE, p_Type := p_Type_1354c3ac, p_Length := p_Length_1354c3ac, p_Length_Clear := TRUE, p_Precision := p_Precision_1354c3ac, p_Precision_Clear := TRUE, p_Scale := p_Scale_1354c3ac, p_Scale_Clear := TRUE, p_AllowsNull := p_AllowsNull_1354c3ac, p_DefaultValue := p_DefaultValue_1354c3ac, p_DefaultValue_Clear := TRUE, p_IsPrimaryKey := p_IsPrimaryKey_1354c3ac, p_IsUniqueKey := p_IsUniqueKey_1354c3ac, p_IsReadOnly := p_IsReadOnly_1354c3ac, p_IsRequired := p_IsRequired_1354c3ac, p_RelatedIntegrationObjectID := p_RelatedIntegrationObjectID_1354c3ac, p_RelatedIntegrationObjectID_Clear := TRUE, p_RelatedIntegrationObjectFieldName := p_RelatedIntegrationObjectFieldName_1354c3ac, p_RelatedIntegrationObjectFieldName_Clear := TRUE, p_Sequence := p_Sequence_1354c3ac, p_Configuration := p_Configuration_1354c3ac, p_Status := p_Status_1354c3ac, p_IsCustom := p_IsCustom_1354c3ac, p_MetadataSource := p_MetadataSource_1354c3ac);
END $mj$;

-- Save MJ: Integration Object Fields (core SP call only)
DO $mj$
DECLARE
  p_ID_7351afa5 UUID;
  p_IntegrationObjectID_7351afa5 UUID;
  p_Name_7351afa5 VARCHAR(255);
  p_DisplayName_7351afa5 VARCHAR(255);
  p_Description_7351afa5 TEXT;
  p_Category_7351afa5 VARCHAR(100);
  p_Type_7351afa5 VARCHAR(100);
  p_Length_7351afa5 INTEGER;
  p_Precision_7351afa5 INTEGER;
  p_Scale_7351afa5 INTEGER;
  p_AllowsNull_7351afa5 BOOLEAN;
  p_DefaultValue_7351afa5 VARCHAR(255);
  p_IsPrimaryKey_7351afa5 BOOLEAN;
  p_IsUniqueKey_7351afa5 BOOLEAN;
  p_IsReadOnly_7351afa5 BOOLEAN;
  p_IsRequired_7351afa5 BOOLEAN;
  p_RelatedIntegrationObjectID_7351afa5 UUID;
  p_RelatedIntegrationObjectFieldName_7351afa5 VARCHAR(255);
  p_Sequence_7351afa5 INTEGER;
  p_Configuration_7351afa5 TEXT;
  p_Status_7351afa5 VARCHAR(25);
  p_IsCustom_7351afa5 BOOLEAN;
  p_MetadataSource_7351afa5 VARCHAR(20);
BEGIN
  p_ID_7351afa5 := 'DC9B21A8-E493-4E9C-9BE8-6B5BFA5D9BA6';
  p_IntegrationObjectID_7351afa5 := 'FB9E1B85-6B87-4561-B332-C264ECF2D87B';
  p_Name_7351afa5 := 'category';
  p_DisplayName_7351afa5 := 'Category';
  p_Description_7351afa5 := 'Top-level grouping the event type belongs to.';
  p_Type_7351afa5 := 'String';
  p_AllowsNull_7351afa5 := TRUE;
  p_IsPrimaryKey_7351afa5 := FALSE;
  p_IsUniqueKey_7351afa5 := FALSE;
  p_IsReadOnly_7351afa5 := TRUE;
  p_IsRequired_7351afa5 := FALSE;
  p_Sequence_7351afa5 := 4;
  p_Configuration_7351afa5 := '{
  "contexts": [
    "view"
  ]
}';
  p_Status_7351afa5 := 'Active';
  p_IsCustom_7351afa5 := FALSE;
  p_MetadataSource_7351afa5 := 'Declared';
  PERFORM __mj."spCreateIntegrationObjectField"(p_ID := p_ID_7351afa5, p_IntegrationObjectID := p_IntegrationObjectID_7351afa5, p_Name := p_Name_7351afa5, p_DisplayName := p_DisplayName_7351afa5, p_Description := p_Description_7351afa5, p_Category := p_Category_7351afa5, p_Category_Clear := TRUE, p_Type := p_Type_7351afa5, p_Length := p_Length_7351afa5, p_Length_Clear := TRUE, p_Precision := p_Precision_7351afa5, p_Precision_Clear := TRUE, p_Scale := p_Scale_7351afa5, p_Scale_Clear := TRUE, p_AllowsNull := p_AllowsNull_7351afa5, p_DefaultValue := p_DefaultValue_7351afa5, p_DefaultValue_Clear := TRUE, p_IsPrimaryKey := p_IsPrimaryKey_7351afa5, p_IsUniqueKey := p_IsUniqueKey_7351afa5, p_IsReadOnly := p_IsReadOnly_7351afa5, p_IsRequired := p_IsRequired_7351afa5, p_RelatedIntegrationObjectID := p_RelatedIntegrationObjectID_7351afa5, p_RelatedIntegrationObjectID_Clear := TRUE, p_RelatedIntegrationObjectFieldName := p_RelatedIntegrationObjectFieldName_7351afa5, p_RelatedIntegrationObjectFieldName_Clear := TRUE, p_Sequence := p_Sequence_7351afa5, p_Configuration := p_Configuration_7351afa5, p_Status := p_Status_7351afa5, p_IsCustom := p_IsCustom_7351afa5, p_MetadataSource := p_MetadataSource_7351afa5);
END $mj$;

-- Save MJ: Integration Object Fields (core SP call only)
DO $mj$
DECLARE
  p_ID_df2f3a15 UUID;
  p_IntegrationObjectID_df2f3a15 UUID;
  p_Name_df2f3a15 VARCHAR(255);
  p_DisplayName_df2f3a15 VARCHAR(255);
  p_Description_df2f3a15 TEXT;
  p_Category_df2f3a15 VARCHAR(100);
  p_Type_df2f3a15 VARCHAR(100);
  p_Length_df2f3a15 INTEGER;
  p_Precision_df2f3a15 INTEGER;
  p_Scale_df2f3a15 INTEGER;
  p_AllowsNull_df2f3a15 BOOLEAN;
  p_DefaultValue_df2f3a15 VARCHAR(255);
  p_IsPrimaryKey_df2f3a15 BOOLEAN;
  p_IsUniqueKey_df2f3a15 BOOLEAN;
  p_IsReadOnly_df2f3a15 BOOLEAN;
  p_IsRequired_df2f3a15 BOOLEAN;
  p_RelatedIntegrationObjectID_df2f3a15 UUID;
  p_RelatedIntegrationObjectFieldName_df2f3a15 VARCHAR(255);
  p_Sequence_df2f3a15 INTEGER;
  p_Configuration_df2f3a15 TEXT;
  p_Status_df2f3a15 VARCHAR(25);
  p_IsCustom_df2f3a15 BOOLEAN;
  p_MetadataSource_df2f3a15 VARCHAR(20);
BEGIN
  p_ID_df2f3a15 := '41CB0754-E4DF-4F84-BC5C-F2C777663BB4';
  p_IntegrationObjectID_df2f3a15 := 'FB9E1B85-6B87-4561-B332-C264ECF2D87B';
  p_Name_df2f3a15 := 'subcategory';
  p_DisplayName_df2f3a15 := 'Subcategory';
  p_Description_df2f3a15 := 'Secondary grouping the event type belongs to.';
  p_Type_df2f3a15 := 'String';
  p_AllowsNull_df2f3a15 := TRUE;
  p_IsPrimaryKey_df2f3a15 := FALSE;
  p_IsUniqueKey_df2f3a15 := FALSE;
  p_IsReadOnly_df2f3a15 := TRUE;
  p_IsRequired_df2f3a15 := FALSE;
  p_Sequence_df2f3a15 := 5;
  p_Configuration_df2f3a15 := '{
  "contexts": [
    "view"
  ]
}';
  p_Status_df2f3a15 := 'Active';
  p_IsCustom_df2f3a15 := FALSE;
  p_MetadataSource_df2f3a15 := 'Declared';
  PERFORM __mj."spCreateIntegrationObjectField"(p_ID := p_ID_df2f3a15, p_IntegrationObjectID := p_IntegrationObjectID_df2f3a15, p_Name := p_Name_df2f3a15, p_DisplayName := p_DisplayName_df2f3a15, p_Description := p_Description_df2f3a15, p_Category := p_Category_df2f3a15, p_Category_Clear := TRUE, p_Type := p_Type_df2f3a15, p_Length := p_Length_df2f3a15, p_Length_Clear := TRUE, p_Precision := p_Precision_df2f3a15, p_Precision_Clear := TRUE, p_Scale := p_Scale_df2f3a15, p_Scale_Clear := TRUE, p_AllowsNull := p_AllowsNull_df2f3a15, p_DefaultValue := p_DefaultValue_df2f3a15, p_DefaultValue_Clear := TRUE, p_IsPrimaryKey := p_IsPrimaryKey_df2f3a15, p_IsUniqueKey := p_IsUniqueKey_df2f3a15, p_IsReadOnly := p_IsReadOnly_df2f3a15, p_IsRequired := p_IsRequired_df2f3a15, p_RelatedIntegrationObjectID := p_RelatedIntegrationObjectID_df2f3a15, p_RelatedIntegrationObjectID_Clear := TRUE, p_RelatedIntegrationObjectFieldName := p_RelatedIntegrationObjectFieldName_df2f3a15, p_RelatedIntegrationObjectFieldName_Clear := TRUE, p_Sequence := p_Sequence_df2f3a15, p_Configuration := p_Configuration_df2f3a15, p_Status := p_Status_df2f3a15, p_IsCustom := p_IsCustom_df2f3a15, p_MetadataSource := p_MetadataSource_df2f3a15);
END $mj$;

-- Save MJ: Integration Object Fields (core SP call only)
DO $mj$
DECLARE
  p_ID_6311f716 UUID;
  p_IntegrationObjectID_6311f716 UUID;
  p_Name_6311f716 VARCHAR(255);
  p_DisplayName_6311f716 VARCHAR(255);
  p_Description_6311f716 TEXT;
  p_Category_6311f716 VARCHAR(100);
  p_Type_6311f716 VARCHAR(100);
  p_Length_6311f716 INTEGER;
  p_Precision_6311f716 INTEGER;
  p_Scale_6311f716 INTEGER;
  p_AllowsNull_6311f716 BOOLEAN;
  p_DefaultValue_6311f716 VARCHAR(255);
  p_IsPrimaryKey_6311f716 BOOLEAN;
  p_IsUniqueKey_6311f716 BOOLEAN;
  p_IsReadOnly_6311f716 BOOLEAN;
  p_IsRequired_6311f716 BOOLEAN;
  p_RelatedIntegrationObjectID_6311f716 UUID;
  p_RelatedIntegrationObjectFieldName_6311f716 VARCHAR(255);
  p_Sequence_6311f716 INTEGER;
  p_Configuration_6311f716 TEXT;
  p_Status_6311f716 VARCHAR(25);
  p_IsCustom_6311f716 BOOLEAN;
  p_MetadataSource_6311f716 VARCHAR(20);
BEGIN
  p_ID_6311f716 := 'B613F52D-00C9-4A75-8705-EFAA9879E513';
  p_IntegrationObjectID_6311f716 := 'FB9E1B85-6B87-4561-B332-C264ECF2D87B';
  p_Name_6311f716 := 'object';
  p_DisplayName_6311f716 := 'Object';
  p_Description_6311f716 := 'Subject this event type concerns.';
  p_Type_6311f716 := 'String';
  p_AllowsNull_6311f716 := TRUE;
  p_IsPrimaryKey_6311f716 := FALSE;
  p_IsUniqueKey_6311f716 := FALSE;
  p_IsReadOnly_6311f716 := TRUE;
  p_IsRequired_6311f716 := FALSE;
  p_Sequence_6311f716 := 6;
  p_Configuration_6311f716 := '{
  "contexts": [
    "view"
  ]
}';
  p_Status_6311f716 := 'Active';
  p_IsCustom_6311f716 := FALSE;
  p_MetadataSource_6311f716 := 'Declared';
  PERFORM __mj."spCreateIntegrationObjectField"(p_ID := p_ID_6311f716, p_IntegrationObjectID := p_IntegrationObjectID_6311f716, p_Name := p_Name_6311f716, p_DisplayName := p_DisplayName_6311f716, p_Description := p_Description_6311f716, p_Category := p_Category_6311f716, p_Category_Clear := TRUE, p_Type := p_Type_6311f716, p_Length := p_Length_6311f716, p_Length_Clear := TRUE, p_Precision := p_Precision_6311f716, p_Precision_Clear := TRUE, p_Scale := p_Scale_6311f716, p_Scale_Clear := TRUE, p_AllowsNull := p_AllowsNull_6311f716, p_DefaultValue := p_DefaultValue_6311f716, p_DefaultValue_Clear := TRUE, p_IsPrimaryKey := p_IsPrimaryKey_6311f716, p_IsUniqueKey := p_IsUniqueKey_6311f716, p_IsReadOnly := p_IsReadOnly_6311f716, p_IsRequired := p_IsRequired_6311f716, p_RelatedIntegrationObjectID := p_RelatedIntegrationObjectID_6311f716, p_RelatedIntegrationObjectID_Clear := TRUE, p_RelatedIntegrationObjectFieldName := p_RelatedIntegrationObjectFieldName_6311f716, p_RelatedIntegrationObjectFieldName_Clear := TRUE, p_Sequence := p_Sequence_6311f716, p_Configuration := p_Configuration_6311f716, p_Status := p_Status_6311f716, p_IsCustom := p_IsCustom_6311f716, p_MetadataSource := p_MetadataSource_6311f716);
END $mj$;

-- Save MJ: Integration Object Fields (core SP call only)
DO $mj$
DECLARE
  p_ID_c90fce9c UUID;
  p_IntegrationObjectID_c90fce9c UUID;
  p_Name_c90fce9c VARCHAR(255);
  p_DisplayName_c90fce9c VARCHAR(255);
  p_Description_c90fce9c TEXT;
  p_Category_c90fce9c VARCHAR(100);
  p_Type_c90fce9c VARCHAR(100);
  p_Length_c90fce9c INTEGER;
  p_Precision_c90fce9c INTEGER;
  p_Scale_c90fce9c INTEGER;
  p_AllowsNull_c90fce9c BOOLEAN;
  p_DefaultValue_c90fce9c VARCHAR(255);
  p_IsPrimaryKey_c90fce9c BOOLEAN;
  p_IsUniqueKey_c90fce9c BOOLEAN;
  p_IsReadOnly_c90fce9c BOOLEAN;
  p_IsRequired_c90fce9c BOOLEAN;
  p_RelatedIntegrationObjectID_c90fce9c UUID;
  p_RelatedIntegrationObjectFieldName_c90fce9c VARCHAR(255);
  p_Sequence_c90fce9c INTEGER;
  p_Configuration_c90fce9c TEXT;
  p_Status_c90fce9c VARCHAR(25);
  p_IsCustom_c90fce9c BOOLEAN;
  p_MetadataSource_c90fce9c VARCHAR(20);
BEGIN
  p_ID_c90fce9c := '3184B995-8214-49A5-94F6-BC5975A84063';
  p_IntegrationObjectID_c90fce9c := 'FB9E1B85-6B87-4561-B332-C264ECF2D87B';
  p_Name_c90fce9c := 'event_type';
  p_DisplayName_c90fce9c := 'Event Type';
  p_Description_c90fce9c := 'Action this event type represents.';
  p_Type_c90fce9c := 'String';
  p_AllowsNull_c90fce9c := TRUE;
  p_IsPrimaryKey_c90fce9c := FALSE;
  p_IsUniqueKey_c90fce9c := FALSE;
  p_IsReadOnly_c90fce9c := TRUE;
  p_IsRequired_c90fce9c := FALSE;
  p_Sequence_c90fce9c := 7;
  p_Configuration_c90fce9c := '{
  "contexts": [
    "view"
  ]
}';
  p_Status_c90fce9c := 'Active';
  p_IsCustom_c90fce9c := FALSE;
  p_MetadataSource_c90fce9c := 'Declared';
  PERFORM __mj."spCreateIntegrationObjectField"(p_ID := p_ID_c90fce9c, p_IntegrationObjectID := p_IntegrationObjectID_c90fce9c, p_Name := p_Name_c90fce9c, p_DisplayName := p_DisplayName_c90fce9c, p_Description := p_Description_c90fce9c, p_Category := p_Category_c90fce9c, p_Category_Clear := TRUE, p_Type := p_Type_c90fce9c, p_Length := p_Length_c90fce9c, p_Length_Clear := TRUE, p_Precision := p_Precision_c90fce9c, p_Precision_Clear := TRUE, p_Scale := p_Scale_c90fce9c, p_Scale_Clear := TRUE, p_AllowsNull := p_AllowsNull_c90fce9c, p_DefaultValue := p_DefaultValue_c90fce9c, p_DefaultValue_Clear := TRUE, p_IsPrimaryKey := p_IsPrimaryKey_c90fce9c, p_IsUniqueKey := p_IsUniqueKey_c90fce9c, p_IsReadOnly := p_IsReadOnly_c90fce9c, p_IsRequired := p_IsRequired_c90fce9c, p_RelatedIntegrationObjectID := p_RelatedIntegrationObjectID_c90fce9c, p_RelatedIntegrationObjectID_Clear := TRUE, p_RelatedIntegrationObjectFieldName := p_RelatedIntegrationObjectFieldName_c90fce9c, p_RelatedIntegrationObjectFieldName_Clear := TRUE, p_Sequence := p_Sequence_c90fce9c, p_Configuration := p_Configuration_c90fce9c, p_Status := p_Status_c90fce9c, p_IsCustom := p_IsCustom_c90fce9c, p_MetadataSource := p_MetadataSource_c90fce9c);
END $mj$;
