-- Oracle Database Connector — connector metadata seed (generated by `mj sync push`)
-- Seeds the core __mj integration catalog (Integration / IntegrationObject / IntegrationObjectField + Actions).
-- Do not hand-edit; regenerate from ../metadata via `mj sync push` + `scripts/wrap-migration.mjs`.

-- SQL Logging Session
-- Session ID: 36d57278-2b39-4ea7-b910-f7d8723193d6
-- Started: 2026-07-10T00:55:23.203Z
-- Description: MetadataSync push operation
-- Generated by MemberJunction

-- Save MJ: Integrations (core SP call only)
DECLARE @Name_a1aaf2b0 NVARCHAR(100),
@Description_a1aaf2b0 NVARCHAR(255),
@NavigationBaseURL_a1aaf2b0 NVARCHAR(500),
@ClassName_a1aaf2b0 NVARCHAR(100),
@ImportPath_a1aaf2b0 NVARCHAR(100),
@BatchMaxRequestCount_a1aaf2b0 INT,
@BatchRequestWaitTime_a1aaf2b0 INT,
@ID_a1aaf2b0 UNIQUEIDENTIFIER,
@CredentialTypeID_a1aaf2b0 UNIQUEIDENTIFIER,
@Icon_a1aaf2b0 NVARCHAR(MAX),
@Configuration_a1aaf2b0 NVARCHAR(MAX)
SET
  @Name_a1aaf2b0 = N'Oracle Database'
SET
  @Description_a1aaf2b0 = N'Ingest data from an external Oracle Database via a shared MJ: External Data Sources connection. Schema is discovered at connection time; the connector delegates connectivity to the EDS ''OracleExternalDriver'' driver.'
SET
  @ClassName_a1aaf2b0 = N'OracleConnector'
SET
  @ImportPath_a1aaf2b0 = N'@memberjunction/connector-oracle'
SET
  @BatchMaxRequestCount_a1aaf2b0 = -1
SET
  @BatchRequestWaitTime_a1aaf2b0 = -1
SET
  @ID_a1aaf2b0 = '3da3a201-34d3-48e6-95c7-f6798d3c092f'
SET
  @Icon_a1aaf2b0 = N'fa-solid fa-database'
SET
  @Configuration_a1aaf2b0 = N'{
  "connectionModel": "external-data-source",
  "note": "Bind this connection to a shared ''MJ: External Data Sources'' row by setting Configuration.externalDataSourceID on the CompanyIntegration. Host + credentials live on that EDS row (credentials via CredentialEngine); objects/fields are discovered at connection time. Requires @memberjunction/external-data-sources + @memberjunction/external-data-source-oracle >= 5.46.0."
}' EXEC [__mj].spCreateIntegration @Name = @Name_a1aaf2b0,
  @Description = @Description_a1aaf2b0,
  @NavigationBaseURL = @NavigationBaseURL_a1aaf2b0,
  @NavigationBaseURL_Clear = 1,
  @ClassName = @ClassName_a1aaf2b0,
  @ImportPath = @ImportPath_a1aaf2b0,
  @BatchMaxRequestCount = @BatchMaxRequestCount_a1aaf2b0,
  @BatchRequestWaitTime = @BatchRequestWaitTime_a1aaf2b0,
  @ID = @ID_a1aaf2b0,
  @CredentialTypeID = @CredentialTypeID_a1aaf2b0,
  @CredentialTypeID_Clear = 1,
  @Icon = @Icon_a1aaf2b0,
  @Configuration = @Configuration_a1aaf2b0;

GO


-- End of SQL Logging Session
-- Session ID: 36d57278-2b39-4ea7-b910-f7d8723193d6
-- Completed: 2026-07-10T00:55:23.356Z
-- Duration: 153ms
-- Total Statements: 1
