-- Bill.com Connector — connector metadata seed (generated by `mj sync push`)
-- Seeds the core __mj integration catalog (Integration / IntegrationObject / IntegrationObjectField + Actions).
-- Do not hand-edit; regenerate from ../metadata via `mj sync push` + `scripts/wrap-migration.mjs`.

-- SQL Logging Session
-- Session ID: 3e840b4d-19eb-4074-98b0-cd23f798712f
-- Started: 2026-08-14T03:05:53.551Z
-- Description: MetadataSync push operation
-- Generated by MemberJunction

-- Save MJ: Integration Object Fields (core SP call only)
DECLARE @IntegrationObjectID_95b57e2d UNIQUEIDENTIFIER,
@Name_95b57e2d NVARCHAR(255),
@DisplayName_95b57e2d NVARCHAR(255),
@Description_95b57e2d NVARCHAR(MAX),
@Category_95b57e2d NVARCHAR(100),
@Type_95b57e2d NVARCHAR(100),
@Length_95b57e2d INT,
@Precision_95b57e2d INT,
@Scale_95b57e2d INT,
@AllowsNull_95b57e2d BIT,
@DefaultValue_95b57e2d NVARCHAR(255),
@IsPrimaryKey_95b57e2d BIT,
@IsUniqueKey_95b57e2d BIT,
@IsReadOnly_95b57e2d BIT,
@IsRequired_95b57e2d BIT,
@RelatedIntegrationObjectID_95b57e2d UNIQUEIDENTIFIER,
@RelatedIntegrationObjectFieldName_95b57e2d NVARCHAR(255),
@Sequence_95b57e2d INT,
@Configuration_95b57e2d NVARCHAR(MAX),
@Status_95b57e2d NVARCHAR(25),
@IsCustom_95b57e2d BIT,
@MetadataSource_95b57e2d NVARCHAR(20),
@ID_95b57e2d UNIQUEIDENTIFIER
SET
  @IntegrationObjectID_95b57e2d = '08C7D86A-E2D8-55DE-8879-F0789FF63D14'
SET
  @Name_95b57e2d = N'customerId'
SET
  @DisplayName_95b57e2d = N'Customer Id'
SET
  @Description_95b57e2d = N'BILL-generated ID of the customer. The value begins with `0cu`.'
SET
  @Type_95b57e2d = N'string'
SET
  @Length_95b57e2d = 255
SET
  @AllowsNull_95b57e2d = 1
SET
  @IsPrimaryKey_95b57e2d = 0
SET
  @IsUniqueKey_95b57e2d = 0
SET
  @IsReadOnly_95b57e2d = 1
SET
  @IsRequired_95b57e2d = 0
SET
  @Sequence_95b57e2d = 8
SET
  @Status_95b57e2d = N'Active'
SET
  @IsCustom_95b57e2d = 0
SET
  @MetadataSource_95b57e2d = N'Declared'
SET
  @ID_95b57e2d = '773C34EC-569D-585D-8116-8689CF6EC617' EXEC [__mj].spUpdateIntegrationObjectField @IntegrationObjectID = @IntegrationObjectID_95b57e2d,
  @Name = @Name_95b57e2d,
  @DisplayName = @DisplayName_95b57e2d,
  @Description = @Description_95b57e2d,
  @Category = @Category_95b57e2d,
  @Category_Clear = 1,
  @Type = @Type_95b57e2d,
  @Length = @Length_95b57e2d,
  @Precision = @Precision_95b57e2d,
  @Precision_Clear = 1,
  @Scale = @Scale_95b57e2d,
  @Scale_Clear = 1,
  @AllowsNull = @AllowsNull_95b57e2d,
  @DefaultValue = @DefaultValue_95b57e2d,
  @DefaultValue_Clear = 1,
  @IsPrimaryKey = @IsPrimaryKey_95b57e2d,
  @IsUniqueKey = @IsUniqueKey_95b57e2d,
  @IsReadOnly = @IsReadOnly_95b57e2d,
  @IsRequired = @IsRequired_95b57e2d,
  @RelatedIntegrationObjectID = @RelatedIntegrationObjectID_95b57e2d,
  @RelatedIntegrationObjectID_Clear = 1,
  @RelatedIntegrationObjectFieldName = @RelatedIntegrationObjectFieldName_95b57e2d,
  @RelatedIntegrationObjectFieldName_Clear = 1,
  @Sequence = @Sequence_95b57e2d,
  @Configuration = @Configuration_95b57e2d,
  @Configuration_Clear = 1,
  @Status = @Status_95b57e2d,
  @IsCustom = @IsCustom_95b57e2d,
  @MetadataSource = @MetadataSource_95b57e2d,
  @ID = @ID_95b57e2d;

GO

-- Save MJ: Integration Object Fields (core SP call only)
DECLARE @ID_3d72a799 UNIQUEIDENTIFIER,
@IntegrationObjectID_3d72a799 UNIQUEIDENTIFIER,
@Name_3d72a799 NVARCHAR(255),
@DisplayName_3d72a799 NVARCHAR(255),
@Description_3d72a799 NVARCHAR(MAX),
@Category_3d72a799 NVARCHAR(100),
@Type_3d72a799 NVARCHAR(100),
@Length_3d72a799 INT,
@Precision_3d72a799 INT,
@Scale_3d72a799 INT,
@AllowsNull_3d72a799 BIT,
@DefaultValue_3d72a799 NVARCHAR(255),
@IsPrimaryKey_3d72a799 BIT,
@IsUniqueKey_3d72a799 BIT,
@IsReadOnly_3d72a799 BIT,
@IsRequired_3d72a799 BIT,
@RelatedIntegrationObjectID_3d72a799 UNIQUEIDENTIFIER,
@RelatedIntegrationObjectFieldName_3d72a799 NVARCHAR(255),
@Sequence_3d72a799 INT,
@Configuration_3d72a799 NVARCHAR(MAX),
@Status_3d72a799 NVARCHAR(25),
@IsCustom_3d72a799 BIT,
@MetadataSource_3d72a799 NVARCHAR(20)
SET
  @ID_3d72a799 = 'D78FD2EA-2614-539C-AC21-0FE7C4384BE1'
SET
  @IntegrationObjectID_3d72a799 = '08C7D86A-E2D8-55DE-8879-F0789FF63D14'
SET
  @Name_3d72a799 = N'customer'
SET
  @DisplayName_3d72a799 = N'Customer'
SET
  @Description_3d72a799 = N'Customer the invoice is issued to, as an InvoiceCustomer object — {"id":"0cu…"}, NOT a bare ID string. Write-only: BILL returns the same value flattened to `customerId` on read.'
SET
  @Type_3d72a799 = N'json'
SET
  @AllowsNull_3d72a799 = 0
SET
  @IsPrimaryKey_3d72a799 = 0
SET
  @IsUniqueKey_3d72a799 = 0
SET
  @IsReadOnly_3d72a799 = 0
SET
  @IsRequired_3d72a799 = 1
SET
  @Sequence_3d72a799 = 28
SET
  @Status_3d72a799 = N'Active'
SET
  @IsCustom_3d72a799 = 0
SET
  @MetadataSource_3d72a799 = N'Declared' EXEC [__mj].spCreateIntegrationObjectField @ID = @ID_3d72a799,
  @IntegrationObjectID = @IntegrationObjectID_3d72a799,
  @Name = @Name_3d72a799,
  @DisplayName = @DisplayName_3d72a799,
  @Description = @Description_3d72a799,
  @Category = @Category_3d72a799,
  @Category_Clear = 1,
  @Type = @Type_3d72a799,
  @Length = @Length_3d72a799,
  @Length_Clear = 1,
  @Precision = @Precision_3d72a799,
  @Precision_Clear = 1,
  @Scale = @Scale_3d72a799,
  @Scale_Clear = 1,
  @AllowsNull = @AllowsNull_3d72a799,
  @DefaultValue = @DefaultValue_3d72a799,
  @DefaultValue_Clear = 1,
  @IsPrimaryKey = @IsPrimaryKey_3d72a799,
  @IsUniqueKey = @IsUniqueKey_3d72a799,
  @IsReadOnly = @IsReadOnly_3d72a799,
  @IsRequired = @IsRequired_3d72a799,
  @RelatedIntegrationObjectID = @RelatedIntegrationObjectID_3d72a799,
  @RelatedIntegrationObjectID_Clear = 1,
  @RelatedIntegrationObjectFieldName = @RelatedIntegrationObjectFieldName_3d72a799,
  @RelatedIntegrationObjectFieldName_Clear = 1,
  @Sequence = @Sequence_3d72a799,
  @Configuration = @Configuration_3d72a799,
  @Configuration_Clear = 1,
  @Status = @Status_3d72a799,
  @IsCustom = @IsCustom_3d72a799,
  @MetadataSource = @MetadataSource_3d72a799;

GO


-- End of SQL Logging Session
-- Session ID: 3e840b4d-19eb-4074-98b0-cd23f798712f
-- Completed: 2026-08-14T03:06:04.555Z
-- Duration: 11004ms
-- Total Statements: 2
