-- Bill.com Connector — connector metadata seed (generated by `mj sync push`)
-- Seeds the core __mj integration catalog (Integration / IntegrationObject / IntegrationObjectField + Actions).
-- Do not hand-edit; regenerate from ../metadata via `mj sync push` + `scripts/wrap-migration.mjs`.

-- SQL Logging Session
-- Session ID: b1c324a3-e27a-4ff9-9a4a-9eb588d2286a
-- Started: 2026-09-27T19:12:16.199Z
-- Description: MetadataSync push operation
-- Generated by MemberJunction

-- Save MJ: Integration Object Fields (core SP call only)
DECLARE @IntegrationObjectID_86a7f49a UNIQUEIDENTIFIER,
@Name_86a7f49a NVARCHAR(255),
@DisplayName_86a7f49a NVARCHAR(255),
@Description_86a7f49a NVARCHAR(MAX),
@Category_86a7f49a NVARCHAR(100),
@Type_86a7f49a NVARCHAR(100),
@Length_86a7f49a INT,
@Precision_86a7f49a INT,
@Scale_86a7f49a INT,
@AllowsNull_86a7f49a BIT,
@DefaultValue_86a7f49a NVARCHAR(255),
@IsPrimaryKey_86a7f49a BIT,
@IsUniqueKey_86a7f49a BIT,
@IsReadOnly_86a7f49a BIT,
@IsRequired_86a7f49a BIT,
@RelatedIntegrationObjectID_86a7f49a UNIQUEIDENTIFIER,
@RelatedIntegrationObjectFieldName_86a7f49a NVARCHAR(255),
@Sequence_86a7f49a INT,
@Configuration_86a7f49a NVARCHAR(MAX),
@Status_86a7f49a NVARCHAR(25),
@IsCustom_86a7f49a BIT,
@MetadataSource_86a7f49a NVARCHAR(20),
@ID_86a7f49a UNIQUEIDENTIFIER
SET
  @IntegrationObjectID_86a7f49a = 'A281C9C5-3AEA-5F3A-86F6-B37F5B31E8A3'
SET
  @Name_86a7f49a = N'companyName'
SET
  @DisplayName_86a7f49a = N'Company Name'
SET
  @Description_86a7f49a = N'Customer company name. This field is overridden when you connect with a customer in the BILL network.'
SET
  @Type_86a7f49a = N'string'
SET
  @Length_86a7f49a = 250
SET
  @AllowsNull_86a7f49a = 1
SET
  @IsPrimaryKey_86a7f49a = 0
SET
  @IsUniqueKey_86a7f49a = 0
SET
  @IsReadOnly_86a7f49a = 0
SET
  @IsRequired_86a7f49a = 0
SET
  @Sequence_86a7f49a = 4
SET
  @Status_86a7f49a = N'Active'
SET
  @IsCustom_86a7f49a = 0
SET
  @MetadataSource_86a7f49a = N'Declared'
SET
  @ID_86a7f49a = 'F390A842-ED89-5BEF-9266-1E39F2A41BCB' EXEC [__mj].spUpdateIntegrationObjectField @IntegrationObjectID = @IntegrationObjectID_86a7f49a,
  @Name = @Name_86a7f49a,
  @DisplayName = @DisplayName_86a7f49a,
  @Description = @Description_86a7f49a,
  @Category = @Category_86a7f49a,
  @Category_Clear = 1,
  @Type = @Type_86a7f49a,
  @Length = @Length_86a7f49a,
  @Precision = @Precision_86a7f49a,
  @Precision_Clear = 1,
  @Scale = @Scale_86a7f49a,
  @Scale_Clear = 1,
  @AllowsNull = @AllowsNull_86a7f49a,
  @DefaultValue = @DefaultValue_86a7f49a,
  @DefaultValue_Clear = 1,
  @IsPrimaryKey = @IsPrimaryKey_86a7f49a,
  @IsUniqueKey = @IsUniqueKey_86a7f49a,
  @IsReadOnly = @IsReadOnly_86a7f49a,
  @IsRequired = @IsRequired_86a7f49a,
  @RelatedIntegrationObjectID = @RelatedIntegrationObjectID_86a7f49a,
  @RelatedIntegrationObjectID_Clear = 1,
  @RelatedIntegrationObjectFieldName = @RelatedIntegrationObjectFieldName_86a7f49a,
  @RelatedIntegrationObjectFieldName_Clear = 1,
  @Sequence = @Sequence_86a7f49a,
  @Configuration = @Configuration_86a7f49a,
  @Configuration_Clear = 1,
  @Status = @Status_86a7f49a,
  @IsCustom = @IsCustom_86a7f49a,
  @MetadataSource = @MetadataSource_86a7f49a,
  @ID = @ID_86a7f49a;

GO

-- Save MJ: Integration Object Fields (core SP call only)
DECLARE @IntegrationObjectID_712e2d40 UNIQUEIDENTIFIER,
@Name_712e2d40 NVARCHAR(255),
@DisplayName_712e2d40 NVARCHAR(255),
@Description_712e2d40 NVARCHAR(MAX),
@Category_712e2d40 NVARCHAR(100),
@Type_712e2d40 NVARCHAR(100),
@Length_712e2d40 INT,
@Precision_712e2d40 INT,
@Scale_712e2d40 INT,
@AllowsNull_712e2d40 BIT,
@DefaultValue_712e2d40 NVARCHAR(255),
@IsPrimaryKey_712e2d40 BIT,
@IsUniqueKey_712e2d40 BIT,
@IsReadOnly_712e2d40 BIT,
@IsRequired_712e2d40 BIT,
@RelatedIntegrationObjectID_712e2d40 UNIQUEIDENTIFIER,
@RelatedIntegrationObjectFieldName_712e2d40 NVARCHAR(255),
@Sequence_712e2d40 INT,
@Configuration_712e2d40 NVARCHAR(MAX),
@Status_712e2d40 NVARCHAR(25),
@IsCustom_712e2d40 BIT,
@MetadataSource_712e2d40 NVARCHAR(20),
@ID_712e2d40 UNIQUEIDENTIFIER
SET
  @IntegrationObjectID_712e2d40 = 'A281C9C5-3AEA-5F3A-86F6-B37F5B31E8A3'
SET
  @Name_712e2d40 = N'name'
SET
  @DisplayName_712e2d40 = N'Name'
SET
  @Description_712e2d40 = N'Customer name'
SET
  @Type_712e2d40 = N'string'
SET
  @Length_712e2d40 = 100
SET
  @AllowsNull_712e2d40 = 0
SET
  @IsPrimaryKey_712e2d40 = 0
SET
  @IsUniqueKey_712e2d40 = 0
SET
  @IsReadOnly_712e2d40 = 0
SET
  @IsRequired_712e2d40 = 1
SET
  @Sequence_712e2d40 = 3
SET
  @Status_712e2d40 = N'Active'
SET
  @IsCustom_712e2d40 = 0
SET
  @MetadataSource_712e2d40 = N'Declared'
SET
  @ID_712e2d40 = '3FE8BE48-030B-5023-B4CA-FC12098B1D44' EXEC [__mj].spUpdateIntegrationObjectField @IntegrationObjectID = @IntegrationObjectID_712e2d40,
  @Name = @Name_712e2d40,
  @DisplayName = @DisplayName_712e2d40,
  @Description = @Description_712e2d40,
  @Category = @Category_712e2d40,
  @Category_Clear = 1,
  @Type = @Type_712e2d40,
  @Length = @Length_712e2d40,
  @Precision = @Precision_712e2d40,
  @Precision_Clear = 1,
  @Scale = @Scale_712e2d40,
  @Scale_Clear = 1,
  @AllowsNull = @AllowsNull_712e2d40,
  @DefaultValue = @DefaultValue_712e2d40,
  @DefaultValue_Clear = 1,
  @IsPrimaryKey = @IsPrimaryKey_712e2d40,
  @IsUniqueKey = @IsUniqueKey_712e2d40,
  @IsReadOnly = @IsReadOnly_712e2d40,
  @IsRequired = @IsRequired_712e2d40,
  @RelatedIntegrationObjectID = @RelatedIntegrationObjectID_712e2d40,
  @RelatedIntegrationObjectID_Clear = 1,
  @RelatedIntegrationObjectFieldName = @RelatedIntegrationObjectFieldName_712e2d40,
  @RelatedIntegrationObjectFieldName_Clear = 1,
  @Sequence = @Sequence_712e2d40,
  @Configuration = @Configuration_712e2d40,
  @Configuration_Clear = 1,
  @Status = @Status_712e2d40,
  @IsCustom = @IsCustom_712e2d40,
  @MetadataSource = @MetadataSource_712e2d40,
  @ID = @ID_712e2d40;

GO

-- Save MJ: Integration Object Fields (core SP call only)
DECLARE @IntegrationObjectID_d348f4d2 UNIQUEIDENTIFIER,
@Name_d348f4d2 NVARCHAR(255),
@DisplayName_d348f4d2 NVARCHAR(255),
@Description_d348f4d2 NVARCHAR(MAX),
@Category_d348f4d2 NVARCHAR(100),
@Type_d348f4d2 NVARCHAR(100),
@Length_d348f4d2 INT,
@Precision_d348f4d2 INT,
@Scale_d348f4d2 INT,
@AllowsNull_d348f4d2 BIT,
@DefaultValue_d348f4d2 NVARCHAR(255),
@IsPrimaryKey_d348f4d2 BIT,
@IsUniqueKey_d348f4d2 BIT,
@IsReadOnly_d348f4d2 BIT,
@IsRequired_d348f4d2 BIT,
@RelatedIntegrationObjectID_d348f4d2 UNIQUEIDENTIFIER,
@RelatedIntegrationObjectFieldName_d348f4d2 NVARCHAR(255),
@Sequence_d348f4d2 INT,
@Configuration_d348f4d2 NVARCHAR(MAX),
@Status_d348f4d2 NVARCHAR(25),
@IsCustom_d348f4d2 BIT,
@MetadataSource_d348f4d2 NVARCHAR(20),
@ID_d348f4d2 UNIQUEIDENTIFIER
SET
  @IntegrationObjectID_d348f4d2 = 'A281C9C5-3AEA-5F3A-86F6-B37F5B31E8A3'
SET
  @Name_d348f4d2 = N'accountNumber'
SET
  @DisplayName_d348f4d2 = N'Account Number'
SET
  @Description_d348f4d2 = N'Customer account number. The number appears in customer invoices.'
SET
  @Type_d348f4d2 = N'string'
SET
  @Length_d348f4d2 = 100
SET
  @AllowsNull_d348f4d2 = 1
SET
  @IsPrimaryKey_d348f4d2 = 0
SET
  @IsUniqueKey_d348f4d2 = 0
SET
  @IsReadOnly_d348f4d2 = 0
SET
  @IsRequired_d348f4d2 = 0
SET
  @Sequence_d348f4d2 = 13
SET
  @Status_d348f4d2 = N'Active'
SET
  @IsCustom_d348f4d2 = 0
SET
  @MetadataSource_d348f4d2 = N'Declared'
SET
  @ID_d348f4d2 = 'E0D4B90A-8F57-58DF-9202-BDF0E474A57B' EXEC [__mj].spUpdateIntegrationObjectField @IntegrationObjectID = @IntegrationObjectID_d348f4d2,
  @Name = @Name_d348f4d2,
  @DisplayName = @DisplayName_d348f4d2,
  @Description = @Description_d348f4d2,
  @Category = @Category_d348f4d2,
  @Category_Clear = 1,
  @Type = @Type_d348f4d2,
  @Length = @Length_d348f4d2,
  @Precision = @Precision_d348f4d2,
  @Precision_Clear = 1,
  @Scale = @Scale_d348f4d2,
  @Scale_Clear = 1,
  @AllowsNull = @AllowsNull_d348f4d2,
  @DefaultValue = @DefaultValue_d348f4d2,
  @DefaultValue_Clear = 1,
  @IsPrimaryKey = @IsPrimaryKey_d348f4d2,
  @IsUniqueKey = @IsUniqueKey_d348f4d2,
  @IsReadOnly = @IsReadOnly_d348f4d2,
  @IsRequired = @IsRequired_d348f4d2,
  @RelatedIntegrationObjectID = @RelatedIntegrationObjectID_d348f4d2,
  @RelatedIntegrationObjectID_Clear = 1,
  @RelatedIntegrationObjectFieldName = @RelatedIntegrationObjectFieldName_d348f4d2,
  @RelatedIntegrationObjectFieldName_Clear = 1,
  @Sequence = @Sequence_d348f4d2,
  @Configuration = @Configuration_d348f4d2,
  @Configuration_Clear = 1,
  @Status = @Status_d348f4d2,
  @IsCustom = @IsCustom_d348f4d2,
  @MetadataSource = @MetadataSource_d348f4d2,
  @ID = @ID_d348f4d2;

GO

-- Save MJ: Integration Object Fields (core SP call only)
DECLARE @IntegrationObjectID_24247a54 UNIQUEIDENTIFIER,
@Name_24247a54 NVARCHAR(255),
@DisplayName_24247a54 NVARCHAR(255),
@Description_24247a54 NVARCHAR(MAX),
@Category_24247a54 NVARCHAR(100),
@Type_24247a54 NVARCHAR(100),
@Length_24247a54 INT,
@Precision_24247a54 INT,
@Scale_24247a54 INT,
@AllowsNull_24247a54 BIT,
@DefaultValue_24247a54 NVARCHAR(255),
@IsPrimaryKey_24247a54 BIT,
@IsUniqueKey_24247a54 BIT,
@IsReadOnly_24247a54 BIT,
@IsRequired_24247a54 BIT,
@RelatedIntegrationObjectID_24247a54 UNIQUEIDENTIFIER,
@RelatedIntegrationObjectFieldName_24247a54 NVARCHAR(255),
@Sequence_24247a54 INT,
@Configuration_24247a54 NVARCHAR(MAX),
@Status_24247a54 NVARCHAR(25),
@IsCustom_24247a54 BIT,
@MetadataSource_24247a54 NVARCHAR(20),
@ID_24247a54 UNIQUEIDENTIFIER
SET
  @IntegrationObjectID_24247a54 = '08C7D86A-E2D8-55DE-8879-F0789FF63D14'
SET
  @Name_24247a54 = N'invoiceNumber'
SET
  @DisplayName_24247a54 = N'Invoice Number'
SET
  @Description_24247a54 = N'User-generated invoice number. This value can be your chosen number scheme.

If you do not set this field, `invoiceNumber` is auto-generated.'
SET
  @Type_24247a54 = N'string'
SET
  @Length_24247a54 = 100
SET
  @AllowsNull_24247a54 = 1
SET
  @IsPrimaryKey_24247a54 = 0
SET
  @IsUniqueKey_24247a54 = 0
SET
  @IsReadOnly_24247a54 = 0
SET
  @IsRequired_24247a54 = 0
SET
  @Sequence_24247a54 = 4
SET
  @Status_24247a54 = N'Active'
SET
  @IsCustom_24247a54 = 0
SET
  @MetadataSource_24247a54 = N'Declared'
SET
  @ID_24247a54 = 'C234AE08-D5B3-527D-A9FF-BEEBF45CB6F3' EXEC [__mj].spUpdateIntegrationObjectField @IntegrationObjectID = @IntegrationObjectID_24247a54,
  @Name = @Name_24247a54,
  @DisplayName = @DisplayName_24247a54,
  @Description = @Description_24247a54,
  @Category = @Category_24247a54,
  @Category_Clear = 1,
  @Type = @Type_24247a54,
  @Length = @Length_24247a54,
  @Precision = @Precision_24247a54,
  @Precision_Clear = 1,
  @Scale = @Scale_24247a54,
  @Scale_Clear = 1,
  @AllowsNull = @AllowsNull_24247a54,
  @DefaultValue = @DefaultValue_24247a54,
  @DefaultValue_Clear = 1,
  @IsPrimaryKey = @IsPrimaryKey_24247a54,
  @IsUniqueKey = @IsUniqueKey_24247a54,
  @IsReadOnly = @IsReadOnly_24247a54,
  @IsRequired = @IsRequired_24247a54,
  @RelatedIntegrationObjectID = @RelatedIntegrationObjectID_24247a54,
  @RelatedIntegrationObjectID_Clear = 1,
  @RelatedIntegrationObjectFieldName = @RelatedIntegrationObjectFieldName_24247a54,
  @RelatedIntegrationObjectFieldName_Clear = 1,
  @Sequence = @Sequence_24247a54,
  @Configuration = @Configuration_24247a54,
  @Configuration_Clear = 1,
  @Status = @Status_24247a54,
  @IsCustom = @IsCustom_24247a54,
  @MetadataSource = @MetadataSource_24247a54,
  @ID = @ID_24247a54;

GO


-- End of SQL Logging Session
-- Session ID: b1c324a3-e27a-4ff9-9a4a-9eb588d2286a
-- Completed: 2026-09-27T19:12:16.478Z
-- Duration: 279ms
-- Total Statements: 4
